local tTable = {}


tTable["index_1"] = {
default={classname="Panel",name="default@fill_layout",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1000",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="13",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
view={classname="Panel",name="view@fill_layout",parName="default",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1000",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="52",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_top={classname="Panel",name="lay_top",parName="view",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="266",width="640",x="0",y="734",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="53",anchorPointX="0",anchorPointY="0",},
lay_tab={classname="Panel",name="lay_tab",parName="view",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="584",width="640",x="0",y="150",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="56",anchorPointX="0",anchorPointY="0",},
lay_bottom={classname="Panel",name="lay_bottom",parName="view",childCount="6",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="150",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="57",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lay_banner_bg={classname="Panel",name="lay_banner_bg",parName="lay_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="266",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="54",anchorPointX="0",anchorPointY="0",},
lay_bar_bg={classname="Panel",name="lay_bar_bg",parName="lay_top",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="ui/bar/v2_bar_b3.png",height="24",width="568",x="36",y="104",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="55",anchorPointX="0",anchorPointY="0",},
lay_list={classname="Panel",name="lay_list",parName="lay_tab",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="522",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="58",anchorPointX="0",anchorPointY="0",},
lay_tab_title={classname="Panel",name="lay_tab_title",parName="lay_tab",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="46",width="640",x="0",y="534",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="82",anchorPointX="0",anchorPointY="0",},
img1={classname="ImageView",name="img1",parName="lay_bottom",ZOrder="0",fileName="#v1_img_xycj.png",scale9Enable="false",scale9Height="34",scale9Width="34",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="34",width="34",x="20",y="120",visible="true",touchAble="false",flipX="false",scaleX="0.8",scaleY="0.8",opacity="255",rotation="0",tag="153",anchorPointX="0",anchorPointY="0.5",},
img2={classname="ImageView",name="img2",parName="lay_bottom",ZOrder="0",fileName="#v1_img_xycj.png",scale9Enable="false",scale9Height="34",scale9Width="34",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="34",width="34",x="20",y="80",visible="true",touchAble="false",flipX="false",scaleX="0.8",scaleY="0.8",opacity="255",rotation="0",tag="155",anchorPointX="0",anchorPointY="0.5",},
img3={classname="ImageView",name="img3",parName="lay_bottom",ZOrder="0",fileName="#v1_img_xycj.png",scale9Enable="false",scale9Height="34",scale9Width="34",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="34",width="34",x="20",y="40",visible="true",touchAble="false",flipX="false",scaleX="0.8",scaleY="0.8",opacity="255",rotation="0",tag="156",anchorPointX="0",anchorPointY="0.5",},
txt_tip1={classname="Label",name="txt_tip1",parName="lay_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="60",y="120",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="157",anchorPointX="0",anchorPointY="0.5",},
txt_tip2={classname="Label",name="txt_tip2",parName="lay_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="60",y="80",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="160",anchorPointX="0",anchorPointY="0.5",},
txt_tip3={classname="Label",name="txt_tip3",parName="lay_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="60",areaWidth="540",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="60",width="540",x="60",y="53",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="161",anchorPointX="0",anchorPointY="1",},
}
tTable["index_5"] = {
lay_tab1={classname="Panel",name="lay_tab1",parName="lay_tab_title",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_btn_yellow6.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="55",capInsetsY="23",height="46",width="128",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="83",anchorPointX="0",anchorPointY="0",},
lay_tab2={classname="Panel",name="lay_tab2",parName="lay_tab_title",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_btn_yellow6.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="55",capInsetsY="23",height="46",width="128",x="128",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="85",anchorPointX="0",anchorPointY="0",},
lay_tab3={classname="Panel",name="lay_tab3",parName="lay_tab_title",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_btn_yellow6.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="55",capInsetsY="23",height="46",width="128",x="256",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="86",anchorPointX="0",anchorPointY="0",},
lay_tab4={classname="Panel",name="lay_tab4",parName="lay_tab_title",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_btn_yellow6.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="55",capInsetsY="23",height="46",width="128",x="384",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="87",anchorPointX="0",anchorPointY="0",},
lay_tab5={classname="Panel",name="lay_tab5",parName="lay_tab_title",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_btn_yellow6.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="55",capInsetsY="23",height="46",width="128",x="512",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="88",anchorPointX="0",anchorPointY="0",},
}
tTable["index_6"] = {
txt_tab_title1={classname="Label",name="txt_tab_title1",parName="lay_tab1",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="第1天",fontName="微软雅黑",fontSize="20",height="27",width="52",x="64",y="23",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="89",anchorPointX="0.5",anchorPointY="0.5",},
img_lock1={classname="ImageView",name="img_lock1",parName="lay_tab1",ZOrder="0",fileName="#v2_img_lock_tjp.png",scale9Enable="false",scale9Height="31",scale9Width="24",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="31",width="24",x="21",y="23",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="219",anchorPointX="0.5",anchorPointY="0.5",},
txt_tab_title2={classname="Label",name="txt_tab_title2",parName="lay_tab2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="64",y="23",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="92",anchorPointX="0.5",anchorPointY="0.5",},
img_lock2={classname="ImageView",name="img_lock2",parName="lay_tab2",ZOrder="0",fileName="#v2_img_lock_tjp.png",scale9Enable="false",scale9Height="31",scale9Width="24",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="31",width="24",x="21",y="22",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="221",anchorPointX="0.5",anchorPointY="0.5",},
txt_tab_title3={classname="Label",name="txt_tab_title3",parName="lay_tab3",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="64",y="23",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="93",anchorPointX="0.5",anchorPointY="0.5",},
img_lock3={classname="ImageView",name="img_lock3",parName="lay_tab3",ZOrder="0",fileName="#v2_img_lock_tjp.png",scale9Enable="false",scale9Height="31",scale9Width="24",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="31",width="24",x="21",y="22",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="222",anchorPointX="0.5",anchorPointY="0.5",},
txt_tab_title4={classname="Label",name="txt_tab_title4",parName="lay_tab4",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="64",y="23",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="94",anchorPointX="0.5",anchorPointY="0.5",},
img_lock4={classname="ImageView",name="img_lock4",parName="lay_tab4",ZOrder="0",fileName="#v2_img_lock_tjp.png",scale9Enable="false",scale9Height="31",scale9Width="24",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="31",width="24",x="21",y="22",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="223",anchorPointX="0.5",anchorPointY="0.5",},
txt_tab_title5={classname="Label",name="txt_tab_title5",parName="lay_tab5",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="64",y="23",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="95",anchorPointX="0.5",anchorPointY="0.5",},
img_lock5={classname="ImageView",name="img_lock5",parName="lay_tab5",ZOrder="0",fileName="#v2_img_lock_tjp.png",scale9Enable="false",scale9Height="31",scale9Width="24",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="31",width="24",x="21",y="22",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="224",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable