local tTable = {}

tTable["texturesPng"] = {"ui/p1_commonse1.plist"}
tTable["index_1"] = {
root={classname="Panel",name="root",parName="root",childCount="17",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="130",width="420",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="43",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_icon={classname="Panel",name="lay_icon",parName="root",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="15",y="13",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="50",anchorPointX="0",anchorPointY="0",},
lb_equip_name={classname="Label",name="lb_equip_name",parName="root",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="装备名称",fontName="微软雅黑",fontSize="22",height="30",width="88",x="140",y="105",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="52",anchorPointX="0",anchorPointY="0.5",},
lb_attr={classname="Label",name="lb_attr",parName="root",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="防御",fontName="微软雅黑",fontSize="22",height="30",width="44",x="332",y="105",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="54",anchorPointX="1",anchorPointY="0.5",},
lb_attr_value={classname="Label",name="lb_attr_value",parName="root",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="+9522",fontName="微软雅黑",fontSize="22",height="30",width="68",x="332",y="105",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="55",anchorPointX="0",anchorPointY="0.5",},
img_attr1_icon={classname="ImageView",name="img_attr1_icon",parName="root",ZOrder="0",fileName="#v1_img_qianggong.png",scale9Enable="false",scale9Height="37",scale9Width="41",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="37",width="41",x="153",y="65",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="56",anchorPointX="0.5",anchorPointY="0.5",},
img_attr3_icon={classname="ImageView",name="img_attr3_icon",parName="root",ZOrder="0",fileName="#v1_img_qianggong.png",scale9Enable="false",scale9Height="37",scale9Width="41",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="37",width="41",x="153",y="27",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="58",anchorPointX="0.5",anchorPointY="0.5",},
img_attr2_icon={classname="ImageView",name="img_attr2_icon",parName="root",ZOrder="0",fileName="#v1_img_qianggong.png",scale9Enable="false",scale9Height="37",scale9Width="41",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="37",width="41",x="305",y="65",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="61",anchorPointX="0.5",anchorPointY="0.5",},
img_attr4_icon={classname="ImageView",name="img_attr4_icon",parName="root",ZOrder="0",fileName="#v1_img_qianggong.png",scale9Enable="false",scale9Height="37",scale9Width="41",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="37",width="41",x="305",y="27",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="62",anchorPointX="0.5",anchorPointY="0.5",},
lb_attr1_name={classname="Label",name="lb_attr1_name",parName="root",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="强攻",fontName="微软雅黑",fontSize="20",height="27",width="40",x="176",y="65",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="67",anchorPointX="0",anchorPointY="0.5",},
lb_attr1_value={classname="Label",name="lb_attr1_value",parName="root",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="lv.6",fontName="微软雅黑",fontSize="20",height="27",width="33",x="221",y="65",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="68",anchorPointX="0",anchorPointY="0.5",},
lb_attr3_name={classname="Label",name="lb_attr3_name",parName="root",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="强攻",fontName="微软雅黑",fontSize="20",height="27",width="40",x="176",y="27",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="71",anchorPointX="0",anchorPointY="0.5",},
lb_attr3_value={classname="Label",name="lb_attr3_value",parName="root",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="lv.6",fontName="微软雅黑",fontSize="20",height="27",width="33",x="221",y="27",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="72",anchorPointX="0",anchorPointY="0.5",},
lb_attr2_name={classname="Label",name="lb_attr2_name",parName="root",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="强攻",fontName="微软雅黑",fontSize="20",height="27",width="40",x="328",y="65",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="73",anchorPointX="0",anchorPointY="0.5",},
lb_attr2_value={classname="Label",name="lb_attr2_value",parName="root",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="lv.6",fontName="微软雅黑",fontSize="20",height="27",width="33",x="373",y="65",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="74",anchorPointX="0",anchorPointY="0.5",},
lb_attr4_name={classname="Label",name="lb_attr4_name",parName="root",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="强攻",fontName="微软雅黑",fontSize="20",height="27",width="40",x="328",y="27",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="75",anchorPointX="0",anchorPointY="0.5",},
lb_attr4_value={classname="Label",name="lb_attr4_value",parName="root",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="lv.6",fontName="微软雅黑",fontSize="20",height="27",width="33",x="373",y="27",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="76",anchorPointX="0",anchorPointY="0.5",},
lay_log={classname="Panel",name="lay_log",parName="root",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_img_xinpin.png",height="70",width="70",x="0",y="60",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="909",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lb_xin={classname="Label",name="lb_xin",parName="lay_log",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="新",fontName="微软雅黑",fontSize="20",height="27",width="20",x="21",y="51",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="-45",tag="910",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable