local tTable = {}

tTable["texturesPng"] = {"ui/p1_commmon2_sep.plist","ui/p1_commmon1_sep.plist"}
tTable["index_1"] = {
root={classname="Panel",name="root",parName="root",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="380",width="560",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="722",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_resitem={classname="Panel",name="lay_resitem",parName="root",childCount="7",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen6.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="130",width="524",x="18",y="242",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="723",anchorPointX="0",anchorPointY="0",},
ly_item_title={classname="Panel",name="ly_item_title",parName="root",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_xiaobiaoti2.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="186",capInsetsY="24",height="50",width="524",x="18",y="182",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="727",anchorPointX="0",anchorPointY="0",},
lay_item_info={classname="Panel",name="lay_item_info",parName="root",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="10",height="150",width="524",x="18",y="32",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="725",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_icon={classname="Panel",name="lay_icon",parName="lay_resitem",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="15",y="11",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="724",anchorPointX="0",anchorPointY="0",},
lb_res_name={classname="Label",name="lb_res_name",parName="lay_resitem",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="铜钱",fontName="微软雅黑",fontSize="22",height="30",width="44",x="138",y="86",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="750",anchorPointX="0",anchorPointY="0.5",},
lb_hourly_output={classname="Label",name="lb_hourly_output",parName="lay_resitem",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="小时产量：",fontName="微软雅黑",fontSize="20",height="27",width="100",x="138",y="38",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="751",anchorPointX="0",anchorPointY="0.5",},
lb_value={classname="Label",name="lb_value",parName="lay_resitem",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9000",fontName="微软雅黑",fontSize="20",height="27",width="48",x="240",y="38",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="752",anchorPointX="0",anchorPointY="0.5",},
lb_plusvalue={classname="Label",name="lb_plusvalue",parName="lay_resitem",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="+9000",fontName="微软雅黑",fontSize="20",height="27",width="63",x="337",y="38",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="753",anchorPointX="0.5",anchorPointY="0.5",},
lay_btn_plus={classname="Panel",name="lay_btn_plus",parName="lay_resitem",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="50",x="447",y="40",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="754",anchorPointX="0",anchorPointY="0",},
Image_22={classname="ImageView",name="Image_22",parName="lay_resitem",ZOrder="0",fileName="#v1_img_kelashen6_b.png",scale9Enable="true",scale9Height="130",scale9Width="350",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="175",capInsetsY="9",height="130",width="350",x="0",y="0",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1527",anchorPointX="0",anchorPointY="0",},
lb_itemtitle={classname="Label",name="lb_itemtitle",parName="ly_item_title",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="产量信息",fontName="微软雅黑",fontSize="20",height="27",width="80",x="20",y="24",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="729",anchorPointX="0",anchorPointY="0.5",},
}

return tTable