local tTable = {}

tTable["texturesPng"] = {"ui/p1_commmon2_sep.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","ui/p1_commmon3_sep.plist","ui/language/cn/p2_font1.plist"}
tTable["index_1"] = {
dlg_hero_info={classname="Panel",name="dlg_hero_info@fill_layout",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1066",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="70",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
ly_main_my={classname="Panel",name="ly_main_my@fill_layout",parName="dlg_hero_info",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_dikuang2.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="320",capInsetsY="56",height="558",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="71",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
ly_content={classname="Panel",name="ly_content",parName="ly_main_my",childCount="18",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="508",width="640",x="0",y="50",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="72",anchorPointX="0",anchorPointY="0",},
ly_info={classname="Panel",name="ly_info",parName="ly_main_my",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_blackjianbianhei.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="141",capInsetsY="25",height="51",width="481",x="79",y="558",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="859",anchorPointX="0",anchorPointY="0",},
lb_star_name={classname="CustomLabel",name="lb_star_name",parName="ly_main_my",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="星级: ",fontName="微软雅黑",fontSize="20",height="27",width="51",x="336",y="534",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="807",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_4"] = {
Image_42={classname="ImageView",name="Image_42",parName="ly_content",ZOrder="0",fileName="#v1_img_jianbian2.png",scale9Enable="false",scale9Height="49",scale9Width="294",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="147",capInsetsY="25",height="49",width="294",x="320",y="409",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="123",anchorPointX="0.5",anchorPointY="0.5",},
Image_42_0={classname="ImageView",name="Image_42_0",parName="ly_content",ZOrder="0",fileName="#v1_img_jianbian2.png",scale9Enable="false",scale9Height="49",scale9Width="294",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="147",capInsetsY="25",height="49",width="294",x="320",y="123",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="125",anchorPointX="0.5",anchorPointY="0.5",},
lb_desc={classname="CustomLabel",name="lb_desc",parName="ly_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="95",areaWidth="415",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="95",width="415",x="108",y="97",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="128",anchorPointX="0",anchorPointY="1",},
Image_48={classname="ImageView",name="Image_48",parName="ly_content",ZOrder="0",fileName="#v1_line_blue1.png",scale9Enable="true",scale9Height="2",scale9Width="500",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="1",height="2",width="500",x="320",y="295",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="129",anchorPointX="0.5",anchorPointY="0.5",},
ly_talent_1={classname="Panel",name="ly_talent_1",parName="ly_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="170",x="107",y="342",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="339",anchorPointX="0",anchorPointY="0",},
ly_talent_2={classname="Panel",name="ly_talent_2",parName="ly_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="170",x="357",y="342",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="340",anchorPointX="0",anchorPointY="0",},
ly_talent_3={classname="Panel",name="ly_talent_3",parName="ly_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="170",x="107",y="306",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="341",anchorPointX="0",anchorPointY="0",},
ly_talent_4={classname="Panel",name="ly_talent_4",parName="ly_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="170",x="107",y="255",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="342",anchorPointX="0",anchorPointY="0",},
ly_talent_5={classname="Panel",name="ly_talent_5",parName="ly_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="170",x="357",y="255",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="343",anchorPointX="0",anchorPointY="0",},
ly_talent_6={classname="Panel",name="ly_talent_6",parName="ly_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="170",x="107",y="220",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="344",anchorPointX="0",anchorPointY="0",},
ly_talent_7={classname="Panel",name="ly_talent_7",parName="ly_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="170",x="357",y="220",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="345",anchorPointX="0",anchorPointY="0",},
ly_talent_8={classname="Panel",name="ly_talent_8",parName="ly_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="170",x="107",y="185",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="346",anchorPointX="0",anchorPointY="0",},
ly_talent_9={classname="Panel",name="ly_talent_9",parName="ly_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="170",x="357",y="185",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="347",anchorPointX="0",anchorPointY="0",},
ly_talent_10={classname="Panel",name="ly_talent_10",parName="ly_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="170",x="107",y="150",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="348",anchorPointX="0",anchorPointY="0",},
ly_talent_11={classname="Panel",name="ly_talent_11",parName="ly_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="170",x="357",y="150",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="349",anchorPointX="0",anchorPointY="0",},
lb_info_name={classname="CustomLabel",name="lb_info_name",parName="ly_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="武将属性",fontName="微软雅黑",fontSize="20",height="27",width="80",x="320",y="409",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="126",anchorPointX="0.5",anchorPointY="0.5",},
lb_hero_life={classname="CustomLabel",name="lb_hero_life",parName="ly_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="320",y="123",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="127",anchorPointX="0.5",anchorPointY="0.5",},
lb_info={classname="CustomLabel",name="lb_info",parName="ly_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="品质: 90 + 10",fontName="微软雅黑",fontSize="20",height="27",width="126",x="320",y="484",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="806",anchorPointX="0.5",anchorPointY="0.5",},
Image_27={classname="ImageView",name="Image_27",parName="ly_info",ZOrder="0",fileName="#v1_img_blackjianbianhei.png",scale9Enable="false",scale9Height="51",scale9Width="481",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="51",width="481",x="240",y="24",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="857",anchorPointX="0.5",anchorPointY="0.5",},
img_soldier_ty={classname="ImageView",name="img_soldier_ty",parName="ly_info",ZOrder="1",fileName="#v1_img_gongbing.png",scale9Enable="false",scale9Height="112",scale9Width="98",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="112",width="98",x="168",y="24",visible="true",touchAble="false",flipX="false",scaleX="0.4",scaleY="0.4",opacity="255",rotation="0",tag="858",anchorPointX="0.5",anchorPointY="0.5",},
img_ig={classname="CustomImageView",name="img_ig",parName="ly_info",ZOrder="1",fileName="#v2_fonts_shen.png",scale9Enable="false",scale9Height="39",scale9Width="29",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="39",width="29",x="126",y="23",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6545",anchorPointX="0.5",anchorPointY="0.5",},
lb_name={classname="CustomLabel",name="lb_name",parName="ly_info",ZOrder="3",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="司马已 lv.11",fontName="微软雅黑",fontSize="20",height="27",width="111",x="203",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="804",anchorPointX="0",anchorPointY="0.5",},
}

return tTable