local tTable = {}

tTable["texturesPng"] = {"ui/v2_bg_hanxin.jpg","ui/p1_commonse4.plist","ui/p2_button1.plist","ui/language/cn/p2_font1.plist"}
tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="850",width="542",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
view={classname="Panel",name="view",parName="default",childCount="6",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="850",width="542",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="25",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_btn_reward={classname="Panel",name="lay_btn_reward",parName="view",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="150",width="542",x="0",y="113",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="40",anchorPointX="0",anchorPointY="0",},
img_bg={classname="CustomImageView",name="img_bg",parName="view",ZOrder="0",fileName="ui/v2_bg_hanxin.jpg",scale9Enable="false",scale9Height="793",scale9Width="542",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="793",width="542",x="272",y="399",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7",anchorPointX="0.5",anchorPointY="0.5",},
lay_btn_hero={classname="Panel",name="lay_btn_hero",parName="view",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="60",width="60",x="316",y="336",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="55",anchorPointX="0",anchorPointY="0",},
lay_tab={classname="Panel",name="lay_tab",parName="view",childCount="9",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="ui/big_img/v2_btn_zjm_toub.png",height="39",width="529",x="8",y="756",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="12",anchorPointX="0",anchorPointY="0",},
img_btn_close={classname="CustomImageView",name="img_btn_close",parName="view",ZOrder="0",fileName="#v2_btn_close02.png",scale9Enable="false",scale9Height="49",scale9Width="48",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="49",width="48",x="527",y="822",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="20",anchorPointX="0.5",anchorPointY="0.5",},
img_btn_go={classname="CustomImageView",name="img_btn_go",parName="view",ZOrder="10",fileName="#v2_btn_goumai.png",scale9Enable="false",scale9Height="70",scale9Width="233",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="70",width="233",x="268",y="46",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="21",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_4"] = {
img_line_right={classname="CustomImageView",name="img_line_right",parName="lay_tab",ZOrder="0",fileName="#v2_line_biao01.png",scale9Enable="false",scale9Height="37",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="37",width="31",x="362",y="20",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="11",anchorPointX="0.5",anchorPointY="0.5",},
img_line_left={classname="CustomImageView",name="img_line_left",parName="lay_tab",ZOrder="0",fileName="#v2_line_biao01.png",scale9Enable="false",scale9Height="37",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="37",width="31",x="165",y="19",visible="true",touchAble="false",flipX="true",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="13",anchorPointX="0.5",anchorPointY="0.5",},
lay_curr_tab={classname="Panel",name="lay_curr_tab",parName="lay_tab",childCount="1",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v2_btn_wujianghblue.png",height="46",width="258",x="-2",y="-7",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="15",anchorPointX="0",anchorPointY="0",},
txt_tab_left={classname="CustomLabel",name="txt_tab_left",parName="lay_tab",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="83",y="21",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="17",anchorPointX="0.5",anchorPointY="0.5",},
txt_tab_right={classname="CustomLabel",name="txt_tab_right",parName="lay_tab",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="440",y="22",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="18",anchorPointX="0.5",anchorPointY="0.5",},
txt_tab_center={classname="CustomLabel",name="txt_tab_center",parName="lay_tab",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="289",y="22",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="19",anchorPointX="0.5",anchorPointY="0.5",},
lay_btn_left={classname="Panel",name="lay_btn_left",parName="lay_tab",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="60",width="150",x="7",y="-22",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="22",anchorPointX="0",anchorPointY="0",},
lay_btn_center={classname="Panel",name="lay_btn_center",parName="lay_tab",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="60",width="150",x="188",y="-22",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="23",anchorPointX="0",anchorPointY="0",},
lay_btn_right={classname="Panel",name="lay_btn_right",parName="lay_tab",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="60",width="150",x="365",y="-22",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="24",anchorPointX="0",anchorPointY="0",},
}
tTable["index_5"] = {
txt_curr_tab={classname="CustomLabel",name="txt_curr_tab",parName="lay_curr_tab",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="128",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="16",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable