local tTable = {}

tTable["texturesPng"] = {"ui/bg_world/v1_bg_qydt.jpg","ui/p1_commonse1.plist","icon/p1_icon_font.plist","icon/p1_icon_ui.plist"}
tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="15",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bg_world/v1_bg_qydt.jpg",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="640",capInsetsY="432",height="1066",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="46",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_map={classname="Panel",name="lay_map",parName="default",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="812",width="640",x="0",y="105",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="51",anchorPointX="0",anchorPointY="0",},
img_title_bg={classname="CustomImageView",name="img_title_bg",parName="default",ZOrder="1",fileName="#v1_img_zhangjiekuang.png",scale9Enable="false",scale9Height="50",scale9Width="386",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="50",width="386",x="320",y="1027",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="605",anchorPointX="0.5",anchorPointY="0.5",},
img_flag={classname="CustomImageView",name="img_flag",parName="default",ZOrder="1",fileName="#v1_img_qun.png",scale9Enable="false",scale9Height="64",scale9Width="51",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="64",width="51",x="197",y="1026",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9333",anchorPointX="0.5",anchorPointY="0.5",},
txt_name={classname="CustomLabel",name="txt_name",parName="default",ZOrder="2",colorB="255",colorG="248",colorR="240",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="三个字",fontName="微软雅黑",fontSize="20",height="27",width="60",x="330",y="1028",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="49",anchorPointX="0.5",anchorPointY="0.5",},
img_country_dot={classname="CustomImageView",name="img_country_dot",parName="default",ZOrder="1",fileName="#v1_img_zhenyingdianlanhong.png",scale9Enable="false",scale9Height="12",scale9Width="12",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="12",width="12",x="34",y="981",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="609",anchorPointX="0.5",anchorPointY="0.5",},
img_country_dot2={classname="CustomImageView",name="img_country_dot2",parName="default",ZOrder="1",fileName="#v1_img_zhenyingdianlanlan.png",scale9Enable="false",scale9Height="12",scale9Width="12",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="12",width="12",x="34",y="1023",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="610",anchorPointX="0.5",anchorPointY="0.5",},
img_country_dot3={classname="CustomImageView",name="img_country_dot3",parName="default",ZOrder="1",fileName="#v1_img_zhenyingdianlanlv.png",scale9Enable="false",scale9Height="12",scale9Width="12",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="12",width="12",x="34",y="938",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="611",anchorPointX="0.5",anchorPointY="0.5",},
img_country_dot4={classname="CustomImageView",name="img_country_dot4",parName="default",ZOrder="1",fileName="#v1_img_zhenyingdianlanhui.png",scale9Enable="false",scale9Height="11",scale9Width="12",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="11",width="12",x="34",y="895",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="612",anchorPointX="0.5",anchorPointY="0.5",},
txt_country_name={classname="CustomLabel",name="txt_country_name",parName="default",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="51",y="981",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="613",anchorPointX="0",anchorPointY="0.5",},
txt_country_name2={classname="CustomLabel",name="txt_country_name2",parName="default",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="51",y="1023",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="614",anchorPointX="0",anchorPointY="0.5",},
txt_country_name3={classname="CustomLabel",name="txt_country_name3",parName="default",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="51",y="939",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="615",anchorPointX="0",anchorPointY="0.5",},
txt_country_name4={classname="CustomLabel",name="txt_country_name4",parName="default",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="51",y="897",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="616",anchorPointX="0",anchorPointY="0.5",},
lay_btn_world={classname="Panel",name="lay_btn_world",parName="default",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="60",width="180",x="235",y="32",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="618",anchorPointX="0",anchorPointY="0",},
img_hide_player={classname="CustomImageView",name="img_hide_player",parName="default",ZOrder="1",fileName="#v1_img_bupingbi.png",scale9Enable="false",scale9Height="108",scale9Width="108",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="108",width="108",x="574",y="911",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="838",anchorPointX="0.5",anchorPointY="0.5",},
lay_top={classname="Panel",name="lay_top",parName="default",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="400",x="120",y="942",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="16571",anchorPointX="0",anchorPointY="0",},
}

return tTable