local tTable = {}

tTable["texturesPng"] = {"ui/p2_commonse1.plist","ui/p1_commmon1_sep.plist","ui/bg_base/v2_bg_tiejiangpu.jpg","ui/p2_commmon1_sep.plist","ui/p1_commonse1.plist","ui/bar/v1_bar_b1.png"}
tTable["index_1"] = {
default={classname="Panel",name="default@fill_layout",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1060",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
view={classname="Panel",name="view@fill_layout",parName="default",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1060",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_banner_bg={classname="Panel",name="lay_banner_bg",parName="view",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="174",width="640",x="0",y="868",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="123",anchorPointX="0",anchorPointY="0",},
lay_tab={classname="Panel",name="lay_tab",parName="view",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="640",x="0",y="817",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="16",anchorPointX="0",anchorPointY="0",},
lay_con={classname="Panel",name="lay_con",parName="view",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="630",width="640",x="0",y="154",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="140",anchorPointX="0",anchorPointY="0",},
lay_bottom1={classname="Panel",name="lay_bottom1",parName="view",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="154",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="23",anchorPointX="0",anchorPointY="0",},
lay_bottom2={classname="Panel",name="lay_bottom2",parName="view",childCount="3",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="154",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="35",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lay_smith_hire={classname="Panel",name="lay_smith_hire",parName="lay_banner_bg",ZOrder="11",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="130",width="600",x="20",y="25",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="11",anchorPointX="0",anchorPointY="0",},
lay_content={classname="Panel",name="lay_content",parName="lay_con",childCount="9",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="630",width="640",x="0",y="-18",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="15",anchorPointX="0",anchorPointY="0",},
lay_btn_smiths={classname="Panel",name="lay_btn_smiths",parName="lay_bottom1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="243",y="35",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="34",anchorPointX="0",anchorPointY="0",},
lay_bottom2_banner={classname="Panel",name="lay_bottom2_banner",parName="lay_bottom2",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_jinduyanjiudi.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="320",capInsetsY="35",height="70",width="640",x="0",y="138",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="36",anchorPointX="0",anchorPointY="0",},
lay_btn_quick={classname="Panel",name="lay_btn_quick",parName="lay_bottom2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="243",y="35",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="48",anchorPointX="0",anchorPointY="0",},
lay_btn_finish={classname="Panel",name="lay_btn_finish",parName="lay_bottom2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="243",y="35",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="49",anchorPointX="0",anchorPointY="0",},
}
tTable["index_5"] = {
lay_equip1={classname="Panel",name="lay_equip1",parName="lay_content",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="90",width="90",x="26",y="545",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="12",anchorPointX="0",anchorPointY="0",},
lay_equip2={classname="Panel",name="lay_equip2",parName="lay_content",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="90",width="90",x="125",y="545",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="13",anchorPointX="0",anchorPointY="0",},
lay_equip3={classname="Panel",name="lay_equip3",parName="lay_content",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="90",width="90",x="225",y="545",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="17",anchorPointX="0",anchorPointY="0",},
lay_equip4={classname="Panel",name="lay_equip4",parName="lay_content",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="90",width="90",x="324",y="545",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="18",anchorPointX="0",anchorPointY="0",},
lay_equip5={classname="Panel",name="lay_equip5",parName="lay_content",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="90",width="90",x="424",y="545",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="19",anchorPointX="0",anchorPointY="0",},
lay_equip6={classname="Panel",name="lay_equip6",parName="lay_content",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="90",width="90",x="523",y="545",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="20",anchorPointX="0",anchorPointY="0",},
lay_curr_equip={classname="Panel",name="lay_curr_equip",parName="lay_content",childCount="1",ZOrder="11",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_hechengmingzidi.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="15",capInsetsY="15",height="40",width="212",x="214",y="185",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="22",anchorPointX="0",anchorPointY="0",},
img_curequip={classname="ImageView",name="img_curequip",parName="lay_content",ZOrder="11",fileName="#v1_img_black50.png",scale9Enable="false",scale9Height="20",scale9Width="20",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="20",width="20",x="320",y="305",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="91",anchorPointX="0.5",anchorPointY="0.5",},
img_bg={classname="ImageView",name="img_bg",parName="lay_content",ZOrder="0",fileName="ui/bg_base/v2_bg_tiejiangpu.jpg",scale9Enable="false",scale9Height="648",scale9Width="640",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="648",width="640",x="0",y="0",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="139",anchorPointX="0",anchorPointY="0",},
img_hammer={classname="CustomImageView",name="img_hammer",parName="lay_bottom2_banner",ZOrder="0",fileName="#v1_img_qabb1.png",scale9Enable="false",scale9Height="44",scale9Width="46",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="44",width="46",x="55",y="35",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="43",anchorPointX="0.5",anchorPointY="0.5",},
lay_bar_cd={classname="Panel",name="lay_bar_cd",parName="lay_bottom2_banner",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v1_bar_b1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="45",capInsetsY="9",height="18",width="392",x="87",y="26",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="44",anchorPointX="0",anchorPointY="0",},
img_clock={classname="CustomImageView",name="img_clock",parName="lay_bottom2_banner",ZOrder="1",fileName="#v2_img_clock.png",scale9Enable="false",scale9Height="24",scale9Width="24",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="24",width="24",x="502",y="35",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="45",anchorPointX="0.5",anchorPointY="0.5",},
txt_clock={classname="CustomLabel",name="txt_clock",parName="lay_bottom2_banner",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="518",y="35",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="46",anchorPointX="0",anchorPointY="0.5",},
}
tTable["index_6"] = {
lb_cureq_info={classname="Label",name="lb_cureq_info",parName="lay_curr_equip",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="106",y="20",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="92",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable