local tTable = {}


tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="430",width="560",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="107",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_top={classname="Panel",name="lay_top",parName="default",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen6.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="50",height="130",width="536",x="12",y="287",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="108",anchorPointX="0",anchorPointY="0",},
lay_bottom={classname="Panel",name="lay_bottom",parName="default",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="154",width="560",x="0",y="130",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="114",anchorPointX="0",anchorPointY="0",},
lay_btn={classname="Panel",name="lay_btn",parName="default",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="202",y="30",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="121",anchorPointX="0",anchorPointY="0",},
img_state={classname="ImageView",name="img_state",parName="default",ZOrder="0",fileName="#v2_fonts_yilingqu.png",scale9Enable="false",scale9Height="46",scale9Width="140",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="46",width="140",x="280",y="62",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="397",anchorPointX="0.5",anchorPointY="0.5",},
txt_tip={classname="Label",name="txt_tip",parName="default",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="280",y="61",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="398",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_3"] = {
lay_bg={classname="Panel",name="lay_bg",parName="lay_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen6_b.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="175",capInsetsY="9",height="129",width="350",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="109",anchorPointX="0",anchorPointY="0",},
lay_title={classname="Panel",name="lay_title",parName="lay_top",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_black20.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="10",height="45",width="536",x="0",y="85",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="110",anchorPointX="0",anchorPointY="0",},
lay_bar={classname="Panel",name="lay_bar",parName="lay_top",childCount="1",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v1_bar_b1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="45",capInsetsY="9",height="18",width="300",x="140",y="34",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="113",anchorPointX="0",anchorPointY="0",},
img_icon={classname="ImageView",name="img_icon",parName="lay_top",ZOrder="2",fileName="#v1_btn_gongcheng.png",scale9Enable="false",scale9Height="111",scale9Width="111",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="111",width="111",x="70",y="64",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="396",anchorPointX="0.5",anchorPointY="0.5",},
img1={classname="ImageView",name="img1",parName="lay_bottom",ZOrder="0",fileName="#v2_img_xsfuduqdd.png",scale9Enable="false",scale9Height="13",scale9Width="157",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="13",width="157",x="340",y="131",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="115",anchorPointX="0",anchorPointY="0.5",},
img2={classname="ImageView",name="img2",parName="lay_bottom",ZOrder="0",fileName="#v2_img_xsfuduqdd.png",scale9Enable="false",scale9Height="13",scale9Width="157",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="13",width="157",x="220",y="131",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="180",tag="117",anchorPointX="0",anchorPointY="0.5",},
txt_bottom_title={classname="Label",name="txt_bottom_title",parName="lay_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="任务说明",fontName="微软雅黑",fontSize="20",height="27",width="80",x="280",y="131",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="119",anchorPointX="0.5",anchorPointY="0.5",},
txt_desc={classname="Label",name="txt_desc",parName="lay_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="90",areaWidth="490",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="90",width="490",x="40",y="113",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="120",anchorPointX="0",anchorPointY="1",},
}
tTable["index_4"] = {
txt_title={classname="Label",name="txt_title",parName="lay_title",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="143",y="22",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="111",anchorPointX="0",anchorPointY="0.5",},
txt_bar={classname="Label",name="txt_bar",parName="lay_bar",ZOrder="3",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="150",y="9",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="217",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable