local tTable = {}

tTable["texturesPng"] = {"ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist"}
tTable["index_1"] = {
root={classname="Panel",name="root",parName="root",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="490",width="560",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="171",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
img_bot={classname="ImageView",name="img_bot",parName="root",ZOrder="0",fileName="#v1_img_yindaokuang2.png",scale9Enable="false",scale9Height="42",scale9Width="351",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="42",width="351",x="381",y="26",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="173",anchorPointX="0.5",anchorPointY="0.5",},
lay_bot={classname="Panel",name="lay_bot",parName="root",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/big_img_sep/v1_img_yindaokuang.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="125",capInsetsY="130",height="374",width="500",x="57",y="47",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="175",anchorPointX="0",anchorPointY="0",},
lb_tip={classname="Label",name="lb_tip",parName="root",ZOrder="10",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="点击屏幕任意位置关闭",fontName="微软雅黑",fontSize="20",height="27",width="200",x="380",y="26",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="180",anchorPointX="0.5",anchorPointY="0.5",},
img_qipao={classname="ImageView",name="img_qipao",parName="root",ZOrder="10",fileName="#v1_img_yunqipao.png",scale9Enable="false",scale9Height="140",scale9Width="295",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="140",width="295",x="406",y="403",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="184",anchorPointX="0.5",anchorPointY="0.5",},
lay_tip={classname="Panel",name="lay_tip",parName="root",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="80",width="200",x="308",y="375",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="191",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_title={classname="Panel",name="lay_title",parName="lay_bot",childCount="1",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_xiaobiaoti2.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="182",capInsetsY="24",height="50",width="464",x="25",y="218",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="176",anchorPointX="0",anchorPointY="0",},
lay_content={classname="Panel",name="lay_content",parName="lay_bot",childCount="4",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="144",width="464",x="25",y="75",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="178",anchorPointX="0",anchorPointY="0",},
img_bg={classname="ImageView",name="img_bg",parName="lay_bot",ZOrder="1",fileName="#v1_bg_banshenyindao.png",scale9Enable="false",scale9Height="296",scale9Width="335",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="296",width="335",x="116",y="372",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="174",anchorPointX="0.5",anchorPointY="0.5",},
lay_btn={classname="Panel",name="lay_btn",parName="lay_bot",ZOrder="11",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="185",y="14",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="181",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lb_title={classname="Label",name="lb_title",parName="lay_title",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="领取奖励",fontName="微软雅黑",fontSize="20",height="27",width="80",x="232",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="177",anchorPointX="0.5",anchorPointY="0.5",},
lay_icon_1={classname="Panel",name="lay_icon_1",parName="lay_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="144",width="116",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="187",anchorPointX="0",anchorPointY="0",},
lay_icon_2={classname="Panel",name="lay_icon_2",parName="lay_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="144",width="116",x="116",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="188",anchorPointX="0",anchorPointY="0",},
lay_icon_3={classname="Panel",name="lay_icon_3",parName="lay_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="144",width="116",x="232",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="189",anchorPointX="0",anchorPointY="0",},
lay_icon_4={classname="Panel",name="lay_icon_4",parName="lay_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="144",width="116",x="348",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="190",anchorPointX="0",anchorPointY="0",},
}

return tTable