local tTable = {}


tTable["index_1"] = {
dlg_fuben_layer={classname="Panel",name="dlg_fuben_layer@fill_layout",parName="root",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1066",width="640",x="0",y="0",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
ly_bg={classname="Panel",name="ly_bg@fill_layout_height",parName="dlg_fuben_layer",childCount="6",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1066",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="3688",anchorPointX="0",anchorPointY="0",},
ly_main={classname="Panel",name="ly_main@fill_layout_height",parName="dlg_fuben_layer",childCount="5",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1066",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="3686",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
ly_top={classname="Panel",name="ly_top",parName="ly_bg",childCount="4",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="180",width="600",x="20",y="885",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="42",anchorPointX="0",anchorPointY="0",},
ly_bg_space1={classname="Panel",name="ly_bg_space1@fill_layout",parName="ly_bg",ZOrder="999999",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="0.01",width="640",x="1",y="885",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="3518",anchorPointX="0",anchorPointY="0",},
ly_bg_container={classname="Panel",name="ly_bg_container",parName="ly_bg",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="654",width="640",x="0",y="229",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="3517",anchorPointX="0",anchorPointY="0",},
ly_bg_space2={classname="Panel",name="ly_bg_space2@fill_layout",parName="ly_bg",ZOrder="999999",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="0.01",width="640",x="0",y="229",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="3519",anchorPointX="0",anchorPointY="0",},
ly_tip={classname="Panel",name="ly_tip",parName="ly_bg",childCount="3",ZOrder="4",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_black30.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="10",height="80",width="640",x="0",y="149",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="69",anchorPointX="0",anchorPointY="0",},
ly_reward={classname="Panel",name="ly_reward",parName="ly_bg",childCount="10",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="150",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1135",anchorPointX="0",anchorPointY="0",},
ly_main_space1={classname="Panel",name="ly_main_space1",parName="ly_main",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="180",width="640",x="0",y="885",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="3689",anchorPointX="0",anchorPointY="0",},
ly_main_space2={classname="Panel",name="ly_main_space2@fill_layout",parName="ly_main",ZOrder="99999",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="0.01",width="640",x="0",y="885",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="3691",anchorPointX="0",anchorPointY="0",},
ly_content={classname="Panel",name="ly_content",parName="ly_main",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="654",width="640",x="0",y="229",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="3693",anchorPointX="0",anchorPointY="0",},
ly_main_space3={classname="Panel",name="ly_main_space3@fill_layout",parName="ly_main",ZOrder="99999",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="0.01",width="640",x="0",y="229",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="3692",anchorPointX="0",anchorPointY="0",},
ly_main_space4={classname="Panel",name="ly_main_space4",parName="ly_main",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="230",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="3690",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lay_btn_l={classname="Panel",name="lay_btn_l",parName="ly_top",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_btn_jiantou.png",height="44",width="36",x="94",y="62",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1281",anchorPointX="0",anchorPointY="0",},
lay_btn_r={classname="Panel",name="lay_btn_r",parName="ly_top",childCount="1",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="44",width="36",x="470",y="63",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1283",anchorPointX="0",anchorPointY="0",},
lay_act_btn={classname="Panel",name="lay_act_btn",parName="ly_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="39",width="124",x="0",y="-61",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2656",anchorPointX="0",anchorPointY="0",},
lay_btn_zj={classname="Panel",name="lay_btn_zj",parName="ly_top",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_btn_zj.png",height="42",width="100",x="499",y="-63",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1279",anchorPointX="0",anchorPointY="0",},
ly_map={classname="Panel",name="ly_map",parName="ly_bg_container",ZOrder="0",useMergedTexture="false",clipAble="true",backGroundScale9Enable="false",backGroundImage="ui/fuben/v1_bg_fbdt.jpg",height="1003",width="640",x="0",y="-182",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="68",anchorPointX="0",anchorPointY="0",},
img_route={classname="ImageView",name="img_route",parName="ly_bg_container",ZOrder="1",fileName="ui/fuben/v2_line_fubendi.png",scale9Enable="false",scale9Height="406",scale9Width="391",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="406",width="391",x="328",y="287",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2806",anchorPointX="0.5",anchorPointY="0.5",},
ly_content1={classname="Panel",name="ly_content1",parName="ly_bg_container",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="32",capInsetsY="32",height="886",width="640",x="0",y="-229",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8",anchorPointX="0",anchorPointY="0",},
lb_tip={classname="Label",name="lb_tip",parName="ly_tip",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="36",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1819",anchorPointX="0",anchorPointY="0.5",},
lb_tili={classname="Label",name="lb_tili",parName="ly_tip",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="36",y="53",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2113",anchorPointX="0",anchorPointY="0.5",},
lay_buy_energy_btn={classname="Panel",name="lay_buy_energy_btn",parName="ly_tip",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="39",width="124",x="493",y="19",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2957",anchorPointX="0",anchorPointY="0",},
ly_reward_1={classname="Panel",name="ly_reward_1",parName="ly_reward",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="154",width="122",x="66",y="0",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1287",anchorPointX="0",anchorPointY="0",},
ly_reward_2={classname="Panel",name="ly_reward_2",parName="ly_reward",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="154",width="122",x="259",y="0",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1288",anchorPointX="0",anchorPointY="0",},
ly_reward_3={classname="Panel",name="ly_reward_3",parName="ly_reward",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="154",width="122",x="452",y="0",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1289",anchorPointX="0",anchorPointY="0",},
img_bg_di={classname="ImageView",name="img_bg_di",parName="ly_reward",ZOrder="3",fileName="ui/big_img_sep/v2_img_zhangjiejianglidi_fb.png",scale9Enable="false",scale9Height="150",scale9Width="640",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="150",width="640",x="320",y="75",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2274",anchorPointX="0.5",anchorPointY="0.5",},
img_icon_di_1={classname="ImageView",name="img_icon_di_1",parName="ly_reward",ZOrder="0",fileName="#v2_img_zhangjiejianglidi_fb_b.png",scale9Enable="false",scale9Height="78",scale9Width="78",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="78",width="78",x="127",y="86",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2275",anchorPointX="0.5",anchorPointY="0.5",},
img_icon_di_2={classname="ImageView",name="img_icon_di_2",parName="ly_reward",ZOrder="0",fileName="#v2_img_zhangjiejianglidi_fb_b.png",scale9Enable="false",scale9Height="78",scale9Width="78",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="78",width="78",x="321",y="86",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2277",anchorPointX="0.5",anchorPointY="0.5",},
img_icon_di_3={classname="ImageView",name="img_icon_di_3",parName="ly_reward",ZOrder="0",fileName="#v2_img_zhangjiejianglidi_fb_b.png",scale9Enable="false",scale9Height="78",scale9Width="78",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="78",width="78",x="513",y="86",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2278",anchorPointX="0.5",anchorPointY="0.5",},
img_icon_1={classname="ImageView",name="img_icon_1",parName="ly_reward",ZOrder="1",fileName="#v2_img_cha_fb.png",scale9Enable="false",scale9Height="52",scale9Width="52",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="52",width="52",x="127",y="86",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2280",anchorPointX="0.5",anchorPointY="0.5",},
img_icon_2={classname="ImageView",name="img_icon_2",parName="ly_reward",ZOrder="1",fileName="#v2_img_cha_fb.png",scale9Enable="false",scale9Height="52",scale9Width="52",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="52",width="52",x="320",y="85",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2282",anchorPointX="0.5",anchorPointY="0.5",},
img_icon_3={classname="ImageView",name="img_icon_3",parName="ly_reward",ZOrder="1",fileName="#v2_img_cha_fb.png",scale9Enable="false",scale9Height="52",scale9Width="52",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="52",width="52",x="513",y="86",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2284",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_5"] = {
img_j_r={classname="ImageView",name="img_j_r",parName="lay_btn_r",ZOrder="0",fileName="#v1_btn_jiantou.png",scale9Enable="false",scale9Height="44",scale9Width="36",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="44",width="36",x="14",y="22",visible="true",touchAble="false",flipX="true",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1285",anchorPointX="0.5",anchorPointY="0.5",},
lb_zj={classname="Label",name="lb_zj",parName="lay_btn_zj",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="50",y="21",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1280",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable