local tTable = {}


tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1060",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_top={classname="Panel",name="lay_top",parName="default",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="32",capInsetsY="32",height="192",width="640",x="0",y="868",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9",anchorPointX="0",anchorPointY="0",},
ly_list={classname="Panel",name="ly_list",parName="default",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="780",width="600",x="20",y="23",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="19",anchorPointX="0",anchorPointY="0",},
ly_show_soldier={classname="Panel",name="ly_show_soldier",parName="default",childCount="6",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_xiaobiaoti3.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="320",capInsetsY="25",height="50",width="640",x="0",y="750",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="494",anchorPointX="0",anchorPointY="0",},
lay_tab={classname="Panel",name="lay_tab",parName="default",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="866",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6349",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
ly_talent={classname="Panel",name="ly_talent",parName="lay_top",childCount="2",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_black50.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="10",height="40",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="23",anchorPointX="0",anchorPointY="0",},
lay_banner_bg={classname="Panel",name="lay_banner_bg",parName="lay_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="192",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="5252",anchorPointX="0",anchorPointY="0",},
Image_9={classname="ImageView",name="Image_9",parName="ly_show_soldier",ZOrder="0",fileName="#v1_img_bujiang02.png",scale9Enable="false",scale9Height="34",scale9Width="34",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="34",width="34",x="74",y="23",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="495",anchorPointX="0.5",anchorPointY="0.5",},
Image_9_0={classname="ImageView",name="Image_9_0",parName="ly_show_soldier",ZOrder="0",fileName="#v1_img_gongjiang02.png",scale9Enable="false",scale9Height="34",scale9Width="34",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="34",width="34",x="273",y="23",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="499",anchorPointX="0.5",anchorPointY="0.5",},
lb_gong_nums={classname="CustomLabel",name="lb_gong_nums",parName="ly_show_soldier",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="1024",fontName="微软雅黑",fontSize="20",height="27",width="48",x="304",y="24",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="502",anchorPointX="0",anchorPointY="0.5",},
lb_bu_nums={classname="CustomLabel",name="lb_bu_nums",parName="ly_show_soldier",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="1024",fontName="微软雅黑",fontSize="20",height="27",width="48",x="107",y="24",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="501",anchorPointX="0",anchorPointY="0.5",},
lb_qi_nums={classname="CustomLabel",name="lb_qi_nums",parName="ly_show_soldier",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="1124",fontName="微软雅黑",fontSize="20",height="27",width="48",x="490",y="24",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="503",anchorPointX="0",anchorPointY="0.5",},
Image_9_1={classname="ImageView",name="Image_9_1",parName="ly_show_soldier",ZOrder="0",fileName="#v1_img_qibing02b.png",scale9Enable="false",scale9Height="34",scale9Width="34",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="34",width="34",x="462",y="23",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="500",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_4"] = {
ly_talent_switch={classname="Panel",name="ly_talent_switch",parName="ly_talent",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="28",width="64",x="512",y="6",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="34",anchorPointX="0",anchorPointY="0",},
lb_talent_tips={classname="CustomLabel",name="lb_talent_tips",parName="ly_talent",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="显示资质",fontName="微软雅黑",fontSize="20",height="27",width="80",x="491",y="20",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="24",anchorPointX="1",anchorPointY="0.5",},
}

return tTable