local tTable = {}


tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="760",width="550",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="393",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
view={classname="Panel",name="view",parName="default",childCount="7",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="760",width="550",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="394",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_info={classname="Panel",name="lay_info",parName="view",childCount="10",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="160",width="520",x="13",y="590",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2163",anchorPointX="0",anchorPointY="0",},
lay_banner={classname="Panel",name="lay_banner",parName="view",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_xiaobiaoti2.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="186",capInsetsY="24",height="40",width="520",x="13",y="542",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2173",anchorPointX="0",anchorPointY="0",},
lay_rewards={classname="Panel",name="lay_rewards",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="270",width="520",x="13",y="270",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2175",anchorPointX="0",anchorPointY="0",},
lay_btn_collection={classname="Panel",name="lay_btn_collection",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="65",width="155",x="200",y="39",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2224",anchorPointX="0",anchorPointY="0",},
lay_richtext_tip={classname="Panel",name="lay_richtext_tip",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="27",width="95",x="67",y="209",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="10147",anchorPointX="0",anchorPointY="0",},
txt_produce_tip={classname="CustomLabel",name="txt_produce_tip",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="278",y="131",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="11286",anchorPointX="0.5",anchorPointY="0.5",},
txt_db_produce_tip={classname="CustomLabel",name="txt_db_produce_tip",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="278",y="23",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="19215",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_4"] = {
txt_name={classname="CustomLabel",name="txt_name",parName="lay_info",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="162",y="132",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2164",anchorPointX="0",anchorPointY="0.5",},
txt_pos_title={classname="CustomLabel",name="txt_pos_title",parName="lay_info",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="坐标：",fontName="微软雅黑",fontSize="20",height="27",width="60",x="162",y="95",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2166",anchorPointX="0",anchorPointY="0.5",},
txt_pos={classname="CustomLabel",name="txt_pos",parName="lay_info",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="224",y="93",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2167",anchorPointX="0",anchorPointY="0.5",},
txt_owner_title={classname="CustomLabel",name="txt_owner_title",parName="lay_info",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="城主：",fontName="微软雅黑",fontSize="20",height="27",width="60",x="162",y="58",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2168",anchorPointX="0",anchorPointY="0.5",},
txt_finish_tip={classname="CustomLabel",name="txt_finish_tip",parName="lay_info",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="图纸已生产完毕",fontName="微软雅黑",fontSize="20",height="27",width="140",x="162",y="21",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2170",anchorPointX="0",anchorPointY="0.5",},
txt_finish_cd={classname="CustomLabel",name="txt_finish_cd",parName="lay_info",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="303",y="21",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2171",anchorPointX="0",anchorPointY="0.5",},
img_flag={classname="CustomImageView",name="img_flag",parName="lay_info",ZOrder="1",fileName="#v1_img_qun.png",scale9Enable="false",scale9Height="64",scale9Width="51",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="64",width="51",x="477",y="115",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2172",anchorPointX="0.5",anchorPointY="0.5",},
txt_owner_name={classname="CustomLabel",name="txt_owner_name",parName="lay_info",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="224",y="57",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2250",anchorPointX="0",anchorPointY="0.5",},
lay_icon={classname="Panel",name="lay_icon",parName="lay_info",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="130",width="150",x="6",y="12",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="5697",anchorPointX="0",anchorPointY="0",},
lay_act_btn={classname="Panel",name="lay_act_btn",parName="lay_info",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="39",width="124",x="324",y="98",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="20832",anchorPointX="0",anchorPointY="0",},
txt_banner_tip={classname="CustomLabel",name="txt_banner_tip",parName="lay_banner",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="30",y="20",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2174",anchorPointX="0",anchorPointY="0.5",},
}

return tTable