local tTable = {}

tTable["texturesPng"] = {"ui/p2_commmon1_sep.plist","ui/language/cn/p1_font1.plist","ui/fuben/v2_bg_duizhan_fuben.jpg","ui/p1_commmon3_sep.plist"}
tTable["index_1"] = {
dlg_fuben_layer={classname="Panel",name="dlg_fuben_layer@fill_layout",parName="root",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1066",width="640",x="0",y="0",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
ly_title={classname="Panel",name="ly_title",parName="dlg_fuben_layer",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="216",width="640",x="0",y="841",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="73",anchorPointX="0",anchorPointY="0",},
ly_content={classname="Panel",name="ly_content@fill_layout",parName="dlg_fuben_layer",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="700",width="640",x="0",y="139",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8",anchorPointX="0",anchorPointY="0",},
ly_down={classname="Panel",name="ly_down",parName="dlg_fuben_layer",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="135",width="640",x="2",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="88",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_zhanli={classname="Panel",name="lay_zhanli",parName="ly_title",childCount="6",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="166",width="640",x="0",y="49",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4650",anchorPointX="0",anchorPointY="0",},
Panel_4={classname="Panel",name="Panel_4",parName="ly_title",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_biaoqiantiao.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="25",capInsetsY="25",height="50",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2442",anchorPointX="0",anchorPointY="0",},
img_duizhan={classname="ImageView",name="img_duizhan",parName="ly_title",ZOrder="0",fileName="ui/fuben/v2_bg_duizhan_fuben.jpg",scale9Enable="false",scale9Height="166",scale9Width="640",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="166",width="640",x="320",y="133",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2443",anchorPointX="0.5",anchorPointY="0.5",},
ly_army={classname="Panel",name="ly_army@fill_layout",parName="ly_content",ZOrder="0",useMergedTexture="false",clipAble="true",backGroundScale9Enable="false",height="700",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="94",anchorPointX="0",anchorPointY="0",},
ly_down_btn_l={classname="Panel",name="ly_down_btn_l",parName="ly_down",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="442",y="27",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="89",anchorPointX="0",anchorPointY="0",},
ly_down_btn_r={classname="Panel",name="ly_down_btn_r",parName="ly_down",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="39",y="27",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="91",anchorPointX="0",anchorPointY="0",},
lb_energy={classname="CustomLabel",name="lb_energy",parName="ly_down",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="517",y="112",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="93",anchorPointX="0.5",anchorPointY="0.5",},
ly_down_btn_m={classname="Panel",name="ly_down_btn_m",parName="ly_down",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="241",y="26",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="3981",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
Image_6={classname="ImageView",name="Image_6",parName="lay_zhanli",ZOrder="1",fileName="#v2_img_zjm_zhanli.png",scale9Enable="false",scale9Height="41",scale9Width="40",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="41",width="40",x="63",y="52",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="81",anchorPointX="0.5",anchorPointY="0.5",},
Image_7={classname="ImageView",name="Image_7",parName="lay_zhanli",ZOrder="1",fileName="#v2_img_zjm_zhanli.png",scale9Enable="false",scale9Height="41",scale9Width="40",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="41",width="40",x="483",y="52",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="82",anchorPointX="0.5",anchorPointY="0.5",},
Image_9={classname="ImageView",name="Image_9",parName="lay_zhanli",ZOrder="1",fileName="#v1_fonts_ofighting.png",scale9Enable="false",scale9Height="24",scale9Width="109",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="24",width="109",x="111",y="93",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="84",anchorPointX="0.5",anchorPointY="0.5",},
Image_10={classname="ImageView",name="Image_10",parName="lay_zhanli",ZOrder="1",fileName="#v1_fonts_efighting.png",scale9Enable="false",scale9Height="24",scale9Width="110",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="24",width="110",x="529",y="93",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="85",anchorPointX="0.5",anchorPointY="0.5",},
lb_my_fight={classname="CustomLabel",name="lb_my_fight",parName="lay_zhanli",ZOrder="2",colorB="70",colorG="235",colorR="251",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="90",y="52",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="86",anchorPointX="0",anchorPointY="0.5",},
lb_enemy_fight={classname="CustomLabel",name="lb_enemy_fight",parName="lay_zhanli",ZOrder="2",colorB="70",colorG="235",colorR="251",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="509",y="52",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="87",anchorPointX="0",anchorPointY="0.5",},
lb_army_account={classname="CustomLabel",name="lb_army_account",parName="Panel_4",ZOrder="0",colorB="181",colorG="151",colorR="118",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="320",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="92",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable