local tTable = {}


tTable["index_1"] = {
default={classname="Panel",name="default@fill_layout",parName="root",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1066",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_bg_top={classname="Panel",name="lay_bg_top",parName="default",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="ui/v1_bg_mengban.png",height="450",width="900",x="-130",y="618",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8",anchorPointX="0",anchorPointY="0",},
lay_bg_bottom={classname="Panel",name="lay_bg_bottom@fill_layout",parName="default",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="32",capInsetsY="32",height="900",width="900",x="-130",y="-275",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9",anchorPointX="0",anchorPointY="0",},
lay_uplv_main={classname="Panel",name="lay_uplv_main@fill_layout_height",parName="default",childCount="3",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1066",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="13",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_up_banner={classname="Panel",name="lay_up_banner",parName="lay_uplv_main",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_bannaerkuang.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="65",capInsetsY="65",height="290",width="600",x="20",y="760",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="11",anchorPointX="0",anchorPointY="0",},
lay_up_content={classname="Panel",name="lay_up_content@fill_layout",parName="lay_uplv_main",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="560",width="600",x="20",y="200",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="14",anchorPointX="0",anchorPointY="0",},
lay_up_bottom={classname="Panel",name="lay_up_bottom",parName="lay_uplv_main",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="200",width="600",x="20",y="2",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="15",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lay_lv={classname="Panel",name="lay_lv",parName="lay_up_banner",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_img_djbq.png",height="46",width="147",x="8",y="20",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="22",anchorPointX="0",anchorPointY="0",},
lay_next={classname="Panel",name="lay_next",parName="lay_up_banner",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_img_djqz.png",height="112",width="112",x="430",y="172",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="24",anchorPointX="0",anchorPointY="0",},
lay_tips={classname="Panel",name="lay_tips",parName="lay_up_content",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_xiaobiaoti2.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="186",capInsetsY="0",height="48",width="600",x="0",y="502",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="16",anchorPointX="0",anchorPointY="0",},
lay_up_details={classname="Panel",name="lay_up_details",parName="lay_up_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="455",width="600",x="0",y="47",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="18",anchorPointX="0",anchorPointY="0",},
lay_tip_bottom={classname="Panel",name="lay_tip_bottom",parName="lay_up_content",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="45",width="600",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="667",anchorPointX="0",anchorPointY="0",},
lay_btn_left={classname="Panel",name="lay_btn_left",parName="lay_up_bottom",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="50",y="40",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="20",anchorPointX="0",anchorPointY="0",},
lay_btn_right={classname="Panel",name="lay_btn_right",parName="lay_up_bottom",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="395",y="40",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="21",anchorPointX="0",anchorPointY="0",},
}
tTable["index_5"] = {
lb_lv={classname="Label",name="lb_lv",parName="lay_lv",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Lv.15 王宫",fontName="微软雅黑",fontSize="20",height="27",width="96",x="5",y="23",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="23",anchorPointX="0",anchorPointY="0.5",},
lb_next_tips={classname="Label",name="lb_next_tips",parName="lay_next",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="下一等级",fontName="微软雅黑",fontSize="20",height="27",width="80",x="56",y="80",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="25",anchorPointX="0.5",anchorPointY="0.5",},
lb_next_lv={classname="Label",name="lb_next_lv",parName="lay_next",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="lv.6",fontName="微软雅黑",fontSize="20",height="27",width="33",x="56",y="45",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="26",anchorPointX="0.5",anchorPointY="0.5",},
lb_tips={classname="Label",name="lb_tips",parName="lay_tips",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="升级需求",fontName="微软雅黑",fontSize="20",height="27",width="80",x="55",y="24",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="17",anchorPointX="0.5",anchorPointY="0.5",},
lb_tips2={classname="Label",name="lb_tips2",parName="lay_tip_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="提示：升级VIP可以免费减少更多建造时间",fontName="微软雅黑",fontSize="20",height="27",width="372",x="299",y="22",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="19",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable