local tTable = {}


tTable["index_1"] = {
dlg_hero_advance={classname="Panel",name="dlg_hero_advance",parName="root",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="740",width="560",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2603",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
ly_hero={classname="Panel",name="ly_hero",parName="dlg_hero_advance",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="420",width="560",x="0",y="319",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2608",anchorPointX="0",anchorPointY="0",},
ly_bottom={classname="Panel",name="ly_bottom",parName="dlg_hero_advance",childCount="8",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="157",capInsetsY="5",height="170",width="560",x="-1",y="-1",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2610",anchorPointX="0",anchorPointY="0",},
ly_content={classname="Panel",name="ly_content",parName="dlg_hero_advance",childCount="3",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="150",width="560",x="0",y="169",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2612",anchorPointX="0",anchorPointY="0",},
lay_autorefinelb={classname="Panel",name="lay_autorefinelb",parName="dlg_hero_advance",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v2_img_jinduyanjiudi.png",height="70",width="640",x="-40",y="299",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="5966",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
ly_hero_1={classname="Panel",name="ly_hero_1",parName="ly_hero",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="400",width="250",x="10",y="2",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2605",anchorPointX="0",anchorPointY="0",},
ly_hero_2={classname="Panel",name="ly_hero_2",parName="ly_hero",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="400",width="250",x="300",y="2",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2607",anchorPointX="0",anchorPointY="0",},
img_arrow={classname="CustomImageView",name="img_arrow",parName="ly_hero",ZOrder="250",fileName="#v1_img_shengjijiantou.png",scale9Enable="false",scale9Height="45",scale9Width="50",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="45",width="50",x="272",y="206",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2611",anchorPointX="0.5",anchorPointY="0.5",},
ly_need={classname="Panel",name="ly_need",parName="ly_bottom",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="27",y="37",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2909",anchorPointX="0",anchorPointY="0",},
lb_need={classname="CustomLabel",name="lb_need",parName="ly_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="进阶石",fontName="微软雅黑",fontSize="20",height="27",width="60",x="160",y="117",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="3194",anchorPointX="0",anchorPointY="0.5",},
lb_cost={classname="CustomLabel",name="lb_cost",parName="ly_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="进阶消耗：",fontName="微软雅黑",fontSize="20",height="27",width="100",x="153",y="69",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="3196",anchorPointX="0",anchorPointY="0.5",},
lb_cost_value={classname="CustomLabel",name="lb_cost_value",parName="ly_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="500/999",fontName="微软雅黑",fontSize="20",height="27",width="81",x="256",y="69",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="3482",anchorPointX="0",anchorPointY="0.5",},
ly_btn={classname="Panel",name="ly_btn",parName="ly_bottom",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="401",y="38",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="3483",anchorPointX="0",anchorPointY="0",},
lb_cost_tips={classname="CustomLabel",name="lb_cost_tips",parName="ly_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="进阶消耗：",fontName="微软雅黑",fontSize="18",height="24",width="90",x="280",y="17",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="5531",anchorPointX="0.5",anchorPointY="0.5",},
lay_checkbox={classname="Panel",name="lay_checkbox",parName="ly_bottom",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="40",x="399",y="101",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="5967",anchorPointX="0",anchorPointY="0",},
lb_checktext={classname="Label",name="lb_checktext",parName="ly_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="自动进阶",fontName="微软雅黑",fontSize="20",height="27",width="80",x="489",y="122",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="5968",anchorPointX="0.5",anchorPointY="0.5",},
ly_tips_1={classname="Panel",name="ly_tips_1",parName="ly_content",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_black30.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="2",capInsetsY="2",height="100",width="520",x="20",y="23",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2613",anchorPointX="0",anchorPointY="0",},
ly_tips_2={classname="Panel",name="ly_tips_2",parName="ly_content",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="100",width="520",x="20",y="27",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2621",anchorPointX="0",anchorPointY="0",},
ly_tips_3={classname="Panel",name="ly_tips_3",parName="ly_content",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="100",width="520",x="20",y="21",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4459",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
ly_bar_info={classname="Panel",name="ly_bar_info",parName="ly_tips_1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v1_bar_b1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="45",capInsetsY="9",height="15",width="296",x="106",y="57",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2615",anchorPointX="0",anchorPointY="0",},
lb_advance={classname="CustomLabel",name="lb_advance",parName="ly_tips_1",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="进阶值",fontName="微软雅黑",fontSize="20",height="27",width="60",x="55",y="65",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2623",anchorPointX="0.5",anchorPointY="0.5",},
lb_advance_value={classname="CustomLabel",name="lb_advance_value",parName="ly_tips_1",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="进阶值",fontName="微软雅黑",fontSize="20",height="27",width="60",x="462",y="65",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2625",anchorPointX="0.5",anchorPointY="0.5",},
lb_advance_tips={classname="CustomLabel",name="lb_advance_tips",parName="ly_tips_1",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="进阶值",fontName="微软雅黑",fontSize="20",height="27",width="60",x="260",y="27",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2627",anchorPointX="0.5",anchorPointY="0.5",},
ly_condition_1={classname="Panel",name="ly_condition_1",parName="ly_tips_2",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="520",x="0",y="54",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2900",anchorPointX="0",anchorPointY="0",},
ly_condition_2={classname="Panel",name="ly_condition_2",parName="ly_tips_2",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="520",x="0",y="7",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2906",anchorPointX="0",anchorPointY="0",},
lb_finish={classname="CustomLabel",name="lb_finish",parName="ly_tips_3",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="24",height="31",width="116",x="260",y="50",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4460",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_5"] = {
img_gou_1={classname="CustomImageView",name="img_gou_1",parName="ly_condition_1",ZOrder="0",fileName="#v1_img_zybz.png",scale9Enable="false",scale9Height="25",scale9Width="28",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="25",width="28",x="114",y="20",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2901",anchorPointX="0.5",anchorPointY="0.5",},
lb_condition_1={classname="CustomLabel",name="lb_condition_1",parName="ly_condition_1",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="24",height="31",width="116",x="152",y="21",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2902",anchorPointX="0",anchorPointY="0.5",},
img_gou_2={classname="CustomImageView",name="img_gou_2",parName="ly_condition_2",ZOrder="0",fileName="#v1_img_zybz.png",scale9Enable="false",scale9Height="25",scale9Width="28",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="25",width="28",x="114",y="20",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2907",anchorPointX="0.5",anchorPointY="0.5",},
lb_condition_2={classname="CustomLabel",name="lb_condition_2",parName="ly_condition_2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="24",height="31",width="116",x="152",y="21",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2908",anchorPointX="0",anchorPointY="0.5",},
}

return tTable