local tTable = {}


tTable["index_1"] = {
default={classname="Panel",name="default@fill_layout",parName="root",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="ui/v2_bg_kejizonglan.jpg",height="1060",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="118",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
img_title={classname="Panel",name="img_title",parName="default",childCount="2",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="230",width="640",x="0",y="826",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="120",anchorPointX="0",anchorPointY="0",},
ly_pro={classname="Panel",name="ly_pro",parName="default",childCount="2",ZOrder="4",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_ptou1d5.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="5",capInsetsY="20",height="110",width="640",x="0",y="716",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="122",anchorPointX="0",anchorPointY="0",},
ly_center={classname="Panel",name="ly_center",parName="default",childCount="12",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="270",width="640",x="0",y="446",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="157",anchorPointX="0",anchorPointY="0",},
lay_bottom={classname="Panel",name="lay_bottom",parName="default",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="5",capInsetsY="5",height="445",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="173",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_banner_bg={classname="Panel",name="lay_banner_bg",parName="img_title",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="230",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="121",anchorPointX="0",anchorPointY="0",},
img_title_2={classname="CustomImageView",name="img_title_2",parName="img_title",ZOrder="10",fileName="#v2_fonts_yjhxkj.png",scale9Enable="false",scale9Height="156",scale9Width="383",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="156",width="383",x="438",y="124",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="190",anchorPointX="0.5",anchorPointY="0.5",},
ly_pro_title={classname="Panel",name="ly_pro_title",parName="ly_pro",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_benxin.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="20",capInsetsY="20",height="26",width="196",x="222",y="82",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="123",anchorPointX="0",anchorPointY="0",},
ly_bar={classname="Panel",name="ly_bar",parName="ly_pro",childCount="11",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v1_bar_yellow_1gg.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="5",capInsetsY="5",height="14",width="570",x="34",y="38",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="125",anchorPointX="0",anchorPointY="0",},
ly_center_title={classname="Panel",name="ly_center_title",parName="ly_center",childCount="1",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_xiaobiaoti2.png",capInsetsHeight="10",capInsetsWidth="200",capInsetsX="150",capInsetsY="40",height="50",width="640",x="0",y="219",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="158",anchorPointX="0",anchorPointY="0",},
img_icon={classname="CustomImageView",name="img_icon",parName="ly_center",ZOrder="0",fileName="#i3009_s.png",scale9Enable="false",scale9Height="96",scale9Width="96",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="96",width="96",x="128",y="125",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="174",anchorPointX="0.5",anchorPointY="0.5",},
img_frame={classname="CustomImageView",name="img_frame",parName="ly_center",ZOrder="10",fileName="#v2_img_gaojiyubi.png",scale9Enable="false",scale9Height="193",scale9Width="170",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="193",width="170",x="129",y="110",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="160",anchorPointX="0.5",anchorPointY="0.5",},
lb_des2={classname="CustomLabel",name="lb_des2",parName="ly_center",ZOrder="11",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="128",y="19",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="180",anchorPointX="0.5",anchorPointY="0.5",},
lb_des={classname="CustomLabel",name="lb_des",parName="ly_center",ZOrder="10",colorB="255",colorG="255",colorR="255",areaHeight="52",areaWidth="350",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="52",width="350",x="246",y="209",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="161",anchorPointX="0",anchorPointY="1",},
lb_tips={classname="CustomLabel",name="lb_tips",parName="ly_center",ZOrder="10",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="解锁条件：",fontName="微软雅黑",fontSize="22",height="30",width="110",x="246",y="134",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="162",anchorPointX="0",anchorPointY="0.5",},
img_state_1={classname="CustomImageView",name="img_state_1",parName="ly_center",ZOrder="10",fileName="#v1_img_goua.png",scale9Enable="false",scale9Height="39",scale9Width="40",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="39",width="40",x="284",y="98",visible="true",touchAble="false",flipX="false",scaleX="0.7",scaleY="0.7",opacity="255",rotation="0",tag="163",anchorPointX="0.5",anchorPointY="0.5",},
img_state_2={classname="CustomImageView",name="img_state_2",parName="ly_center",ZOrder="10",fileName="#v1_img_goua.png",scale9Enable="false",scale9Height="39",scale9Width="40",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="39",width="40",x="284",y="62",visible="true",touchAble="false",flipX="false",scaleX="0.7",scaleY="0.7",opacity="255",rotation="0",tag="165",anchorPointX="0.5",anchorPointY="0.5",},
img_state_3={classname="CustomImageView",name="img_state_3",parName="ly_center",ZOrder="10",fileName="#v1_img_goua.png",scale9Enable="false",scale9Height="39",scale9Width="40",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="39",width="40",x="284",y="27",visible="true",touchAble="false",flipX="false",scaleX="0.7",scaleY="0.7",opacity="255",rotation="0",tag="167",anchorPointX="0.5",anchorPointY="0.5",},
lb_state_1={classname="CustomLabel",name="lb_state_1",parName="ly_center",ZOrder="10",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="319",y="98",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="168",anchorPointX="0",anchorPointY="0.5",},
lb_state_2={classname="CustomLabel",name="lb_state_2",parName="ly_center",ZOrder="10",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="319",y="62",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="170",anchorPointX="0",anchorPointY="0.5",},
lb_state_3={classname="CustomLabel",name="lb_state_3",parName="ly_center",ZOrder="10",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="319",y="27",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="172",anchorPointX="0",anchorPointY="0.5",},
lay_content={classname="Panel",name="lay_content@fill_layout",parName="lay_bottom",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="440",width="600",x="20",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="191",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lb_pro_title={classname="CustomLabel",name="lb_pro_title",parName="ly_pro_title",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="98",y="14",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="124",anchorPointX="0.5",anchorPointY="0.5",},
bar_1={classname="Panel",name="bar_1",parName="ly_bar",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v2_bar_b2a.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="5",capInsetsY="5",height="14",width="114",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="137",anchorPointX="0",anchorPointY="0",},
bar_2={classname="Panel",name="bar_2",parName="ly_bar",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v2_bar_b2a.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="5",capInsetsY="5",height="14",width="114",x="114",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="139",anchorPointX="0",anchorPointY="0",},
bar_3={classname="Panel",name="bar_3",parName="ly_bar",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v2_bar_b2a.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="5",capInsetsY="5",height="14",width="114",x="228",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="141",anchorPointX="0",anchorPointY="0",},
bar_4={classname="Panel",name="bar_4",parName="ly_bar",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v2_bar_b2a.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="5",capInsetsY="5",height="14",width="114",x="342",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="143",anchorPointX="0",anchorPointY="0",},
bar_5={classname="Panel",name="bar_5",parName="ly_bar",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v2_bar_b2a.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="5",capInsetsY="5",height="14",width="114",x="456",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="145",anchorPointX="0",anchorPointY="0",},
ly_img_1={classname="Panel",name="ly_img_1",parName="ly_bar",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="75",width="75",x="-26",y="-31",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="146",anchorPointX="0",anchorPointY="0",},
ly_img_2={classname="Panel",name="ly_img_2",parName="ly_bar",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="75",width="75",x="84",y="-31",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="149",anchorPointX="0",anchorPointY="0",},
ly_img_3={classname="Panel",name="ly_img_3",parName="ly_bar",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="75",width="75",x="197",y="-31",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="151",anchorPointX="0",anchorPointY="0",},
ly_img_4={classname="Panel",name="ly_img_4",parName="ly_bar",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="75",width="75",x="311",y="-31",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="153",anchorPointX="0",anchorPointY="0",},
ly_img_5={classname="Panel",name="ly_img_5",parName="ly_bar",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="75",width="75",x="424",y="-31",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="155",anchorPointX="0",anchorPointY="0",},
lay_reward={classname="Panel",name="lay_reward",parName="ly_bar",childCount="1",ZOrder="15",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="100",width="100",x="516",y="-47",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="236",anchorPointX="0",anchorPointY="0",},
img_title_1={classname="CustomImageView",name="img_title_1",parName="ly_center_title",ZOrder="0",fileName="#v2_fonts_cjybs.png",scale9Enable="false",scale9Height="24",scale9Width="120",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="24",width="120",x="16",y="26",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="159",anchorPointX="0",anchorPointY="0.5",},
}
tTable["index_5"] = {
img_6={classname="CustomImageView",name="img_6",parName="lay_reward",ZOrder="100",fileName="#v1_img_guojia_renwubaoxiang1.png",scale9Enable="false",scale9Height="96",scale9Width="96",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="96",width="96",x="49",y="53",visible="true",touchAble="false",flipX="false",scaleX="0.9",scaleY="0.9",opacity="255",rotation="0",tag="156",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable