local tTable = {}

tTable["texturesPng"] = {"ui/p1_commmon1_sep.plist","ui/p1_commmon2_sep.plist","ui/p2_commmon1_sep.plist","ui/bar/v1_bar_b1.png","ui/p1_commonse2.plist"}
tTable["index_1"] = {
dlg_hero_train={classname="Panel",name="dlg_hero_train",parName="root",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="460",width="560",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="587",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
ly_hero_list={classname="Panel",name="ly_hero_list",parName="dlg_hero_train",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="160",width="560",x="0",y="300",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="588",anchorPointX="0",anchorPointY="0",},
ly_content={classname="Panel",name="ly_content",parName="dlg_hero_train",childCount="27",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="300",width="500",x="30",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="591",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
img_arrow={classname="ImageView",name="img_arrow",parName="ly_hero_list",ZOrder="5",fileName="#v1_img_sanjiaojiantou.png",scale9Enable="false",scale9Height="26",scale9Width="41",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="26",width="41",x="72",y="13",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="589",anchorPointX="0.5",anchorPointY="0.5",},
ly_hero_online={classname="Panel",name="ly_hero_online",parName="ly_hero_list",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen7.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="63",capInsetsY="65",height="130",width="542",x="9",y="21",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="590",anchorPointX="0",anchorPointY="0",},
img_1={classname="ImageView",name="img_1",parName="ly_content",ZOrder="1",fileName="#v1_img_jianbian2.png",scale9Enable="true",scale9Height="49",scale9Width="500",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="147",capInsetsY="25",height="49",width="500",x="250",y="324",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="597",anchorPointX="0.5",anchorPointY="0.5",},
lb_train_title={classname="CustomLabel",name="lb_train_title",parName="ly_content",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="250",y="325",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="598",anchorPointX="0.5",anchorPointY="0.5",},
img_2={classname="ImageView",name="img_2",parName="ly_content",ZOrder="1",fileName="#v1_img_jianbian2.png",scale9Enable="false",scale9Height="49",scale9Width="294",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="147",capInsetsY="25",height="49",width="294",x="247",y="260",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="600",anchorPointX="0.5",anchorPointY="0.5",},
img_info_1={classname="ImageView",name="img_info_1",parName="ly_content",ZOrder="1",fileName="#v2_img_wj_zizhi.png",scale9Enable="false",scale9Height="30",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="30",width="31",x="70",y="194",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="606",anchorPointX="0.5",anchorPointY="0.5",},
img_info_2={classname="ImageView",name="img_info_2",parName="ly_content",ZOrder="1",fileName="#v2_img_wj_gong.png",scale9Enable="false",scale9Height="30",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="30",width="31",x="70",y="136",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="607",anchorPointX="0.5",anchorPointY="0.5",},
img_info_3={classname="ImageView",name="img_info_3",parName="ly_content",ZOrder="1",fileName="#v2_img_wj_fang.png",scale9Enable="false",scale9Height="30",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="30",width="31",x="70",y="78",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="608",anchorPointX="0.5",anchorPointY="0.5",},
img_info_4={classname="ImageView",name="img_info_4",parName="ly_content",ZOrder="1",fileName="#v2_img_wj_bing.png",scale9Enable="false",scale9Height="30",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="30",width="31",x="70",y="20",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="609",anchorPointX="0.5",anchorPointY="0.5",},
lb_info_n_1={classname="CustomLabel",name="lb_info_n_1",parName="ly_content",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="资",fontName="微软雅黑",fontSize="20",height="27",width="20",x="105",y="194",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="611",anchorPointX="0",anchorPointY="0.5",},
lb_info_n_2={classname="CustomLabel",name="lb_info_n_2",parName="ly_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="攻",fontName="微软雅黑",fontSize="20",height="27",width="20",x="105",y="136",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="612",anchorPointX="0",anchorPointY="0.5",},
lb_info_n_3={classname="CustomLabel",name="lb_info_n_3",parName="ly_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="防",fontName="微软雅黑",fontSize="20",height="27",width="20",x="105",y="78",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="613",anchorPointX="0",anchorPointY="0.5",},
lb_info_n_4={classname="CustomLabel",name="lb_info_n_4",parName="ly_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="兵",fontName="微软雅黑",fontSize="20",height="27",width="20",x="105",y="20",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="614",anchorPointX="0",anchorPointY="0.5",},
ly_bar_info_1={classname="Panel",name="ly_bar_info_1",parName="ly_content",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v1_bar_b1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="45",capInsetsY="9",height="18",width="146",x="151",y="185",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="618",anchorPointX="0",anchorPointY="0",},
ly_bar_info_2={classname="Panel",name="ly_bar_info_2",parName="ly_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v1_bar_b1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="45",capInsetsY="9",height="18",width="146",x="151",y="126",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="619",anchorPointX="0",anchorPointY="0",},
ly_bar_info_3={classname="Panel",name="ly_bar_info_3",parName="ly_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v1_bar_b1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="45",capInsetsY="9",height="18",width="146",x="151",y="69",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="620",anchorPointX="0",anchorPointY="0",},
ly_bar_info_4={classname="Panel",name="ly_bar_info_4",parName="ly_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v1_bar_b1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="45",capInsetsY="9",height="18",width="146",x="151",y="11",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="621",anchorPointX="0",anchorPointY="0",},
lb_info_v_1={classname="CustomLabel",name="lb_info_v_1",parName="ly_content",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="40",fontName="微软雅黑",fontSize="20",height="27",width="24",x="330",y="194",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="622",anchorPointX="0",anchorPointY="0.5",},
lb_info_v_2={classname="CustomLabel",name="lb_info_v_2",parName="ly_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="40",fontName="微软雅黑",fontSize="20",height="27",width="24",x="330",y="136",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="623",anchorPointX="0",anchorPointY="0.5",},
lb_info_v_3={classname="CustomLabel",name="lb_info_v_3",parName="ly_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="40",fontName="微软雅黑",fontSize="20",height="27",width="24",x="330",y="78",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="624",anchorPointX="0",anchorPointY="0.5",},
lb_info_v_4={classname="CustomLabel",name="lb_info_v_4",parName="ly_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="40",fontName="微软雅黑",fontSize="20",height="27",width="24",x="330",y="20",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="625",anchorPointX="0",anchorPointY="0.5",},
lb_add={classname="CustomLabel",name="lb_add",parName="ly_content",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="+20",fontName="微软雅黑",fontSize="20",height="27",width="39",x="361",y="194",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="626",anchorPointX="0",anchorPointY="0.5",},
lb_info_ex_1={classname="CustomLabel",name="lb_info_ex_1",parName="ly_content",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="1",fontName="微软雅黑",fontSize="20",height="27",width="12",x="445",y="194",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="627",anchorPointX="0.5",anchorPointY="0.5",},
lb_info_ex_2={classname="CustomLabel",name="lb_info_ex_2",parName="ly_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="已满",fontName="微软雅黑",fontSize="20",height="27",width="40",x="445",y="136",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="628",anchorPointX="0.5",anchorPointY="0.5",},
lb_info_ex_3={classname="CustomLabel",name="lb_info_ex_3",parName="ly_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="已满",fontName="微软雅黑",fontSize="20",height="27",width="40",x="445",y="78",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="629",anchorPointX="0.5",anchorPointY="0.5",},
lb_info_ex_4={classname="CustomLabel",name="lb_info_ex_4",parName="ly_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="已满",fontName="微软雅黑",fontSize="20",height="27",width="40",x="445",y="20",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="630",anchorPointX="0.5",anchorPointY="0.5",},
img_ex={classname="ImageView",name="img_ex",parName="ly_content",ZOrder="1",fileName="#v1_img_xiangshangjiantou.png",scale9Enable="false",scale9Height="17",scale9Width="12",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="17",width="12",x="425",y="194",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="631",anchorPointX="0.5",anchorPointY="0.5",},
lb_time={classname="CustomLabel",name="lb_time",parName="ly_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="(21:00:00)",fontName="微软雅黑",fontSize="20",height="27",width="96",x="231",y="-20",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="596",anchorPointX="0.5",anchorPointY="0.5",},
img_zhizhibg={classname="ImageView",name="img_zhizhibg",parName="ly_content",ZOrder="0",fileName="#v2_img_jinduyanjiudi.png",scale9Enable="false",scale9Height="70",scale9Width="640",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="70",width="640",x="250",y="194",visible="true",touchAble="false",flipX="false",scaleX="0.79999995",scaleY="0.79999995",opacity="255",rotation="0",tag="2191",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_4"] = {
ly_hero_1={classname="Panel",name="ly_hero_1",parName="ly_hero_online",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="15",y="11",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="695",anchorPointX="0",anchorPointY="0",},
ly_hero_2={classname="Panel",name="ly_hero_2",parName="ly_hero_online",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="149",y="11",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="696",anchorPointX="0",anchorPointY="0",},
ly_hero_3={classname="Panel",name="ly_hero_3",parName="ly_hero_online",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="284",y="11",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="697",anchorPointX="0",anchorPointY="0",},
ly_hero_4={classname="Panel",name="ly_hero_4",parName="ly_hero_online",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="418",y="11",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="698",anchorPointX="0",anchorPointY="0",},
}

return tTable