local tTable = {}

tTable["texturesPng"] = {"ui/v2_bg_yubingshu.jpg","ui/p1_commmon1_sep.plist","ui/p1_commmon4_sep.plist","ui/bar/v1_bar_b3.png","ui/p1_commonse1.plist","ui/p2_commmon1_sep.plist","ui/language/cn/p2_font1.plist","ui/big_img_sep/v2_img_gaojiyubingshudi.png","GUI/image.png"}
tTable["index_1"] = {
dlg_troops_detail={classname="Panel",name="dlg_troops_detail",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1060",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_mian={classname="Panel",name="lay_mian",parName="dlg_troops_detail",childCount="11",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/v2_bg_yubingshu.jpg",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="320",capInsetsY="800",height="1006",width="640",x="0",y="54",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="57",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_detail={classname="Panel",name="lay_detail",parName="lay_mian",childCount="2",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_blackjianbian.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="133",capInsetsY="62",height="90",width="640",x="0",y="317",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="60",anchorPointX="0",anchorPointY="0",},
lay_progresss={classname="Panel",name="lay_progresss",parName="lay_mian",childCount="6",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="100",width="640",x="0",y="210",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="61",anchorPointX="0",anchorPointY="0",},
lb_lock_tip={classname="Label",name="lb_lock_tip",parName="lay_mian",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="28",height="36",width="134",x="320",y="182",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="63",anchorPointX="0.5",anchorPointY="0.5",},
lb_limit_tip={classname="Label",name="lb_limit_tip",parName="lay_mian",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="28",height="36",width="134",x="320",y="225",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="171",anchorPointX="0.5",anchorPointY="0.5",},
img_left={classname="ImageView",name="img_left",parName="lay_mian",ZOrder="0",fileName="#v2_img_xsfuduqdd02a.png",scale9Enable="false",scale9Height="13",scale9Width="162",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="13",width="162",x="100",y="934",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="77",anchorPointX="0.5",anchorPointY="0.5",},
img_font_title={classname="ImageView",name="img_font_title",parName="lay_mian",ZOrder="0",fileName="#v2_fonts_gaojiyubingshu.png",scale9Enable="false",scale9Height="85",scale9Width="240",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="85",width="240",x="320",y="918",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="78",anchorPointX="0.5",anchorPointY="0.5",},
img_right={classname="ImageView",name="img_right",parName="lay_mian",ZOrder="0",fileName="#v2_img_xsfuduqdd02a.png",scale9Enable="false",scale9Height="13",scale9Width="162",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="13",width="162",x="540",y="934",visible="true",touchAble="false",flipX="true",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="80",anchorPointX="0.5",anchorPointY="0.5",},
img_bg={classname="ImageView",name="img_bg",parName="lay_mian",ZOrder="0",fileName="ui/big_img_sep/v2_img_gaojiyubingshudi.png",scale9Enable="false",scale9Height="364",scale9Width="409",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="364",width="409",x="320",y="537",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="100",anchorPointX="0.5",anchorPointY="0.5",},
img_troop_icon={classname="ImageView",name="img_troop_icon",parName="lay_mian",ZOrder="10",fileName="GUI/image.png",scale9Enable="false",scale9Height="80",scale9Width="80",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="80",width="80",x="320",y="537",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="106",anchorPointX="0.5",anchorPointY="0.5",},
lay_bot={classname="Panel",name="lay_bot",parName="lay_mian",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="150",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="127",anchorPointX="0",anchorPointY="0",},
lb_bot_tip={classname="Label",name="lb_bot_tip",parName="lay_mian",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="320",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="163",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_4"] = {
lay_level_unfull={classname="Panel",name="lay_level_unfull",parName="lay_detail",childCount="5",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="90",width="640",x="0",y="0",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="104",anchorPointX="0",anchorPointY="0",},
lay_level_full={classname="Panel",name="lay_level_full",parName="lay_detail",childCount="2",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="90",width="640",x="0",y="0",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="105",anchorPointX="0",anchorPointY="0",},
lay_bar={classname="Panel",name="lay_bar",parName="lay_progresss",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="ui/bar/v1_bar_b3.png",height="18",width="570",x="35",y="47",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="76",anchorPointX="0",anchorPointY="0",},
img_res_1={classname="ImageView",name="img_res_1",parName="lay_progresss",ZOrder="0",fileName="#v1_img_tongqian.png",scale9Enable="false",scale9Height="26",scale9Width="25",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="26",width="25",x="151",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="129",anchorPointX="0.5",anchorPointY="0.5",},
lb_cost_1={classname="Label",name="lb_cost_1",parName="lay_progresss",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="167",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="130",anchorPointX="0",anchorPointY="0.5",},
img_res_2={classname="ImageView",name="img_res_2",parName="lay_progresss",ZOrder="0",fileName="#v1_img_mucai.png",scale9Enable="false",scale9Height="23",scale9Width="32",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="23",width="32",x="394",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="131",anchorPointX="0.5",anchorPointY="0.5",},
lb_cost_2={classname="Label",name="lb_cost_2",parName="lay_progresss",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="417",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="132",anchorPointX="0",anchorPointY="0.5",},
lb_sec={classname="Label",name="lb_sec",parName="lay_progresss",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="320",y="84",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="147",anchorPointX="0.5",anchorPointY="0.5",},
lay_btn={classname="Panel",name="lay_btn",parName="lay_bot",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="242",y="80",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="59",anchorPointX="0",anchorPointY="0",},
lb_cd={classname="Label",name="lb_cd",parName="lay_bot",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="320",y="56",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="75",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_5"] = {
lb_pa_1={classname="Label",name="lb_pa_1",parName="lay_level_unfull",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="100",y="60",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="65",anchorPointX="0",anchorPointY="0.5",},
lb_pa_2={classname="Label",name="lb_pa_2",parName="lay_level_unfull",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="100",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="66",anchorPointX="0",anchorPointY="0.5",},
lb_pa_3={classname="Label",name="lb_pa_3",parName="lay_level_unfull",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="420",y="60",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="67",anchorPointX="0",anchorPointY="0.5",},
lb_pa_4={classname="Label",name="lb_pa_4",parName="lay_level_unfull",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="420",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="68",anchorPointX="0",anchorPointY="0.5",},
img_arrow={classname="ImageView",name="img_arrow",parName="lay_level_unfull",ZOrder="0",fileName="#v1_img_zhiyin_sj.png",scale9Enable="false",scale9Height="48",scale9Width="58",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="48",width="58",x="320",y="50",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="-90",tag="64",anchorPointX="0.5",anchorPointY="0.5",},
lb_pa_5={classname="Label",name="lb_pa_5",parName="lay_level_full",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="320",y="60",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="107",anchorPointX="0.5",anchorPointY="0.5",},
lb_pa_6={classname="Label",name="lb_pa_6",parName="lay_level_full",ZOrder="30",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="320",y="21",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="108",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable