local tTable = {}


tTable["index_1"] = {
root={classname="Panel",name="root",parName="root",childCount="9",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="32",capInsetsY="32",height="1138",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="382",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
img_bg={classname="ImageView",name="img_bg",parName="root",ZOrder="0",fileName="ui/v1_bg_xzgj.jpg",scale9Enable="false",scale9Height="798",scale9Width="640",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="798",width="640",x="320",y="268",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="385",anchorPointX="0.5",anchorPointY="0",},
lay_title={classname="Panel",name="lay_title",parName="root",childCount="2",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_title.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="72",width="640",x="0",y="1066",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="869",anchorPointX="0",anchorPointY="0",},
lb_prize={classname="Label",name="lb_prize",parName="root",ZOrder="10",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="320",y="783",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1848",anchorPointX="0.5",anchorPointY="0.5",},
img_npc={classname="ImageView",name="img_npc",parName="root",ZOrder="10",fileName="ui/bg_guide/v1_img_hanliubang.png",scale9Enable="false",scale9Height="412",scale9Width="640",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="412",width="640",x="320",y="248",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1853",anchorPointX="0.5",anchorPointY="0",},
lay_effect={classname="Panel",name="lay_effect",parName="root",ZOrder="20",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_img_zhenyingqin.png",height="146",width="103",x="99",y="607",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="102",rotation="0",tag="2311",anchorPointX="0",anchorPointY="0",},
lay_bot={classname="Panel",name="lay_bot",parName="root",childCount="3",ZOrder="15",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/big_img_sep/v1_img_yindaotankuang2.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="320",capInsetsY="111",height="268",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="3589",anchorPointX="0",anchorPointY="0",},
lay_han={classname="Panel",name="lay_han",parName="root",childCount="1",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="297",width="174",x="433",y="730",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6292",anchorPointX="0",anchorPointY="0",},
lay_chu={classname="Panel",name="lay_chu",parName="root",childCount="1",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="297",width="174",x="233",y="730",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6293",anchorPointX="0",anchorPointY="0",},
lay_qin={classname="Panel",name="lay_qin",parName="root",childCount="1",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="297",width="174",x="32",y="730",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6294",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
txt_title={classname="CustomLabel",name="txt_title",parName="lay_title",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="22",height="30",width="106",x="320",y="36",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="870",anchorPointX="0.5",anchorPointY="0.5",},
img_back={classname="ImageView",name="img_back",parName="lay_title",ZOrder="1",fileName="#v1_btn_back.png",scale9Enable="false",scale9Height="66",scale9Width="108",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="66",width="108",x="586",y="36",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1846",anchorPointX="0.5",anchorPointY="0.5",},
lb_tip_1={classname="Label",name="lb_tip_1",parName="lay_bot",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="22",height="30",width="106",x="319",y="240",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1851",anchorPointX="0.5",anchorPointY="0.5",},
lay_btn={classname="Panel",name="lay_btn",parName="lay_bot",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="242",y="30",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="386",anchorPointX="0",anchorPointY="0",},
img_arrow={classname="ImageView",name="img_arrow",parName="lay_bot",ZOrder="0",fileName="#v1_img_tiaoguojiantou.png",scale9Enable="false",scale9Height="54",scale9Width="65",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="54",width="65",x="592",y="46",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2953",anchorPointX="0.5",anchorPointY="0.5",},
img_han={classname="ImageView",name="img_han",parName="lay_han",ZOrder="10",fileName="#v1_img_zyh.png",scale9Enable="false",scale9Height="297",scale9Width="174",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="297",width="174",x="86",y="146",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="388",anchorPointX="0.5",anchorPointY="0.5",},
img_chu={classname="ImageView",name="img_chu",parName="lay_chu",ZOrder="10",fileName="#v1_img_zyc.png",scale9Enable="false",scale9Height="297",scale9Width="174",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="297",width="174",x="87",y="146",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="387",anchorPointX="0.5",anchorPointY="0.5",},
img_qin={classname="ImageView",name="img_qin",parName="lay_qin",ZOrder="10",fileName="#v1_img_zyq.png",scale9Enable="false",scale9Height="297",scale9Width="174",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="297",width="174",x="86",y="146",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="389",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable