local tTable = {}

tTable["texturesPng"] = { }
tTable["index_1"] = {
base={classname="Panel",name="base",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="355",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
view={classname="Panel",name="view",parName="base",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/big_img_sep/v1_bg_popup.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="200",capInsetsY="150",height="355",width="450",x="95",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
layout_top={classname="Panel",name="layout_top",parName="view",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="83",capInsetsY="30",height="60",width="450",x="0",y="295",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="12",anchorPointX="0",anchorPointY="0",},
layout_content={classname="Panel",name="layout_content",parName="view",childCount="7",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="190",width="450",x="0",y="105",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="21",anchorPointX="0",anchorPointY="0",},
layout_bottom={classname="Panel",name="layout_bottom",parName="view",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="105",width="450",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="18",anchorPointX="0",anchorPointY="0",},
layout_listview_account={classname="Panel",name="layout_listview_account",parName="view",ZOrder="99",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="215",width="386",x="32",y="0",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="55",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lb_title={classname="CustomLabel",name="lb_title",parName="layout_top",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="标题",fontName="微软雅黑",fontSize="24",height="31",width="48",x="225",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9",anchorPointX="0.5",anchorPointY="0.5",},
btn_close={classname="ImageView",name="btn_close",parName="layout_top",ZOrder="0",fileName="#v1_btn_close.png",scale9Enable="false",scale9Height="32",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="32",width="31",x="415",y="30",visible="true",touchAble="true",flipX="false",scaleX="0.79999995",scaleY="0.79999995",opacity="255",rotation="0",tag="17",anchorPointX="0.5",anchorPointY="0.5",},
btn_return={classname="ImageView",name="btn_return",parName="layout_top",ZOrder="0",fileName="#v1_btn_back.png",scale9Enable="false",scale9Height="66",scale9Width="108",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="66",width="108",x="405",y="30",visible="true",touchAble="false",flipX="false",scaleX="0.79999995",scaleY="0.79999995",opacity="255",rotation="0",tag="111",anchorPointX="0.5",anchorPointY="0.5",},
img_shuru_mima_bg={classname="ImageView",name="img_shuru_mima_bg",parName="layout_content",ZOrder="0",fileName="#v1_bg_1.png",scale9Enable="true",scale9Height="55",scale9Width="386",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="32",capInsetsY="32",height="55",width="386",x="225",y="50",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="27",anchorPointX="0.5",anchorPointY="0.5",},
label_mima={classname="TextField",name="label_mima",parName="layout_content",ZOrder="10",colorB="195",colorG="195",colorR="195",areaHeight="50",areaWidth="275",fontName="微软雅黑",fontSize="20",maxLength="10",maxLengthEnable="false",passwordStyleText="*",passwordEnable="true",height="50",width="275",x="140",y="50",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="64",anchorPointX="0",anchorPointY="0.5",},
lb_mima={classname="Label",name="lb_mima",parName="layout_content",ZOrder="10",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="密码：",fontName="微软雅黑",fontSize="20",height="27",width="60",x="110",y="50",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="88",anchorPointX="0.5",anchorPointY="0.5",},
img_pss={classname="ImageView",name="img_pss",parName="layout_content",ZOrder="10",fileName="#v1_img_shuxie.png",scale9Enable="false",scale9Height="49",scale9Width="51",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="49",width="51",x="56",y="50",visible="true",touchAble="false",flipX="false",scaleX="0.55",scaleY="0.55",opacity="255",rotation="0",tag="113",anchorPointX="0.5",anchorPointY="0.5",},
layout_zhanghao={classname="Panel",name="layout_zhanghao",parName="layout_content",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="55",width="386",x="32",y="110",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="36",anchorPointX="0",anchorPointY="0",},
layout_zhanghao_num={classname="Panel",name="layout_zhanghao_num",parName="layout_content",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="110",width="386",x="32",y="80",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="37",anchorPointX="0",anchorPointY="0",},
layout_select_account={classname="Panel",name="layout_select_account",parName="layout_content",childCount="1",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="50",x="367",y="113",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="53",anchorPointX="0",anchorPointY="0",},
layout_btn_left={classname="Panel",name="layout_btn_left",parName="layout_bottom",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="50",y="55",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="19",anchorPointX="0",anchorPointY="0",},
layout_btn_right={classname="Panel",name="layout_btn_right",parName="layout_bottom",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="270",y="55",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="20",anchorPointX="0",anchorPointY="0",},
label_warming={classname="CustomLabel",name="label_warming",parName="layout_bottom",ZOrder="0",colorB="33",colorG="33",colorR="216",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="225",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="35",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_5"] = {
img_shuru_zhanghao_bg={classname="ImageView",name="img_shuru_zhanghao_bg",parName="layout_zhanghao",ZOrder="0",fileName="#v1_bg_1.png",scale9Enable="true",scale9Height="55",scale9Width="386",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="32",capInsetsY="32",height="55",width="386",x="193",y="28",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="25",anchorPointX="0.5",anchorPointY="0.5",},
label_zhanghao={classname="TextField",name="label_zhanghao",parName="layout_zhanghao",ZOrder="0",colorB="195",colorG="195",colorR="195",areaHeight="50",areaWidth="225",fontName="微软雅黑",fontSize="20",maxLength="10",maxLengthEnable="false",passwordStyleText="*",passwordEnable="false",height="50",width="225",x="108",y="28",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="68",anchorPointX="0",anchorPointY="0.5",},
lb_zhanghao={classname="Label",name="lb_zhanghao",parName="layout_zhanghao",ZOrder="10",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="账号：",fontName="微软雅黑",fontSize="20",height="27",width="60",x="78",y="27",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="89",anchorPointX="0.5",anchorPointY="0.5",},
img_acc={classname="ImageView",name="img_acc",parName="layout_zhanghao",ZOrder="10",fileName="#v1_img_ud.png",scale9Enable="false",scale9Height="32",scale9Width="30",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="32",width="30",x="24",y="27",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="112",anchorPointX="0.5",anchorPointY="0.5",},
label_tip_zhanghao_success={classname="CustomLabel",name="label_tip_zhanghao_success",parName="layout_zhanghao_num",ZOrder="0",colorB="195",colorG="195",colorR="195",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="注册成功",fontName="微软雅黑",fontSize="20",height="27",width="80",x="152",y="96",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="43",anchorPointX="0",anchorPointY="0.5",},
label_tip_zhanghao_zh={classname="CustomLabel",name="label_tip_zhanghao_zh",parName="layout_zhanghao_num",ZOrder="0",colorB="195",colorG="195",colorR="195",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="账号:",fontName="微软雅黑",fontSize="20",height="27",width="45",x="27",y="65",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="41",anchorPointX="0",anchorPointY="0.5",},
label_tip_zhanghao_mm={classname="CustomLabel",name="label_tip_zhanghao_mm",parName="layout_zhanghao_num",ZOrder="0",colorB="195",colorG="195",colorR="195",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="密码:",fontName="微软雅黑",fontSize="20",height="27",width="45",x="27",y="24",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="44",anchorPointX="0",anchorPointY="0.5",},
label_shuru_mima={classname="CustomLabel",name="label_shuru_mima",parName="layout_zhanghao_num",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",fontName="微软雅黑",fontSize="20",height="0",width="0",x="90",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="49",anchorPointX="0",anchorPointY="0.5",},
label_shuru_zhanghao={classname="CustomLabel",name="label_shuru_zhanghao",parName="layout_zhanghao_num",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",fontName="微软雅黑",fontSize="20",height="0",width="0",x="90",y="65",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="51",anchorPointX="0",anchorPointY="0.5",},
img_arrow={classname="ImageView",name="img_arrow",parName="layout_select_account",ZOrder="2",fileName="#v1_img_up.png",scale9Enable="false",scale9Height="16",scale9Width="24",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="16",width="24",x="25",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="52",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable