local tTable = {}

tTable["texturesPng"] = {"ui/p1_commmon1_sep.plist","ui/p1_commmon3_sep.plist"}
tTable["index_1"] = {
dlg_hero_mansion={classname="Panel",name="dlg_hero_mansion",parName="root",childCount="8",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1060",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
ly_title={classname="Panel",name="ly_title",parName="dlg_hero_mansion",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="270",width="640",x="0",y="790",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8",anchorPointX="0",anchorPointY="0",},
ly_bot_btn={classname="Panel",name="ly_bot_btn",parName="dlg_hero_mansion",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="435",y="50",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9",anchorPointX="0",anchorPointY="0",},
ly_content={classname="Panel",name="ly_content",parName="dlg_hero_mansion",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="645",width="600",x="20",y="135",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="10",anchorPointX="0",anchorPointY="0",},
lb_have_time={classname="CustomLabel",name="lb_have_time",parName="dlg_hero_mansion",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="免费次数: 0/9",fontName="微软雅黑",fontSize="20",height="27",width="124",x="45",y="98",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="12",anchorPointX="0",anchorPointY="0.5",},
lb_cost_tip={classname="CustomLabel",name="lb_cost_tip",parName="dlg_hero_mansion",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="45",y="50",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="13",anchorPointX="0",anchorPointY="0.5",},
lb_show_time={classname="CustomLabel",name="lb_show_time",parName="dlg_hero_mansion",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="(恢复时间 20:20:20)",fontName="微软雅黑",fontSize="20",height="27",width="182",x="179",y="98",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="14",anchorPointX="0",anchorPointY="0.5",},
lb_cost_coin={classname="CustomLabel",name="lb_cost_coin",parName="dlg_hero_mansion",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="177",y="50",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="15",anchorPointX="0",anchorPointY="0.5",},
lay_red={classname="Panel",name="lay_red",parName="dlg_hero_mansion",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="20",width="20",x="580",y="100",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="300",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
ly_hero_info={classname="Panel",name="ly_hero_info",parName="ly_title",childCount="1",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_black50.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="10",height="28",width="204",x="430",y="230",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="212",anchorPointX="0",anchorPointY="0",},
ly_list={classname="Panel",name="ly_list",parName="ly_content",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="635",width="600",x="0",y="5",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="11",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lb_info={classname="CustomLabel",name="lb_info",parName="ly_hero_info",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="lb_info",fontName="微软雅黑",fontSize="20",height="27",width="64",x="196",y="14",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="213",anchorPointX="1",anchorPointY="0.5",},
}

return tTable