local tTable = {}


tTable["index_1"] = {
root={classname="Panel",name="root@fill_layout",parName="root",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1066",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="3",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_top={classname="Panel",name="lay_top",parName="root",childCount="8",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="500",width="640",x="0",y="565",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="445",anchorPointX="0",anchorPointY="0",},
lay_content={classname="Panel",name="lay_content@fill_layout",parName="root",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="200",width="640",x="0",y="200",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="447",anchorPointX="0",anchorPointY="0",},
lay_bottom={classname="Panel",name="lay_bottom",parName="root",childCount="8",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="200",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="446",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_btn_1={classname="Panel",name="lay_btn_1",parName="lay_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="64",width="250",x="50",y="376",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4",anchorPointX="0",anchorPointY="0",},
lay_btn_2={classname="Panel",name="lay_btn_2",parName="lay_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="64",width="250",x="340",y="376",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6",anchorPointX="0",anchorPointY="0",},
lay_btn_3={classname="Panel",name="lay_btn_3",parName="lay_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="64",width="250",x="50",y="282",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7",anchorPointX="0",anchorPointY="0",},
lay_btn_4={classname="Panel",name="lay_btn_4",parName="lay_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="64",width="250",x="340",y="282",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8",anchorPointX="0",anchorPointY="0",},
lay_btn_5={classname="Panel",name="lay_btn_5",parName="lay_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="64",width="250",x="50",y="188",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9",anchorPointX="0",anchorPointY="0",},
lay_btn_6={classname="Panel",name="lay_btn_6",parName="lay_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="64",width="250",x="340",y="188",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="10",anchorPointX="0",anchorPointY="0",},
lay_btn_7={classname="Panel",name="lay_btn_7",parName="lay_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="64",width="250",x="50",y="94",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="309",anchorPointX="0",anchorPointY="0",},
lay_btn_8={classname="Panel",name="lay_btn_8",parName="lay_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="64",width="250",x="340",y="94",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="407",anchorPointX="0",anchorPointY="0",},
lb_tip_1={classname="Label",name="lb_tip_1",parName="lay_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="当前服：",fontName="微软雅黑",fontSize="22",height="30",width="88",x="20",y="123",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="11",anchorPointX="0",anchorPointY="0.5",},
lb_tip_2={classname="Label",name="lb_tip_2",parName="lay_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="游戏ID：",fontName="微软雅黑",fontSize="22",height="30",width="89",x="20",y="78",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="12",anchorPointX="0",anchorPointY="0.5",},
lb_tip_3={classname="Label",name="lb_tip_3",parName="lay_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="当前版本：",fontName="微软雅黑",fontSize="22",height="30",width="110",x="484",y="78",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="13",anchorPointX="1",anchorPointY="0.5",},
lb_tip_4={classname="Label",name="lb_tip_4",parName="lay_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="当前服：",fontName="微软雅黑",fontSize="22",height="30",width="88",x="374",y="123",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="340",anchorPointX="0",anchorPointY="0.5",},
lb_service={classname="Label",name="lb_service",parName="lay_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="a1_天地一斗",fontName="微软雅黑",fontSize="22",height="30",width="123",x="109",y="123",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="14",anchorPointX="0",anchorPointY="0.5",},
lb_gameid={classname="Label",name="lb_gameid",parName="lay_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9574",fontName="微软雅黑",fontSize="22",height="30",width="52",x="109",y="78",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="15",anchorPointX="0",anchorPointY="0.5",},
lb_version={classname="Label",name="lb_version",parName="lay_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="100.1535.9.9",fontName="微软雅黑",fontSize="22",height="30",width="132",x="487",y="78",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="16",anchorPointX="0",anchorPointY="0.5",},
lb_guid={classname="Label",name="lb_guid",parName="lay_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="当前服：",fontName="微软雅黑",fontSize="22",height="30",width="88",x="487",y="122",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="375",anchorPointX="0",anchorPointY="0.5",},
}

return tTable