local tTable = {}

tTable["texturesPng"] = {"ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commonse1.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","icon/p1_icon_ui.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","ui/bg_world/v1_img_shijieditu.jpg","ui/p1_commmon1_sep.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","ui/p1_button1.plist"}
tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="471",width="400",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2255",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
view={classname="Panel",name="view",parName="default",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/big_img_sep/v1_bg_popup.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="200",capInsetsY="150",height="539.7591",width="400",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="3516",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
main={classname="Panel",name="main",parName="view",childCount="17",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="411",width="400",x="1",y="35",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2293",anchorPointX="0",anchorPointY="0",},
img_close={classname="CustomImageView",name="img_close",parName="view",ZOrder="0",fileName="#v1_btn_close.png",scale9Enable="false",scale9Height="32",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="32",width="31",x="368",y="506",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="3517",anchorPointX="0.5",anchorPointY="0.5",},
txt_title={classname="CustomLabel",name="txt_title",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="205",y="507",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="3518",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_4"] = {
txt_x_title={classname="CustomLabel",name="txt_x_title",parName="main",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="X",fontName="微软雅黑",fontSize="20",height="27",width="13",x="33",y="372",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2294",anchorPointX="0.5",anchorPointY="0.5",},
txt_y_title={classname="CustomLabel",name="txt_y_title",parName="main",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Y",fontName="微软雅黑",fontSize="20",height="27",width="12",x="218",y="372",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2295",anchorPointX="0.5",anchorPointY="0.5",},
lay_input_x={classname="Panel",name="lay_input_x",parName="main",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="50",width="140",x="50",y="346",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2296",anchorPointX="0",anchorPointY="0",},
lay_input_y={classname="Panel",name="lay_input_y",parName="main",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="50",width="140",x="235",y="346",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2297",anchorPointX="0",anchorPointY="0",},
lay_btn1={classname="Panel",name="lay_btn1",parName="main",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_btn_shuzi.png",height="60",width="100",x="14",y="263",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2298",anchorPointX="0",anchorPointY="0",},
lay_btn2={classname="Panel",name="lay_btn2",parName="main",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_btn_shuzi.png",height="60",width="100",x="148",y="263",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2299",anchorPointX="0",anchorPointY="0",},
lay_btn3={classname="Panel",name="lay_btn3",parName="main",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_btn_shuzi.png",height="60",width="100",x="280",y="262",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2300",anchorPointX="0",anchorPointY="0",},
lay_btn4={classname="Panel",name="lay_btn4",parName="main",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_btn_shuzi.png",height="60",width="100",x="14",y="179",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2301",anchorPointX="0",anchorPointY="0",},
lay_btn5={classname="Panel",name="lay_btn5",parName="main",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_btn_shuzi.png",height="60",width="100",x="148",y="179",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2302",anchorPointX="0",anchorPointY="0",},
lay_btn6={classname="Panel",name="lay_btn6",parName="main",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_btn_shuzi.png",height="60",width="100",x="280",y="178",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2303",anchorPointX="0",anchorPointY="0",},
lay_btn7={classname="Panel",name="lay_btn7",parName="main",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_btn_shuzi.png",height="60",width="100",x="15",y="95",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2304",anchorPointX="0",anchorPointY="0",},
lay_btn8={classname="Panel",name="lay_btn8",parName="main",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_btn_shuzi.png",height="60",width="100",x="148",y="95",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2305",anchorPointX="0",anchorPointY="0",},
lay_btn9={classname="Panel",name="lay_btn9",parName="main",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_btn_shuzi.png",height="60",width="100",x="280",y="95",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2306",anchorPointX="0",anchorPointY="0",},
lay_btn_del={classname="Panel",name="lay_btn_del",parName="main",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_btn_shanchu.png",height="60",width="100",x="16",y="11",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2307",anchorPointX="0",anchorPointY="0",},
lay_btn0={classname="Panel",name="lay_btn0",parName="main",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_btn_shuzi.png",height="60",width="100",x="148",y="11",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2308",anchorPointX="0",anchorPointY="0",},
lay_btn_go={classname="Panel",name="lay_btn_go",parName="main",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_btn_qianwang.png",height="60",width="100",x="280",y="11",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2309",anchorPointX="0",anchorPointY="0",},
lay_selected={classname="Panel",name="lay_selected",parName="main",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_quyukuang.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="38",capInsetsY="38",height="50",width="140",x="49",y="346",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2847",anchorPointX="0",anchorPointY="0",},
}
tTable["index_5"] = {
txt_x={classname="CustomLabel",name="txt_x",parName="lay_input_x",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="72",y="24",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2848",anchorPointX="0.5",anchorPointY="0.5",},
txt_y={classname="CustomLabel",name="txt_y",parName="lay_input_y",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="70",y="24",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2849",anchorPointX="0.5",anchorPointY="0.5",},
txt_num1={classname="CustomLabel",name="txt_num1",parName="lay_btn1",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="50",y="31",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2850",anchorPointX="0.5",anchorPointY="0.5",},
txt_num2={classname="CustomLabel",name="txt_num2",parName="lay_btn2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="50",y="31",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2851",anchorPointX="0.5",anchorPointY="0.5",},
txt_num3={classname="CustomLabel",name="txt_num3",parName="lay_btn3",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="49",y="32",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2852",anchorPointX="0.5",anchorPointY="0.5",},
txt_num4={classname="CustomLabel",name="txt_num4",parName="lay_btn4",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="50",y="32",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2853",anchorPointX="0.5",anchorPointY="0.5",},
txt_num5={classname="CustomLabel",name="txt_num5",parName="lay_btn5",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="50",y="32",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2854",anchorPointX="0.5",anchorPointY="0.5",},
txt_num6={classname="CustomLabel",name="txt_num6",parName="lay_btn6",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="49",y="33",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2855",anchorPointX="0.5",anchorPointY="0.5",},
txt_num7={classname="CustomLabel",name="txt_num7",parName="lay_btn7",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="49",y="28",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2856",anchorPointX="0.5",anchorPointY="0.5",},
txt_num8={classname="CustomLabel",name="txt_num8",parName="lay_btn8",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="50",y="28",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2857",anchorPointX="0.5",anchorPointY="0.5",},
txt_num9={classname="CustomLabel",name="txt_num9",parName="lay_btn9",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="49",y="28",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2858",anchorPointX="0.5",anchorPointY="0.5",},
txt_del={classname="CustomLabel",name="txt_del",parName="lay_btn_del",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="49",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2859",anchorPointX="0.5",anchorPointY="0.5",},
txt_num0={classname="CustomLabel",name="txt_num0",parName="lay_btn0",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="50",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2860",anchorPointX="0.5",anchorPointY="0.5",},
txt_go={classname="CustomLabel",name="txt_go",parName="lay_btn_go",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="49",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2861",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable