local tTable = {}

tTable["texturesPng"] = {"ui/p1_commonse1.plist","ui/bg_base/v2_bg_guojiarenwu.jpg","ui/p1_commmon3_sep.plist"}
tTable["index_1"] = {
lay_root={classname="Panel",name="lay_root@fill_layout",parName="root",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1060",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="178",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_top={classname="Panel",name="lay_top",parName="lay_root",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="60",width="640",x="0",y="999",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="293",anchorPointX="0",anchorPointY="0",},
lay_main={classname="Panel",name="lay_main@fill_layout",parName="lay_root",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="900",width="640",x="0",y="100",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="179",anchorPointX="0",anchorPointY="0",},
lay_bot={classname="Panel",name="lay_bot",parName="lay_root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="100",width="640",x="0",y="0",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="180",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_icon_list={classname="Panel",name="lay_icon_list@fill_layout_height",parName="lay_main",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="900",width="600",x="20",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="182",anchorPointX="0",anchorPointY="0",},
lay_box={classname="Panel",name="lay_box@fill_layout_height",parName="lay_main",childCount="2",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="900",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="250",anchorPointX="0",anchorPointY="0",},
lay_btn={classname="Panel",name="lay_btn",parName="lay_bot",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="243",y="20",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="181",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lay_prev_view={classname="Panel",name="lay_prev_view",parName="lay_box",childCount="10",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="244",width="640",x="0",y="656",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="251",anchorPointX="0",anchorPointY="0",},
lay_box_list={classname="Panel",name="lay_box_list@fill_layout",parName="lay_box",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="656",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="253",anchorPointX="0",anchorPointY="0",},
}
tTable["index_5"] = {
img_arrow={classname="ImageView",name="img_arrow",parName="lay_prev_view",ZOrder="1",fileName="#v1_img_lanjiantou.png",scale9Enable="false",scale9Height="41",scale9Width="65",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="41",width="65",x="320",y="133",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="282",anchorPointX="0.5",anchorPointY="0.5",},
img_bg={classname="ImageView",name="img_bg",parName="lay_prev_view",ZOrder="0",fileName="ui/bg_base/v2_bg_guojiarenwu.jpg",scale9Enable="false",scale9Height="318",scale9Width="640",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="318",width="640",x="0",y="-74",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="252",anchorPointX="0",anchorPointY="0",},
lay_icon_1={classname="Panel",name="lay_icon_1",parName="lay_prev_view",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="100",y="86",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="271",anchorPointX="0",anchorPointY="0",},
lb_pa_1={classname="Label",name="lb_pa_1",parName="lay_prev_view",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="154",y="215",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="254",anchorPointX="0.5",anchorPointY="0.5",},
lb_pa_2={classname="Label",name="lb_pa_2",parName="lay_prev_view",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="154",y="69",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="272",anchorPointX="0.5",anchorPointY="0.5",},
lb_pa_3={classname="Label",name="lb_pa_3",parName="lay_prev_view",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="154",y="40",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="273",anchorPointX="0.5",anchorPointY="0.5",},
lay_icon_2={classname="Panel",name="lay_icon_2",parName="lay_prev_view",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="433",y="85",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="278",anchorPointX="0",anchorPointY="0",},
lb_pa_4={classname="Label",name="lb_pa_4",parName="lay_prev_view",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="487",y="214",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="279",anchorPointX="0.5",anchorPointY="0.5",},
lb_pa_5={classname="Label",name="lb_pa_5",parName="lay_prev_view",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="487",y="68",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="280",anchorPointX="0.5",anchorPointY="0.5",},
lb_pa_6={classname="Label",name="lb_pa_6",parName="lay_prev_view",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="487",y="40",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="281",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable