local tTable = {}


tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="695",width="550",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="401",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
view={classname="Panel",name="view",parName="default",childCount="13",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="695",width="550",x="1",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="402",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_banner={classname="Panel",name="lay_banner",parName="view",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_btn_biaoqian.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="40",capInsetsY="30",height="52",width="520",x="12",y="577",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="3514",anchorPointX="0",anchorPointY="0",},
lay_candidate={classname="Panel",name="lay_candidate",parName="view",childCount="1",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="284",width="520",x="12",y="298",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="403",anchorPointX="0",anchorPointY="0",},
txt_cd={classname="CustomLabel",name="txt_cd",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="26",height="35",width="127",x="275",y="197",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="405",anchorPointX="0.5",anchorPointY="0.5",},
txt_content_tip1={classname="CustomLabel",name="txt_content_tip1",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="成功申请城主后将自动重建",fontName="微软雅黑",fontSize="22",height="30",width="264",x="275",y="659",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2216",anchorPointX="0.5",anchorPointY="0.5",},
txt_content_tip2={classname="CustomLabel",name="txt_content_tip2",parName="view",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="275",y="248",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="15647",anchorPointX="0.5",anchorPointY="1",},
txt_cost_title={classname="CustomLabel",name="txt_cost_title",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="申请消耗：",fontName="微软雅黑",fontSize="20",height="27",width="100",x="126",y="270",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6637",anchorPointX="0",anchorPointY="0.5",},
img_res1={classname="CustomImageView",name="img_res1",parName="view",ZOrder="0",fileName="#v1_img_qianbi.png",scale9Enable="false",scale9Height="36",scale9Width="36",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="36",width="36",x="257",y="270",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6638",anchorPointX="0.5",anchorPointY="0.5",},
txt_res1={classname="CustomLabel",name="txt_res1",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="99999",fontName="微软雅黑",fontSize="20",height="27",width="60",x="281",y="270",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6639",anchorPointX="0",anchorPointY="0.5",},
img_res2={classname="CustomImageView",name="img_res2",parName="view",ZOrder="0",fileName="#v1_img_qianbi.png",scale9Enable="false",scale9Height="36",scale9Width="36",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="36",width="36",x="392",y="270",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6640",anchorPointX="0.5",anchorPointY="0.5",},
txt_res2={classname="CustomLabel",name="txt_res2",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="99999",fontName="微软雅黑",fontSize="20",height="27",width="60",x="418",y="270",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6641",anchorPointX="0",anchorPointY="0.5",},
txt_tip2={classname="CustomLabel",name="txt_tip2",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="275",y="237",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6642",anchorPointX="0.5",anchorPointY="0.5",},
txt_tip3={classname="CustomLabel",name="txt_tip3",parName="view",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="275",y="165",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="26288",anchorPointX="0.5",anchorPointY="0.5",},
lay_btn={classname="Panel",name="lay_btn",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="197",y="30",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="26289",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
txt_banner_tip={classname="CustomLabel",name="txt_banner_tip",parName="lay_banner",ZOrder="3",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="260",y="26",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="3515",anchorPointX="0.5",anchorPointY="0.5",},
txt_no_tip={classname="Label",name="txt_no_tip",parName="lay_candidate",ZOrder="3",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="30",height="39",width="145",x="260",y="165",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="25737",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable