local tTable = {}

tTable["texturesPng"] = {"ui/p2_button1.plist","GUI/image.png","ui/p1_commmon3_sep.plist"}
tTable["index_1"] = {
default={classname="Panel",name="default@fill_layout",parName="root",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1066",width="522",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_title={classname="Panel",name="lay_title",parName="default",childCount="11",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="375",width="522",x="0",y="697",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8",anchorPointX="0",anchorPointY="0",},
lay_title_tab={classname="Panel",name="lay_title_tab",parName="default",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="60",width="522",x="0",y="639",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="13",anchorPointX="0",anchorPointY="0",},
lay_content={classname="Panel",name="lay_content@fill_layout",parName="default",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="600",width="522",x="0",y="41",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_time={classname="Panel",name="lay_time",parName="lay_title",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="28",width="294",x="0",y="342",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="10",anchorPointX="0",anchorPointY="0",},
lay_btn_1={classname="Panel",name="lay_btn_1",parName="lay_title",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="46",width="110",x="16",y="76",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="14",anchorPointX="0",anchorPointY="0",},
lay_btn_2={classname="Panel",name="lay_btn_2",parName="lay_title",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="46",width="110",x="136",y="76",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="16",anchorPointX="0",anchorPointY="0",},
lay_btn_3={classname="Panel",name="lay_btn_3",parName="lay_title",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="46",width="110",x="256",y="76",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="17",anchorPointX="0",anchorPointY="0",},
lay_btn_4={classname="Panel",name="lay_btn_4",parName="lay_title",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="46",width="110",x="16",y="16",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="18",anchorPointX="0",anchorPointY="0",},
lay_btn_5={classname="Panel",name="lay_btn_5",parName="lay_title",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="46",width="110",x="136",y="16",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="19",anchorPointX="0",anchorPointY="0",},
lay_btn_6={classname="Panel",name="lay_btn_6",parName="lay_title",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="46",width="110",x="256",y="16",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="20",anchorPointX="0",anchorPointY="0",},
lay_btn_7={classname="Panel",name="lay_btn_7",parName="lay_title",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="140",width="130",x="376",y="16",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="21",anchorPointX="0",anchorPointY="0",},
img_shuoming={classname="ImageView",name="img_shuoming",parName="lay_title",ZOrder="1",fileName="#v2_btn_shuoming.png",scale9Enable="false",scale9Height="34",scale9Width="34",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="34",width="34",x="480",y="335",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="31",anchorPointX="0.5",anchorPointY="0.5",},
lay_banner_bg={classname="Panel",name="lay_banner_bg",parName="lay_title",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="315",width="522",x="0",y="60",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="41",anchorPointX="0",anchorPointY="0",},
img_tip={classname="ImageView",name="img_tip",parName="lay_title",ZOrder="10",fileName="GUI/image.png",scale9Enable="false",scale9Height="80",scale9Width="80",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="80",width="80",x="160",y="260",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="51",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable