local tTable = {}

tTable["texturesPng"] = {"ui/v2_bg_popup_b.png","ui/v2_bg_popup_a.png","ui/p1_button1.plist","ui/p1_commmon3_sep.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist"}
tTable["index_1"] = {
root={classname="Panel",name="root",parName="root",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="540",width="400",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="797",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_bot={classname="Panel",name="lay_bot",parName="root",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/v2_bg_popup_b.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="150",capInsetsY="25",height="70",width="400",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="798",anchorPointX="0",anchorPointY="0",},
lay_top={classname="Panel",name="lay_top",parName="root",childCount="13",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/v2_bg_popup_a.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="150",capInsetsY="125",height="470",width="400",x="0",y="70",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="799",anchorPointX="0",anchorPointY="0",},
lay_close={classname="Panel",name="lay_close",parName="root",childCount="1",ZOrder="100",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="70",width="150",x="250",y="470",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="801",anchorPointX="0",anchorPointY="0",},
lb_title={classname="Label",name="lb_title",parName="root",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="200",y="505",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="800",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_3"] = {
lay_num_1={classname="Panel",name="lay_num_1",parName="lay_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_btn_shuzi.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="30",height="60",width="100",x="30",y="250",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="803",anchorPointX="0",anchorPointY="0",},
lay_num_2={classname="Panel",name="lay_num_2",parName="lay_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_btn_shuzi.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="30",height="60",width="100",x="150",y="250",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="804",anchorPointX="0",anchorPointY="0",},
lay_num_3={classname="Panel",name="lay_num_3",parName="lay_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_btn_shuzi.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="30",height="60",width="100",x="270",y="250",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="806",anchorPointX="0",anchorPointY="0",},
lay_num_4={classname="Panel",name="lay_num_4",parName="lay_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_btn_shuzi.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="30",height="60",width="100",x="30",y="175",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="807",anchorPointX="0",anchorPointY="0",},
lay_num_5={classname="Panel",name="lay_num_5",parName="lay_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_btn_shuzi.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="30",height="60",width="100",x="150",y="175",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="808",anchorPointX="0",anchorPointY="0",},
lay_num_6={classname="Panel",name="lay_num_6",parName="lay_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_btn_shuzi.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="30",height="60",width="100",x="270",y="175",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="809",anchorPointX="0",anchorPointY="0",},
lay_num_7={classname="Panel",name="lay_num_7",parName="lay_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_btn_shuzi.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="30",height="60",width="100",x="30",y="100",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="810",anchorPointX="0",anchorPointY="0",},
lay_num_8={classname="Panel",name="lay_num_8",parName="lay_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_btn_shuzi.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="30",height="60",width="100",x="150",y="100",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="811",anchorPointX="0",anchorPointY="0",},
lay_num_9={classname="Panel",name="lay_num_9",parName="lay_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_btn_shuzi.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="30",height="60",width="100",x="270",y="100",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="813",anchorPointX="0",anchorPointY="0",},
lay_num_0={classname="Panel",name="lay_num_0",parName="lay_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_btn_shuzi.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="30",height="60",width="100",x="150",y="25",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="815",anchorPointX="0",anchorPointY="0",},
lay_cancel={classname="Panel",name="lay_cancel",parName="lay_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_btn_shanchu.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="30",height="60",width="100",x="30",y="25",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="814",anchorPointX="0",anchorPointY="0",},
lay_sure={classname="Panel",name="lay_sure",parName="lay_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_btn_qianwang.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="30",height="60",width="100",x="270",y="25",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="816",anchorPointX="0",anchorPointY="0",},
lay_num={classname="Panel",name="lay_num",parName="lay_top",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="46",width="120",x="140",y="331",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="817",anchorPointX="0",anchorPointY="0",},
img_close={classname="ImageView",name="img_close",parName="lay_close",ZOrder="0",fileName="#v1_btn_close.png",scale9Enable="false",scale9Height="32",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="32",width="31",x="140",y="35",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="802",anchorPointX="1",anchorPointY="0.5",},
}
tTable["index_4"] = {
lb_cur_num={classname="Label",name="lb_cur_num",parName="lay_num",ZOrder="10",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="60",y="23",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="819",anchorPointX="0.5",anchorPointY="0.5",},
img_bg={classname="ImageView",name="img_bg",parName="lay_num",ZOrder="0",fileName="#v1_img_selected.png",scale9Enable="true",scale9Height="46",scale9Width="120",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="13",capInsetsY="13",height="46",width="120",x="60",y="23",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="818",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable