local tTable = {}


tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1066",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="348",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
view={classname="Panel",name="view",parName="default",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1066",width="640",x="0",y="-1",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="349",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_info1={classname="Panel",name="lay_info1",parName="view",childCount="8",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="ui/big_img_sep/v2_bg_caijibeijing.jpg",height="191",width="640",x="0",y="864",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1727",anchorPointX="0",anchorPointY="0",},
lay_banner1={classname="Panel",name="lay_banner1",parName="view",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v2_img_xiaobiaoti3.png",height="50",width="640",x="0",y="836",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1734",anchorPointX="0",anchorPointY="0",},
lay_info2={classname="Panel",name="lay_info2",parName="view",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="150",width="640",x="0",y="686",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1736",anchorPointX="0",anchorPointY="0",},
lay_banner2={classname="Panel",name="lay_banner2",parName="view",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v2_img_xiaobiaoti3.png",height="50",width="640",x="0",y="636",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1742",anchorPointX="0",anchorPointY="0",},
lay_content={classname="Panel",name="lay_content",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="636",width="640",x="0",y="-2",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1744",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
txt_name={classname="CustomLabel",name="txt_name",parName="lay_info1",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="45",y="142",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1729",anchorPointX="0",anchorPointY="0.5",},
txt_pos={classname="CustomLabel",name="txt_pos",parName="lay_info1",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="45",y="102",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1731",anchorPointX="0",anchorPointY="0.5",},
txt_move_time={classname="CustomLabel",name="txt_move_time",parName="lay_info1",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="45",y="62",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1733",anchorPointX="0",anchorPointY="0.5",},
lay_icon={classname="Panel",name="lay_icon",parName="lay_info1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="100",width="150",x="438",y="50",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7163",anchorPointX="0",anchorPointY="0",},
lay_act_btn={classname="Panel",name="lay_act_btn",parName="lay_info1",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="39",width="124",x="497",y="133",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="20347",anchorPointX="0",anchorPointY="0",},
Panel_19={classname="Panel",name="Panel_19",parName="lay_info1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_zjm_utje.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="44",capInsetsY="12",height="24",width="168",x="25",y="130",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="23807",anchorPointX="0",anchorPointY="0",},
Panel_20={classname="Panel",name="Panel_20",parName="lay_info1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_zjm_utje.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="44",capInsetsY="12",height="24",width="168",x="25",y="90",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="23808",anchorPointX="0",anchorPointY="0",},
Panel_21={classname="Panel",name="Panel_21",parName="lay_info1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_zjm_utje.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="44",capInsetsY="12",height="24",width="168",x="25",y="50",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="23809",anchorPointX="0",anchorPointY="0",},
txt_banner_tip1={classname="CustomLabel",name="txt_banner_tip1",parName="lay_banner1",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="22",height="30",width="106",x="321",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1735",anchorPointX="0.5",anchorPointY="0.5",},
txt_remain={classname="CustomLabel",name="txt_remain",parName="lay_info2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="216",y="124",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1737",anchorPointX="0",anchorPointY="0.5",},
txt_speed={classname="CustomLabel",name="txt_speed",parName="lay_info2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="216",y="92",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1738",anchorPointX="0",anchorPointY="0.5",},
txt_collect_time={classname="CustomLabel",name="txt_collect_time",parName="lay_info2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="216",y="59",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1739",anchorPointX="0",anchorPointY="0.5",},
txt_preview={classname="CustomLabel",name="txt_preview",parName="lay_info2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="216",y="27",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1740",anchorPointX="0",anchorPointY="0.5",},
lay_icon1={classname="Panel",name="lay_icon1",parName="lay_info2",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="100",width="150",x="32",y="26",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7162",anchorPointX="0",anchorPointY="0",},
lay_banner_tip2={classname="CustomLabel",name="lay_banner_tip2",parName="lay_banner2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="22",height="30",width="106",x="321",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1743",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_5"] = {
txt_res_name={classname="CustomLabel",name="txt_res_name",parName="lay_icon1",ZOrder="10",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="元宝",fontName="微软雅黑",fontSize="20",height="27",width="40",x="75",y="20",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="11061",anchorPointX="0.5",anchorPointY="0.5",},
img_icon_bg={classname="CustomImageView",name="img_icon_bg",parName="lay_icon1",ZOrder="9",fileName="#v1_img_namebg1.png",scale9Enable="false",scale9Height="28",scale9Width="108",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="28",width="108",x="74",y="18",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="23811",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable