local tTable = {}


tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="6",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="552",width="560",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8738",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
ly_hero_1={classname="Panel",name="ly_hero_1",parName="default",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="24",y="427",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9166",anchorPointX="0",anchorPointY="0",},
ly_hero_2={classname="Panel",name="ly_hero_2",parName="default",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="158",y="426",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9168",anchorPointX="0",anchorPointY="0",},
ly_hero_3={classname="Panel",name="ly_hero_3",parName="default",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="291",y="426",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9169",anchorPointX="0",anchorPointY="0",},
ly_hero_4={classname="Panel",name="ly_hero_4",parName="default",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="423",y="426",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9170",anchorPointX="0",anchorPointY="0",},
img_select={classname="ImageView",name="img_select",parName="default",ZOrder="1",fileName="#v2_img_liaotiantoushi2.png",scale9Enable="true",scale9Height="130",scale9Width="142",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="1",capInsetsY="65",height="130",width="142",x="14",y="544",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="90",tag="9186",anchorPointX="0",anchorPointY="0",},
lay_con={classname="Panel",name="lay_con",parName="default",childCount="6",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="ui/big_img/v2_bg_longdi.jpg",height="410",width="546",x="7",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9171",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lb_name={classname="Label",name="lb_name",parName="lay_con",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="名字 等级",fontName="微软雅黑",fontSize="20",height="27",width="86",x="273",y="394",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9172",anchorPointX="0.5",anchorPointY="0.5",},
lay_btn_recover={classname="Panel",name="lay_btn_recover",parName="lay_con",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v2_btn_blue6.png",height="46",width="110",x="436",y="357",visible="true",touchAble="true",flipX="false",scaleX="0.79999995",scaleY="0.79999995",opacity="255",rotation="0",tag="9173",anchorPointX="0",anchorPointY="0",},
lay_soul_items={classname="Panel",name="lay_soul_items",parName="lay_con",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="410",width="546",x="0",y="0",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9191",anchorPointX="0",anchorPointY="0",},
lay_lines={classname="Panel",name="lay_lines",parName="lay_con",childCount="9",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="410",width="546",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9504",anchorPointX="0",anchorPointY="0",},
lay_lines_1={classname="Panel",name="lay_lines_1",parName="lay_con",childCount="9",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="410",width="546",x="0",y="0",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9193",anchorPointX="0",anchorPointY="0",},
lay_break={classname="Panel",name="lay_break",parName="lay_con",childCount="3",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="410",width="546",x="0",y="0",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9206",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lb_recover={classname="Label",name="lb_recover",parName="lay_btn_recover",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="还  原",fontName="微软雅黑",fontSize="25",height="32",width="64",x="22",y="8",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9177",anchorPointX="0",anchorPointY="0",},
line_1={classname="ImageView",name="line_1",parName="lay_lines",ZOrder="0",fileName="#v2_line_longx.png",scale9Enable="true",scale9Height="110",scale9Width="2",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="1",capInsetsY="5",height="110",width="2",x="79",y="189",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="20",tag="9505",anchorPointX="0.5",anchorPointY="0",},
line_2={classname="ImageView",name="line_2",parName="lay_lines",ZOrder="0",fileName="#v2_line_longx.png",scale9Enable="true",scale9Height="110",scale9Width="2",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="1",capInsetsY="5",height="110",width="2",x="121",y="306",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="120",tag="9506",anchorPointX="0.5",anchorPointY="0",},
line_3={classname="ImageView",name="line_3",parName="lay_lines",ZOrder="0",fileName="#v2_line_longx.png",scale9Enable="true",scale9Height="110",scale9Width="2",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="1",capInsetsY="5",height="110",width="2",x="204",y="234",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="18",tag="9507",anchorPointX="0.5",anchorPointY="1",},
line_4={classname="ImageView",name="line_4",parName="lay_lines",ZOrder="0",fileName="#v2_line_longx.png",scale9Enable="true",scale9Height="110",scale9Width="2",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="1",capInsetsY="5",height="110",width="2",x="160",y="97",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="86",tag="9508",anchorPointX="0.5",anchorPointY="0",},
line_5={classname="ImageView",name="line_5",parName="lay_lines",ZOrder="0",fileName="#v2_line_longx.png",scale9Enable="true",scale9Height="110",scale9Width="2",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="1",capInsetsY="5",height="110",width="2",x="263",y="106",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="20",tag="9509",anchorPointX="0.5",anchorPointY="0",},
line_6={classname="ImageView",name="line_6",parName="lay_lines",ZOrder="0",fileName="#v2_line_longx.png",scale9Enable="true",scale9Height="110",scale9Width="2",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="1",capInsetsY="5",height="110",width="2",x="302",y="212",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="140",tag="9510",anchorPointX="0.5",anchorPointY="0",},
line_7={classname="ImageView",name="line_7",parName="lay_lines",ZOrder="0",fileName="#v2_line_longx.png",scale9Enable="true",scale9Height="110",scale9Width="2",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="1",capInsetsY="5",height="110",width="2",x="374",y="120",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="30",tag="9511",anchorPointX="0.5",anchorPointY="0",},
line_8={classname="ImageView",name="line_8",parName="lay_lines",ZOrder="0",fileName="#v2_line_longx.png",scale9Enable="true",scale9Height="110",scale9Width="2",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="1",capInsetsY="5",height="110",width="2",x="420",y="211",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="142",tag="9512",anchorPointX="0.5",anchorPointY="1",},
line_9={classname="ImageView",name="line_9",parName="lay_lines",ZOrder="0",fileName="#v2_line_longx.png",scale9Enable="true",scale9Height="110",scale9Width="2",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="1",capInsetsY="5",height="110",width="2",x="361",y="302",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="90",tag="9513",anchorPointX="0.5",anchorPointY="0",},
line_1_1={classname="ImageView",name="line_1_1",parName="lay_lines_1",ZOrder="0",fileName="#v2_line_longx.png",scale9Enable="true",scale9Height="110",scale9Width="2",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="1",capInsetsY="5",height="110",width="2",x="98",y="241",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="20",tag="9194",anchorPointX="0.5",anchorPointY="0.5",},
line_2_1={classname="ImageView",name="line_2_1",parName="lay_lines_1",ZOrder="0",fileName="#v2_line_longx.png",scale9Enable="true",scale9Height="110",scale9Width="2",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="1",capInsetsY="5",height="110",width="2",x="169",y="278",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="120",tag="9196",anchorPointX="0.5",anchorPointY="0.5",},
line_3_1={classname="ImageView",name="line_3_1",parName="lay_lines_1",ZOrder="0",fileName="#v2_line_longx.png",scale9Enable="true",scale9Height="110",scale9Width="2",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="1",capInsetsY="5",height="110",width="2",x="187",y="182",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="18",tag="9197",anchorPointX="0.5",anchorPointY="0.5",},
line_4_1={classname="ImageView",name="line_4_1",parName="lay_lines_1",ZOrder="0",fileName="#v2_line_longx.png",scale9Enable="true",scale9Height="110",scale9Width="2",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="1",capInsetsY="5",height="110",width="2",x="215",y="100",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="86",tag="9198",anchorPointX="0.5",anchorPointY="0.5",},
line_5_1={classname="ImageView",name="line_5_1",parName="lay_lines_1",ZOrder="0",fileName="#v2_line_longx.png",scale9Enable="true",scale9Height="110",scale9Width="2",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="1",capInsetsY="5",height="110",width="2",x="282",y="157",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="20",tag="9199",anchorPointX="0.5",anchorPointY="0.5",},
line_6_1={classname="ImageView",name="line_6_1",parName="lay_lines_1",ZOrder="0",fileName="#v2_line_longx.png",scale9Enable="true",scale9Height="110",scale9Width="2",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="1",capInsetsY="5",height="110",width="2",x="337",y="170",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="140",tag="9200",anchorPointX="0.5",anchorPointY="0.5",},
line_7_1={classname="ImageView",name="line_7_1",parName="lay_lines_1",ZOrder="0",fileName="#v2_line_longx.png",scale9Enable="true",scale9Height="110",scale9Width="2",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="1",capInsetsY="5",height="110",width="2",x="401",y="167",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="30",tag="9201",anchorPointX="0.5",anchorPointY="0.5",},
line_8_1={classname="ImageView",name="line_8_1",parName="lay_lines_1",ZOrder="0",fileName="#v2_line_longx.png",scale9Enable="true",scale9Height="110",scale9Width="2",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="1",capInsetsY="5",height="110",width="2",x="386",y="255",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="142",tag="9202",anchorPointX="0.5",anchorPointY="0.5",},
line_9_1={classname="ImageView",name="line_9_1",parName="lay_lines_1",ZOrder="0",fileName="#v2_line_longx.png",scale9Enable="true",scale9Height="110",scale9Width="2",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="1",capInsetsY="5",height="110",width="2",x="415",y="302",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="90",tag="9203",anchorPointX="0.5",anchorPointY="0.5",},
img_break_di={classname="ImageView",name="img_break_di",parName="lay_break",ZOrder="0",fileName="#v2_img_wodepaimingdi.png",scale9Enable="true",scale9Height="99",scale9Width="448",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="224",capInsetsY="20",height="99",width="448",x="273",y="259",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9207",anchorPointX="0.5",anchorPointY="1",},
lb_break_add={classname="Label",name="lb_break_add",parName="lay_break",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="273",y="210",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9208",anchorPointX="0.5",anchorPointY="0.5",},
img_fonts_tpxg={classname="ImageView",name="img_fonts_tpxg",parName="lay_break",ZOrder="0",fileName="#v2_fonts_tpxg.png",scale9Enable="false",scale9Height="40",scale9Width="130",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="40",width="130",x="273",y="285",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9209",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable