local tTable = {}


tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1060",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
view={classname="Panel",name="view",parName="default",childCount="6",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1060",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_top={classname="Panel",name="lay_top",parName="view",childCount="6",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="270",width="640",x="0",y="790",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8",anchorPointX="0",anchorPointY="0",},
lay_content={classname="Panel",name="lay_content",parName="view",childCount="13",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="ui/big_img_sep/v2_bg_laba.png",height="623",width="640",x="0",y="163",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="10",anchorPointX="0",anchorPointY="0",},
lay_btn_left={classname="Panel",name="lay_btn_left",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="30",y="38",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="11",anchorPointX="0",anchorPointY="0",},
lay_btn_right={classname="Panel",name="lay_btn_right",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="455",y="38",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="12",anchorPointX="0",anchorPointY="0",},
lay_btn_center={classname="Panel",name="lay_btn_center",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="246",y="37",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="82",anchorPointX="0",anchorPointY="0",},
lay_stop={classname="Panel",name="lay_stop",parName="view",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1060",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="109",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lay_jianbian={classname="Panel",name="lay_jianbian",parName="lay_top",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_black30.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="10",height="87",width="640",x="0",y="5",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="52",anchorPointX="0",anchorPointY="0",},
txt_desc={classname="CustomLabel",name="txt_desc",parName="lay_top",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="80",areaWidth="600",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="80",width="600",x="20",y="89",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="23",anchorPointX="0",anchorPointY="1",},
lay_banner_bg={classname="Panel",name="lay_banner_bg",parName="lay_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="270",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="57",anchorPointX="0",anchorPointY="0",},
img_font={classname="ImageView",name="img_font",parName="lay_top",ZOrder="0",fileName="#v2_fonts_jipindajiang.png",scale9Enable="false",scale9Height="95",scale9Width="369",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="95",width="369",x="204",y="142",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="61",anchorPointX="0.5",anchorPointY="0.5",},
lay_img_yl={classname="Panel",name="lay_img_yl",parName="lay_top",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="100",width="100",x="504",y="138",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="63",anchorPointX="0",anchorPointY="0",},
lay_yl_btn={classname="Panel",name="lay_yl_btn",parName="lay_top",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="100",x="503",y="96",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="65",anchorPointX="0",anchorPointY="0",},
img_zj={classname="ImageView",name="img_zj",parName="lay_content",ZOrder="5",fileName="#v2_fonts_benqizuiji.png",scale9Enable="false",scale9Height="65",scale9Width="60",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="65",width="60",x="85",y="497",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="68",anchorPointX="0.5",anchorPointY="0.5",},
img_title={classname="ImageView",name="img_title",parName="lay_content",ZOrder="5",fileName="#v2_fonts_quanminlaba.png",scale9Enable="false",scale9Height="115",scale9Width="282",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="115",width="282",x="320",y="597",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="66",anchorPointX="0.5",anchorPointY="0.5",},
lay_zj_slot1={classname="Panel",name="lay_zj_slot1",parName="lay_content",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="80",width="80",x="147",y="452",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="69",anchorPointX="0",anchorPointY="0",},
lay_zj_slot2={classname="Panel",name="lay_zj_slot2",parName="lay_content",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="80",width="80",x="267",y="452",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="71",anchorPointX="0",anchorPointY="0",},
lay_zj_slot3={classname="Panel",name="lay_zj_slot3",parName="lay_content",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="80",width="80",x="387",y="452",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="72",anchorPointX="0",anchorPointY="0",},
lay_zj_slot4={classname="Panel",name="lay_zj_slot4",parName="lay_content",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="80",width="80",x="507",y="452",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="73",anchorPointX="0",anchorPointY="0",},
lay_laba1={classname="Panel",name="lay_laba1",parName="lay_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="336",width="118",x="89",y="62",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="84",anchorPointX="0",anchorPointY="0",},
lay_laba2={classname="Panel",name="lay_laba2",parName="lay_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="336",width="118",x="261",y="62",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="86",anchorPointX="0",anchorPointY="0",},
lay_laba3={classname="Panel",name="lay_laba3",parName="lay_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="336",width="118",x="432",y="62",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="87",anchorPointX="0",anchorPointY="0",},
img_laba3={classname="ImageView",name="img_laba3",parName="lay_content",ZOrder="6",fileName="ui/big_img/v2_bg_laba2.png",scale9Enable="false",scale9Height="360",scale9Width="131",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="360",width="131",x="491",y="228",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="80",anchorPointX="0.5",anchorPointY="0.5",},
img_laba2={classname="ImageView",name="img_laba2",parName="lay_content",ZOrder="5",fileName="ui/big_img/v2_bg_laba2.png",scale9Enable="false",scale9Height="360",scale9Width="131",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="360",width="131",x="319",y="228",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="79",anchorPointX="0.5",anchorPointY="0.5",},
img_laba1={classname="ImageView",name="img_laba1",parName="lay_content",ZOrder="5",fileName="ui/big_img/v2_bg_laba2.png",scale9Enable="false",scale9Height="360",scale9Width="131",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="360",width="131",x="148",y="228",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="77",anchorPointX="0.5",anchorPointY="0.5",},
lay_best={classname="Panel",name="lay_best",parName="lay_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="110",width="460",x="91",y="175",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="97",anchorPointX="0",anchorPointY="0",},
}

return tTable