local tTable = {}

tTable["texturesPng"] = {"ui/p1_commmon1_sep.plist","ui/p1_commmon2_sep.plist","ui/p1_commonse2.plist","ui/bar/v1_bar_b1.png","ui/p1_commonse1.plist","ui/p1_button1.plist"}
tTable["index_1"] = {
dlg_hero_update={classname="Panel",name="dlg_hero_update",parName="root",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="610",width="560",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="632",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
ly_hero_list={classname="Panel",name="ly_hero_list",parName="dlg_hero_update",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="159",width="560",x="0",y="451",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="706",anchorPointX="0",anchorPointY="0",},
ly_content={classname="Panel",name="ly_content",parName="dlg_hero_update",childCount="23",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="460",width="530",x="15",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="639",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
img_arrow={classname="ImageView",name="img_arrow",parName="ly_hero_list",ZOrder="5",fileName="#v1_img_sanjiaojiantou.png",scale9Enable="false",scale9Height="26",scale9Width="41",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="26",width="41",x="72",y="17",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="707",anchorPointX="0.5",anchorPointY="0.5",},
ly_hero_online={classname="Panel",name="ly_hero_online",parName="ly_hero_list",childCount="4",ZOrder="6",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen7.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="63",capInsetsY="65",height="130",width="542",x="9",y="17",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="708",anchorPointX="0",anchorPointY="0",},
lb_update_title={classname="CustomLabel",name="lb_update_title",parName="ly_content",ZOrder="15",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="lb_title",fontName="微软雅黑",fontSize="20",height="27",width="62",x="265",y="437",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="649",anchorPointX="0.5",anchorPointY="0.5",},
img_1={classname="ImageView",name="img_1",parName="ly_content",ZOrder="1",fileName="#v1_img_jianbian2.png",scale9Enable="true",scale9Height="49",scale9Width="530",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="147",capInsetsY="25",height="49",width="530",x="265",y="411",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="648",anchorPointX="0.5",anchorPointY="0",},
ly_arrow_up={classname="Panel",name="ly_arrow_up",parName="ly_content",childCount="2",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="47",width="33",x="123",y="364",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="668",anchorPointX="0",anchorPointY="0",},
ly_arrow_down={classname="Panel",name="ly_arrow_down",parName="ly_content",childCount="2",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="47",width="33",x="123",y="316",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="669",anchorPointX="0",anchorPointY="0",},
ly_bar={classname="Panel",name="ly_bar",parName="ly_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v1_bar_b1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="45",capInsetsY="9",height="16",width="488",x="20",y="355",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="672",anchorPointX="0",anchorPointY="0",},
lb_exp_percent={classname="CustomLabel",name="lb_exp_percent",parName="ly_content",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="100%",fontName="微软雅黑",fontSize="20",height="27",width="54",x="265",y="363",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="674",anchorPointX="0.5",anchorPointY="0.5",},
ly_tl_l_1={classname="Panel",name="ly_tl_l_1",parName="ly_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="27",width="100",x="50",y="316",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="652",anchorPointX="0",anchorPointY="0",},
ly_tl_l_2={classname="Panel",name="ly_tl_l_2",parName="ly_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="27",width="100",x="50",y="283",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="654",anchorPointX="0",anchorPointY="0",},
ly_tl_l_3={classname="Panel",name="ly_tl_l_3",parName="ly_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="27",width="100",x="50",y="251",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="656",anchorPointX="0",anchorPointY="0",},
img_arrow_lan={classname="ImageView",name="img_arrow_lan",parName="ly_content",ZOrder="0",fileName="#v1_img_shengjijiantou.png",scale9Enable="false",scale9Height="45",scale9Width="50",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="45",width="50",x="265",y="312",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="650",anchorPointX="0.5",anchorPointY="0.5",},
lb_show_exp={classname="CustomLabel",name="lb_show_exp",parName="ly_content",ZOrder="5",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="10k/50k",fontName="微软雅黑",fontSize="20",height="27",width="79",x="265",y="363",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="813",anchorPointX="0.5",anchorPointY="0.5",},
img_line={classname="ImageView",name="img_line",parName="ly_content",ZOrder="0",fileName="#v1_line_blue1.png",scale9Enable="true",scale9Height="3",scale9Width="526",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="1",height="3",width="526",x="265",y="240",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="663",anchorPointX="0.5",anchorPointY="0.5",},
lay_reduce={classname="Panel",name="lay_reduce",parName="ly_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_btn_reduce.png",height="34",width="34",x="5",y="15",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8413",anchorPointX="0",anchorPointY="0",},
lay_increase={classname="Panel",name="lay_increase",parName="ly_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_btn_increase.png",height="34",width="34",x="375",y="15",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8415",anchorPointX="0",anchorPointY="0",},
lay_bar_select={classname="Panel",name="lay_bar_select",parName="ly_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="18",width="300",x="57",y="23",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8416",anchorPointX="0",anchorPointY="0",},
lay_num={classname="Panel",name="lay_num",parName="ly_content",childCount="1",ZOrder="9",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen9.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="15",capInsetsY="15",height="30",width="90",x="430",y="17",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8417",anchorPointX="0",anchorPointY="0",},
ly_icon_1={classname="Panel",name="ly_icon_1",parName="ly_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="34",y="60",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8419",anchorPointX="0",anchorPointY="0",},
ly_icon_2={classname="Panel",name="ly_icon_2",parName="ly_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="212",y="60",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8421",anchorPointX="0",anchorPointY="0",},
ly_icon_3={classname="Panel",name="ly_icon_3",parName="ly_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="390",y="60",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8422",anchorPointX="0",anchorPointY="0",},
lb_cur_lv={classname="Label",name="lb_cur_lv",parName="ly_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="当前",fontName="微软雅黑",fontSize="18",height="24",width="36",x="20",y="387",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8423",anchorPointX="0",anchorPointY="0.5",},
lb_after_lv={classname="Label",name="lb_after_lv",parName="ly_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="预览",fontName="微软雅黑",fontSize="18",height="24",width="36",x="510",y="387",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8425",anchorPointX="1",anchorPointY="0.5",},
lb_add_exp={classname="Label",name="lb_add_exp",parName="ly_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="本次提升经验",fontName="微软雅黑",fontSize="18",height="24",width="108",x="265",y="386",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8427",anchorPointX="0.5",anchorPointY="0.5",},
lb_lv_full={classname="Label",name="lb_lv_full",parName="ly_content",ZOrder="9",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="等级已满",fontName="微软雅黑",fontSize="20",height="27",width="80",x="387",y="297",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8428",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_4"] = {
ly_hero_1={classname="Panel",name="ly_hero_1",parName="ly_hero_online",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="15",y="11",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="709",anchorPointX="0",anchorPointY="0",},
ly_hero_2={classname="Panel",name="ly_hero_2",parName="ly_hero_online",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="149",y="11",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="710",anchorPointX="0",anchorPointY="0",},
ly_hero_3={classname="Panel",name="ly_hero_3",parName="ly_hero_online",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="284",y="11",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="711",anchorPointX="0",anchorPointY="0",},
ly_hero_4={classname="Panel",name="ly_hero_4",parName="ly_hero_online",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="418",y="11",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="712",anchorPointX="0",anchorPointY="0",},
Image_34={classname="ImageView",name="Image_34",parName="ly_arrow_up",ZOrder="0",fileName="#v1_img_lansejiantou.png",scale9Enable="false",scale9Height="47",scale9Width="33",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="47",width="33",x="16",y="24",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="666",anchorPointX="0.5",anchorPointY="0.5",},
lb_percent_up={classname="CustomLabel",name="lb_percent_up",parName="ly_arrow_up",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="90%",fontName="微软雅黑",fontSize="12",height="17",width="25",x="16",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="670",anchorPointX="0.5",anchorPointY="0.5",},
Image_35={classname="ImageView",name="Image_35",parName="ly_arrow_down",ZOrder="0",fileName="#v1_img_huasngjiantou.png",scale9Enable="false",scale9Height="47",scale9Width="33",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="47",width="33",x="16",y="24",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="667",anchorPointX="0.5",anchorPointY="0.5",},
lb_percent_down={classname="CustomLabel",name="lb_percent_down",parName="ly_arrow_down",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="90%",fontName="微软雅黑",fontSize="12",height="17",width="25",x="16",y="15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="671",anchorPointX="0.5",anchorPointY="0.5",},
lb_item_num={classname="Label",name="lb_item_num",parName="lay_num",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="999",fontName="微软雅黑",fontSize="20",height="27",width="36",x="45",y="15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8418",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable