local tTable = {}


tTable["index_1"] = {
dlg_hero_advance_m={classname="Panel",name="dlg_hero_advance_m",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1066",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4114",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
ly_main={classname="Panel",name="ly_main",parName="dlg_hero_advance_m",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1066",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4115",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
ly_icon={classname="Panel",name="ly_icon",parName="ly_main",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="460",width="640",x="0",y="606",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4116",anchorPointX="0",anchorPointY="0",},
ly_title={classname="Panel",name="ly_title",parName="ly_main",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_xiaobiaoti2.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="100",capInsetsY="10",height="50",width="640",x="0",y="555",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4121",anchorPointX="0",anchorPointY="0",},
ly_equip={classname="Panel",name="ly_equip",parName="ly_main",childCount="6",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="20",capInsetsY="20",height="390",width="640",x="0",y="163",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4124",anchorPointX="0",anchorPointY="0",},
ly_bottom={classname="Panel",name="ly_bottom",parName="ly_main",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="162",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4131",anchorPointX="0",anchorPointY="0",},
ly_tips={classname="Panel",name="ly_tips",parName="ly_main",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="640",x="0",y="370",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4923",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
ly_hero_1={classname="Panel",name="ly_hero_1",parName="ly_icon",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="400",width="250",x="30",y="31",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4117",anchorPointX="0",anchorPointY="0",},
ly_hero_2={classname="Panel",name="ly_hero_2",parName="ly_icon",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="400",width="250",x="358",y="31",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4118",anchorPointX="0",anchorPointY="0",},
img_arrow={classname="CustomImageView",name="img_arrow",parName="ly_icon",ZOrder="0",fileName="#v1_img_shengjijiantou.png",scale9Enable="false",scale9Height="45",scale9Width="50",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="45",width="50",x="320",y="237",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4120",anchorPointX="0.5",anchorPointY="0.5",},
lb_title={classname="CustomLabel",name="lb_title",parName="ly_title",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="17",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4122",anchorPointX="0",anchorPointY="0.5",},
lb_tips={classname="CustomLabel",name="lb_tips",parName="ly_title",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="616",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4123",anchorPointX="1",anchorPointY="0.5",},
ly_equip_1={classname="Panel",name="ly_equip_1",parName="ly_equip",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="148",width="108",x="64",y="221",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4125",anchorPointX="0",anchorPointY="0",},
ly_equip_2={classname="Panel",name="ly_equip_2",parName="ly_equip",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="148",width="108",x="267",y="221",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4126",anchorPointX="0",anchorPointY="0",},
ly_equip_3={classname="Panel",name="ly_equip_3",parName="ly_equip",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="148",width="108",x="469",y="221",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4127",anchorPointX="0",anchorPointY="0",},
ly_equip_4={classname="Panel",name="ly_equip_4",parName="ly_equip",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="148",width="108",x="64",y="38",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4128",anchorPointX="0",anchorPointY="0",},
ly_equip_5={classname="Panel",name="ly_equip_5",parName="ly_equip",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="148",width="108",x="267",y="38",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4129",anchorPointX="0",anchorPointY="0",},
ly_equip_6={classname="Panel",name="ly_equip_6",parName="ly_equip",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="148",width="108",x="469",y="38",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4130",anchorPointX="0",anchorPointY="0",},
lb_advanceTip={classname="CustomLabel",name="lb_advanceTip",parName="ly_bottom",ZOrder="0",colorB="34",colorG="35",colorR="215",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="321",y="139",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4132",anchorPointX="0.5",anchorPointY="0.5",},
ly_down_btn_l={classname="Panel",name="ly_down_btn_l",parName="ly_bottom",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="72",y="36",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4133",anchorPointX="0",anchorPointY="0",},
ly_down_btn_r={classname="Panel",name="ly_down_btn_r",parName="ly_bottom",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="389",y="38",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4134",anchorPointX="0",anchorPointY="0",},
lb_finishTips={classname="CustomLabel",name="lb_finishTips",parName="ly_tips",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="24",height="31",width="116",x="320",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4924",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable