local tTable = {}

tTable["texturesPng"] = {"ui/p1_commmon2_sep.plist","ui/p1_commmon1_sep.plist","ui/p1_button1.plist"}
tTable["index_1"] = {
root={classname="Panel",name="root",parName="root",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_yindaotankuang.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="125",capInsetsY="130",height="350",width="572",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1026",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_info={classname="Panel",name="lay_info",parName="root",childCount="7",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="125",capInsetsY="130",height="260",width="508",x="62",y="32",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1027",anchorPointX="0",anchorPointY="0",},
img_yindao={classname="ImageView",name="img_yindao",parName="root",ZOrder="1",fileName="#v1_bg_banshenyindao.png",scale9Enable="false",scale9Height="434",scale9Width="294",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="434",width="294",x="0",y="-43",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1030",anchorPointX="0",anchorPointY="0",},
img_close={classname="ImageView",name="img_close",parName="root",ZOrder="0",fileName="#v1_btn_closebig2.png",scale9Enable="false",scale9Height="50",scale9Width="50",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="50",width="50",x="572",y="350",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1606",anchorPointX="1",anchorPointY="1",},
}
tTable["index_3"] = {
lb_tip_2={classname="Label",name="lb_tip_2",parName="lay_info",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="主公在离开期间，百姓变动如下",fontName="微软雅黑",fontSize="20",height="27",width="280",x="190",y="191",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1033",anchorPointX="0",anchorPointY="0.5",},
lb_tip_3={classname="Label",name="lb_tip_3",parName="lay_info",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="城内百姓：",fontName="微软雅黑",fontSize="20",height="27",width="100",x="190",y="149",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1037",anchorPointX="0",anchorPointY="0.5",},
lb_tip_4={classname="Label",name="lb_tip_4",parName="lay_info",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="国家百姓：",fontName="微软雅黑",fontSize="20",height="27",width="100",x="190",y="107",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1035",anchorPointX="0",anchorPointY="0.5",},
lb_tip_5={classname="Label",name="lb_tip_5",parName="lay_info",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="工坊生产队列总耗时：",fontName="微软雅黑",fontSize="20",height="27",width="200",x="190",y="65",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1036",anchorPointX="0",anchorPointY="0.5",},
lb_city_p={classname="Label",name="lb_city_p",parName="lay_info",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="-1491",fontName="微软雅黑",fontSize="20",height="27",width="57",x="290",y="149",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1039",anchorPointX="0",anchorPointY="0.5",},
lb_country_p={classname="Label",name="lb_country_p",parName="lay_info",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="+1993",fontName="微软雅黑",fontSize="20",height="27",width="63",x="290",y="107",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1040",anchorPointX="0",anchorPointY="0.5",},
lb_time={classname="Label",name="lb_time",parName="lay_info",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="耗时",fontName="微软雅黑",fontSize="20",height="27",width="40",x="390",y="65",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1041",anchorPointX="0",anchorPointY="0.5",},
}

return tTable