local tTable = {}


tTable["index_1"] = {
default={classname="Panel",name="default@fill_layout",parName="root",childCount="6",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1060",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_temp_1={classname="Panel",name="lay_temp_1",parName="default",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="11",width="640",x="0",y="1052",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="38",anchorPointX="0",anchorPointY="0",},
lay_camp_top={classname="Panel",name="lay_camp_top",parName="default",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="192",width="640",x="0",y="874",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8",anchorPointX="0",anchorPointY="0",},
lay_temp_2={classname="Panel",name="lay_temp_2",parName="default",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="4",width="640",x="0",y="861",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="37",anchorPointX="0",anchorPointY="0",},
lay_recruiting={classname="Panel",name="lay_recruiting",parName="default",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="120",width="600",x="20",y="756",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="218",anchorPointX="0",anchorPointY="0",},
lay_camp_center={classname="Panel",name="lay_camp_center@fill_layout",parName="default",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="603",width="640",x="0",y="154",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="39",anchorPointX="0",anchorPointY="0",},
lay_camp_bottom={classname="Panel",name="lay_camp_bottom",parName="default",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="153",width="600",x="20",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="40",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
img_arm={classname="ImageView",name="img_arm",parName="lay_camp_top",ZOrder="10",fileName="#v1_img_bubingqs.png",scale9Enable="false",scale9Height="200",scale9Width="153",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="200",width="153",x="115",y="99",visible="true",touchAble="false",flipX="false",scaleX="0.79999995",scaleY="0.79999995",opacity="255",rotation="0",tag="125",anchorPointX="0.5",anchorPointY="0.5",},
img_typs={classname="ImageView",name="img_typs",parName="lay_camp_top",ZOrder="10",fileName="#v1_img_bubing.png",scale9Enable="false",scale9Height="112",scale9Width="98",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="112",width="98",x="50",y="165",visible="true",touchAble="false",flipX="false",scaleX="0.5",scaleY="0.5",opacity="255",rotation="0",tag="27",anchorPointX="0.5",anchorPointY="0.5",},
lay_c_t_r={classname="Panel",name="lay_c_t_r",parName="lay_camp_top",childCount="3",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="200",width="200",x="400",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="18",anchorPointX="0",anchorPointY="0",},
lay_c_t_c={classname="Panel",name="lay_c_t_c",parName="lay_camp_top",childCount="4",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="175",width="190",x="180",y="17",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9",anchorPointX="0",anchorPointY="0",},
lay_banner_bg={classname="Panel",name="lay_banner_bg",parName="lay_camp_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="192",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="19498",anchorPointX="0",anchorPointY="0",},
lay_btn_left={classname="Panel",name="lay_btn_left",parName="lay_camp_bottom",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="50",y="36",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="41",anchorPointX="0",anchorPointY="0",},
lay_btn_right={classname="Panel",name="lay_btn_right",parName="lay_camp_bottom",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="395",y="36",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="42",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lay_line_v={classname="Panel",name="lay_line_v",parName="lay_c_t_r",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_line_blue2.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="1",capInsetsY="12",height="140",width="2",x="0",y="30",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="21",anchorPointX="0",anchorPointY="0",},
lay_zy={classname="Panel",name="lay_zy",parName="lay_c_t_r",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="100",width="200",x="0",y="100",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="28",anchorPointX="0",anchorPointY="0",},
lay_jj={classname="Panel",name="lay_jj",parName="lay_c_t_r",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="100",width="200",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="29",anchorPointX="0",anchorPointY="0",},
lay_tips1={classname="Panel",name="lay_tips1",parName="lay_c_t_c",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_zjm_utje.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="44",capInsetsY="12",height="24",width="200",x="0",y="125",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="19259",anchorPointX="0",anchorPointY="0",},
lay_tips2={classname="Panel",name="lay_tips2",parName="lay_c_t_c",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_zjm_utje.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="44",capInsetsY="12",height="24",width="200",x="0",y="85",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="19332",anchorPointX="0",anchorPointY="0",},
lay_tips3={classname="Panel",name="lay_tips3",parName="lay_c_t_c",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_zjm_utje.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="44",capInsetsY="12",height="24",width="200",x="0",y="45",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="19335",anchorPointX="0",anchorPointY="0",},
lay_tips4={classname="Panel",name="lay_tips4",parName="lay_c_t_c",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_zjm_utje.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="44",capInsetsY="12",height="24",width="200",x="0",y="5",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="19338",anchorPointX="0",anchorPointY="0",},
}
tTable["index_5"] = {
lay_icon_1={classname="Panel",name="lay_icon_1",parName="lay_zy",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="88",width="88",x="14",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="19",anchorPointX="0",anchorPointY="0",},
lb_f_name={classname="Label",name="lb_f_name",parName="lay_zy",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="110",y="60",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="23",anchorPointX="0",anchorPointY="0.5",},
lb_f_param={classname="Label",name="lb_f_param",parName="lay_zy",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="110",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="24",anchorPointX="0",anchorPointY="0.5",},
lay_icon_2={classname="Panel",name="lay_icon_2",parName="lay_jj",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="88",width="88",x="14",y="7",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="20",anchorPointX="0",anchorPointY="0",},
lb_s_name={classname="Label",name="lb_s_name",parName="lay_jj",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="110",y="68",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="25",anchorPointX="0",anchorPointY="0.5",},
lb_s_param={classname="Label",name="lb_s_param",parName="lay_jj",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="50",areaWidth="120",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="50",width="120",x="110",y="29",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="26",anchorPointX="0",anchorPointY="0.5",},
lb_pa_tips1={classname="Label",name="lb_pa_tips1",parName="lay_tips1",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="20",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="10",anchorPointX="0",anchorPointY="0.5",},
lb_param1={classname="Label",name="lb_param1",parName="lay_tips1",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="55555",fontName="微软雅黑",fontSize="20",height="27",width="60",x="120",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="14",anchorPointX="0",anchorPointY="0.5",},
lb_pa_tips2={classname="Label",name="lb_pa_tips2",parName="lay_tips2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="20",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="11",anchorPointX="0",anchorPointY="0.5",},
lb_param2={classname="Label",name="lb_param2",parName="lay_tips2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="44444",fontName="微软雅黑",fontSize="20",height="27",width="60",x="120",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="15",anchorPointX="0",anchorPointY="0.5",},
lb_pa_tips3={classname="Label",name="lb_pa_tips3",parName="lay_tips3",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="20",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="12",anchorPointX="0",anchorPointY="0.5",},
lb_param3={classname="Label",name="lb_param3",parName="lay_tips3",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="66666",fontName="微软雅黑",fontSize="20",height="27",width="60",x="120",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="16",anchorPointX="0",anchorPointY="0.5",},
lb_pa_tips4={classname="Label",name="lb_pa_tips4",parName="lay_tips4",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="20",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="13",anchorPointX="0",anchorPointY="0.5",},
lb_param4={classname="Label",name="lb_param4",parName="lay_tips4",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="88888",fontName="微软雅黑",fontSize="20",height="27",width="60",x="120",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="17",anchorPointX="0",anchorPointY="0.5",},
}

return tTable