local tTable = {}


tTable["index_1"] = {
default={classname="Panel",name="default@fill_layout",parName="root",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1066",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="114",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_top={classname="Panel",name="lay_top",parName="default",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="270",width="640",x="0",y="795",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="115",anchorPointX="0",anchorPointY="0",},
lay_title={classname="Panel",name="lay_title",parName="default",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="66",width="640",x="0",y="729",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="198",anchorPointX="0",anchorPointY="0",},
lay_bg={classname="Panel",name="lay_bg@fill_layout",parName="default",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="30",capInsetsWidth="30",capInsetsX="7",capInsetsY="7",height="710",width="600",x="20",y="20",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="117",anchorPointX="0",anchorPointY="0",},
lay_bottom={classname="Panel",name="lay_bottom",parName="default",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="20",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="199",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
img_jianbian={classname="ImageView",name="img_jianbian",parName="lay_top",ZOrder="2",fileName="ui/big_img_sep/v1_img_jianbian.png",scale9Enable="true",scale9Height="87",scale9Width="640",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="87",width="640",x="320",y="50",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="180",tag="129",anchorPointX="0.5",anchorPointY="0.5",},
img_fonts1={classname="ImageView",name="img_fonts1",parName="lay_top",ZOrder="5",fileName="#v1_bg_wgfntrww.png",scale9Enable="false",scale9Height="46",scale9Width="183",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="46",width="183",x="200",y="48",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="118",anchorPointX="0.5",anchorPointY="0.5",},
img_fonts2={classname="ImageView",name="img_fonts2",parName="lay_top",ZOrder="5",fileName="#v1_bg_bvrrrk.png",scale9Enable="false",scale9Height="45",scale9Width="180",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="45",width="180",x="440",y="48",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="128",anchorPointX="0.5",anchorPointY="0.5",},
lay_banner_bg={classname="Panel",name="lay_banner_bg",parName="lay_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="270",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="170",anchorPointX="0",anchorPointY="0",},
lay_title_bg={classname="Panel",name="lay_title_bg",parName="lay_title",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_title3.png",capInsetsHeight="27",capInsetsWidth="42",capInsetsX="10",capInsetsY="10",height="51",width="600",x="19",y="7",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="143",anchorPointX="0",anchorPointY="0",},
lb_title={classname="Label",name="lb_title",parName="lay_title",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="特价礼包刷新时间：",fontName="微软雅黑",fontSize="20",height="27",width="180",x="115",y="33",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="144",anchorPointX="0.5",anchorPointY="0.5",},
lb_r_time={classname="Label",name="lb_r_time",parName="lay_title",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="219",y="33",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="145",anchorPointX="0",anchorPointY="0.5",},
lay_list={classname="Panel",name="lay_list@fill_layout",parName="lay_bg",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="690",width="584",x="8",y="37",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="133",anchorPointX="0",anchorPointY="0",},
lay_tip={classname="Panel",name="lay_tip",parName="lay_bg",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="37",width="600",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="200",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
txt_tip={classname="Label",name="txt_tip",parName="lay_tip",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="320",y="18",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="185",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable