local tTable = {}


tTable["index_1"] = {
dlg_chatper_info={classname="Panel",name="dlg_chatper_info",parName="root",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="760",width="560",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="641",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
ly_top={classname="Panel",name="ly_top",parName="dlg_chatper_info",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="142",width="560",x="0",y="618",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="642",anchorPointX="0",anchorPointY="0",},
ly_center={classname="Panel",name="ly_center",parName="dlg_chatper_info",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="480",width="520",x="20",y="138",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="643",anchorPointX="0",anchorPointY="0",},
ly_bottom={classname="Panel",name="ly_bottom",parName="dlg_chatper_info",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="138",width="560",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="645",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
ly_top_bottom={classname="Panel",name="ly_top_bottom",parName="ly_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen6.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="10",height="130",width="523",x="18",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="646",anchorPointX="0",anchorPointY="0",},
ly_top_bottom_1={classname="Panel",name="ly_top_bottom_1",parName="ly_top",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen6_b.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="129",width="350",x="18",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="881",anchorPointX="0",anchorPointY="0",},
img_top={classname="CustomImageView",name="img_top",parName="ly_top",ZOrder="5",fileName="#v1_img_tjmc.png",scale9Enable="false",scale9Height="96",scale9Width="96",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="96",width="96",x="86",y="67",visible="true",touchAble="false",flipX="false",scaleX="1.5",scaleY="1.5",opacity="255",rotation="0",tag="647",anchorPointX="0.5",anchorPointY="0.5",},
lb_des={classname="CustomLabel",name="lb_des",parName="ly_top",ZOrder="5",colorB="255",colorG="255",colorR="255",areaHeight="86",areaWidth="350",hAlignment="0",vAlignment="0",text="粮草突然被乱军阻断。为今之计，只有紧急扩充军备，以万全之姿突围，方能置诸死地而后生。",fontName="微软雅黑",fontSize="20",height="86",width="350",x="170",y="85",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="648",anchorPointX="0",anchorPointY="1",},
img_title={classname="CustomImageView",name="img_title",parName="ly_top",ZOrder="5",fileName="#v2_fonts_zjt_2.png",scale9Enable="false",scale9Height="36",scale9Width="125",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="36",width="125",x="167",y="102",visible="true",touchAble="false",flipX="false",scaleX="0.8",scaleY="0.8",opacity="255",rotation="0",tag="854",anchorPointX="0",anchorPointY="0.5",},
img_0={classname="CustomImageView",name="img_0",parName="ly_bottom",ZOrder="0",fileName="#v2_img_xsfuduqdd02a.png",scale9Enable="false",scale9Height="13",scale9Width="162",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="13",width="162",x="143",y="109",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="652",anchorPointX="0.5",anchorPointY="0.5",},
img_1={classname="CustomImageView",name="img_1",parName="ly_bottom",ZOrder="0",fileName="#v2_img_xsfuduqdd02a.png",scale9Enable="false",scale9Height="13",scale9Width="162",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="13",width="162",x="403",y="109",visible="true",touchAble="false",flipX="true",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="738",anchorPointX="0.5",anchorPointY="0.5",},
lb_prize_title={classname="CustomLabel",name="lb_prize_title",parName="ly_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="章节奖励",fontName="微软雅黑",fontSize="22",height="30",width="88",x="272",y="111",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="739",anchorPointX="0.5",anchorPointY="0.5",},
ly_itemList={classname="Panel",name="ly_itemList",parName="ly_bottom",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="68",width="380",x="32",y="14",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="742",anchorPointX="0",anchorPointY="0",},
ly_btn={classname="Panel",name="ly_btn",parName="ly_bottom",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="90",x="441",y="25",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="743",anchorPointX="0",anchorPointY="0",},
}

return tTable