local tTable = {}

tTable["texturesPng"] = {"icon/p1_icon_font.plist","ui/p1_commonse1.plist"}
tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="740",width="560",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="296",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
view={classname="Panel",name="view",parName="default",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="740",width="560",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="297",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_info={classname="Panel",name="lay_info",parName="view",childCount="8",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="63",capInsetsY="65",height="160",width="518",x="22",y="564",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4092",anchorPointX="0",anchorPointY="0",},
lay_banner={classname="Panel",name="lay_banner",parName="view",childCount="5",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_biaoqian5.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="25",capInsetsY="23",height="47",width="520",x="19",y="513",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4100",anchorPointX="0",anchorPointY="0",},
lay_content={classname="Panel",name="lay_content",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="354",width="520",x="21",y="155",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="298",anchorPointX="0",anchorPointY="0",},
lay_richtext_tip={classname="Panel",name="lay_richtext_tip",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="27",width="350",x="104",y="108",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4107",anchorPointX="0",anchorPointY="0",},
lay_btn_garrison={classname="Panel",name="lay_btn_garrison",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="65",width="150",x="207",y="33",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="299",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lay_icon={classname="Panel",name="lay_icon",parName="lay_info",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="150",width="150",x="23",y="6",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4093",anchorPointX="0",anchorPointY="0",},
txt_name={classname="CustomLabel",name="txt_name",parName="lay_info",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="204",y="140",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4094",anchorPointX="0",anchorPointY="0.5",},
txt_pos={classname="CustomLabel",name="txt_pos",parName="lay_info",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="204",y="110",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4095",anchorPointX="0",anchorPointY="0.5",},
txt_move_time={classname="CustomLabel",name="txt_move_time",parName="lay_info",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="204",y="81",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4096",anchorPointX="0",anchorPointY="0.5",},
txt_hero_count_title={classname="CustomLabel",name="txt_hero_count_title",parName="lay_info",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="已驻防武将数：",fontName="微软雅黑",fontSize="20",height="27",width="140",x="204",y="51",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4097",anchorPointX="0",anchorPointY="0.5",},
txt_troops={classname="CustomLabel",name="txt_troops",parName="lay_info",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="204",y="23",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4098",anchorPointX="0",anchorPointY="0.5",},
img_flag={classname="CustomImageView",name="img_flag",parName="lay_info",ZOrder="1",fileName="#v1_img_qun.png",scale9Enable="false",scale9Height="64",scale9Width="51",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="64",width="51",x="476",y="116",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4099",anchorPointX="0.5",anchorPointY="0.5",},
lay_richtext_hero_count={classname="Panel",name="lay_richtext_hero_count",parName="lay_info",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="27",width="95",x="346",y="38",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="5695",anchorPointX="0",anchorPointY="0",},
txt_banner_title1={classname="CustomLabel",name="txt_banner_title1",parName="lay_banner",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="56",y="23",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4101",anchorPointX="0.5",anchorPointY="0.5",},
txt_banner_title2={classname="CustomLabel",name="txt_banner_title2",parName="lay_banner",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="158",y="23",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4102",anchorPointX="0.5",anchorPointY="0.5",},
txt_banner_title3={classname="CustomLabel",name="txt_banner_title3",parName="lay_banner",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="259",y="23",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4103",anchorPointX="0.5",anchorPointY="0.5",},
txt_banner_title4={classname="CustomLabel",name="txt_banner_title4",parName="lay_banner",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="361",y="23",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4104",anchorPointX="0.5",anchorPointY="0.5",},
txt_banner_title5={classname="CustomLabel",name="txt_banner_title5",parName="lay_banner",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="463",y="23",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4106",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable