local tTable = {}

tTable["texturesPng"] = {"ui/v2_bg_popup_a.png","ui/p2_commonse1.plist","ui/language/cn/p2_font1.plist","ui/p2_commmon2_sep.plist","ui/p1_commonse1.plist","ui/p1_button1.plist","ui/v2_bg_popup_b.png"}
tTable["index_1"] = {
lay_def={classname="Panel",name="lay_def",parName="root",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="710",width="560",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_top={classname="Panel",name="lay_top",parName="lay_def",childCount="12",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/v2_bg_popup_a.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="150",capInsetsY="125",height="580",width="560",x="0",y="130",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8",anchorPointX="0",anchorPointY="0",},
lay_bot={classname="Panel",name="lay_bot",parName="lay_def",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/v2_bg_popup_b.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="150",capInsetsY="25",height="130",width="560",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
img_title_bg={classname="ImageView",name="img_title_bg",parName="lay_top",ZOrder="0",fileName="ui/big_img/v2_bg_zhandou.png",scale9Enable="false",scale9Height="105",scale9Width="591",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="105",width="591",x="280",y="561",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="10",anchorPointX="0.5",anchorPointY="0.5",},
img_title={classname="ImageView",name="img_title",parName="lay_top",ZOrder="1",fileName="#v2_fonts_wangquanzhsh.png",scale9Enable="false",scale9Height="26",scale9Width="104",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="26",width="104",x="280",y="550",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="11",anchorPointX="0.5",anchorPointY="0.5",},
lay_btn_get={classname="Panel",name="lay_btn_get",parName="lay_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="391",y="299",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="13",anchorPointX="0",anchorPointY="0",},
lay_prize={classname="Panel",name="lay_prize",parName="lay_top",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_wangquandi.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="40",capInsetsY="40",height="152",width="516",x="22",y="15",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="15",anchorPointX="0",anchorPointY="0",},
img_baoxiang={classname="ImageView",name="img_baoxiang",parName="lay_top",ZOrder="0",fileName="#v1_img_wangquanzhengshou.png",scale9Enable="false",scale9Height="96",scale9Width="96",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="96",width="96",x="454",y="403",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="19",anchorPointX="0.5",anchorPointY="0.5",},
lay_close={classname="Panel",name="lay_close",parName="lay_top",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="60",width="64",x="492",y="521",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="95",anchorPointX="0",anchorPointY="0",},
lay_btn_1={classname="Panel",name="lay_btn_1",parName="lay_top",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="63",width="106",x="15",y="184",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="31",anchorPointX="0",anchorPointY="0",},
lay_btn_2={classname="Panel",name="lay_btn_2",parName="lay_top",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="63",width="106",x="121",y="184",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="43",anchorPointX="0",anchorPointY="0",},
lay_btn_3={classname="Panel",name="lay_btn_3",parName="lay_top",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="63",width="106",x="227",y="184",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="49",anchorPointX="0",anchorPointY="0",},
lay_btn_4={classname="Panel",name="lay_btn_4",parName="lay_top",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="63",width="106",x="333",y="184",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="55",anchorPointX="0",anchorPointY="0",},
lay_btn_5={classname="Panel",name="lay_btn_5",parName="lay_top",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="63",width="106",x="439",y="184",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="61",anchorPointX="0",anchorPointY="0",},
lay_desc={classname="Panel",name="lay_desc",parName="lay_top",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="200",width="330",x="25",y="269",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="91",anchorPointX="0",anchorPointY="0",},
lay_btn={classname="Panel",name="lay_btn",parName="lay_bot",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="203",y="34",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="14",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lay_item_1={classname="Panel",name="lay_item_1",parName="lay_prize",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="86",width="86",x="20",y="12",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="64",anchorPointX="0",anchorPointY="0",},
lay_item_2={classname="Panel",name="lay_item_2",parName="lay_prize",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="86",width="86",x="150",y="11",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="67",anchorPointX="0",anchorPointY="0",},
lay_item_3={classname="Panel",name="lay_item_3",parName="lay_prize",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="86",width="86",x="280",y="11",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="69",anchorPointX="0",anchorPointY="0",},
lay_item_4={classname="Panel",name="lay_item_4",parName="lay_prize",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="86",width="86",x="410",y="11",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="71",anchorPointX="0",anchorPointY="0",},
img_close={classname="ImageView",name="img_close",parName="lay_close",ZOrder="0",fileName="#v1_btn_close.png",scale9Enable="false",scale9Height="32",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="32",width="31",x="32",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="16",anchorPointX="0.5",anchorPointY="0.5",},
lb_title_1={classname="Label",name="lb_title_1",parName="lay_btn_1",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="53",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="34",anchorPointX="0.5",anchorPointY="0.5",},
img_btn_bg_1={classname="ImageView",name="img_btn_bg_1",parName="lay_btn_1",ZOrder="0",fileName="#v1_btn_biaoqian4.png",scale9Enable="false",scale9Height="70",scale9Width="118",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="70",width="118",x="0",y="0",visible="true",touchAble="false",flipX="false",scaleX="0.9",scaleY="0.9",opacity="255",rotation="0",tag="39",anchorPointX="0",anchorPointY="0",},
lb_title_2={classname="Label",name="lb_title_2",parName="lay_btn_2",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="53",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="44",anchorPointX="0.5",anchorPointY="0.5",},
img_btn_bg_2={classname="ImageView",name="img_btn_bg_2",parName="lay_btn_2",ZOrder="0",fileName="#v1_btn_biaoqian4.png",scale9Enable="false",scale9Height="70",scale9Width="118",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="70",width="118",x="0",y="0",visible="true",touchAble="false",flipX="false",scaleX="0.9",scaleY="0.9",opacity="255",rotation="0",tag="45",anchorPointX="0",anchorPointY="0",},
lb_title_3={classname="Label",name="lb_title_3",parName="lay_btn_3",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="53",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="50",anchorPointX="0.5",anchorPointY="0.5",},
img_btn_bg_3={classname="ImageView",name="img_btn_bg_3",parName="lay_btn_3",ZOrder="0",fileName="#v1_btn_biaoqian4.png",scale9Enable="false",scale9Height="70",scale9Width="118",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="70",width="118",x="0",y="0",visible="true",touchAble="false",flipX="false",scaleX="0.9",scaleY="0.9",opacity="255",rotation="0",tag="51",anchorPointX="0",anchorPointY="0",},
lb_title_4={classname="Label",name="lb_title_4",parName="lay_btn_4",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="53",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="56",anchorPointX="0.5",anchorPointY="0.5",},
img_btn_bg_4={classname="ImageView",name="img_btn_bg_4",parName="lay_btn_4",ZOrder="0",fileName="#v1_btn_biaoqian4.png",scale9Enable="false",scale9Height="70",scale9Width="118",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="70",width="118",x="0",y="0",visible="true",touchAble="false",flipX="false",scaleX="0.9",scaleY="0.9",opacity="255",rotation="0",tag="57",anchorPointX="0",anchorPointY="0",},
lb_title_5={classname="Label",name="lb_title_5",parName="lay_btn_5",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="53",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="62",anchorPointX="0.5",anchorPointY="0.5",},
img_btn_bg_5={classname="ImageView",name="img_btn_bg_5",parName="lay_btn_5",ZOrder="0",fileName="#v1_btn_biaoqian4.png",scale9Enable="false",scale9Height="70",scale9Width="118",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="70",width="118",x="0",y="0",visible="true",touchAble="false",flipX="false",scaleX="0.9",scaleY="0.9",opacity="255",rotation="0",tag="63",anchorPointX="0",anchorPointY="0",},
lb_desc={classname="Label",name="lb_desc",parName="lay_desc",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="180",areaWidth="320",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="180",width="320",x="5",y="180",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="12",anchorPointX="0",anchorPointY="1",},
}

return tTable