local tTable = {}

tTable["texturesPng"] = {"ui/p2_commmon1_sep.plist","ui/bar/v1_bar_b2.png","ui/bar/v1_bar_b1.png"}
tTable["index_1"] = {
dlg_hero_arr_1={classname="Panel",name="dlg_hero_arr_1",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="240",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_attr={classname="Panel",name="lay_attr",parName="dlg_hero_arr_1",childCount="29",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="10",height="240",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1400",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
img_zz={classname="ImageView",name="img_zz",parName="lay_attr",ZOrder="0",fileName="#v2_img_wj_zizhi.png",scale9Enable="false",scale9Height="30",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="30",width="31",x="41",y="190",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1408",anchorPointX="0.5",anchorPointY="0.5",},
img_gong={classname="ImageView",name="img_gong",parName="lay_attr",ZOrder="0",fileName="#v2_img_wj_gong.png",scale9Enable="false",scale9Height="30",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="30",width="31",x="42",y="140",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1409",anchorPointX="0.5",anchorPointY="0.5",},
img_fang={classname="ImageView",name="img_fang",parName="lay_attr",ZOrder="0",fileName="#v2_img_wj_fang.png",scale9Enable="false",scale9Height="30",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="30",width="31",x="42",y="90",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1410",anchorPointX="0.5",anchorPointY="0.5",},
img_bing={classname="ImageView",name="img_bing",parName="lay_attr",ZOrder="0",fileName="#v2_img_wj_bing.png",scale9Enable="false",scale9Height="30",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="30",width="31",x="42",y="40",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1411",anchorPointX="0.5",anchorPointY="0.5",},
img_dengj={classname="ImageView",name="img_dengj",parName="lay_attr",ZOrder="0",fileName="#v2_img_dengjizg.png",scale9Enable="false",scale9Height="30",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="30",width="31",x="372",y="190",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1412",anchorPointX="0.5",anchorPointY="0.5",},
img_gongji={classname="ImageView",name="img_gongji",parName="lay_attr",ZOrder="0",fileName="#v2_img_wj_gongji.png",scale9Enable="false",scale9Height="29",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="29",width="31",x="372",y="140",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1413",anchorPointX="0.5",anchorPointY="0.5",},
img_fy={classname="ImageView",name="img_fy",parName="lay_attr",ZOrder="0",fileName="#v2_img_wj_fangyu.png",scale9Enable="false",scale9Height="29",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="29",width="31",x="372",y="90",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1603",anchorPointX="0.5",anchorPointY="0.5",},
img_bl={classname="ImageView",name="img_bl",parName="lay_attr",ZOrder="0",fileName="#v2_img_wj_bingli.png",scale9Enable="false",scale9Height="29",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="29",width="31",x="371",y="40",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1604",anchorPointX="0.5",anchorPointY="0.5",},
img_line={classname="ImageView",name="img_line",parName="lay_attr",ZOrder="0",fileName="#v2_line_wujiang.png",scale9Enable="false",scale9Height="229",scale9Width="3",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="229",width="3",x="321",y="119",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1795",anchorPointX="0.5",anchorPointY="0.5",},
ly_att_3={classname="Panel",name="ly_att_3",parName="lay_attr",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="170",x="394",y="25",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="300",anchorPointX="0",anchorPointY="0",},
ly_att_2={classname="Panel",name="ly_att_2",parName="lay_attr",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="170",x="394",y="75",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="304",anchorPointX="0",anchorPointY="0",},
ly_att_1={classname="Panel",name="ly_att_1",parName="lay_attr",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="170",x="394",y="125",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="302",anchorPointX="0",anchorPointY="0",},
lb_m_3={classname="CustomLabel",name="lb_m_3",parName="lay_attr",ZOrder="3",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="999",fontName="微软雅黑",fontSize="20",height="27",width="36",x="260",y="40",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="299",anchorPointX="0",anchorPointY="0.5",},
lb_m_2={classname="CustomLabel",name="lb_m_2",parName="lay_attr",ZOrder="3",colorB="112",colorG="110",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="999",fontName="微软雅黑",fontSize="20",height="27",width="36",x="260",y="90",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="298",anchorPointX="0",anchorPointY="0.5",},
lb_m_1={classname="CustomLabel",name="lb_m_1",parName="lay_attr",ZOrder="3",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="999",fontName="微软雅黑",fontSize="20",height="27",width="36",x="260",y="140",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="297",anchorPointX="0",anchorPointY="0.5",},
lb_so={classname="CustomLabel",name="lb_so",parName="lay_attr",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="兵",fontName="微软雅黑",fontSize="20",height="27",width="20",x="307",y="70",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="294",anchorPointX="0.5",anchorPointY="0.5",},
lb_l_4={classname="CustomLabel",name="lb_l_4",parName="lay_attr",ZOrder="2",colorB="218",colorG="199",colorR="198",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="兵",fontName="微软雅黑",fontSize="20",height="27",width="20",x="67",y="40",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="45",anchorPointX="0",anchorPointY="0.5",},
lb_de={classname="CustomLabel",name="lb_de",parName="lay_attr",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="防",fontName="微软雅黑",fontSize="20",height="27",width="20",x="163",y="70",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="293",anchorPointX="0.5",anchorPointY="0.5",},
lb_l_3={classname="CustomLabel",name="lb_l_3",parName="lay_attr",ZOrder="2",colorB="218",colorG="199",colorR="198",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="防",fontName="微软雅黑",fontSize="20",height="27",width="20",x="67",y="90",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="44",anchorPointX="0",anchorPointY="0.5",},
lb_at={classname="CustomLabel",name="lb_at",parName="lay_attr",ZOrder="5",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="攻",fontName="微软雅黑",fontSize="20",height="27",width="20",x="234",y="192",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="292",anchorPointX="0.5",anchorPointY="0.5",},
ly_add={classname="Panel",name="ly_add",parName="lay_attr",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="34",width="34",x="591",y="173",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="66",anchorPointX="0",anchorPointY="0",},
ly_bar_1={classname="Panel",name="ly_bar_1",parName="lay_attr",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v1_bar_b2.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="41",capInsetsY="6",height="18",width="123",x="456",y="182",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="58",anchorPointX="0",anchorPointY="0",},
lb_r_1={classname="CustomLabel",name="lb_r_1",parName="lay_attr",ZOrder="2",colorB="218",colorG="199",colorR="198",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="等级",fontName="微软雅黑",fontSize="20",height="27",width="40",x="394",y="190",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="46",anchorPointX="0",anchorPointY="0.5",},
lb_l_2={classname="CustomLabel",name="lb_l_2",parName="lay_attr",ZOrder="2",colorB="218",colorG="199",colorR="198",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="攻",fontName="微软雅黑",fontSize="20",height="27",width="20",x="67",y="140",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="43",anchorPointX="0",anchorPointY="0.5",},
lb_l_1={classname="CustomLabel",name="lb_l_1",parName="lay_attr",ZOrder="2",colorB="218",colorG="199",colorR="198",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="资质",fontName="微软雅黑",fontSize="20",height="27",width="40",x="67",y="190",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="42",anchorPointX="0",anchorPointY="0.5",},
img_shuxing={classname="ImageView",name="img_shuxing",parName="lay_attr",ZOrder="2",fileName="#v2_img_shuxingtu.png",scale9Enable="false",scale9Height="112",scale9Width="130",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="112",width="130",x="236",y="126",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="41",anchorPointX="0.5",anchorPointY="0.5",},
lay_m_bar_1={classname="Panel",name="lay_m_bar_1",parName="lay_attr",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v1_bar_b1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="45",capInsetsY="9",height="18",width="142",x="101",y="131",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8734",anchorPointX="0",anchorPointY="0",},
lay_m_bar_2={classname="Panel",name="lay_m_bar_2",parName="lay_attr",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v1_bar_b1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="45",capInsetsY="9",height="18",width="142",x="101",y="82",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8736",anchorPointX="0",anchorPointY="0",},
lay_m_bar_3={classname="Panel",name="lay_m_bar_3",parName="lay_attr",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v1_bar_b1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="45",capInsetsY="9",height="18",width="142",x="101",y="32",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8737",anchorPointX="0",anchorPointY="0",},
}

return tTable