local tTable = {}

tTable["texturesPng"] = {"ui/bar/v1_bar_b1.png","ui/p1_commonse1.plist","icon/p1_icon_font.plist"}
tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="740",width="560",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7406",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
view={classname="Panel",name="view",parName="default",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="740",width="560",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7407",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_info={classname="Panel",name="lay_info",parName="view",childCount="13",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="63",capInsetsY="65",height="160",width="520",x="19",y="571",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7408",anchorPointX="0",anchorPointY="0",},
lay_content={classname="Panel",name="lay_content",parName="view",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="346",width="520",x="19",y="218",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7419",anchorPointX="0",anchorPointY="0",},
txt_bottom_tip2={classname="CustomLabel",name="txt_bottom_tip2",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="284",y="177",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7424",anchorPointX="0.5",anchorPointY="0.5",},
txt_bottom_tip3={classname="CustomLabel",name="txt_bottom_tip3",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="284",y="102",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7425",anchorPointX="0.5",anchorPointY="0.5",},
lay_btn={classname="Panel",name="lay_btn",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="65",width="155",x="207",y="14",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7426",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lay_icon={classname="Panel",name="lay_icon",parName="lay_info",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="130",width="160",x="8",y="16",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7409",anchorPointX="0",anchorPointY="0",},
txt_name={classname="CustomLabel",name="txt_name",parName="lay_info",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="179",y="134",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7410",anchorPointX="0",anchorPointY="0.5",},
txt_pos_title={classname="CustomLabel",name="txt_pos_title",parName="lay_info",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="坐标：",fontName="微软雅黑",fontSize="20",height="27",width="60",x="179",y="106",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7411",anchorPointX="0",anchorPointY="0.5",},
txt_people_title={classname="CustomLabel",name="txt_people_title",parName="lay_info",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="人口：",fontName="微软雅黑",fontSize="20",height="27",width="60",x="179",y="79",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7412",anchorPointX="0",anchorPointY="0.5",},
txt_army_lv_title={classname="CustomLabel",name="txt_army_lv_title",parName="lay_info",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="御林军等级：",fontName="微软雅黑",fontSize="20",height="27",width="120",x="179",y="51",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7413",anchorPointX="0",anchorPointY="0.5",},
txt_army_lv={classname="CustomLabel",name="txt_army_lv",parName="lay_info",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="301",y="51",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7414",anchorPointX="0",anchorPointY="0.5",},
txt_exp_title={classname="CustomLabel",name="txt_exp_title",parName="lay_info",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="经验：",fontName="微软雅黑",fontSize="20",height="27",width="60",x="179",y="26",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7415",anchorPointX="0",anchorPointY="0.5",},
lay_exp_bg={classname="Panel",name="lay_exp_bg",parName="lay_info",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v1_bar_b1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="45",capInsetsY="9",height="14",width="146",x="240",y="13",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7416",anchorPointX="0",anchorPointY="0",},
img_rename={classname="CustomImageView",name="img_rename",parName="lay_info",ZOrder="1",fileName="#v1_img_shuxie.png",scale9Enable="false",scale9Height="49",scale9Width="51",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="49",width="51",x="394",y="124",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7417",anchorPointX="0.5",anchorPointY="0.5",},
img_flag={classname="CustomImageView",name="img_flag",parName="lay_info",ZOrder="1",fileName="#v1_img_qun.png",scale9Enable="false",scale9Height="64",scale9Width="51",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="64",width="51",x="20",y="139",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7418",anchorPointX="0.5",anchorPointY="0.5",},
txt_pos={classname="CustomLabel",name="txt_pos",parName="lay_info",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="txt_pos",fontName="微软雅黑",fontSize="20",height="27",width="68",x="240",y="105",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7492",anchorPointX="0",anchorPointY="0.5",},
txt_people={classname="CustomLabel",name="txt_people",parName="lay_info",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="240",y="79",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7986",anchorPointX="0",anchorPointY="0.5",},
lay_btn_rename={classname="Panel",name="lay_btn_rename",parName="lay_info",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="110",x="366",y="100",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="23929",anchorPointX="0",anchorPointY="0",},
txt_army_tip1={classname="CustomLabel",name="txt_army_tip1",parName="lay_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="264",y="303",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7420",anchorPointX="0.5",anchorPointY="0.5",},
lay_armys={classname="Panel",name="lay_armys",parName="lay_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="260",width="520",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7422",anchorPointX="0",anchorPointY="0",},
txt_army_tip3={classname="CustomLabel",name="txt_army_tip3",parName="lay_content",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="264",y="142",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7423",anchorPointX="0.5",anchorPointY="0.5",},
txt_city_tip1={classname="CustomLabel",name="txt_city_tip1",parName="lay_content",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="264",y="177",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7427",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable