local tTable = {}

tTable["texturesPng"] = {"ui/p1_commmon2_sep.plist"}
tTable["index_1"] = {
default={classname="Panel",name="default@fill_layout",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1066",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
view={classname="Panel",name="view@fill_layout",parName="default",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1066",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_top={classname="Panel",name="lay_top",parName="view",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="350",width="640",x="0",y="716",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="46",anchorPointX="0",anchorPointY="0",},
lay_listview={classname="Panel",name="lay_listview@fill_layout",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="680",width="600",x="18",y="36",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="22",anchorPointX="0",anchorPointY="0",},
lay_bottom={classname="Panel",name="lay_bottom",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="20",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="47",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lay_banner_bg={classname="Panel",name="lay_banner_bg",parName="lay_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="192",width="640",x="0",y="150",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="34",anchorPointX="0",anchorPointY="0",},
lay_rank={classname="Panel",name="lay_rank",parName="lay_top",childCount="10",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen7.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="63",capInsetsY="65",height="130",width="600",x="18",y="10",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="10",anchorPointX="0",anchorPointY="0",},
}
tTable["index_5"] = {
txt_fc_title={classname="CustomLabel",name="txt_fc_title",parName="lay_rank",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="当前战斗力：",fontName="微软雅黑",fontSize="20",height="27",width="120",x="11",y="101",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="11",anchorPointX="0",anchorPointY="0.5",},
txt_world_rank_title={classname="CustomLabel",name="txt_world_rank_title",parName="lay_rank",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="世界排行榜：",fontName="微软雅黑",fontSize="20",height="27",width="120",x="11",y="65",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="12",anchorPointX="0",anchorPointY="0.5",},
txt_country_rank_title={classname="CustomLabel",name="txt_country_rank_title",parName="lay_rank",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="国内排行榜：",fontName="微软雅黑",fontSize="20",height="27",width="120",x="11",y="29",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="13",anchorPointX="0",anchorPointY="0.5",},
txt_world_rank={classname="CustomLabel",name="txt_world_rank",parName="lay_rank",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="999",fontName="微软雅黑",fontSize="20",height="27",width="36",x="131",y="65",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="16",anchorPointX="0",anchorPointY="0.5",},
txt_country_rank={classname="CustomLabel",name="txt_country_rank",parName="lay_rank",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="未上榜",fontName="微软雅黑",fontSize="20",height="27",width="60",x="131",y="29",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="17",anchorPointX="0",anchorPointY="0.5",},
lay_richtext_fc={classname="Panel",name="lay_richtext_fc",parName="lay_rank",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="27",width="200",x="131",y="88",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="18",anchorPointX="0",anchorPointY="0",},
txt_rank_refresh_tip1={classname="CustomLabel",name="txt_rank_refresh_tip1",parName="lay_rank",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="200",y="65",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="19",anchorPointX="0",anchorPointY="0.5",},
txt_rank_refresh_tip2={classname="CustomLabel",name="txt_rank_refresh_tip2",parName="lay_rank",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="200",y="29",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="20",anchorPointX="0",anchorPointY="0.5",},
lay_btn_power={classname="Panel",name="lay_btn_power",parName="lay_rank",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="447",y="70",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="71",anchorPointX="0",anchorPointY="0",},
lay_btn_rank={classname="Panel",name="lay_btn_rank",parName="lay_rank",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="447",y="10",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="21",anchorPointX="0",anchorPointY="0",},
}

return tTable