local tTable = {}

tTable["texturesPng"] = {"icon/p1_icon_font.plist","ui/p1_commmon1_sep.plist"}
tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="706",width="560",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="52",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
view={classname="Panel",name="view",parName="default",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="200",capInsetsY="150",height="706",width="560",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="53",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
txt_tip={classname="CustomLabel",name="txt_tip",parName="view",ZOrder="0",colorB="0",colorG="0",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="281",y="169",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="60",anchorPointX="0.5",anchorPointY="0.5",},
lay_btn_attack={classname="Panel",name="lay_btn_attack",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="203",y="30",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="59",anchorPointX="0",anchorPointY="0",},
lay_info={classname="Panel",name="lay_info",parName="view",childCount="6",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="130",width="528",x="16",y="564",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1079",anchorPointX="0",anchorPointY="0",},
lay_space={classname="Panel",name="lay_space",parName="view",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_xiaobiaoti2.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="160",capInsetsY="24",height="48",width="528",x="15",y="509",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1081",anchorPointX="0",anchorPointY="0",},
lay_goods={classname="Panel",name="lay_goods",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="290",width="528",x="15",y="208",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1083",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
txt_name={classname="CustomLabel",name="txt_name",parName="lay_info",ZOrder="1",colorB="0",colorG="0",colorR="0",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="182",y="108",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="54",anchorPointX="0",anchorPointY="0.5",},
txt_pos={classname="CustomLabel",name="txt_pos",parName="lay_info",ZOrder="1",colorB="0",colorG="0",colorR="0",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="182",y="65",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="55",anchorPointX="0",anchorPointY="0.5",},
txt_move_time={classname="CustomLabel",name="txt_move_time",parName="lay_info",ZOrder="1",colorB="0",colorG="100",colorR="0",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="182",y="23",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="56",anchorPointX="0",anchorPointY="0.5",},
img_flag={classname="CustomImageView",name="img_flag",parName="lay_info",ZOrder="3",fileName="#v1_img_qun.png",scale9Enable="false",scale9Height="64",scale9Width="51",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="64",width="51",x="20",y="109",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1391",anchorPointX="0.5",anchorPointY="0.5",},
lay_icon={classname="Panel",name="lay_icon",parName="lay_info",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="100",width="150",x="14",y="17",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6217",anchorPointX="0",anchorPointY="0",},
lay_act_btn={classname="Panel",name="lay_act_btn",parName="lay_info",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="39",width="124",x="330",y="75",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="18810",anchorPointX="0",anchorPointY="0",},
txt_space_tip={classname="CustomLabel",name="txt_space_tip",parName="lay_space",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="22",y="24",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1082",anchorPointX="0",anchorPointY="0.5",},
}

return tTable