local tTable = {}


tTable["index_1"] = {
default={classname="Panel",name="default@fill_layout",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="817",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="35",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
view={classname="Panel",name="view@fill_layout",parName="default",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="817",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="36",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_bg={classname="Panel",name="lay_bg@fill_layout",parName="view",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="762",width="640",x="0",y="54",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="62",anchorPointX="0",anchorPointY="0",},
lay_bottom={classname="Panel",name="lay_bottom",parName="view",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="54",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="428",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lay_top={classname="Panel",name="lay_top",parName="lay_bg",childCount="12",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="185",width="640",x="0",y="578",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="37",anchorPointX="0",anchorPointY="0",},
lay_banner={classname="Panel",name="lay_banner",parName="lay_bg",childCount="4",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_black30.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="10",height="74",width="640",x="0",y="510",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="52",anchorPointX="0",anchorPointY="0",},
lay_banner3={classname="Panel",name="lay_banner3",parName="lay_bg",childCount="4",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v2_img_xiaobiaoti3.png",height="50",width="640",x="0",y="460",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="57",anchorPointX="0",anchorPointY="0",},
lay_listview={classname="Panel",name="lay_listview@fill_layout",parName="lay_bg",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="459",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="63",anchorPointX="0",anchorPointY="0",},
txt_tip2={classname="CustomLabel",name="txt_tip2",parName="lay_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="50",areaWidth="550",hAlignment="1",vAlignment="0",text="Text LabelText Label",fontName="微软雅黑",fontSize="16",height="50",width="550",x="320",y="27",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="109",anchorPointX="0.5",anchorPointY="0.5",},
txt_tip2_1={classname="CustomLabel",name="txt_tip2_1",parName="lay_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="1",vAlignment="0",text="Text LabelText Label",fontName="微软雅黑",fontSize="20",height="27",width="190",x="320",y="20",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="255",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_5"] = {
img_rank_bg2={classname="CustomImageView",name="img_rank_bg2",parName="lay_top",ZOrder="0",fileName="#v2_img_yinq.png",scale9Enable="false",scale9Height="230",scale9Width="150",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="230",width="150",x="168",y="78",visible="true",touchAble="false",flipX="false",scaleX="0.5",scaleY="0.5",opacity="255",rotation="0",tag="38",anchorPointX="0.5",anchorPointY="0.5",},
img_rank_bg1={classname="CustomImageView",name="img_rank_bg1",parName="lay_top",ZOrder="0",fileName="#v2_img_yinq.png",scale9Enable="false",scale9Height="230",scale9Width="150",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="230",width="150",x="322",y="91",visible="true",touchAble="false",flipX="false",scaleX="0.5",scaleY="0.5",opacity="255",rotation="0",tag="39",anchorPointX="0.5",anchorPointY="0.5",},
img_rank_bg3={classname="CustomImageView",name="img_rank_bg3",parName="lay_top",ZOrder="0",fileName="#v2_img_yinq.png",scale9Enable="false",scale9Height="230",scale9Width="150",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="230",width="150",x="476",y="78",visible="true",touchAble="false",flipX="false",scaleX="0.5",scaleY="0.5",opacity="255",rotation="0",tag="40",anchorPointX="0.5",anchorPointY="0.5",},
img_rank1={classname="CustomImageView",name="img_rank1",parName="lay_top",ZOrder="1",fileName="#v1_img_paixingbang1.png",scale9Enable="false",scale9Height="96",scale9Width="96",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="96",width="96",x="323",y="144",visible="true",touchAble="false",flipX="false",scaleX="0.8",scaleY="0.8",opacity="255",rotation="0",tag="41",anchorPointX="0.5",anchorPointY="0.5",},
img_rank2={classname="CustomImageView",name="img_rank2",parName="lay_top",ZOrder="1",fileName="#v1_img_paixingbang2.png",scale9Enable="false",scale9Height="96",scale9Width="96",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="96",width="96",x="167",y="131",visible="true",touchAble="false",flipX="false",scaleX="0.8",scaleY="0.8",opacity="255",rotation="0",tag="42",anchorPointX="0.5",anchorPointY="0.5",},
img_rank3={classname="CustomImageView",name="img_rank3",parName="lay_top",ZOrder="1",fileName="#v1_img_paixingbang3.png",scale9Enable="false",scale9Height="96",scale9Width="96",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="96",width="96",x="478",y="131",visible="true",touchAble="false",flipX="false",scaleX="0.8",scaleY="0.8",opacity="255",rotation="0",tag="43",anchorPointX="0.5",anchorPointY="0.5",},
img_country2={classname="CustomImageView",name="img_country2",parName="lay_top",ZOrder="2",fileName="ui/daitu.png",scale9Enable="false",scale9Height="10",scale9Width="10",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="10",width="10",x="168",y="73",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="45",anchorPointX="0.5",anchorPointY="0.5",},
img_country1={classname="CustomImageView",name="img_country1",parName="lay_top",ZOrder="2",fileName="ui/daitu.png",scale9Enable="false",scale9Height="10",scale9Width="10",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="10",width="10",x="324",y="86",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="47",anchorPointX="0.5",anchorPointY="0.5",},
img_country3={classname="CustomImageView",name="img_country3",parName="lay_top",ZOrder="2",fileName="ui/daitu.png",scale9Enable="false",scale9Height="10",scale9Width="10",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="10",width="10",x="476",y="73",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="48",anchorPointX="0.5",anchorPointY="0.5",},
txt_score2={classname="CustomLabel",name="txt_score2",parName="lay_top",ZOrder="3",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="16",height="21",width="77",x="168",y="11",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="49",anchorPointX="0.5",anchorPointY="0.5",},
txt_score1={classname="CustomLabel",name="txt_score1",parName="lay_top",ZOrder="3",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="16",height="21",width="77",x="322",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="50",anchorPointX="0.5",anchorPointY="0.5",},
txt_score3={classname="CustomLabel",name="txt_score3",parName="lay_top",ZOrder="3",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="16",height="21",width="77",x="477",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="51",anchorPointX="0.5",anchorPointY="0.5",},
txt_tip1={classname="CustomLabel",name="txt_tip1",parName="lay_banner",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="320",y="52",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="53",anchorPointX="0.5",anchorPointY="0.5",},
txt_my_point={classname="CustomLabel",name="txt_my_point",parName="lay_banner",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="517",y="21",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="356",anchorPointX="0.5",anchorPointY="0.5",},
txt_my_rank={classname="CustomLabel",name="txt_my_rank",parName="lay_banner",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="319",y="21",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="56",anchorPointX="0.5",anchorPointY="0.5",},
txt_my_country={classname="CustomLabel",name="txt_my_country",parName="lay_banner",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="37",y="21",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="55",anchorPointX="0",anchorPointY="0.5",},
txt_sub_tilte1={classname="CustomLabel",name="txt_sub_tilte1",parName="lay_banner3",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="排行",fontName="微软雅黑",fontSize="20",height="27",width="40",x="60",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="58",anchorPointX="0.5",anchorPointY="0.5",},
txt_sub_tilte2={classname="CustomLabel",name="txt_sub_tilte2",parName="lay_banner3",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="主公昵称",fontName="微软雅黑",fontSize="20",height="27",width="80",x="178",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="59",anchorPointX="0.5",anchorPointY="0.5",},
txt_sub_tilte3={classname="CustomLabel",name="txt_sub_tilte3",parName="lay_banner3",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="积分",fontName="微软雅黑",fontSize="20",height="27",width="40",x="307",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="60",anchorPointX="0.5",anchorPointY="0.5",},
txt_sub_tilte4={classname="CustomLabel",name="txt_sub_tilte4",parName="lay_banner3",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="奖励",fontName="微软雅黑",fontSize="20",height="27",width="40",x="516",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="61",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable