local tTable = {}

tTable["texturesPng"] = {"ui/p1_commmon2_sep.plist","ui/p1_commmon1_sep.plist"}
tTable["index_1"] = {
root={classname="Panel",name="root",parName="root",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="550",width="560",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="299",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_top={classname="Panel",name="lay_top",parName="root",childCount="10",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen6.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="63",capInsetsY="65",height="130",width="530",x="15",y="412",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="300",anchorPointX="0",anchorPointY="0",},
lay_title={classname="Panel",name="lay_title",parName="root",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_xiaobiaoti2.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="186",capInsetsY="24",height="50",width="530",x="15",y="354",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="312",anchorPointX="0",anchorPointY="0",},
lay_center={classname="Panel",name="lay_center",parName="root",ZOrder="0",useMergedTexture="false",clipAble="true",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="350",width="530",x="15",y="4",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="311",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_icon={classname="Panel",name="lay_icon",parName="lay_top",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="15",y="11",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="301",anchorPointX="0",anchorPointY="0",},
lb_nobility={classname="Label",name="lb_nobility",parName="lay_top",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="犀利哥",fontName="微软雅黑",fontSize="20",height="27",width="60",x="140",y="90",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="302",anchorPointX="0",anchorPointY="0.5",},
lb_next_nobility={classname="Label",name="lb_next_nobility",parName="lay_top",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="爆浆哥",fontName="微软雅黑",fontSize="20",height="27",width="60",x="347",y="90",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="303",anchorPointX="0",anchorPointY="0.5",},
lb_arrow_1={classname="Label",name="lb_arrow_1",parName="lay_top",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="→",fontName="微软雅黑",fontSize="20",height="27",width="20",x="244",y="90",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="304",anchorPointX="0",anchorPointY="0.5",},
lv_tip_1={classname="Label",name="lv_tip_1",parName="lay_top",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="上阵武将加成：",fontName="微软雅黑",fontSize="20",height="27",width="140",x="140",y="45",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="305",anchorPointX="0",anchorPointY="0.5",},
lb_adddes={classname="Label",name="lb_adddes",parName="lay_top",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="攻击",fontName="微软雅黑",fontSize="20",height="27",width="40",x="277",y="45",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="306",anchorPointX="0",anchorPointY="0.5",},
lb_cur_value={classname="Label",name="lb_cur_value",parName="lay_top",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="20",height="27",width="48",x="348",y="44",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="307",anchorPointX="0",anchorPointY="0.5",},
lb_arrow_2={classname="Label",name="lb_arrow_2",parName="lay_top",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="→",fontName="微软雅黑",fontSize="20",height="27",width="20",x="404",y="45",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="308",anchorPointX="0",anchorPointY="0.5",},
lb_add_value={classname="Label",name="lb_add_value",parName="lay_top",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="20",height="27",width="48",x="432",y="45",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="309",anchorPointX="0",anchorPointY="0.5",},
Image_9={classname="ImageView",name="Image_9",parName="lay_top",ZOrder="0",fileName="#v1_img_kelashen6_b.png",scale9Enable="true",scale9Height="130",scale9Width="350",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="175",capInsetsY="9",height="130",width="350",x="0",y="0",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4896",anchorPointX="0",anchorPointY="0",},
lb_title={classname="Label",name="lb_title",parName="lay_title",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="升级消耗",fontName="微软雅黑",fontSize="20",height="27",width="80",x="20",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="313",anchorPointX="0",anchorPointY="0.5",},
}

return tTable