local tTable = {}


tTable["index_1"] = {
default={classname="Panel",name="default@fill_layout",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1066",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="276",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
view={classname="Panel",name="view@fill_layout",parName="default",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1066",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="278",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_top={classname="Panel",name="lay_top",parName="view",childCount="6",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="63",capInsetsY="65",height="170",width="640",x="0",y="896",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1429",anchorPointX="0",anchorPointY="0",},
lay_banner={classname="Panel",name="lay_banner",parName="view",childCount="4",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_xiaobiaoti2.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="186",capInsetsY="25",height="50",width="640",x="0",y="843",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1430",anchorPointX="0",anchorPointY="0",},
lay_content={classname="Panel",name="lay_content@fill_layout",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="666",width="640",x="0",y="176",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1432",anchorPointX="0",anchorPointY="0",},
lay_bottom={classname="Panel",name="lay_bottom",parName="view",childCount="2",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="175",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="24692",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
txt_name={classname="CustomLabel",name="txt_name",parName="lay_top",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="22",height="30",width="106",x="231",y="116",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1435",anchorPointX="0",anchorPointY="0.5",},
txt_pos={classname="CustomLabel",name="txt_pos",parName="lay_top",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="231",y="71",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1436",anchorPointX="0",anchorPointY="0.5",},
txt_move_time={classname="CustomLabel",name="txt_move_time",parName="lay_top",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="231",y="32",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1439",anchorPointX="0",anchorPointY="0.5",},
img_flag={classname="CustomImageView",name="img_flag",parName="lay_top",ZOrder="1",fileName="#v1_img_qun.png",scale9Enable="false",scale9Height="64",scale9Width="51",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="64",width="51",x="559",y="118",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1440",anchorPointX="0.5",anchorPointY="0.5",},
lay_icon={classname="Panel",name="lay_icon",parName="lay_top",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="140",width="140",x="69",y="6",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4613",anchorPointX="0",anchorPointY="0",},
lay_banner_bg={classname="Panel",name="lay_banner_bg",parName="lay_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="192",width="640",x="0",y="-32",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="22877",anchorPointX="0",anchorPointY="0",},
lay_banner_tip={classname="CustomLabel",name="lay_banner_tip",parName="lay_banner",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="增益：",fontName="微软雅黑",fontSize="20",height="27",width="60",x="27",y="24",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1431",anchorPointX="0",anchorPointY="0.5",},
txt_banner_tip2={classname="CustomLabel",name="txt_banner_tip2",parName="lay_banner",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="出征全部武将",fontName="微软雅黑",fontSize="20",height="27",width="120",x="531",y="24",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="14186",anchorPointX="1",anchorPointY="0.5",},
lay_switch={classname="Panel",name="lay_switch",parName="lay_banner",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="80",x="538",y="9",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="14187",anchorPointX="0",anchorPointY="0",},
lay_buff_click={classname="Panel",name="lay_buff_click",parName="lay_banner",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="60",width="250",x="18",y="-7",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="22879",anchorPointX="0",anchorPointY="0",},
lay_btn_battle={classname="Panel",name="lay_btn_battle",parName="lay_bottom",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="60",width="150",x="242",y="62",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="284",anchorPointX="0",anchorPointY="0",},
txt_banner_tip3={classname="CustomLabel",name="txt_banner_tip3",parName="lay_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="313",y="212",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="14189",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable