local tTable = {}


tTable["index_1"] = {
root={classname="Panel",name="root",parName="root",childCount="8",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1066",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="3",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
img_bg={classname="ImageView",name="img_bg",parName="root",ZOrder="0",fileName="ui/v1_bg_shouchong.jpg",scale9Enable="false",scale9Height="532",scale9Width="590",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="532",width="590",x="320",y="772",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="5",anchorPointX="0.5",anchorPointY="0.5",},
img_bg_kuang={classname="ImageView",name="img_bg_kuang",parName="root",ZOrder="1",fileName="#v1_img_bannaerkuang.png",scale9Enable="true",scale9Height="1002",scale9Width="600",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="65",capInsetsY="65",height="1002",width="600",x="319",y="543",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4",anchorPointX="0.5",anchorPointY="0.5",},
lay_tip_1={classname="Panel",name="lay_tip_1",parName="root",childCount="1",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_blackjianbian.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="133",capInsetsY="32",height="106",width="586",x="26",y="400",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8",anchorPointX="0",anchorPointY="0",},
lay_btn={classname="Panel",name="lay_btn",parName="root",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="415",y="577",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9",anchorPointX="0",anchorPointY="0",},
lay_items={classname="Panel",name="lay_items",parName="root",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="218",width="564",x="37",y="110",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="10",anchorPointX="0",anchorPointY="0",},
img_baoxiang={classname="ImageView",name="img_baoxiang",parName="root",ZOrder="30",fileName="#v1_img_shouchongbaoxiang.png",scale9Enable="false",scale9Height="96",scale9Width="96",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="96",width="96",x="493",y="709",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="15",anchorPointX="0.5",anchorPointY="0.5",},
lay_title={classname="Panel",name="lay_title",parName="root",childCount="1",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_xiaobiaoti2.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="186",capInsetsY="24",height="50",width="564",x="37",y="328",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="11",anchorPointX="0",anchorPointY="0",},
Image_12={classname="ImageView",name="Image_12",parName="root",ZOrder="0",fileName="#v1_img_bannaerkuang.png",scale9Enable="true",scale9Height="1002",scale9Width="600",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="65",capInsetsY="65",height="1002",width="600",x="320",y="547",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="33",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_3"] = {
lb_desc={classname="Label",name="lb_desc",parName="lay_tip_1",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="90",areaWidth="550",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="90",width="550",x="16",y="98",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="27",anchorPointX="0",anchorPointY="1",},
lb_title={classname="Label",name="lb_title",parName="lay_title",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="礼包物品如下：",fontName="微软雅黑",fontSize="20",height="27",width="140",x="15",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="12",anchorPointX="0",anchorPointY="0.5",},
}

return tTable