local tTable = {}

tTable["texturesPng"] = {"ui/v2_bg_popup_a.png","ui/p2_commmon3_sep.plist","ui/language/cn/p2_font2.plist","ui/v2_bg_popup_b.png","ui/p1_commonse1.plist"}
tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/v2_bg_popup_a.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="150",capInsetsY="125",height="794",width="560",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="0",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
view={classname="Panel",name="view",parName="default",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="734",width="560",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="459",anchorPointX="0",anchorPointY="0",},
img_close={classname="CustomImageView",name="img_close",parName="default",ZOrder="1",fileName="#v1_btn_close.png",scale9Enable="false",scale9Height="32",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="32",width="31",x="525",y="763",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="836",anchorPointX="0.5",anchorPointY="0.5",},
txt_title={classname="CustomLabel",name="txt_title",parName="default",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="282",y="762",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="837",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_3"] = {
lay_top={classname="Panel",name="lay_top",parName="view",childCount="11",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="556",x="2",y="684",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="566",anchorPointX="0",anchorPointY="0",},
lay_middle={classname="Panel",name="lay_middle",parName="view",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="630",width="556",x="2",y="54",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="571",anchorPointX="0",anchorPointY="0",},
lay_bottom={classname="Panel",name="lay_bottom",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/v2_bg_popup_b.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="150",capInsetsY="25",height="54",width="560",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="572",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
img_top_bg_left={classname="CustomImageView",name="img_top_bg_left",parName="lay_top",ZOrder="1",fileName="#v2_img_jingongfang_hong.png",scale9Enable="false",scale9Height="46",scale9Width="228",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="46",width="228",x="114",y="23",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="567",anchorPointX="0.5",anchorPointY="0.5",},
img_top_bg_middle={classname="CustomImageView",name="img_top_bg_middle",parName="lay_top",ZOrder="0",fileName="#v2_img_gongshou_jzhc.png",scale9Enable="false",scale9Height="40",scale9Width="346",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="40",width="346",x="280",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="568",anchorPointX="0.5",anchorPointY="0.5",},
img_top_bg_right={classname="CustomImageView",name="img_top_bg_right",parName="lay_top",ZOrder="1",fileName="#v2_img_fangshoufang_lan.png",scale9Enable="false",scale9Height="46",scale9Width="228",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="46",width="228",x="442",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="569",anchorPointX="0.5",anchorPointY="0.5",},
txt_def_troops={classname="CustomLabel",name="txt_def_troops",parName="lay_top",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="999999",fontName="微软雅黑",fontSize="16",height="21",width="54",x="465",y="13",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="641",anchorPointX="0.5",anchorPointY="0.5",},
txt_def_country={classname="CustomLabel",name="txt_def_country",parName="lay_top",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="秦",fontName="微软雅黑",fontSize="20",height="27",width="20",x="465",y="34",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="640",anchorPointX="0.5",anchorPointY="0.5",},
txt_atk_country1={classname="CustomLabel",name="txt_atk_country1",parName="lay_top",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="汉",fontName="微软雅黑",fontSize="20",height="27",width="20",x="39",y="34",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="642",anchorPointX="0.5",anchorPointY="0.5",},
txt_atk_troops1={classname="CustomLabel",name="txt_atk_troops1",parName="lay_top",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="16",height="21",width="36",x="39",y="13",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="643",anchorPointX="0.5",anchorPointY="0.5",},
txt_atk_country2={classname="CustomLabel",name="txt_atk_country2",parName="lay_top",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="汉",fontName="微软雅黑",fontSize="20",height="27",width="20",x="100",y="34",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="644",anchorPointX="0.5",anchorPointY="0.5",},
txt_atk_troops2={classname="CustomLabel",name="txt_atk_troops2",parName="lay_top",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="16",height="21",width="36",x="100",y="13",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="645",anchorPointX="0.5",anchorPointY="0.5",},
txt_atk_country3={classname="CustomLabel",name="txt_atk_country3",parName="lay_top",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="汉",fontName="微软雅黑",fontSize="20",height="27",width="20",x="156",y="34",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="646",anchorPointX="0.5",anchorPointY="0.5",},
txt_atk_troops3={classname="CustomLabel",name="txt_atk_troops3",parName="lay_top",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="16",height="21",width="36",x="156",y="13",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="647",anchorPointX="0.5",anchorPointY="0.5",},
txt_none={classname="CustomLabel",name="txt_none",parName="lay_middle",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="无进攻部队",fontName="微软雅黑",fontSize="20",height="27",width="100",x="138",y="333",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1188",anchorPointX="0.5",anchorPointY="0.5",},
lay_listview_left={classname="Panel",name="lay_listview_left",parName="lay_middle",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="630",width="258",x="10",y="1",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="573",anchorPointX="0",anchorPointY="0",},
lay_listview_right={classname="Panel",name="lay_listview_right",parName="lay_middle",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="630",width="258",x="288",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="574",anchorPointX="0",anchorPointY="0",},
}

return tTable