local tTable = {}

tTable["texturesPng"] = {"ui/p2_commmon1_sep.plist","ui/bg_hero/v2_img_caiwenji.png","ui/language/cn/p2_font1.plist","ui/bg_hero/v1_img_zhujue.png","ui/p2_commonse1.plist","ui/bg_hero/v2_img_yangguifei.png"}
tTable["index_1"] = {
dlg_chief_house={classname="Panel",name="dlg_chief_house",parName="root",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1060",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_collect={classname="Panel",name="lay_collect",parName="dlg_chief_house",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_jinduyanjiudi.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="320",capInsetsY="33",height="280",width="640",x="0",y="753",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9",anchorPointX="0",anchorPointY="0",},
lay_defense={classname="Panel",name="lay_defense",parName="dlg_chief_house",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_jinduyanjiudi.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="320",capInsetsY="33",height="280",width="640",x="0",y="418",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="11",anchorPointX="0",anchorPointY="0",},
lay_operation={classname="Panel",name="lay_operation",parName="dlg_chief_house",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_jinduyanjiudi.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="320",capInsetsY="33",height="280",width="640",x="0",y="83",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="12",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
img_role_1={classname="ImageView",name="img_role_1",parName="lay_collect",ZOrder="0",fileName="ui/bg_hero/v2_img_caiwenji.png",scale9Enable="false",scale9Height="330",scale9Width="326",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="330",width="326",x="640",y="0",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="14",anchorPointX="1",anchorPointY="0",},
img_title_1={classname="ImageView",name="img_title_1",parName="lay_collect",ZOrder="1",fileName="#v2_fonts_caojiwujiang.png",scale9Enable="false",scale9Height="46",scale9Width="166",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="46",width="166",x="150",y="220",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="19",anchorPointX="0.5",anchorPointY="0.5",},
lb_title_1={classname="Label",name="lb_title_1",parName="lay_collect",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="90",areaWidth="300",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="90",width="300",x="20",y="175",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="21",anchorPointX="0",anchorPointY="1",},
img_role_2={classname="ImageView",name="img_role_2",parName="lay_defense",ZOrder="0",fileName="ui/bg_hero/v1_img_zhujue.png",scale9Enable="false",scale9Height="339",scale9Width="341",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="339",width="341",x="640",y="0",visible="true",touchAble="false",flipX="true",scaleX="0.94",scaleY="0.94",opacity="255",rotation="0",tag="15",anchorPointX="1",anchorPointY="0",},
img_title_2={classname="ImageView",name="img_title_2",parName="lay_defense",ZOrder="0",fileName="#v2_fonts_chengfangwujiang.png",scale9Enable="false",scale9Height="46",scale9Width="167",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="46",width="167",x="150",y="220",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="17",anchorPointX="0.5",anchorPointY="0.5",},
lb_title_2={classname="Label",name="lb_title_2",parName="lay_defense",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="90",areaWidth="300",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="90",width="300",x="20",y="175",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="22",anchorPointX="0",anchorPointY="1",},
lay_tip_2={classname="Panel",name="lay_tip_2",parName="lay_defense",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_hechengmingzidi.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="15",capInsetsY="15",height="30",width="320",x="10",y="30",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="24",anchorPointX="0",anchorPointY="0",},
img_role_3={classname="ImageView",name="img_role_3",parName="lay_operation",ZOrder="0",fileName="ui/bg_hero/v2_img_yangguifei.png",scale9Enable="false",scale9Height="330",scale9Width="326",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="330",width="326",x="640",y="0",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="16",anchorPointX="1",anchorPointY="0",},
img_title_3={classname="ImageView",name="img_title_3",parName="lay_operation",ZOrder="0",fileName="#v2_fonts_gaojiyubingshu.png",scale9Enable="false",scale9Height="85",scale9Width="240",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="85",width="240",x="150",y="220",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="20",anchorPointX="0.5",anchorPointY="0.5",},
lb_title_3={classname="Label",name="lb_title_3",parName="lay_operation",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="90",areaWidth="300",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="90",width="300",x="20",y="175",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="23",anchorPointX="0",anchorPointY="1",},
lay_tip_3={classname="Panel",name="lay_tip_3",parName="lay_operation",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_hechengmingzidi.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="15",capInsetsY="15",height="30",width="320",x="10",y="42",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="25",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lb_tip_2={classname="Label",name="lb_tip_2",parName="lay_tip_2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="160",y="15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="27",anchorPointX="0.5",anchorPointY="0.5",},
img_lock={classname="ImageView",name="img_lock",parName="lay_tip_2",ZOrder="0",fileName="#v2_img_lock_tjp.png",scale9Enable="false",scale9Height="31",scale9Width="24",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="31",width="24",x="90",y="15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="28",anchorPointX="0.5",anchorPointY="0.5",},
lb_tip_3={classname="Label",name="lb_tip_3",parName="lay_tip_3",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="160",y="15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="26",anchorPointX="0.5",anchorPointY="0.5",},
img_lock_3={classname="ImageView",name="img_lock_3",parName="lay_tip_3",ZOrder="0",fileName="#v2_img_lock_tjp.png",scale9Enable="false",scale9Height="31",scale9Width="24",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="31",width="24",x="89",y="15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="36",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable