local tTable = {}

tTable["texturesPng"] = {"ui/p1_commmon2_sep.plist","ui/language/cn/p2_font1.plist","ui/p1_commonse1.plist"}
tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="400",width="500",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_daily_gift={classname="Panel",name="lay_daily_gift",parName="default",childCount="6",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen6.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="50",height="180",width="470",x="15",y="200",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8",anchorPointX="0",anchorPointY="0",},
lay_discount_gift={classname="Panel",name="lay_discount_gift",parName="default",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen6.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="50",height="180",width="470",x="15",y="10",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="10",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_daily_gift_btn={classname="Panel",name="lay_daily_gift_btn",parName="lay_daily_gift",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="330",y="44",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="11",anchorPointX="0",anchorPointY="0",},
lay_icon1={classname="Panel",name="lay_icon1",parName="lay_daily_gift",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="70",width="70",x="20",y="3",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="12",anchorPointX="0",anchorPointY="0",},
txt_time={classname="Label",name="txt_time",parName="lay_daily_gift",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="394",y="110",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="17",anchorPointX="0.5",anchorPointY="0.5",},
lay_title={classname="Panel",name="lay_title",parName="lay_daily_gift",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen6_b.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="175",capInsetsY="9",height="44",width="350",x="0",y="136",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="21",anchorPointX="0",anchorPointY="0",},
lay_line={classname="Panel",name="lay_line",parName="lay_daily_gift",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_line_blue1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="1",height="2",width="470",x="0",y="134",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="23",anchorPointX="0",anchorPointY="0",},
txt_desc1={classname="Label",name="txt_desc1",parName="lay_daily_gift",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="80",areaWidth="180",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="80",width="180",x="121",y="97",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="30",anchorPointX="0",anchorPointY="1",},
lay_discount_gift_btn={classname="Panel",name="lay_discount_gift_btn",parName="lay_discount_gift",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="330",y="44",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="14",anchorPointX="0",anchorPointY="0",},
lay_icon2={classname="Panel",name="lay_icon2",parName="lay_discount_gift",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="70",width="70",x="20",y="3",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="16",anchorPointX="0",anchorPointY="0",},
lay_title2={classname="Panel",name="lay_title2",parName="lay_discount_gift",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen6_b.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="175",capInsetsY="9",height="44",width="350",x="0",y="136",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="26",anchorPointX="0",anchorPointY="0",},
lay_line_2={classname="Panel",name="lay_line_2",parName="lay_discount_gift",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_line_blue1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="1",height="2",width="470",x="0",y="134",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="29",anchorPointX="0",anchorPointY="0",},
txt_desc2={classname="Label",name="txt_desc2",parName="lay_discount_gift",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="80",areaWidth="180",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="80",width="180",x="121",y="97",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="32",anchorPointX="0",anchorPointY="1",},
}
tTable["index_4"] = {
img_title={classname="ImageView",name="img_title",parName="lay_title",ZOrder="1",fileName="#v2_fonts_mianfeifuli.png",scale9Enable="false",scale9Height="21",scale9Width="79",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="21",width="79",x="54",y="20",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="22",anchorPointX="0.5",anchorPointY="0.5",},
img_title2={classname="ImageView",name="img_title2",parName="lay_title2",ZOrder="1",fileName="#v2_fonts_jinrishekou.png",scale9Enable="false",scale9Height="21",scale9Width="80",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="21",width="80",x="54",y="20",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="27",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable