local tTable = {}


tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="470",width="560",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2256",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
view={classname="Panel",name="view",parName="default",childCount="6",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="470",width="560",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2257",anchorPointX="0",anchorPointY="0",},
lb_tip={classname="Label",name="lb_tip",parName="default",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="280",y="-21",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="21276",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_3"] = {
lay_info={classname="Panel",name="lay_info",parName="view",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="282",width="520",x="15",y="60",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2259",anchorPointX="0",anchorPointY="0",},
lay_bottom_free={classname="Panel",name="lay_bottom_free",parName="view",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="150",width="560",x="9",y="-272",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2267",anchorPointX="0",anchorPointY="0",},
lay_bottom_call={classname="Panel",name="lay_bottom_call",parName="view",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="150",width="560",x="9",y="-272",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2270",anchorPointX="0",anchorPointY="0",},
lay_bottom_recall={classname="Panel",name="lay_bottom_recall",parName="view",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="150",width="560",x="9",y="-272",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2272",anchorPointX="0",anchorPointY="0",},
lay_bottom_response={classname="Panel",name="lay_bottom_response",parName="view",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="150",width="560",x="9",y="-272",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6644",anchorPointX="0",anchorPointY="0",},
txt_desc={classname="CustomLabel",name="txt_desc",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="110",areaWidth="500",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="110",width="500",x="25",y="457",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="11914",anchorPointX="0",anchorPointY="1",},
}
tTable["index_4"] = {
txt_title={classname="CustomLabel",name="txt_title",parName="lay_info",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="官职：XXX",fontName="微软雅黑",fontSize="20",height="27",width="99",x="259",y="255",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2261",anchorPointX="0.5",anchorPointY="0.5",},
txt_call_member={classname="CustomLabel",name="txt_call_member",parName="lay_info",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="可召唤人数：9",fontName="微软雅黑",fontSize="20",height="27",width="132",x="259",y="219",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2263",anchorPointX="0.5",anchorPointY="0.5",},
txt_call_num={classname="CustomLabel",name="txt_call_num",parName="lay_info",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="今天召唤次数：0/9",fontName="微软雅黑",fontSize="20",height="27",width="173",x="259",y="181",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2264",anchorPointX="0.5",anchorPointY="0.5",},
lay_icon={classname="Panel",name="lay_icon",parName="lay_info",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="150",width="108",x="208",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2266",anchorPointX="0",anchorPointY="0",},
lay_btn_free={classname="Panel",name="lay_btn_free",parName="lay_bottom_free",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="60",width="150",x="202",y="40",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2269",anchorPointX="0",anchorPointY="0",},
lay_btn_call={classname="Panel",name="lay_btn_call",parName="lay_bottom_call",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="60",width="150",x="202",y="40",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2277",anchorPointX="0",anchorPointY="0",},
lay_btn_recall={classname="Panel",name="lay_btn_recall",parName="lay_bottom_recall",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="60",width="150",x="202",y="40",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2280",anchorPointX="0",anchorPointY="0",},
lay_btn_response={classname="Panel",name="lay_btn_response",parName="lay_bottom_response",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="60",width="150",x="202",y="40",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6645",anchorPointX="0",anchorPointY="0",},
}

return tTable