local tTable = {}


tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="750",width="550",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
view={classname="Panel",name="view",parName="default",childCount="6",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="750",width="550",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_border={classname="Panel",name="lay_border",parName="view",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="65",capInsetsY="65",height="237",width="514",x="18",y="501",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8",anchorPointX="0",anchorPointY="0",},
lay_banner={classname="Panel",name="lay_banner",parName="view",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_xiaobiaoti2.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="186",capInsetsY="24",height="48",width="514",x="18",y="442",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="10",anchorPointX="0",anchorPointY="0",},
lay_content={classname="Panel",name="lay_content",parName="view",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="167",width="514",x="18",y="275",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="11",anchorPointX="0",anchorPointY="0",},
txt_tip={classname="CustomLabel",name="txt_tip",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="120",areaWidth="514",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="120",width="514",x="18",y="260",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="12",anchorPointX="0",anchorPointY="1",},
lay_btn={classname="Panel",name="lay_btn",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="202",y="48",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="13",anchorPointX="0",anchorPointY="0",},
txt_tip2={classname="CustomLabel",name="txt_tip2",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="280",y="28",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="59",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_4"] = {
lay_capture={classname="Panel",name="lay_capture",parName="lay_border",childCount="6",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_black50.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="10",height="46",width="514",x="0",y="6",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="138",anchorPointX="0",anchorPointY="0",},
txt_banner={classname="CustomLabel",name="txt_banner",parName="lay_banner",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="任务奖励",fontName="微软雅黑",fontSize="20",height="27",width="80",x="23",y="24",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="58",anchorPointX="0",anchorPointY="0.5",},
lay_goods={classname="Panel",name="lay_goods",parName="lay_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="149",width="500",x="7",y="9",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="96",anchorPointX="0",anchorPointY="0",},
}
tTable["index_5"] = {
img_country1={classname="CustomImageView",name="img_country1",parName="lay_capture",ZOrder="0",fileName="#v1_img_qun.png",scale9Enable="false",scale9Height="64",scale9Width="51",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="64",width="51",x="28",y="22",visible="true",touchAble="false",flipX="false",scaleX="0.8",scaleY="0.8",opacity="255",rotation="0",tag="139",anchorPointX="0.5",anchorPointY="0.5",},
txt_country1={classname="CustomLabel",name="txt_country1",parName="lay_capture",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="已未成",fontName="微软雅黑",fontSize="20",height="27",width="60",x="49",y="22",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="140",anchorPointX="0",anchorPointY="0.5",},
img_country2={classname="CustomImageView",name="img_country2",parName="lay_capture",ZOrder="0",fileName="#v1_img_qun.png",scale9Enable="false",scale9Height="64",scale9Width="51",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="64",width="51",x="220",y="20",visible="true",touchAble="false",flipX="false",scaleX="0.8",scaleY="0.8",opacity="255",rotation="0",tag="141",anchorPointX="0.5",anchorPointY="0.5",},
txt_country2={classname="CustomLabel",name="txt_country2",parName="lay_capture",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="已未成",fontName="微软雅黑",fontSize="20",height="27",width="60",x="241",y="22",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="142",anchorPointX="0",anchorPointY="0.5",},
img_country3={classname="CustomImageView",name="img_country3",parName="lay_capture",ZOrder="0",fileName="#v1_img_qun.png",scale9Enable="false",scale9Height="64",scale9Width="51",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="64",width="51",x="412",y="22",visible="true",touchAble="false",flipX="false",scaleX="0.8",scaleY="0.8",opacity="255",rotation="0",tag="143",anchorPointX="0.5",anchorPointY="0.5",},
txt_country3={classname="CustomLabel",name="txt_country3",parName="lay_capture",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="已未成",fontName="微软雅黑",fontSize="20",height="27",width="60",x="433",y="22",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="144",anchorPointX="0",anchorPointY="0.5",},
}

return tTable