local tTable = {}


tTable["index_1"] = {
root={classname="Panel",name="root",parName="root",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1060",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="3",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_civil={classname="Panel",name="lay_civil",parName="root",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="63",capInsetsY="65",height="130",width="600",x="20",y="892",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6",anchorPointX="0",anchorPointY="0",},
lay_res_info={classname="Panel",name="lay_res_info",parName="root",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="454",width="640",x="1",y="359",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="13",anchorPointX="0",anchorPointY="0",},
lay_bot={classname="Panel",name="lay_bot",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_jinduyanjiudi.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="320",capInsetsY="35",height="200",width="640",x="0",y="108",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="14",anchorPointX="0",anchorPointY="0",},
lay_res_title={classname="Panel",name="lay_res_title",parName="root",childCount="2",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_xiaobiaoti2.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="188",capInsetsY="24",height="50",width="640",x="1",y="815",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="21",anchorPointX="0",anchorPointY="0",},
lay_banner_bg={classname="Panel",name="lay_banner_bg",parName="root",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="192",width="640",x="0",y="867",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1675",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
img_line1={classname="ImageView",name="img_line1",parName="lay_res_info",ZOrder="1",fileName="#v1_line_blue1.png",scale9Enable="true",scale9Height="2",scale9Width="550",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="1",height="2",width="550",x="320",y="337",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="25",anchorPointX="0.5",anchorPointY="0.5",},
img_line2={classname="ImageView",name="img_line2",parName="lay_res_info",ZOrder="1",fileName="#v1_line_blue1.png",scale9Enable="true",scale9Height="2",scale9Width="550",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="1",height="2",width="550",x="320",y="227",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="28",anchorPointX="0.5",anchorPointY="0.5",},
img_line3={classname="ImageView",name="img_line3",parName="lay_res_info",ZOrder="1",fileName="#v1_line_blue1.png",scale9Enable="true",scale9Height="2",scale9Width="550",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="1",height="2",width="550",x="320",y="117",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="29",anchorPointX="0.5",anchorPointY="0.5",},
img_line={classname="ImageView",name="img_line",parName="lay_bot",ZOrder="0",fileName="#v1_line_blue2a.png",scale9Enable="true",scale9Height="180",scale9Width="2",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="1",capInsetsY="12",height="180",width="2",x="320",y="100",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1412",anchorPointX="0.5",anchorPointY="0.5",},
lb_res_title={classname="Label",name="lb_res_title",parName="lay_res_title",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="资源产量",fontName="微软雅黑",fontSize="20",height="27",width="80",x="20",y="24",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="22",anchorPointX="0",anchorPointY="0.5",},
lay_btn_share={classname="Panel",name="lay_btn_share",parName="lay_res_title",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="104",x="526",y="5",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="419",anchorPointX="0",anchorPointY="0",},
}

return tTable