local tTable = {}

tTable["texturesPng"] = {"ui/bg_weapon/v1_bg_shenbing.jpg","ui/language/cn/p1_font1.plist","ui/p1_commonse3.plist","ui/p1_commonse1.plist","ui/p1_commmon3_sep.plist","ui/p1_commmon2_sep.plist","ui/p2_commmon1_sep.plist"}
tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1066",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="27",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_top_list={classname="Panel",name="lay_top_list",parName="default",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="110",width="600",x="20",y="956",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="28",anchorPointX="0",anchorPointY="0",},
lay_center={classname="Panel",name="lay_center",parName="default",childCount="12",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="65",capInsetsY="65",height="900",width="600",x="20",y="55",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="33",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_icon={classname="Panel",name="lay_icon",parName="lay_top_list",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="80",width="80",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="94",anchorPointX="0",anchorPointY="0",},
lay_bg={classname="Panel",name="lay_bg",parName="lay_center",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bg_weapon/v1_bg_shenbing.jpg",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="300",capInsetsY="250",height="495",width="580",x="10",y="400",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="48",anchorPointX="0",anchorPointY="0",},
lay_pageview={classname="Panel",name="lay_pageview",parName="lay_center",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="475",width="580",x="10",y="420",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="29",anchorPointX="0",anchorPointY="0",},
lay_share={classname="Panel",name="lay_share",parName="lay_center",childCount="1",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="80",width="85",x="505",y="814",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="39",anchorPointX="0",anchorPointY="0",},
lay_jie={classname="Panel",name="lay_jie",parName="lay_center",childCount="1",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_img_moji.png",height="54",width="130",x="21",y="648",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="42",anchorPointX="0",anchorPointY="0",},
btn_left={classname="Button",name="btn_left",parName="lay_center",ZOrder="2",fontName="微软雅黑",fontSize="14",scale9Enable="false",scale9Height="52",scale9Width="32",textColorB="255",textColorG="255",textColorR="255",normal="#v1_img_qiehuanjiantou.png",pressed="#v1_img_qiehuanjiantou.png",height="52",width="32",x="23",y="612",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="180",tag="31",anchorPointX="0.5",anchorPointY="0.5",},
btn_right={classname="Button",name="btn_right",parName="lay_center",ZOrder="2",fontName="微软雅黑",fontSize="14",scale9Enable="false",scale9Height="52",scale9Width="32",textColorB="255",textColorG="255",textColorR="255",normal="#v1_img_qiehuanjiantou.png",pressed="#v1_img_qiehuanjiantou.png",height="52",width="32",x="575",y="612",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="32",anchorPointX="0.5",anchorPointY="0.5",},
img_w_name={classname="ImageView",name="img_w_name",parName="lay_center",ZOrder="2",fileName="#v1_img_shenbingmingzidi.png",scale9Enable="false",scale9Height="194",scale9Width="68",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="194",width="68",x="59",y="796",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="36",anchorPointX="0.5",anchorPointY="0.5",},
lb_w_name={classname="Label",name="lb_w_name",parName="lay_center",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="名字",fontName="微软雅黑",fontSize="30",height="39",width="60",x="58",y="809",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="37",anchorPointX="0.5",anchorPointY="0.5",},
lay_attrdi={classname="Panel",name="lay_attrdi",parName="lay_center",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_shenbingjianbian.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="172",capInsetsY="21",height="90",width="582",x="8",y="305",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="34",anchorPointX="0",anchorPointY="0",},
lb_maxlv={classname="Label",name="lb_maxlv",parName="lay_center",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="297",y="162",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="89",anchorPointX="0.5",anchorPointY="0.5",},
lay_bottom={classname="Panel",name="lay_bottom",parName="lay_center",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="287",width="580",x="8",y="20",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="57",anchorPointX="0",anchorPointY="0",},
lay_auto_upgrade={classname="Panel",name="lay_auto_upgrade",parName="lay_center",childCount="1",ZOrder="99",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_jinduyanjiudi.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="320",capInsetsY="33",height="70",width="640",x="-20",y="400",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="481",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
img_share={classname="ImageView",name="img_share",parName="lay_share",ZOrder="0",fileName="#v1_btn_fenxiang.png",scale9Enable="false",scale9Height="64",scale9Width="42",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="64",width="42",x="44",y="43",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="204",anchorPointX="0.5",anchorPointY="0.5",},
img_jie={classname="ImageView",name="img_jie",parName="lay_jie",ZOrder="1",fileName="#v1_fonts_jie.png",scale9Enable="false",scale9Height="40",scale9Width="40",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="40",width="40",x="53",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="43",anchorPointX="0.5",anchorPointY="0.5",},
lay_attr={classname="Panel",name="lay_attr",parName="lay_attrdi",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="90",width="582",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="155",anchorPointX="0",anchorPointY="0",},
lb_auto_upgrade={classname="Label",name="lb_auto_upgrade",parName="lay_auto_upgrade",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="正在进行自动洗炼...第1次",fontName="微软雅黑",fontSize="26",height="35",width="293",x="320",y="35",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="482",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable