local tTable = {}

tTable["texturesPng"] = {"ui/bg_hero/v1_img_role.png","ui/p1_button1.plist","ui/language/cn/p2_font1.plist","ui/p2_commmon1_sep.plist","icon/p1_icon_font.plist","ui/p1_commmon3_sep.plist","ui/v1_img_roleshade.png","ui/p1_commmon1_sep.plist","ui/bar/v1_bar_b1.png"}
tTable["index_1"] = {
default={classname="Panel",name="default@fill_layout",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1066",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
viewgroup={classname="Panel",name="viewgroup@fill_layout",parName="default",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1066",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_center={classname="Panel",name="lay_center",parName="viewgroup",childCount="7",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="666",width="640",x="0",y="400",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="17",anchorPointX="0",anchorPointY="0",},
lay_msg={classname="Panel",name="lay_msg",parName="viewgroup",childCount="2",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_black20.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="10",height="200",width="640",x="0",y="195",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="23",anchorPointX="0",anchorPointY="0",},
lay_space={classname="Panel",name="lay_space@fill_layout",parName="viewgroup",ZOrder="100",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="0.01",width="640",x="0",y="195",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="311",anchorPointX="0",anchorPointY="0",},
lay_bottom={classname="Panel",name="lay_bottom",parName="viewgroup",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="195",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="18",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
view_hero={classname="Panel",name="view_hero",parName="lay_center",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="515",width="640",x="0",y="145",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="193",anchorPointX="0",anchorPointY="0",},
img_hero={classname="ImageView",name="img_hero",parName="lay_center",ZOrder="0",fileName="ui/bg_hero/v1_img_role.png",scale9Enable="false",scale9Height="515",scale9Width="640",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="515",width="640",x="320",y="145",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="22",anchorPointX="0.5",anchorPointY="0",},
lay_fight={classname="Panel",name="lay_fight",parName="lay_center",childCount="2",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_btn_fighting.png",height="63",width="285",x="176",y="106",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="25",anchorPointX="0",anchorPointY="0",},
img_flag={classname="ImageView",name="img_flag",parName="lay_center",ZOrder="3",fileName="#v1_img_qing.png",scale9Enable="false",scale9Height="64",scale9Width="51",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="64",width="51",x="50",y="553",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="24",anchorPointX="0.5",anchorPointY="0.5",},
lay_top={classname="Panel",name="lay_top",parName="lay_center",childCount="5",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="92",width="640",x="0",y="3",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9",anchorPointX="0",anchorPointY="0",},
img_shade_l={classname="ImageView",name="img_shade_l",parName="lay_center",ZOrder="1",fileName="ui/v1_img_roleshade.png",scale9Enable="false",scale9Height="353",scale9Width="320",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="353",width="320",x="160",y="58",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="122",anchorPointX="0.5",anchorPointY="0.5",},
img_shade_r={classname="ImageView",name="img_shade_r",parName="lay_center",ZOrder="1",fileName="ui/v1_img_roleshade.png",scale9Enable="false",scale9Height="353",scale9Width="320",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="353",width="320",x="480",y="58",visible="true",touchAble="false",flipX="true",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="124",anchorPointX="0.5",anchorPointY="0.5",},
lay_msg_left={classname="Panel",name="lay_msg_left",parName="lay_msg",childCount="9",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="200",width="240",x="29",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="26",anchorPointX="0",anchorPointY="0",},
lay_msg_right={classname="Panel",name="lay_msg_right",parName="lay_msg",childCount="13",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="200",width="345",x="279",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="27",anchorPointX="0",anchorPointY="0",},
lay_btn_b={classname="Panel",name="lay_btn_b",parName="lay_bottom",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="243",y="80",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="20",anchorPointX="0",anchorPointY="0",},
lay_btn_c={classname="Panel",name="lay_btn_c",parName="lay_bottom",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="465",y="80",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="21",anchorPointX="0",anchorPointY="0",},
lay_btn_a={classname="Panel",name="lay_btn_a",parName="lay_bottom",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="20",y="80",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="176",anchorPointX="0",anchorPointY="0",},
}
tTable["index_5"] = {
lay_c_f={classname="Panel",name="lay_c_f",parName="lay_fight",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="210",x="34",y="9",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="72",anchorPointX="0",anchorPointY="0",},
img_zjd={classname="ImageView",name="img_zjd",parName="lay_fight",ZOrder="0",fileName="#v2_img_zjd_amw.png",scale9Enable="false",scale9Height="35",scale9Width="33",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="35",width="33",x="28",y="49",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="121",anchorPointX="0.5",anchorPointY="0.5",},
lb_cur_location={classname="Label",name="lb_cur_location",parName="lay_top",ZOrder="0",colorB="131",colorG="170",colorR="188",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="当前位置：",fontName="微软雅黑",fontSize="20",height="27",width="100",x="150",y="80",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="10",anchorPointX="0",anchorPointY="0.5",},
lb_location={classname="Label",name="lb_location",parName="lay_top",ZOrder="0",colorB="202",colorG="183",colorR="161",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="荆州",fontName="微软雅黑",fontSize="20",height="27",width="40",x="260",y="80",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="11",anchorPointX="0",anchorPointY="0.5",},
lay_name={classname="Panel",name="lay_name",parName="lay_top",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_shurukuang.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="20",capInsetsY="20",height="40",width="335",x="161",y="29",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="12",anchorPointX="0",anchorPointY="0",},
lay_refresh={classname="Panel",name="lay_refresh",parName="lay_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="34",width="34",x="528",y="32",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="13",anchorPointX="0",anchorPointY="0",},
lay_icon={classname="Panel",name="lay_icon",parName="lay_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="87",width="87",x="55",y="5",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="47",anchorPointX="0",anchorPointY="0",},
lb_tip_1={classname="Label",name="lb_tip_1",parName="lay_msg_left",ZOrder="0",colorB="131",colorG="170",colorR="188",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="排行：",fontName="微软雅黑",fontSize="20",height="27",width="60",x="40",y="160",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="28",anchorPointX="0",anchorPointY="0.5",},
lb_tip_2={classname="Label",name="lb_tip_2",parName="lay_msg_left",ZOrder="0",colorB="131",colorG="170",colorR="188",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="爵位：",fontName="微软雅黑",fontSize="20",height="27",width="60",x="40",y="100",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="29",anchorPointX="0",anchorPointY="0.5",},
lb_tip_3={classname="Label",name="lb_tip_3",parName="lay_msg_left",ZOrder="0",colorB="131",colorG="170",colorR="188",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="战功：",fontName="微软雅黑",fontSize="20",height="27",width="60",x="40",y="40",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="30",anchorPointX="0",anchorPointY="0.5",},
lb_param_1={classname="Label",name="lb_param_1",parName="lay_msg_left",ZOrder="0",colorB="202",colorG="183",colorR="161",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="250",fontName="微软雅黑",fontSize="20",height="27",width="36",x="110",y="160",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="31",anchorPointX="0",anchorPointY="0.5",},
lb_param_2={classname="Label",name="lb_param_2",parName="lay_msg_left",ZOrder="0",colorB="202",colorG="183",colorR="161",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="打负分打负分",fontName="微软雅黑",fontSize="20",height="27",width="120",x="110",y="100",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="32",anchorPointX="0",anchorPointY="0.5",},
lb_param_3={classname="Label",name="lb_param_3",parName="lay_msg_left",ZOrder="0",colorB="202",colorG="183",colorR="161",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="荆州",fontName="微软雅黑",fontSize="20",height="27",width="40",x="110",y="41",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="33",anchorPointX="0",anchorPointY="0.5",},
l_img_1={classname="ImageView",name="l_img_1",parName="lay_msg_left",ZOrder="0",fileName="#v2_img_paihangzg.png",scale9Enable="false",scale9Height="30",scale9Width="29",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="30",width="29",x="0",y="160",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="155",anchorPointX="0",anchorPointY="0.5",},
l_img_2={classname="ImageView",name="l_img_2",parName="lay_msg_left",ZOrder="0",fileName="#v2_img_jueweizg.png",scale9Enable="false",scale9Height="30",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="30",width="31",x="0",y="100",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="157",anchorPointX="0",anchorPointY="0.5",},
l_img_3={classname="ImageView",name="l_img_3",parName="lay_msg_left",ZOrder="0",fileName="#v2_img_wj_zhangong.png",scale9Enable="false",scale9Height="30",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="30",width="31",x="0",y="40",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="158",anchorPointX="0",anchorPointY="0.5",},
lay_vip={classname="Panel",name="lay_vip",parName="lay_msg_right",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="60",width="193",x="0",y="150",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="35",anchorPointX="0",anchorPointY="0",},
lay_jump_vip={classname="Panel",name="lay_jump_vip",parName="lay_msg_right",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="34",width="34",x="305",y="145",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="39",anchorPointX="0",anchorPointY="0",},
lay_jump_energy={classname="Panel",name="lay_jump_energy",parName="lay_msg_right",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="34",width="34",x="305",y="84",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="40",anchorPointX="0",anchorPointY="0",},
lay_bar_bg_energy={classname="Panel",name="lay_bar_bg_energy",parName="lay_msg_right",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v1_bar_b1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="40",capInsetsY="0",height="18",width="146",x="110",y="90",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="41",anchorPointX="0",anchorPointY="0",},
lay_bar_bg_lv={classname="Panel",name="lay_bar_bg_lv",parName="lay_msg_right",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v1_bar_b1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="40",capInsetsY="0",height="18",width="146",x="110",y="30",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="42",anchorPointX="0",anchorPointY="0",},
lb_tip_4={classname="Label",name="lb_tip_4",parName="lay_msg_right",ZOrder="0",colorB="131",colorG="170",colorR="188",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="VIP等级：",fontName="微软雅黑",fontSize="20",height="27",width="92",x="40",y="160",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="118",anchorPointX="0",anchorPointY="0.5",},
lb_tip_5={classname="Label",name="lb_tip_5",parName="lay_msg_right",ZOrder="0",colorB="131",colorG="170",colorR="188",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="体力：",fontName="微软雅黑",fontSize="20",height="27",width="60",x="40",y="100",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="115",anchorPointX="0",anchorPointY="0.5",},
lb_tip_6={classname="Label",name="lb_tip_6",parName="lay_msg_right",ZOrder="0",colorB="131",colorG="170",colorR="188",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="LV.78：",fontName="微软雅黑",fontSize="20",height="27",width="73",x="40",y="40",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="117",anchorPointX="0",anchorPointY="0.5",},
lb_param_4={classname="Label",name="lb_param_4",parName="lay_msg_right",ZOrder="0",colorB="131",colorG="170",colorR="188",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="0",fontName="微软雅黑",fontSize="20",height="27",width="12",x="146",y="160",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="120",anchorPointX="0",anchorPointY="0.5",},
r_img_1={classname="ImageView",name="r_img_1",parName="lay_msg_right",ZOrder="0",fileName="#v2_img_vipzg.png",scale9Enable="false",scale9Height="30",scale9Width="29",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="30",width="29",x="0",y="160",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="159",anchorPointX="0",anchorPointY="0.5",},
r_img_2={classname="ImageView",name="r_img_2",parName="lay_msg_right",ZOrder="0",fileName="#v2_img_tilizg.png",scale9Enable="false",scale9Height="30",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="30",width="31",x="0",y="99",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="161",anchorPointX="0",anchorPointY="0.5",},
r_img_3={classname="ImageView",name="r_img_3",parName="lay_msg_right",ZOrder="0",fileName="#v2_img_dengjizg.png",scale9Enable="false",scale9Height="30",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="30",width="31",x="0",y="40",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="162",anchorPointX="0",anchorPointY="0.5",},
lay_vip_lb={classname="Panel",name="lay_vip_lb",parName="lay_msg_right",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="110",x="142",y="146",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="343",anchorPointX="0",anchorPointY="0",},
}
tTable["index_6"] = {
img_fight={classname="ImageView",name="img_fight",parName="lay_c_f",ZOrder="0",fileName="#v2_fonts_fighting.png",scale9Enable="false",scale9Height="22",scale9Width="74",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="22",width="74",x="30",y="28",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="71",anchorPointX="0.5",anchorPointY="0.5",},
lb_fight={classname="Label",name="lb_fight",parName="lay_c_f",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",fontName="微软雅黑",fontSize="20",height="0",width="0",x="82",y="27",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="95",anchorPointX="0",anchorPointY="0.5",},
lb_name={classname="Label",name="lb_name",parName="lay_name",ZOrder="10",colorB="202",colorG="183",colorR="161",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="24",height="31",width="116",x="168",y="20",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="14",anchorPointX="0.5",anchorPointY="0.5",},
lb_vip={classname="Label",name="lb_vip",parName="lay_vip",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="特权未激活",fontName="微软雅黑",fontSize="20",height="27",width="100",x="110",y="32",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="36",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable