local tTable = {}

tTable["texturesPng"] = {"ui/bar/v1_bar_b1.png","ui/p1_commonse1.plist"}
tTable["index_1"] = {
root={classname="Panel",name="root",parName="root",childCount="11",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="670",width="560",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="261",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lb_tip_1={classname="Label",name="lb_tip_1",parName="root",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="国家等级：",fontName="微软雅黑",fontSize="20",height="27",width="100",x="34",y="626",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="264",anchorPointX="0",anchorPointY="0.5",},
lb_tip_2={classname="Label",name="lb_tip_2",parName="root",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="下等级效果：",fontName="微软雅黑",fontSize="20",height="27",width="120",x="34",y="585",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="265",anchorPointX="0",anchorPointY="0.5",},
lb_tip_3={classname="Label",name="lb_tip_3",parName="root",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="54",areaWidth="340",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="54",width="340",x="34",y="559",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="266",anchorPointX="0",anchorPointY="1",},
lb_tip_4={classname="Label",name="lb_tip_4",parName="root",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="国家经验：",fontName="微软雅黑",fontSize="20",height="27",width="100",x="34",y="478",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="267",anchorPointX="0",anchorPointY="0.5",},
lb_country_exp={classname="Label",name="lb_country_exp",parName="root",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="999k",fontName="微软雅黑",fontSize="20",height="27",width="47",x="137",y="478",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="268",anchorPointX="0",anchorPointY="0.5",},
lb_target_exp={classname="Label",name="lb_target_exp",parName="root",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="/999k",fontName="微软雅黑",fontSize="20",height="27",width="56",x="185",y="478",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="270",anchorPointX="0",anchorPointY="0.5",},
lb_lv={classname="Label",name="lb_lv",parName="root",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Lv9",fontName="微软雅黑",fontSize="20",height="27",width="33",x="133",y="626",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="329",anchorPointX="0",anchorPointY="0.5",},
lay_bar_bg={classname="Panel",name="lay_bar_bg",parName="root",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v1_bar_b1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="45",capInsetsY="9",height="18",width="422",x="69",y="410",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="269",anchorPointX="0",anchorPointY="0",},
lay_center={classname="Panel",name="lay_center",parName="root",childCount="18",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="340",width="530",x="15",y="36",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="271",anchorPointX="0",anchorPointY="0",},
img_line_1={classname="ImageView",name="img_line_1",parName="root",ZOrder="0",fileName="#v1_line_blue1.png",scale9Enable="true",scale9Height="2",scale9Width="530",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="1",height="2",width="530",x="280",y="381",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4754",anchorPointX="0.5",anchorPointY="0.5",},
img_line_2={classname="ImageView",name="img_line_2",parName="root",ZOrder="0",fileName="#v1_line_blue1.png",scale9Enable="true",scale9Height="2",scale9Width="530",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="1",height="2",width="530",x="280",y="201",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4756",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_3"] = {
lb_title_1={classname="Label",name="lb_title_1",parName="lay_center",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="开发消耗",fontName="微软雅黑",fontSize="20",height="27",width="80",x="20",y="308",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="281",anchorPointX="0",anchorPointY="0.5",},
lb_title_2={classname="Label",name="lb_title_2",parName="lay_center",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="开发获得",fontName="微软雅黑",fontSize="20",height="27",width="80",x="20",y="135",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="282",anchorPointX="0",anchorPointY="0.5",},
img_res_1={classname="ImageView",name="img_res_1",parName="lay_center",ZOrder="0",fileName="#v1_img_qianbi.png",scale9Enable="false",scale9Height="36",scale9Width="36",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="36",width="36",x="72",y="250",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="274",anchorPointX="0.5",anchorPointY="0.5",},
img_prize_1={classname="ImageView",name="img_prize_1",parName="lay_center",ZOrder="0",fileName="#v1_img_qianbi.png",scale9Enable="false",scale9Height="36",scale9Width="36",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="36",width="36",x="72",y="55",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="275",anchorPointX="0.5",anchorPointY="0.5",},
img_prize_2={classname="ImageView",name="img_prize_2",parName="lay_center",ZOrder="0",fileName="#v1_img_qianbi.png",scale9Enable="false",scale9Height="36",scale9Width="36",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="36",width="36",x="290",y="55",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="276",anchorPointX="0.5",anchorPointY="0.5",},
img_res_2={classname="ImageView",name="img_res_2",parName="lay_center",ZOrder="0",fileName="#v1_img_qianbi.png",scale9Enable="false",scale9Height="36",scale9Width="36",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="36",width="36",x="290",y="250",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="277",anchorPointX="0.5",anchorPointY="0.5",},
img_res_3={classname="ImageView",name="img_res_3",parName="lay_center",ZOrder="0",fileName="#v1_img_qianbi.png",scale9Enable="false",scale9Height="36",scale9Width="36",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="36",width="36",x="72",y="206",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="278",anchorPointX="0.5",anchorPointY="0.5",},
img_res_4={classname="ImageView",name="img_res_4",parName="lay_center",ZOrder="0",fileName="#v1_img_qianbi.png",scale9Enable="false",scale9Height="36",scale9Width="36",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="36",width="36",x="290",y="206",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="279",anchorPointX="0.5",anchorPointY="0.5",},
lb_prize_1={classname="Label",name="lb_prize_1",parName="lay_center",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="国家经验",fontName="微软雅黑",fontSize="20",height="27",width="80",x="91",y="56",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="283",anchorPointX="0",anchorPointY="0.5",},
lb_prize_2={classname="Label",name="lb_prize_2",parName="lay_center",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="国家经验",fontName="微软雅黑",fontSize="20",height="27",width="80",x="312",y="55",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="285",anchorPointX="0",anchorPointY="0.5",},
lb_res_num_1={classname="Label",name="lb_res_num_1",parName="lay_center",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="500",fontName="微软雅黑",fontSize="20",height="27",width="36",x="91",y="250",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="287",anchorPointX="0",anchorPointY="0.5",},
lb_res_target_num_1={classname="Label",name="lb_res_target_num_1",parName="lay_center",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="136",y="252",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="288",anchorPointX="0",anchorPointY="0.5",},
lb_res_num_2={classname="Label",name="lb_res_num_2",parName="lay_center",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="310",y="250",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="289",anchorPointX="0",anchorPointY="0.5",},
lb_res_target_num_2={classname="Label",name="lb_res_target_num_2",parName="lay_center",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="416",y="250",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="290",anchorPointX="0",anchorPointY="0.5",},
lb_res_num_3={classname="Label",name="lb_res_num_3",parName="lay_center",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="91",y="206",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="291",anchorPointX="0",anchorPointY="0.5",},
lb_res_target_num_3={classname="Label",name="lb_res_target_num_3",parName="lay_center",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="183",y="206",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="292",anchorPointX="0",anchorPointY="0.5",},
lb_res_num_4={classname="Label",name="lb_res_num_4",parName="lay_center",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="310",y="206",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="293",anchorPointX="0",anchorPointY="0.5",},
lb_res_target_num_4={classname="Label",name="lb_res_target_num_4",parName="lay_center",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="422",y="206",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="294",anchorPointX="0",anchorPointY="0.5",},
}

return tTable