local tTable = {}

tTable["texturesPng"] = {"ui/p1_commmon3_sep.plist","ui/p1_commmon1_sep.plist"}
tTable["index_1"] = {
root={classname="Panel",name="root@fill_layout",parName="root",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1066",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="801",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_main={classname="Panel",name="lay_main@fill_layout",parName="root",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="890",width="640",x="0",y="154",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1259",anchorPointX="0",anchorPointY="0",},
lay_bottom={classname="Panel",name="lay_bottom",parName="root",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="154",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="20031",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_top={classname="Panel",name="lay_top",parName="lay_main",childCount="2",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="240",width="640",x="0",y="647",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="803",anchorPointX="0",anchorPointY="0",},
lay_center={classname="Panel",name="lay_center@fill_layout",parName="lay_main",childCount="2",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="390",width="640",x="0",y="47",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="811",anchorPointX="0",anchorPointY="0",},
lay_bot={classname="Panel",name="lay_bot",parName="lay_main",childCount="6",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="208",width="640",x="0",y="439",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="815",anchorPointX="0",anchorPointY="0",},
lay_tmp={classname="Panel",name="lay_tmp",parName="lay_main",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="47",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="20078",anchorPointX="0",anchorPointY="0",},
lb_timer={classname="Label",name="lb_timer",parName="lay_bottom",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="55:55:55",fontName="微软雅黑",fontSize="22",height="30",width="88",x="319",y="125",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="821",anchorPointX="0.5",anchorPointY="0.5",},
lay_btn={classname="Panel",name="lay_btn",parName="lay_bottom",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="241",y="34",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="819",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lb_title1={classname="Label",name="lb_title1",parName="lay_top",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="选择生产材料",fontName="微软雅黑",fontSize="20",height="27",width="120",x="20",y="216",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="806",anchorPointX="0",anchorPointY="0.5",},
lay_biaoti1={classname="Panel",name="lay_biaoti1",parName="lay_top",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_xiaobiaoti2.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="186",capInsetsY="24",height="50",width="640",x="0",y="190",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="805",anchorPointX="0",anchorPointY="0",},
lay_biaoti2={classname="Panel",name="lay_biaoti2",parName="lay_center",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_xiaobiaoti2.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="186",capInsetsY="24",height="50",width="640",x="0",y="340",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="812",anchorPointX="0",anchorPointY="0",},
lay_scroll={classname="Panel",name="lay_scroll",parName="lay_center",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="342",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="814",anchorPointX="0",anchorPointY="0",},
lay_biaoti3={classname="Panel",name="lay_biaoti3",parName="lay_bot",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_xiaobiaoti2.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="186",capInsetsY="24",height="50",width="640",x="0",y="158",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="816",anchorPointX="0",anchorPointY="0",},
lb_title3={classname="Label",name="lb_title3",parName="lay_bot",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="生产消耗",fontName="微软雅黑",fontSize="20",height="27",width="80",x="20",y="184",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="817",anchorPointX="0",anchorPointY="0.5",},
lay_par_2={classname="Panel",name="lay_par_2",parName="lay_bot",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="27",width="150",x="380",y="106",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="959",anchorPointX="0",anchorPointY="0",},
lay_par_3={classname="Panel",name="lay_par_3",parName="lay_bot",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="27",width="150",x="80",y="49",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="960",anchorPointX="0",anchorPointY="0",},
lay_par_4={classname="Panel",name="lay_par_4",parName="lay_bot",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="27",width="150",x="380",y="49",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="994",anchorPointX="0",anchorPointY="0",},
lay_par_1={classname="Panel",name="lay_par_1",parName="lay_bot",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="27",width="150",x="80",y="106",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1167",anchorPointX="0",anchorPointY="0",},
}
tTable["index_5"] = {
lb_title2={classname="Label",name="lb_title2",parName="lay_biaoti2",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="选择消耗图纸",fontName="微软雅黑",fontSize="20",height="27",width="120",x="19",y="27",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="813",anchorPointX="0",anchorPointY="0.5",},
}

return tTable