local tTable = {}

tTable["texturesPng"] = {"ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commonse1.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","icon/p1_icon_ui.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","ui/bg_world/v1_img_shijieditu.jpg","ui/p1_commmon1_sep.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","ui/p1_button1.plist","ui/p1_commonse1.plist","ui/bar/v1_bar_b1.png","ui/p1_commonse1.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commonse1.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","icon/p1_icon_ui.plist","ui/p1_commonse1.plist","icon/p1_icon_ui.plist","ui/p1_commonse1.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commmon1_sep.plist","icon/p1_icon_font.plist","ui/language/cn/p1_font1.plist","icon/p1_icon_ui.plist","ui/p1_commonse1.plist","ui/p1_button1.plist","icon/p1_icon_font.plist","ui/p1_commmon1_sep.plist","ui/language/cn/p1_font1.plist","ui/p1_commonse1.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","ui/bar/v1_bar_b1.png"}
tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="420",width="500",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6610",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
view={classname="Panel",name="view",parName="default",childCount="6",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="420",width="500",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6611",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_icon={classname="Panel",name="lay_icon",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="100",width="100",x="198",y="247",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6612",anchorPointX="0",anchorPointY="0",},
lay_bar_troops={classname="Panel",name="lay_bar_troops",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v1_bar_b1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="45",capInsetsY="9",height="18",width="110",x="194",y="220",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6613",anchorPointX="0",anchorPointY="0",},
txt_lv={classname="CustomLabel",name="txt_lv",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="248",y="193",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6614",anchorPointX="0.5",anchorPointY="0.5",},
lay_richtext_tip={classname="Panel",name="lay_richtext_tip",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="27",width="200",x="148",y="130",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6615",anchorPointX="0",anchorPointY="0",},
lay_btn_cancel={classname="Panel",name="lay_btn_cancel",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="60",width="150",x="38",y="34",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6616",anchorPointX="0",anchorPointY="0",},
lay_btn_submit={classname="Panel",name="lay_btn_submit",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="60",width="150",x="308",y="35",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6617",anchorPointX="0",anchorPointY="0",},
}

return tTable