local tTable = {}

tTable["texturesPng"] = {"ui/p1_commmon1_sep.plist","ui/language/cn/p2_font_ac.plist","ui/p1_commmon3_sep.plist","icon/p1_icon_ui.plist","ui/big_img/v2_bg_jihaole.jpg"}
tTable["index_1"] = {
default={classname="Panel",name="default@fill_layout_height",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1066",width="522",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="408",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
ly_main={classname="Panel",name="ly_main@fill_layout",parName="default",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="15",height="1066",width="522",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="416",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
ly_title={classname="Panel",name="ly_title",parName="ly_main",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="186",capInsetsY="24",height="200",width="522",x="0",y="866",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="417",anchorPointX="0",anchorPointY="0",},
ly_sec_tile={classname="Panel",name="ly_sec_tile",parName="ly_main",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_xiaobiaoti2.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="90",capInsetsY="25",height="48",width="522",x="0",y="814",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="419",anchorPointX="0",anchorPointY="0",},
ly_con={classname="Panel",name="ly_con",parName="ly_main",childCount="6",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="10",capInsetsWidth="35",capInsetsX="5",capInsetsY="5",height="651",width="522",x="0",y="163",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="421",anchorPointX="0",anchorPointY="0",},
lay_bottom={classname="Panel",name="lay_bottom",parName="ly_main",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="163",width="522",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2980",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
ly_time={classname="Panel",name="ly_time",parName="ly_title",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="28",width="294",x="0",y="167",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="425",anchorPointX="0",anchorPointY="0",},
lay_jianbian={classname="Panel",name="lay_jianbian",parName="ly_title",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_blackjianbian.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="134",capInsetsY="32",height="70",width="488",x="8",y="6",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="455",anchorPointX="0",anchorPointY="0",},
lay_banner_bg={classname="Panel",name="lay_banner_bg",parName="ly_title",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="200",width="522",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="471",anchorPointX="0",anchorPointY="0",},
img_fonts={classname="ImageView",name="img_fonts",parName="ly_title",ZOrder="3",fileName="#v2_fonts_chijitili.png",scale9Enable="false",scale9Height="29",scale9Width="345",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="29",width="345",x="261",y="41",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2978",anchorPointX="0.5",anchorPointY="0.5",},
lb_sec_tile={classname="CustomLabel",name="lb_sec_tile",parName="ly_sec_tile",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="每日吃鸡",fontName="微软雅黑",fontSize="22",height="30",width="88",x="261",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="420",anchorPointX="0.5",anchorPointY="0.5",},
txt_time_title={classname="CustomLabel",name="txt_time_title",parName="ly_con",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="每日吃鸡时间段：",fontName="微软雅黑",fontSize="20",height="27",width="160",x="29",y="38",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="457",anchorPointX="0",anchorPointY="1",},
txt_time1={classname="CustomLabel",name="txt_time1",parName="ly_con",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="午餐12:00-14:00",fontName="微软雅黑",fontSize="18",height="24",width="140",x="200",y="37",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="465",anchorPointX="0",anchorPointY="1",},
txt_time2={classname="CustomLabel",name="txt_time2",parName="ly_con",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="晚餐12:00-14:00",fontName="微软雅黑",fontSize="18",height="24",width="140",x="352",y="37",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="466",anchorPointX="0",anchorPointY="1",},
img_plate={classname="CustomImageView",name="img_plate",parName="ly_con",ZOrder="1",fileName="#v1_img_chiji2.png",scale9Enable="false",scale9Height="96",scale9Width="96",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="96",width="96",x="258",y="349",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="469",anchorPointX="0.5",anchorPointY="0.5",},
img_chicken={classname="CustomImageView",name="img_chicken",parName="ly_con",ZOrder="2",fileName="#v1_img_chiji.png",scale9Enable="false",scale9Height="200",scale9Width="200",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="200",width="200",x="258",y="374",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="470",anchorPointX="0.5",anchorPointY="0.5",},
img_chicken_state={classname="ImageView",name="img_chicken_state",parName="ly_con",ZOrder="0",fileName="ui/big_img/v2_bg_jihaole.jpg",scale9Enable="false",scale9Height="651",scale9Width="523",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="651",width="523",x="0",y="0",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2979",anchorPointX="0",anchorPointY="0",},
txt_eat_state={classname="CustomLabel",name="txt_eat_state",parName="lay_bottom",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="描述XXXXXXXXXXXXXXXXXXXXXXXX",fontName="微软雅黑",fontSize="20",height="27",width="352",x="258",y="130",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="467",anchorPointX="0.5",anchorPointY="0",},
txt_buy_energy={classname="CustomLabel",name="txt_buy_energy",parName="lay_bottom",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="描述XXXXXXXXXXXXXXXXXXXXXXXX",fontName="微软雅黑",fontSize="20",height="27",width="352",x="258",y="107",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2977",anchorPointX="0.5",anchorPointY="0",},
ly_btn_m={classname="Panel",name="ly_btn_m",parName="lay_bottom",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="179",y="37",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="446",anchorPointX="0",anchorPointY="0",},
}

return tTable