local tTable = {}


tTable["index_1"] = {
dlg_buy_hero={classname="Panel",name="dlg_buy_hero@fill_layout",parName="root",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1066",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_main={classname="Panel",name="lay_main",parName="dlg_buy_hero",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="915",width="640",x="0",y="150",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="253",anchorPointX="0",anchorPointY="0",},
lay_space={classname="Panel",name="lay_space@fill_layout",parName="dlg_buy_hero",ZOrder="99999",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="0.01",width="640",x="0",y="150",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="326",anchorPointX="0",anchorPointY="0",},
lay_bottom={classname="Panel",name="lay_bottom",parName="dlg_buy_hero",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="150",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="254",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
ly_liang={classname="Panel",name="ly_liang",parName="lay_main",childCount="8",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="426",width="600",x="20",y="475",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8",anchorPointX="0",anchorPointY="0",},
ly_shen={classname="Panel",name="ly_shen",parName="lay_main",childCount="8",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="426",width="600",x="20",y="40",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="32",anchorPointX="0",anchorPointY="0",},
btn_preview={classname="Panel",name="btn_preview",parName="lay_bottom",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="251",y="100",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
img_l_bg={classname="ImageView",name="img_l_bg",parName="ly_liang",ZOrder="0",fileName="ui/v1_img_tuiyan01.jpg",scale9Enable="false",scale9Height="426",scale9Width="600",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="426",width="600",x="0",y="0",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="10",anchorPointX="0",anchorPointY="0",},
lb_up_1={classname="CustomLabel",name="lb_up_1",parName="ly_liang",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="22",height="30",width="106",x="135",y="265",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="11",anchorPointX="0.5",anchorPointY="0.5",},
lb_up_2={classname="CustomLabel",name="lb_up_2",parName="ly_liang",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="22",height="30",width="106",x="134",y="225",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="12",anchorPointX="0.5",anchorPointY="0.5",},
lb_up_3={classname="CustomLabel",name="lb_up_3",parName="ly_liang",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="22",height="30",width="106",x="91",y="185",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="13",anchorPointX="0",anchorPointY="0.5",},
lb_up_4={classname="CustomLabel",name="lb_up_4",parName="ly_liang",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="300",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="18",anchorPointX="0.5",anchorPointY="0.5",},
ly_btn_up_l={classname="Panel",name="ly_btn_up_l",parName="ly_liang",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="64",width="252",x="30",y="55",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="14",anchorPointX="0",anchorPointY="0",},
ly_btn_up_r={classname="Panel",name="ly_btn_up_r",parName="ly_liang",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="64",width="252",x="320",y="55",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="16",anchorPointX="0",anchorPointY="0",},
img_liang_item={classname="ImageView",name="img_liang_item",parName="ly_liang",ZOrder="1",fileName="#i100091.png",scale9Enable="false",scale9Height="96",scale9Width="96",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="96",width="96",x="64",y="185",visible="true",touchAble="false",flipX="false",scaleX="0.4",scaleY="0.4",opacity="255",rotation="0",tag="19",anchorPointX="0.5",anchorPointY="0.5",},
img_s_bg={classname="ImageView",name="img_s_bg",parName="ly_shen",ZOrder="0",fileName="ui/v1_img_tuiyan02.jpg",scale9Enable="false",scale9Height="426",scale9Width="600",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="426",width="600",x="0",y="0",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="33",anchorPointX="0",anchorPointY="0",},
lb_dn_1={classname="CustomLabel",name="lb_dn_1",parName="ly_shen",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="22",height="30",width="106",x="135",y="265",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="34",anchorPointX="0.5",anchorPointY="0.5",},
lb_dn_2={classname="CustomLabel",name="lb_dn_2",parName="ly_shen",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="22",height="30",width="106",x="136",y="226",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="35",anchorPointX="0.5",anchorPointY="0.5",},
lb_dn_3={classname="CustomLabel",name="lb_dn_3",parName="ly_shen",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="90",y="184",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="52",anchorPointX="0",anchorPointY="0.5",},
lb_dn_4={classname="CustomLabel",name="lb_dn_4",parName="ly_shen",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="300",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="37",anchorPointX="0.5",anchorPointY="0.5",},
img_shen_item={classname="ImageView",name="img_shen_item",parName="ly_shen",ZOrder="1",fileName="#i100091.png",scale9Enable="false",scale9Height="96",scale9Width="96",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="96",width="96",x="64",y="185",visible="true",touchAble="false",flipX="false",scaleX="0.4",scaleY="0.4",opacity="255",rotation="0",tag="51",anchorPointX="0.5",anchorPointY="0.5",},
ly_percent={classname="Panel",name="ly_percent",parName="ly_shen",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="100",width="600",x="0",y="55",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="41",anchorPointX="0",anchorPointY="0",},
ly_btn={classname="Panel",name="ly_btn",parName="ly_shen",childCount="2",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="100",width="600",x="0",y="55",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="43",anchorPointX="0",anchorPointY="0",},
}
tTable["index_5"] = {
ly_bar={classname="Panel",name="ly_bar",parName="ly_percent",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="ui/bar/v1_bar_b3.png",height="18",width="570",x="15",y="10",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="53",anchorPointX="0",anchorPointY="0",},
ly_btn_dn_l={classname="Panel",name="ly_btn_dn_l",parName="ly_btn",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="64",width="252",x="30",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="38",anchorPointX="0",anchorPointY="0",},
ly_btn_dn_r={classname="Panel",name="ly_btn_dn_r",parName="ly_btn",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="64",width="252",x="320",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="39",anchorPointX="0",anchorPointY="0",},
}

return tTable