local tTable = {}

tTable["texturesPng"] = {"ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","ui/language/cn/p2_font2.plist","ui/p1_commmon3_sep.plist"}
tTable["index_1"] = {
root={classname="Panel",name="root@fill_layout",parName="root",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1060",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="420",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_banner_bg={classname="Panel",name="lay_banner_bg",parName="root",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="192",width="640",x="0",y="868",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="643",anchorPointX="0",anchorPointY="0",},
lay_content={classname="Panel",name="lay_content@fill_layout",parName="root",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="813",width="640",x="0",y="54",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="653",anchorPointX="0",anchorPointY="0",},
lay_bot={classname="Panel",name="lay_bot",parName="root",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="54",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="652",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_top_tip={classname="Panel",name="lay_top_tip",parName="lay_banner_bg",childCount="3",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_black50.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="10",height="48",width="640",x="0",y="6",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="759",anchorPointX="0",anchorPointY="0",},
img_top_fonts={classname="ImageView",name="img_top_fonts",parName="lay_banner_bg",ZOrder="5",fileName="#v2_fonts_ziyuanduihuan.png",scale9Enable="false",scale9Height="91",scale9Width="342",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="91",width="342",x="320",y="120",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="760",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_4"] = {
lay_resinfotitle={classname="Panel",name="lay_resinfotitle",parName="lay_top_tip",childCount="4",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="186",capInsetsY="24",height="30",width="640",x="0",y="9",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="766",anchorPointX="0",anchorPointY="0",},
lay_res_info={classname="Panel",name="lay_res_info",parName="lay_top_tip",childCount="2",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="186",capInsetsY="24",height="30",width="640",x="0",y="8",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="776",anchorPointX="0",anchorPointY="0",},
lb_pack_tip={classname="Label",name="lb_pack_tip",parName="lay_top_tip",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="320",y="18",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="783",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_5"] = {
lb_protect_value={classname="Label",name="lb_protect_value",parName="lay_resinfotitle",ZOrder="0",colorB="70",colorG="235",colorR="251",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="40K",fontName="微软雅黑",fontSize="20",height="27",width="37",x="45",y="15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="767",anchorPointX="0",anchorPointY="0.5",},
lb_plunder_value={classname="Label",name="lb_plunder_value",parName="lay_resinfotitle",ZOrder="0",colorB="70",colorG="235",colorR="251",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999K",fontName="微软雅黑",fontSize="20",height="27",width="61",x="620",y="15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="768",anchorPointX="1",anchorPointY="0.5",},
img_lv={classname="ImageView",name="img_lv",parName="lay_resinfotitle",ZOrder="0",fileName="#v1_img_lv.png",scale9Enable="false",scale9Height="20",scale9Width="20",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="20",width="20",x="20",y="15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="769",anchorPointX="0",anchorPointY="0.5",},
img_huang={classname="ImageView",name="img_huang",parName="lay_resinfotitle",ZOrder="0",fileName="#v1_img_huang.png",scale9Enable="false",scale9Height="20",scale9Width="20",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="20",width="20",x="544",y="15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="770",anchorPointX="1",anchorPointY="0.5",},
lb_my_res={classname="Label",name="lb_my_res",parName="lay_res_info",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="我的资源:",fontName="微软雅黑",fontSize="20",height="27",width="85",x="103",y="15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="781",anchorPointX="0",anchorPointY="0.5",},
lay_res={classname="Panel",name="lay_res",parName="lay_res_info",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="365",x="193",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="782",anchorPointX="0",anchorPointY="0",},
}

return tTable