local tTable = {}


tTable["index_1"] = {
dlg_search_beauty={classname="Panel",name="dlg_search_beauty",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1060",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="64",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
view={classname="Panel",name="view",parName="dlg_search_beauty",childCount="7",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="ui/v2_bg_xunfangmeiren.jpg",height="1136",width="640",x="0",y="5",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="65",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_top={classname="Panel",name="lay_top",parName="view",childCount="3",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="180",width="640",x="0",y="876",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="66",anchorPointX="0",anchorPointY="0",},
lay_content={classname="Panel",name="lay_content",parName="view",childCount="6",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="200",width="640",x="0",y="210",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="72",anchorPointX="0",anchorPointY="0",},
lay_bottom={classname="Panel",name="lay_bottom",parName="view",childCount="3",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="167",width="640",x="0",y="-1",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="97",anchorPointX="0",anchorPointY="0",},
ly_attr_btn={classname="Panel",name="ly_attr_btn",parName="view",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v2_btn_wj_xiangqing.png",height="40",width="40",x="540",y="508",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="79",anchorPointX="0",anchorPointY="0",},
lb_hero_tips_1={classname="CustomLabel",name="lb_hero_tips_1",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="资质",fontName="微软雅黑",fontSize="18",height="24",width="36",x="423",y="530",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="155",anchorPointX="0",anchorPointY="0.5",},
lb_hero_talent={classname="CustomLabel",name="lb_hero_talent",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="999",fontName="微软雅黑",fontSize="18",height="24",width="33",x="464",y="530",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="156",anchorPointX="0",anchorPointY="0.5",},
lb_hero_talent_add={classname="CustomLabel",name="lb_hero_talent_add",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="99",fontName="微软雅黑",fontSize="20",height="27",width="24",x="505",y="530",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="157",anchorPointX="0",anchorPointY="0.5",},
}
tTable["index_4"] = {
txt_desc={classname="CustomLabel",name="txt_desc",parName="lay_top",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="100",areaWidth="450",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="100",width="450",x="10",y="140",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="69",anchorPointX="0",anchorPointY="1",},
lay_img_yl={classname="Panel",name="lay_img_yl",parName="lay_top",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="100",width="100",x="504",y="68",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="70",anchorPointX="0",anchorPointY="0",},
lay_yl_btn={classname="Panel",name="lay_yl_btn",parName="lay_top",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="100",x="503",y="24",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="71",anchorPointX="0",anchorPointY="0",},
lb_des={classname="CustomLabel",name="lb_des",parName="lay_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="320",y="40",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="124",anchorPointX="0.5",anchorPointY="0.5",},
ly_letter_1={classname="CustomImageView",name="ly_letter_1",parName="lay_content",ZOrder="5",fileName="#v2_bar_dianliangtuijian.png",scale9Enable="false",scale9Height="107",scale9Width="145",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="107",width="145",x="0",y="115",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="125",anchorPointX="0",anchorPointY="0.5",},
ly_letter_2={classname="CustomImageView",name="ly_letter_2",parName="lay_content",ZOrder="4",fileName="#v2_bar_meidianliangtuijian.png",scale9Enable="false",scale9Height="107",scale9Width="145",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="107",width="145",x="120",y="115",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="128",anchorPointX="0",anchorPointY="0.5",},
ly_letter_3={classname="CustomImageView",name="ly_letter_3",parName="lay_content",ZOrder="3",fileName="#v2_bar_meidianliangtuijian.png",scale9Enable="false",scale9Height="107",scale9Width="145",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="107",width="145",x="246",y="115",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="130",anchorPointX="0",anchorPointY="0.5",},
ly_letter_4={classname="CustomImageView",name="ly_letter_4",parName="lay_content",ZOrder="2",fileName="#v2_bar_meidianliangtuijian.png",scale9Enable="false",scale9Height="107",scale9Width="145",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="107",width="145",x="372",y="115",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="132",anchorPointX="0",anchorPointY="0.5",},
ly_letter_5={classname="CustomImageView",name="ly_letter_5",parName="lay_content",ZOrder="1",fileName="#v2_bar_meidianliangtuijian.png",scale9Enable="false",scale9Height="107",scale9Width="145",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="107",width="145",x="569",y="115",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="134",anchorPointX="0.5",anchorPointY="0.5",},
ly_btn_l={classname="Panel",name="ly_btn_l",parName="lay_bottom",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="65",width="155",x="71",y="50",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="99",anchorPointX="0",anchorPointY="0",},
ly_btn_r={classname="Panel",name="ly_btn_r",parName="lay_bottom",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="65",width="155",x="408",y="49",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="101",anchorPointX="0",anchorPointY="0",},
lb_ten_tips={classname="CustomLabel",name="lb_ten_tips",parName="lay_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="486",y="32",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="102",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable