local tTable = {}

tTable["texturesPng"] = {"ui/p1_commmon3_sep.plist","ui/v1_img_wujiangtuiyan.jpg","ui/language/cn/p1_font1.plist","ui/p1_commonse4.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist"}
tTable["index_1"] = {
dlg_buy_hero_get={classname="Panel",name="dlg_buy_hero_get@fill_layout",parName="root",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="1138",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="70",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
ly_bg={classname="Panel",name="ly_bg@fill_layout_height",parName="dlg_buy_hero_get",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1138",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="328",anchorPointX="0",anchorPointY="0",},
ly_content={classname="Panel",name="ly_content@fill_layout_height",parName="dlg_buy_hero_get",childCount="5",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1138",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="331",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
ly_bg_space1={classname="Panel",name="ly_bg_space1@fill_layout",parName="ly_bg",ZOrder="99999",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="0.01",width="640",x="0",y="1138",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="329",anchorPointX="0",anchorPointY="0",},
ly_tuiyan={classname="Panel",name="ly_tuiyan",parName="ly_bg",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="ui/v1_img_wujiangtuiyan.jpg",height="1138",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="135",anchorPointX="0",anchorPointY="0",},
ly_bg_space2={classname="Panel",name="ly_bg_space2@fill_layout",parName="ly_bg",ZOrder="99999",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="0.01",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="330",anchorPointX="0",anchorPointY="0",},
ly_content_space1={classname="Panel",name="ly_content_space1@fill_layout",parName="ly_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="0.01",width="640",x="0",y="1138",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="334",anchorPointX="0",anchorPointY="0",},
ly_title={classname="Panel",name="ly_title",parName="ly_content",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="255",width="640",x="0",y="880",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="336",anchorPointX="0",anchorPointY="0",},
ly_cn={classname="Panel",name="ly_cn",parName="ly_content",childCount="4",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="312",capInsetsY="272",height="589",width="640",x="0",y="289",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="99",anchorPointX="0",anchorPointY="0",},
ly_content_space3={classname="Panel",name="ly_content_space3@fill_layout",parName="ly_content",ZOrder="99999",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="0.01",width="640",x="0",y="289",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="332",anchorPointX="0",anchorPointY="0",},
ly_bottom={classname="Panel",name="ly_bottom",parName="ly_content",childCount="2",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="285",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="335",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
img_gxhd={classname="ImageView",name="img_gxhd",parName="ly_title",ZOrder="1",fileName="#v1_bg_gxhdxsa_01.png",scale9Enable="false",scale9Height="67",scale9Width="240",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="67",width="240",x="319",y="140",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="113",anchorPointX="0.5",anchorPointY="0.5",},
Image_4={classname="ImageView",name="Image_4",parName="ly_title",ZOrder="0",fileName="#v1_bg_gxhdxsa_x_01.png",scale9Enable="false",scale9Height="160",scale9Width="420",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="160",width="420",x="319",y="145",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="174",anchorPointX="0.5",anchorPointY="0.5",},
ly_show_cn={classname="Panel",name="ly_show_cn",parName="ly_cn",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="485",width="640",x="0",y="105",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="100",anchorPointX="0",anchorPointY="0",},
ly_hero_info={classname="Panel",name="ly_hero_info",parName="ly_cn",childCount="4",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="320",capInsetsY="40",height="518",width="640",x="0",y="77",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="139",anchorPointX="0",anchorPointY="0",},
ly_show_tx={classname="Panel",name="ly_show_tx",parName="ly_cn",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="465",width="640",x="-1",y="125",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="163",anchorPointX="0",anchorPointY="0",},
lb_quality_tips={classname="CustomLabel",name="lb_quality_tips",parName="ly_cn",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="320",y="40",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="392",anchorPointX="0.5",anchorPointY="0.5",},
ly_down_confirm={classname="Panel",name="ly_down_confirm",parName="ly_bottom",childCount="4",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="195",width="640",x="0",y="90",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="146",anchorPointX="0",anchorPointY="0",},
ly_down_btn={classname="Panel",name="ly_down_btn",parName="ly_bottom",childCount="4",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="195",width="640",x="0",y="90",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="71",anchorPointX="0",anchorPointY="0",},
}
tTable["index_5"] = {
ly_down={classname="Panel",name="ly_down",parName="ly_hero_info",childCount="8",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_black70.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="10",height="106",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="121",anchorPointX="0",anchorPointY="0",},
ly_show_hero={classname="Panel",name="ly_show_hero",parName="ly_hero_info",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="520",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="115",anchorPointX="0",anchorPointY="0",},
img_kuang1={classname="ImageView",name="img_kuang1",parName="ly_hero_info",ZOrder="4",fileName="#v2_img_awfkaqtjh_lu.png",scale9Enable="false",scale9Height="34",scale9Width="640",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="320",capInsetsY="20",height="34",width="640",x="320",y="11",visible="true",touchAble="false",flipX="true",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="173",anchorPointX="0.5",anchorPointY="0.5",},
img_kuang2={classname="ImageView",name="img_kuang2",parName="ly_hero_info",ZOrder="4",fileName="#v2_img_awfkaqtjh_lu.png",scale9Enable="false",scale9Height="34",scale9Width="640",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="34",width="640",x="320",y="503",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="197",anchorPointX="0.5",anchorPointY="0.5",},
ly_btn_m={classname="Panel",name="ly_btn_m",parName="ly_down_confirm",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="65",width="155",x="243",y="90",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="149",anchorPointX="0",anchorPointY="0",},
checkbox={classname="CheckBox",name="checkbox",parName="ly_down_confirm",ZOrder="0",selectedState="false",backGroundBox="#v1_img_gouxuankuang.png",frontCross="#v1_img_gouxuan.png",height="40",width="40",x="259",y="175",visible="true",touchAble="true",flipX="false",scaleX="0.75",scaleY="0.75",opacity="255",rotation="0",tag="150",anchorPointX="0.5",anchorPointY="0.5",},
lb_btn_r_tips={classname="CustomLabel",name="lb_btn_r_tips",parName="ly_down_confirm",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="跳过招募动画",fontName="微软雅黑",fontSize="20",height="27",width="120",x="278",y="175",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="151",anchorPointX="0",anchorPointY="0.5",},
lb_have_get={classname="CustomLabel",name="lb_have_get",parName="ly_down_confirm",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="320",y="208",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="158",anchorPointX="0.5",anchorPointY="0.5",},
ly_btn_l={classname="Panel",name="ly_btn_l",parName="ly_down_btn",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="65",width="155",x="70",y="90",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="73",anchorPointX="0",anchorPointY="0",},
ly_btn_r={classname="Panel",name="ly_btn_r",parName="ly_down_btn",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="65",width="155",x="415",y="90",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="75",anchorPointX="0",anchorPointY="0",},
lb_tips={classname="CustomLabel",name="lb_tips",parName="ly_down_btn",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="319",y="257",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="72",anchorPointX="0.5",anchorPointY="0.5",},
lb_get_tip={classname="Label",name="lb_get_tip",parName="ly_down_btn",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="320",y="60",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="208",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_6"] = {
lb_hero_ne={classname="CustomLabel",name="lb_hero_ne",parName="ly_down",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="项羽",fontName="微软雅黑",fontSize="36",height="46",width="72",x="120",y="72",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="128",anchorPointX="0",anchorPointY="0.5",},
img_hero_type={classname="ImageView",name="img_hero_type",parName="ly_down",ZOrder="0",fileName="#v1_img_bubing.png",scale9Enable="false",scale9Height="112",scale9Width="98",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="112",width="98",x="60",y="51",visible="true",touchAble="false",flipX="false",scaleX="0.8",scaleY="0.8",opacity="255",rotation="0",tag="127",anchorPointX="0.5",anchorPointY="0.5",},
lb_hero_info={classname="CustomLabel",name="lb_hero_info",parName="ly_down",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="22",height="30",width="106",x="120",y="23",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="129",anchorPointX="0",anchorPointY="0.5",},
lb_hero_tips_1={classname="CustomLabel",name="lb_hero_tips_1",parName="ly_down",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="资质",fontName="微软雅黑",fontSize="22",height="30",width="44",x="348",y="75",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="386",anchorPointX="0.5",anchorPointY="0.5",},
lb_hero_talent={classname="CustomLabel",name="lb_hero_talent",parName="ly_down",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="1000",fontName="微软雅黑",fontSize="22",height="30",width="52",x="378",y="75",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="387",anchorPointX="0",anchorPointY="0.5",},
lb_hero_talent_add={classname="CustomLabel",name="lb_hero_talent_add",parName="ly_down",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="+199",fontName="微软雅黑",fontSize="22",height="30",width="55",x="429",y="75",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="388",anchorPointX="0",anchorPointY="0.5",},
lb_hero_tips_2={classname="CustomLabel",name="lb_hero_tips_2",parName="ly_down",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="品质",fontName="微软雅黑",fontSize="22",height="30",width="44",x="517",y="75",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="390",anchorPointX="0.5",anchorPointY="0.5",},
lb_hero_quality={classname="CustomLabel",name="lb_hero_quality",parName="ly_down",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="蓝",fontName="微软雅黑",fontSize="22",height="30",width="22",x="560",y="75",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="391",anchorPointX="0.5",anchorPointY="0.5",},
ly_share={classname="Panel",name="ly_share",parName="ly_show_hero",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen8.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="43",capInsetsY="40",height="80",width="85",x="555",y="432",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="116",anchorPointX="0",anchorPointY="0",},
ly_info={classname="Panel",name="ly_info",parName="ly_show_hero",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen8.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="43",capInsetsY="40",height="80",width="85",x="555",y="352",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="118",anchorPointX="0",anchorPointY="0",},
}
tTable["index_7"] = {
Image_9={classname="ImageView",name="Image_9",parName="ly_share",ZOrder="0",fileName="#v1_btn_fenxiang.png",scale9Enable="false",scale9Height="72",scale9Width="72",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="72",width="72",x="43",y="40",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="119",anchorPointX="0.5",anchorPointY="0.5",},
Image_10={classname="ImageView",name="Image_10",parName="ly_info",ZOrder="0",fileName="#v1_btn_shuxing.png",scale9Enable="false",scale9Height="62",scale9Width="42",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="62",width="42",x="43",y="38",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="120",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable