local tTable = {}


tTable["index_1"] = {
dlg_hero_main={classname="Panel",name="dlg_hero_main@fill_layout",parName="root",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1066",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
ly_main={classname="Panel",name="ly_main@fill_layout_height",parName="dlg_hero_main",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="10",height="1066",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7",anchorPointX="0",anchorPointY="0",},
lay_tab={classname="Panel",name="lay_tab@fill_layout_height",parName="dlg_hero_main",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="10",height="1066",width="640",x="0",y="0",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6775",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_top_tab={classname="Panel",name="lay_top_tab",parName="ly_main",ZOrder="99999",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="640",x="0",y="1013",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7407",anchorPointX="0",anchorPointY="0",},
ly_content={classname="Panel",name="ly_content",parName="ly_main",childCount="17",ZOrder="99998",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="82",capInsetsY="82",height="874",width="640",x="0",y="136",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="14",anchorPointX="0",anchorPointY="0",},
ly_space={classname="Panel",name="ly_space@fill_layout",parName="ly_main",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="0.01",width="640",x="0",y="135",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8109",anchorPointX="0",anchorPointY="0",},
ly_down={classname="Panel",name="ly_down",parName="ly_main",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="136",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
ly_kuang1={classname="Panel",name="ly_kuang1",parName="ly_content",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen8.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="43",capInsetsY="40",height="170",width="85",x="0",y="545",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="16",anchorPointX="0",anchorPointY="0",},
img_bg2={classname="ImageView",name="img_bg2",parName="ly_content",ZOrder="1",fileName="ui/v1_img_roleshade.png",scale9Enable="false",scale9Height="353",scale9Width="320",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="353",width="320",x="0",y="-31",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="29",anchorPointX="0",anchorPointY="0",},
Image_23={classname="ImageView",name="Image_23",parName="ly_content",ZOrder="10",fileName="#v1_img_figure.png",scale9Enable="true",scale9Height="755",scale9Width="640",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="82",capInsetsY="82",height="755",width="640",x="0",y="-30",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="30",anchorPointX="0",anchorPointY="0",},
ly_equip_1={classname="Panel",name="ly_equip_1",parName="ly_content",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="168",width="106",x="0",y="354",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="35",anchorPointX="0",anchorPointY="0",},
ly_equip_2={classname="Panel",name="ly_equip_2",parName="ly_content",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="148",width="106",x="101",y="304",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="36",anchorPointX="0",anchorPointY="0",},
ly_equip_3={classname="Panel",name="ly_equip_3",parName="ly_content",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="148",width="106",x="211",y="279",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="37",anchorPointX="0",anchorPointY="0",},
ly_equip_4={classname="Panel",name="ly_equip_4",parName="ly_content",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="148",width="106",x="323",y="279",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="38",anchorPointX="0",anchorPointY="0",},
ly_equip_5={classname="Panel",name="ly_equip_5",parName="ly_content",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="148",width="106",x="433",y="304",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="39",anchorPointX="0",anchorPointY="0",},
ly_equip_6={classname="Panel",name="ly_equip_6",parName="ly_content",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="148",width="106",x="534",y="354",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="40",anchorPointX="0",anchorPointY="0",},
Image_60={classname="ImageView",name="Image_60",parName="ly_content",ZOrder="11",fileName="#v1_img_mingzidi.png",scale9Enable="false",scale9Height="49",scale9Width="186",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="49",width="186",x="320",y="710",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="67",anchorPointX="0.5",anchorPointY="0.5",},
img_circle1={classname="ImageView",name="img_circle1",parName="ly_content",ZOrder="1",fileName="#v2_img_roleshade_wujiang.png",scale9Enable="false",scale9Height="160",scale9Width="320",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="160",width="320",x="160",y="376",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1398",anchorPointX="0.5",anchorPointY="0.5",},
img_circle2={classname="ImageView",name="img_circle2",parName="ly_content",ZOrder="1",fileName="#v2_img_roleshade_wujiang.png",scale9Enable="false",scale9Height="160",scale9Width="320",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="160",width="320",x="480",y="376",visible="true",touchAble="false",flipX="true",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1399",anchorPointX="0.5",anchorPointY="0.5",},
lay_attr={classname="Panel",name="lay_attr",parName="ly_content",childCount="6",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_black20.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="10",height="280",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1400",anchorPointX="0",anchorPointY="0",},
img_turn_left={classname="ImageView",name="img_turn_left",parName="ly_content",ZOrder="5",fileName="#v1_btn_jiantou.png",scale9Enable="false",scale9Height="44",scale9Width="36",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="44",width="36",x="35",y="589",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1985",anchorPointX="0.5",anchorPointY="0.5",},
img_turn_right={classname="ImageView",name="img_turn_right",parName="ly_content",ZOrder="5",fileName="#v1_btn_jiantou.png",scale9Enable="false",scale9Height="44",scale9Width="36",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="44",width="36",x="605",y="589",visible="true",touchAble="false",flipX="true",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1986",anchorPointX="0.5",anchorPointY="0.5",},
lay_name={classname="Panel",name="lay_name",parName="ly_content",childCount="5",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="250",width="200",x="0",y="621",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1988",anchorPointX="0",anchorPointY="0",},
lay_pageview={classname="Panel",name="lay_pageview",parName="ly_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="515",width="640",x="0",y="359",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1999",anchorPointX="0",anchorPointY="0",},
ly_down_btn_cd={classname="Panel",name="ly_down_btn_cd",parName="ly_down",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="20",y="48",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4114",anchorPointX="0",anchorPointY="0",},
ly_down_btn_l={classname="Panel",name="ly_down_btn_l",parName="ly_down",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="246",y="48",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9",anchorPointX="0",anchorPointY="0",},
ly_down_btn_m={classname="Panel",name="ly_down_btn_m",parName="ly_down",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="465",y="48",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="12",anchorPointX="0",anchorPointY="0",},
ly_down_btn_r={classname="Panel",name="ly_down_btn_r",parName="ly_down",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="355",y="48",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="13",anchorPointX="0",anchorPointY="0",},
}
tTable["index_5"] = {
lay_title={classname="Panel",name="lay_title",parName="lay_attr",childCount="2",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_kelashen6youjianweidu.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="300",capInsetsY="21",height="42",width="640",x="0",y="238",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1401",anchorPointX="0",anchorPointY="0",},
lay_attr_list={classname="Panel",name="lay_attr_list",parName="lay_attr",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="240",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7039",anchorPointX="0",anchorPointY="0",},
img_arr_left={classname="CustomImageView",name="img_arr_left",parName="lay_attr",ZOrder="5",fileName="#v1_btn_jiantou.png",scale9Enable="false",scale9Height="44",scale9Width="36",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="44",width="36",x="20",y="121",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7040",anchorPointX="0.5",anchorPointY="0.5",},
img_arr_right={classname="CustomImageView",name="img_arr_right",parName="lay_attr",ZOrder="5",fileName="#v1_btn_jiantou.png",scale9Enable="false",scale9Height="44",scale9Width="36",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="44",width="36",x="619",y="121",visible="true",touchAble="false",flipX="true",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7041",anchorPointX="0.5",anchorPointY="0.5",},
img_huanye_1={classname="CustomImageView",name="img_huanye_1",parName="lay_attr",ZOrder="0",fileName="ui/daitu.png",scale9Enable="false",scale9Height="10",scale9Width="10",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="10",width="10",x="305",y="14",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7093",anchorPointX="0.5",anchorPointY="0.5",},
img_huanye_2={classname="CustomImageView",name="img_huanye_2",parName="lay_attr",ZOrder="0",fileName="ui/daitu.png",scale9Enable="false",scale9Height="10",scale9Width="10",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="10",width="10",x="334",y="14",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7094",anchorPointX="0.5",anchorPointY="0.5",},
img_ig={classname="CustomImageView",name="img_ig",parName="lay_name",ZOrder="2",fileName="#v2_fonts_shen.png",scale9Enable="false",scale9Height="39",scale9Width="29",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="39",width="29",x="86",y="215",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6335",anchorPointX="0.5",anchorPointY="0.5",},
img_bg_state={classname="ImageView",name="img_bg_state",parName="lay_name",ZOrder="0",fileName="#v2_img_pelgbai.png",scale9Enable="false",scale9Height="215",scale9Width="73",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="215",width="73",x="45",y="144",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1987",anchorPointX="0.5",anchorPointY="0.5",},
img_soldier={classname="ImageView",name="img_soldier",parName="lay_name",ZOrder="2",fileName="#v2_img_wj_bubing.png",scale9Enable="false",scale9Height="48",scale9Width="47",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="48",width="47",x="46",y="213",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1990",anchorPointX="0.5",anchorPointY="0.5",},
lb_hero_name={classname="CustomLabel",name="lb_hero_name",parName="lay_name",ZOrder="100",colorB="255",colorG="255",colorR="255",areaHeight="136",areaWidth="30",hAlignment="0",vAlignment="0",text="诸葛亮liang",fontName="微软雅黑",fontSize="30",height="136",width="30",x="30",y="175",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1991",anchorPointX="0",anchorPointY="1",},
lay_bg_star={classname="Panel",name="lay_bg_star",parName="lay_name",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v2_img_wj_xingjidi.png",height="169",width="26",x="74",y="43",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1992",anchorPointX="0",anchorPointY="0",},
}
tTable["index_6"] = {
lay_base={classname="Panel",name="lay_base",parName="lay_title",childCount="2",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="135",x="81",y="-3",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2189",anchorPointX="0",anchorPointY="0",},
lay_hero={classname="Panel",name="lay_hero",parName="lay_title",childCount="2",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="135",x="408",y="-4",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2190",anchorPointX="0",anchorPointY="0",},
img_star1={classname="ImageView",name="img_star1",parName="lay_bg_star",ZOrder="0",fileName="#v1_img_star5.png",scale9Enable="false",scale9Height="38",scale9Width="40",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="38",width="40",x="13",y="140",visible="true",touchAble="false",flipX="false",scaleX="0.6",scaleY="0.6",opacity="255",rotation="0",tag="1993",anchorPointX="0.5",anchorPointY="0.5",},
img_star2={classname="ImageView",name="img_star2",parName="lay_bg_star",ZOrder="0",fileName="#v1_img_star5.png",scale9Enable="false",scale9Height="38",scale9Width="40",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="38",width="40",x="13",y="116",visible="true",touchAble="false",flipX="false",scaleX="0.6",scaleY="0.6",opacity="255",rotation="0",tag="1994",anchorPointX="0.5",anchorPointY="0.5",},
img_star3={classname="ImageView",name="img_star3",parName="lay_bg_star",ZOrder="0",fileName="#v1_img_star5.png",scale9Enable="false",scale9Height="38",scale9Width="40",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="38",width="40",x="13",y="92",visible="true",touchAble="false",flipX="false",scaleX="0.6",scaleY="0.6",opacity="255",rotation="0",tag="1996",anchorPointX="0.5",anchorPointY="0.5",},
img_star4={classname="ImageView",name="img_star4",parName="lay_bg_star",ZOrder="0",fileName="#v1_img_star5.png",scale9Enable="false",scale9Height="38",scale9Width="40",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="38",width="40",x="13",y="67",visible="true",touchAble="false",flipX="false",scaleX="0.6",scaleY="0.6",opacity="255",rotation="0",tag="1997",anchorPointX="0.5",anchorPointY="0.5",},
img_star5={classname="ImageView",name="img_star5",parName="lay_bg_star",ZOrder="0",fileName="#v1_img_star5.png",scale9Enable="false",scale9Height="38",scale9Width="40",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="38",width="40",x="13",y="40",visible="true",touchAble="false",flipX="false",scaleX="0.6",scaleY="0.6",opacity="255",rotation="0",tag="1998",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_7"] = {
lb_base_attr={classname="CustomLabel",name="lb_base_attr",parName="lay_base",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="基础资质",fontName="微软雅黑",fontSize="20",height="27",width="80",x="40",y="22",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1402",anchorPointX="0.5",anchorPointY="0.5",},
ly_share={classname="Panel",name="ly_share",parName="lay_base",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="39",x="90",y="3",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="25",anchorPointX="0",anchorPointY="0",},
lb_hero_attr={classname="CustomLabel",name="lb_hero_attr",parName="lay_hero",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="武将属性",fontName="微软雅黑",fontSize="20",height="27",width="80",x="40",y="22",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1403",anchorPointX="0.5",anchorPointY="0.5",},
ly_info={classname="Panel",name="ly_info",parName="lay_hero",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="39",x="90",y="3",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="27",anchorPointX="0",anchorPointY="0",},
}
tTable["index_8"] = {
img_share={classname="ImageView",name="img_share",parName="ly_share",ZOrder="0",fileName="#v2_btn_wj_fenxiang.png",scale9Enable="false",scale9Height="40",scale9Width="39",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="40",width="39",x="20",y="20",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="17",anchorPointX="0.5",anchorPointY="0.5",},
img_info={classname="ImageView",name="img_info",parName="ly_info",ZOrder="0",fileName="#v2_btn_wj_xiangqing.png",scale9Enable="false",scale9Height="34",scale9Width="34",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="34",width="34",x="19",y="20",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="24",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable