local tTable = {}


tTable["index_1"] = {
root={classname="Panel",name="root@fill_layout",parName="root",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1060",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="14",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_tab={classname="Panel",name="lay_tab",parName="root",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="60",width="640",x="0",y="1000",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="320",anchorPointX="0",anchorPointY="0",},
lay_content={classname="Panel",name="lay_content@fill_layout",parName="root",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="982",width="640",x="0",y="20",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="644",anchorPointX="0",anchorPointY="0",},
lay_bottom={classname="Panel",name="lay_bottom",parName="root",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="20",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="641",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_task_layer={classname="Panel",name="lay_task_layer@fill_layout_height",parName="lay_content",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="982",width="640",x="0",y="0",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="571",anchorPointX="0",anchorPointY="0",},
lay_daily_layer={classname="Panel",name="lay_daily_layer@fill_layout_height",parName="lay_content",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="982",width="640",x="0",y="0",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="573",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lay_task_top={classname="Panel",name="lay_task_top",parName="lay_task_layer",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="185",width="640",x="0",y="785",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="642",anchorPointX="0",anchorPointY="0",},
lay_list={classname="Panel",name="lay_list@fill_layout",parName="lay_task_layer",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="785",width="600",x="20",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="44",anchorPointX="0",anchorPointY="0",},
lay_detail_top={classname="Panel",name="lay_detail_top",parName="lay_daily_layer",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="330",width="640",x="0",y="652",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="643",anchorPointX="0",anchorPointY="0",},
lay_daily_list={classname="Panel",name="lay_daily_list@fill_layout",parName="lay_daily_layer",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="651",width="600",x="20",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="580",anchorPointX="0",anchorPointY="0",},
}
tTable["index_5"] = {
lay_title_1={classname="Panel",name="lay_title_1",parName="lay_task_top",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_xiaobiaoti2.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="186",capInsetsY="24",height="50",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="42",anchorPointX="0",anchorPointY="0",},
lay_taskmain={classname="Panel",name="lay_taskmain",parName="lay_task_top",childCount="1",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="130",width="600",x="19",y="55",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="39",anchorPointX="0",anchorPointY="0",},
lay_banner_bg={classname="Panel",name="lay_banner_bg",parName="lay_task_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="192",width="640",x="0",y="49",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="457",anchorPointX="0",anchorPointY="0",},
lb_tip_3={classname="Label",name="lb_tip_3",parName="lay_task_top",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="主公，什么都没有哦~",fontName="微软雅黑",fontSize="22",height="30",width="214",x="319",y="-341",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="196",anchorPointX="0.5",anchorPointY="0.5",},
lay_daily={classname="Panel",name="lay_daily",parName="lay_detail_top",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="280",width="640",x="0",y="50",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="322",anchorPointX="0",anchorPointY="0",},
lay_banner_bg2={classname="Panel",name="lay_banner_bg2",parName="lay_detail_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="280",width="640",x="0",y="28",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="514",anchorPointX="0",anchorPointY="0",},
lay_title_2={classname="Panel",name="lay_title_2",parName="lay_detail_top",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_xiaobiaoti2.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="186",capInsetsY="24",height="50",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="578",anchorPointX="0",anchorPointY="0",},
}
tTable["index_6"] = {
lb_tip_1={classname="Label",name="lb_tip_1",parName="lay_title_1",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="支线任务",fontName="微软雅黑",fontSize="20",height="27",width="80",x="15",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="43",anchorPointX="0",anchorPointY="0.5",},
lb_tip_4={classname="Label",name="lb_tip_4",parName="lay_taskmain",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="22",height="30",width="106",x="300",y="70",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="265",anchorPointX="0.5",anchorPointY="0.5",},
lb_tip_2={classname="Label",name="lb_tip_2",parName="lay_title_2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="支线任务",fontName="微软雅黑",fontSize="20",height="27",width="80",x="15",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="579",anchorPointX="0",anchorPointY="0.5",},
}

return tTable