local tTable = {}


tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="695",width="550",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="393",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
view={classname="Panel",name="view",parName="default",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="695",width="550",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="394",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_content={classname="Panel",name="lay_content",parName="view",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="471",width="520",x="14",y="203",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2201",anchorPointX="0",anchorPointY="0",},
lay_bottom={classname="Panel",name="lay_bottom",parName="view",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="200",width="550",x="1",y="2",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2207",anchorPointX="0",anchorPointY="0",},
lay_bottom2={classname="Panel",name="lay_bottom2",parName="view",childCount="7",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="200",width="550",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2211",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
txt_content_tip1={classname="CustomLabel",name="txt_content_tip1",parName="lay_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="成功申请城主后将自动重建城池名字",fontName="微软雅黑",fontSize="20",height="27",width="320",x="260",y="408",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2202",anchorPointX="0.5",anchorPointY="0.5",},
lay_icon={classname="Panel",name="lay_icon",parName="lay_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="200",width="200",x="160",y="154",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="5696",anchorPointX="0",anchorPointY="0",},
txt_content_tip2={classname="CustomLabel",name="txt_content_tip2",parName="lay_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="260",y="120",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="15105",anchorPointX="0.5",anchorPointY="1",},
txt_bottom_tip={classname="CustomLabel",name="txt_bottom_tip",parName="lay_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="277",y="160",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2208",anchorPointX="0.5",anchorPointY="0.5",},
txt_bottom_cd={classname="CustomLabel",name="txt_bottom_cd",parName="lay_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="271",y="70",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2209",anchorPointX="1",anchorPointY="0.5",},
txt_bottom_cd_tip={classname="CustomLabel",name="txt_bottom_cd_tip",parName="lay_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="22",height="30",width="106",x="275",y="70",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2210",anchorPointX="0",anchorPointY="0.5",},
txt_cost_title={classname="CustomLabel",name="txt_cost_title",parName="lay_bottom2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="申请消耗：",fontName="微软雅黑",fontSize="20",height="27",width="100",x="122",y="171",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2212",anchorPointX="0",anchorPointY="0.5",},
lay_btn_apply={classname="Panel",name="lay_btn_apply",parName="lay_bottom2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="65",width="155",x="198",y="20",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2215",anchorPointX="0",anchorPointY="0",},
img_res1={classname="CustomImageView",name="img_res1",parName="lay_bottom2",ZOrder="0",fileName="#v1_img_qianbi.png",scale9Enable="false",scale9Height="36",scale9Width="36",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="36",width="36",x="249",y="169",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6633",anchorPointX="0.5",anchorPointY="0.5",},
txt_res1={classname="CustomLabel",name="txt_res1",parName="lay_bottom2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="99999",fontName="微软雅黑",fontSize="20",height="27",width="60",x="275",y="169",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6634",anchorPointX="0",anchorPointY="0.5",},
img_res2={classname="CustomImageView",name="img_res2",parName="lay_bottom2",ZOrder="0",fileName="#v1_img_qianbi.png",scale9Enable="false",scale9Height="36",scale9Width="36",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="36",width="36",x="381",y="169",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6635",anchorPointX="0.5",anchorPointY="0.5",},
txt_res2={classname="CustomLabel",name="txt_res2",parName="lay_bottom2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="99999",fontName="微软雅黑",fontSize="20",height="27",width="60",x="407",y="169",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6636",anchorPointX="0",anchorPointY="0.5",},
txt_bottom2_tip={classname="CustomLabel",name="txt_bottom2_tip",parName="lay_bottom2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="275",y="105",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6643",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable