local tTable = {}


tTable["index_1"] = {
root={classname="Panel",name="root",parName="root",childCount="13",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="390",width="500",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="46",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lb_tip_1={classname="Label",name="lb_tip_1",parName="root",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="游戏免打扰",fontName="微软雅黑",fontSize="20",height="27",width="100",x="25",y="330",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="47",anchorPointX="0",anchorPointY="0.5",},
lb_status={classname="Label",name="lb_status",parName="root",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="（已关闭）",fontName="微软雅黑",fontSize="20",height="27",width="100",x="125",y="330",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="48",anchorPointX="0",anchorPointY="0.5",},
lay_btn={classname="Panel",name="lay_btn",parName="root",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="104",x="360",y="310",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="51",anchorPointX="0",anchorPointY="0",},
lb_tip_2={classname="Label",name="lb_tip_2",parName="root",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="开启",fontName="微软雅黑",fontSize="20",height="27",width="40",x="25",y="260",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="52",anchorPointX="0",anchorPointY="0.5",},
lb_time={classname="Label",name="lb_time",parName="root",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="（20:00-8:00）",fontName="微软雅黑",fontSize="20",height="27",width="143",x="83",y="260",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="53",anchorPointX="0",anchorPointY="0.5",},
lb_tip_3={classname="Label",name="lb_tip_3",parName="root",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="起始时间",fontName="微软雅黑",fontSize="20",height="27",width="80",x="25",y="161",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="54",anchorPointX="0",anchorPointY="0.5",},
lb_tip_4={classname="Label",name="lb_tip_4",parName="root",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="结束时间",fontName="微软雅黑",fontSize="20",height="27",width="80",x="25",y="90",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="55",anchorPointX="0",anchorPointY="0.5",},
lay_input_1={classname="Panel",name="lay_input_1",parName="root",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_shurukuang.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="20",capInsetsY="20",height="40",width="120",x="111",y="141",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="57",anchorPointX="0",anchorPointY="0",},
tf_start={classname="TextField",name="tf_start",parName="root",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="27",areaWidth="120",fontName="微软雅黑",fontSize="20",maxLength="2",maxLengthEnable="true",passwordStyleText="*",passwordEnable="false",height="27",width="120",x="171",y="161",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="58",anchorPointX="0.5",anchorPointY="0.5",},
lb_tip_5={classname="Label",name="lb_tip_5",parName="root",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="点",fontName="微软雅黑",fontSize="20",height="27",width="20",x="240",y="161",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="59",anchorPointX="0",anchorPointY="0.5",},
lb_tip_6={classname="Label",name="lb_tip_6",parName="root",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="点",fontName="微软雅黑",fontSize="20",height="27",width="20",x="240",y="90",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="60",anchorPointX="0",anchorPointY="0.5",},
lay_input_2={classname="Panel",name="lay_input_2",parName="root",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_shurukuang.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="20",capInsetsY="20",height="40",width="120",x="111",y="70",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="61",anchorPointX="0",anchorPointY="0",},
tf_end={classname="TextField",name="tf_end",parName="root",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="27",areaWidth="120",fontName="微软雅黑",fontSize="20",maxLength="2",maxLengthEnable="true",passwordStyleText="*",passwordEnable="false",height="27",width="120",x="171",y="90",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="62",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable