local tTable = {}

tTable["texturesPng"] = {"ui/p1_commonse1.plist","GUI/image.png"}
tTable["index_1"] = {
root={classname="Panel",name="root",parName="root",childCount="7",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="390",width="500",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="206",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_info={classname="Panel",name="lay_info",parName="root",childCount="9",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="370",width="500",x="0",y="10",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="207",anchorPointX="0",anchorPointY="0",},
lay_btn_1={classname="Panel",name="lay_btn_1",parName="root",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="14",y="-92",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="250",anchorPointX="0",anchorPointY="0",},
lay_btn_2={classname="Panel",name="lay_btn_2",parName="root",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="188",y="-92",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="251",anchorPointX="0",anchorPointY="0",},
lay_btn_3={classname="Panel",name="lay_btn_3",parName="root",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="356",y="-92",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="252",anchorPointX="0",anchorPointY="0",},
lay_btn_4={classname="Panel",name="lay_btn_4",parName="root",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="14",y="-178",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="254",anchorPointX="0",anchorPointY="0",},
lay_btn_5={classname="Panel",name="lay_btn_5",parName="root",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="188",y="-178",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="256",anchorPointX="0",anchorPointY="0",},
lay_btn_6={classname="Panel",name="lay_btn_6",parName="root",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="356",y="-178",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="394",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
img_line={classname="ImageView",name="img_line",parName="lay_info",ZOrder="0",fileName="#v1_line_blue1.png",scale9Enable="true",scale9Height="2",scale9Width="464",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="1",height="2",width="464",x="250",y="185",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="208",anchorPointX="0.5",anchorPointY="0.5",},
lay_icon={classname="Panel",name="lay_icon",parName="lay_info",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="18",y="224",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="209",anchorPointX="0",anchorPointY="0",},
lb_vip_lv={classname="Label",name="lb_vip_lv",parName="lay_info",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="VIP6",fontName="微软雅黑",fontSize="22",height="30",width="47",x="71",y="351",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="214",anchorPointX="0.5",anchorPointY="0.5",},
img_dianzan={classname="ImageView",name="img_dianzan",parName="lay_info",ZOrder="0",fileName="#v1_img_dianzan.png",scale9Enable="false",scale9Height="36",scale9Width="36",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="36",width="36",x="156",y="315",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="215",anchorPointX="0.5",anchorPointY="0.5",},
lb_name={classname="Label",name="lb_name",parName="lay_info",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="秦王",fontName="微软雅黑",fontSize="20",height="27",width="40",x="140",y="252",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="240",anchorPointX="0",anchorPointY="0.5",},
lb_fc={classname="Label",name="lb_fc",parName="lay_info",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="12m",fontName="微软雅黑",fontSize="20",height="27",width="43",x="140",y="221",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="241",anchorPointX="0",anchorPointY="0.5",},
lb_zan={classname="Label",name="lb_zan",parName="lay_info",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="1200",fontName="微软雅黑",fontSize="20",height="27",width="48",x="180",y="313",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="243",anchorPointX="0",anchorPointY="0.5",},
img_flag={classname="ImageView",name="img_flag",parName="lay_info",ZOrder="10",fileName="GUI/image.png",scale9Enable="false",scale9Height="80",scale9Width="80",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="80",width="80",x="460",y="317",visible="true",touchAble="false",flipX="false",scaleX="0.7",scaleY="0.7",opacity="255",rotation="0",tag="244",anchorPointX="0.5",anchorPointY="0.5",},
lb_lv={classname="Label",name="lb_lv",parName="lay_info",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="23",fontName="微软雅黑",fontSize="20",height="27",width="24",x="140",y="282",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="265",anchorPointX="0",anchorPointY="0.5",},
}

return tTable