local tTable = {}


tTable["index_1"] = {
dlg_phone_bind={classname="Panel",name="dlg_phone_bind",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1066",width="522",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="440",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_main={classname="Panel",name="lay_main",parName="dlg_phone_bind",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1066",width="522",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="441",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
ly_title={classname="Panel",name="ly_title",parName="lay_main",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="186",capInsetsY="24",height="200",width="522",x="0",y="866",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="442",anchorPointX="0",anchorPointY="0",},
ly_show={classname="Panel",name="ly_show",parName="lay_main",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="821",width="522",x="0",y="44",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="446",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
img_jianbian={classname="ImageView",name="img_jianbian",parName="ly_title",ZOrder="20",fileName="#v1_img_blackjianbian.png",scale9Enable="true",scale9Height="70",scale9Width="486",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="133",capInsetsY="31",height="70",width="486",x="251",y="40",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="451",anchorPointX="0.5",anchorPointY="0.5",},
lay_banner_bg={classname="Panel",name="lay_banner_bg",parName="ly_title",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="200",width="522",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="457",anchorPointX="0",anchorPointY="0",},
lb_tips={classname="Label",name="lb_tips",parName="ly_title",ZOrder="30",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="不区分大小写，每个礼包兑换码只可使用一次",fontName="微软雅黑",fontSize="20",height="27",width="400",x="34",y="65",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="466",anchorPointX="0",anchorPointY="1",},
lay_btn={classname="Panel",name="lay_btn",parName="ly_show",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="64",width="168",x="164",y="61",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="447",anchorPointX="0",anchorPointY="0",},
lb_dec={classname="Label",name="lb_dec",parName="ly_show",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="不区分大小写，每个礼包兑换码只可使用一次",fontName="微软雅黑",fontSize="20",height="27",width="400",x="20",y="751",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="450",anchorPointX="0",anchorPointY="1",},
lay_icon={classname="Panel",name="lay_icon",parName="ly_show",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="400",x="49",y="214",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="476",anchorPointX="0",anchorPointY="0",},
ly_sec_tile={classname="Panel",name="ly_sec_tile",parName="ly_show",childCount="1",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_xiaobiaoti2.png",capInsetsHeight="20",capInsetsWidth="300",capInsetsX="0",capInsetsY="0",height="50",width="522",x="0",y="771",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="463",anchorPointX="0",anchorPointY="0",},
ly_third_tile={classname="Panel",name="ly_third_tile",parName="ly_show",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_xiaobiaoti2.png",capInsetsHeight="20",capInsetsWidth="300",capInsetsX="0",capInsetsY="0",height="50",width="522",x="0",y="342",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="473",anchorPointX="0",anchorPointY="0",},
}
tTable["index_5"] = {
lb_sec_title={classname="CustomLabel",name="lb_sec_title",parName="ly_sec_tile",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="22",height="30",width="106",x="20",y="26",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="464",anchorPointX="0",anchorPointY="0.5",},
lb_third_title={classname="CustomLabel",name="lb_third_title",parName="ly_third_tile",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="22",height="30",width="106",x="20",y="26",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="474",anchorPointX="0",anchorPointY="0.5",},
}

return tTable