local tTable = {}


tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1066",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="37",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_top={classname="Panel",name="lay_top",parName="default",childCount="10",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="244",width="640",x="0",y="822",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="38",anchorPointX="0",anchorPointY="0",},
lay_center={classname="Panel",name="lay_center",parName="default",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="ui/v2_img_xunlongdi.jpg",height="636",width="640",x="0",y="175",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="42",anchorPointX="0",anchorPointY="0",},
lay_bottom={classname="Panel",name="lay_bottom",parName="default",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="175",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="43",anchorPointX="0",anchorPointY="0",},
img_xou_l={classname="ImageView",name="img_xou_l",parName="default",ZOrder="1",fileName="#v2_img_xunlongtou.png",scale9Enable="false",scale9Height="37",scale9Width="320",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="37",width="320",x="160",y="793",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="44",anchorPointX="0.5",anchorPointY="0",},
img_xou_r={classname="ImageView",name="img_xou_r",parName="default",ZOrder="1",fileName="#v2_img_xunlongtou.png",scale9Enable="false",scale9Height="37",scale9Width="320",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="37",width="320",x="480",y="793",visible="true",touchAble="false",flipX="true",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="46",anchorPointX="0.5",anchorPointY="0",},
}
tTable["index_3"] = {
lay_banner_bg={classname="Panel",name="lay_banner_bg",parName="lay_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="192",width="640",x="0",y="46",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="39",anchorPointX="0",anchorPointY="0",},
lay_time={classname="Panel",name="lay_time",parName="lay_top",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="28",width="294",x="0",y="210",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="40",anchorPointX="0",anchorPointY="0",},
img_xunlongzi={classname="ImageView",name="img_xunlongzi",parName="lay_top",ZOrder="1",fileName="#v2_fonts_xunlongzi.png",scale9Enable="false",scale9Height="69",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="69",width="404",x="320",y="205",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="41",anchorPointX="0.5",anchorPointY="1",},
lay_item_1={classname="Panel",name="lay_item_1",parName="lay_top",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="86",width="86",x="131",y="42",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="47",anchorPointX="0",anchorPointY="0",},
lay_item_2={classname="Panel",name="lay_item_2",parName="lay_top",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="86",width="86",x="277",y="42",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="49",anchorPointX="0",anchorPointY="0",},
lay_item_3={classname="Panel",name="lay_item_3",parName="lay_top",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="86",width="86",x="423",y="42",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="50",anchorPointX="0",anchorPointY="0",},
lb_item_1={classname="Label",name="lb_item_1",parName="lay_top",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="174",y="32",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="51",anchorPointX="0.5",anchorPointY="1",},
lb_item_2={classname="Label",name="lb_item_2",parName="lay_top",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="320",y="31",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="53",anchorPointX="0.5",anchorPointY="1",},
lb_item_3={classname="Label",name="lb_item_3",parName="lay_top",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="466",y="31",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="54",anchorPointX="0.5",anchorPointY="1",},
lay_shuoming={classname="Panel",name="lay_shuoming",parName="lay_top",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v2_btn_shuoming.png",height="50",width="50",x="580",y="172",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="104",anchorPointX="0",anchorPointY="0",},
lay_center_good={classname="Panel",name="lay_center_good",parName="lay_center",childCount="3",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="280",width="280",x="182",y="177",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="101",anchorPointX="0",anchorPointY="0",},
lb_getcnt={classname="Label",name="lb_getcnt",parName="lay_center",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="累计抽取:999",fontName="微软雅黑",fontSize="20",height="27",width="121",x="20",y="583",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="105",anchorPointX="0",anchorPointY="0.5",},
lay_cost={classname="Panel",name="lay_cost",parName="lay_center",childCount="3",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_shurukuang.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="20",capInsetsY="20",height="36",width="144",x="471",y="563",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="106",anchorPointX="0",anchorPointY="0",},
lay_btn_left={classname="Panel",name="lay_btn_left",parName="lay_bottom",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="35",y="55",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="55",anchorPointX="0",anchorPointY="0",},
lay_btn_right={classname="Panel",name="lay_btn_right",parName="lay_bottom",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="450",y="55",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="57",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lb_good_cnt={classname="Label",name="lb_good_cnt",parName="lay_center_good",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="数量:35",fontName="微软雅黑",fontSize="20",height="27",width="69",x="140",y="88",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="102",anchorPointX="0.5",anchorPointY="0",},
lb_take={classname="Label",name="lb_take",parName="lay_center_good",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="今日再抽5次可得",fontName="微软雅黑",fontSize="20",height="27",width="152",x="140",y="78",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="103",anchorPointX="0.5",anchorPointY="1",},
lay_center_tx={classname="Panel",name="lay_center_tx",parName="lay_center_good",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="0.01",width="0.01",x="140",y="160",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="134",anchorPointX="0",anchorPointY="0",},
img_icon={classname="ImageView",name="img_icon",parName="lay_cost",ZOrder="0",fileName="ui/daitu.png",scale9Enable="false",scale9Height="10",scale9Width="10",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="10",width="10",x="13",y="18",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="107",anchorPointX="0.5",anchorPointY="0.5",},
img_add={classname="ImageView",name="img_add",parName="lay_cost",ZOrder="0",fileName="#v1_btn_increase.png",scale9Enable="false",scale9Height="34",scale9Width="34",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="34",width="34",x="135",y="18",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="108",anchorPointX="0.5",anchorPointY="0.5",},
lb_cost_cnt={classname="Label",name="lb_cost_cnt",parName="lay_cost",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="999",fontName="微软雅黑",fontSize="20",height="27",width="36",x="72",y="18",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="109",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_5"] = {
lay_center_good_bottom={classname="Panel",name="lay_center_good_bottom",parName="lay_center_tx",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="0.01",width="0.01",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="135",anchorPointX="0",anchorPointY="0",},
img_center_good={classname="ImageView",name="img_center_good",parName="lay_center_tx",ZOrder="50",fileName="#v2_img_emobiaozhi2.png",scale9Enable="false",scale9Height="59",scale9Width="59",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="59",width="59",x="0",y="10",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="100",anchorPointX="0.5",anchorPointY="0.5",},
img_center_good_up={classname="CustomImageView",name="img_center_good_up",parName="lay_center_tx",ZOrder="100",fileName="#v2_img_emobiaozhi2.png",scale9Enable="false",scale9Height="59",scale9Width="59",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="59",width="59",x="0",y="10",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="121",anchorPointX="0.5",anchorPointY="0.5",},
img_center_good_shadow={classname="CustomImageView",name="img_center_good_shadow",parName="lay_center_tx",ZOrder="200",fileName="#v2_img_emobiaozhi2.png",scale9Enable="false",scale9Height="59",scale9Width="59",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="59",width="59",x="0",y="10",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="136",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable