local tTable = {}


tTable["index_1"] = {
dlg_hero_arr_2={classname="Panel",name="dlg_hero_arr_2",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="240",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7042",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_attr={classname="Panel",name="lay_attr",parName="dlg_hero_arr_2",childCount="23",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="240",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7043",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
img_line={classname="CustomImageView",name="img_line",parName="lay_attr",ZOrder="0",fileName="#v1_line_blue1.png",scale9Enable="true",scale9Height="2",scale9Width="580",capInsetsHeight="2",capInsetsWidth="20",capInsetsX="0",capInsetsY="0",height="2",width="580",x="30",y="165",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7044",anchorPointX="0",anchorPointY="0.5",},
img_2={classname="CustomImageView",name="img_2",parName="lay_attr",ZOrder="0",fileName="#v2_img_wj_qg.png",scale9Enable="false",scale9Height="31",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="31",width="31",x="54",y="143",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7045",anchorPointX="0.5",anchorPointY="0.5",},
img_1={classname="ImageView",name="img_1",parName="lay_attr",ZOrder="0",fileName="#v2_img_wj_gongji.png",scale9Enable="false",scale9Height="29",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="29",width="31",x="54",y="190",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7047",anchorPointX="0.5",anchorPointY="0.5",},
img_3={classname="CustomImageView",name="img_3",parName="lay_attr",ZOrder="0",fileName="#v2_img_wj_sc.png",scale9Enable="false",scale9Height="31",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="31",width="31",x="54",y="95",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7050",anchorPointX="0.5",anchorPointY="0.5",},
img_4={classname="CustomImageView",name="img_4",parName="lay_attr",ZOrder="0",fileName="#v2_img_wj_bj.png",scale9Enable="false",scale9Height="31",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="31",width="31",x="54",y="47",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7051",anchorPointX="0.5",anchorPointY="0.5",},
img_6={classname="CustomImageView",name="img_6",parName="lay_attr",ZOrder="0",fileName="#v2_img_wj_qf.png",scale9Enable="false",scale9Height="31",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="31",width="31",x="247",y="144",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7056",anchorPointX="0.5",anchorPointY="0.5",},
img_5={classname="ImageView",name="img_5",parName="lay_attr",ZOrder="0",fileName="#v2_img_wj_fangyu.png",scale9Enable="false",scale9Height="29",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="29",width="31",x="247",y="190",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7057",anchorPointX="0.5",anchorPointY="0.5",},
img_7={classname="CustomImageView",name="img_7",parName="lay_attr",ZOrder="0",fileName="#v2_img_wj_mz.png",scale9Enable="false",scale9Height="31",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="31",width="31",x="247",y="96",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7058",anchorPointX="0.5",anchorPointY="0.5",},
img_8={classname="CustomImageView",name="img_8",parName="lay_attr",ZOrder="0",fileName="#v2_img_wj_jr.png",scale9Enable="false",scale9Height="31",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="31",width="31",x="247",y="47",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7059",anchorPointX="0.5",anchorPointY="0.5",},
img_10={classname="CustomImageView",name="img_10",parName="lay_attr",ZOrder="0",fileName="#v2_img_wj_gc.png",scale9Enable="false",scale9Height="31",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="31",width="31",x="442",y="143",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7066",anchorPointX="0.5",anchorPointY="0.5",},
img_9={classname="ImageView",name="img_9",parName="lay_attr",ZOrder="0",fileName="#v2_img_wj_bingli.png",scale9Enable="false",scale9Height="29",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="29",width="31",x="442",y="190",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7067",anchorPointX="0.5",anchorPointY="0.5",},
img_11={classname="CustomImageView",name="img_11",parName="lay_attr",ZOrder="0",fileName="#v2_img_wj_sb.png",scale9Enable="false",scale9Height="31",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="31",width="31",x="442",y="96",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7068",anchorPointX="0.5",anchorPointY="0.5",},
ly_att_6={classname="Panel",name="ly_att_6",parName="lay_attr",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="160",x="71",y="33",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7078",anchorPointX="0",anchorPointY="0",},
ly_att_2={classname="Panel",name="ly_att_2",parName="lay_attr",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="160",x="263",y="177",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7083",anchorPointX="0",anchorPointY="0",},
ly_att_9={classname="Panel",name="ly_att_9",parName="lay_attr",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="160",x="263",y="129",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7084",anchorPointX="0",anchorPointY="0",},
ly_att_4={classname="Panel",name="ly_att_4",parName="lay_attr",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="160",x="263",y="81",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7085",anchorPointX="0",anchorPointY="0",},
ly_att_7={classname="Panel",name="ly_att_7",parName="lay_attr",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="160",x="263",y="33",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7086",anchorPointX="0",anchorPointY="0",},
ly_att_3={classname="Panel",name="ly_att_3",parName="lay_attr",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="168",x="460",y="177",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7090",anchorPointX="0",anchorPointY="0",},
ly_att_10={classname="Panel",name="ly_att_10",parName="lay_attr",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="168",x="460",y="129",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7091",anchorPointX="0",anchorPointY="0",},
ly_att_5={classname="Panel",name="ly_att_5",parName="lay_attr",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="168",x="460",y="81",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7092",anchorPointX="0",anchorPointY="0",},
ly_att_1={classname="Panel",name="ly_att_1",parName="lay_attr",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="160",x="71",y="176",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7072",anchorPointX="0",anchorPointY="0",},
ly_att_8={classname="Panel",name="ly_att_8",parName="lay_attr",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="160",x="71",y="129",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7074",anchorPointX="0",anchorPointY="0",},
ly_att_11={classname="Panel",name="ly_att_11",parName="lay_attr",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="160",x="71",y="81",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7076",anchorPointX="0",anchorPointY="0",},
}

return tTable