local tTable = {}


tTable["index_1"] = {
root={classname="Panel",name="root",parName="root",childCount="10",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="265",width="500",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="766",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_stuffinfo={classname="Panel",name="lay_stuffinfo",parName="root",childCount="4",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen6.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="50",height="130",width="470",x="15",y="118",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="767",anchorPointX="0",anchorPointY="0",},
lay_bar_bg={classname="Panel",name="lay_bar_bg",parName="root",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v1_bar_b1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="45",capInsetsY="9",height="16",width="247",x="125",y="71",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="768",anchorPointX="0",anchorPointY="0",},
lay_rich_text={classname="Panel",name="lay_rich_text",parName="root",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="200",x="150",y="34",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="804",anchorPointX="0",anchorPointY="0",},
lb_rich_text={classname="Label",name="lb_rich_text",parName="root",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="250",y="49",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1323",anchorPointX="0.5",anchorPointY="0.5",},
lay_btn_right1={classname="ImageView",name="lay_btn_right1",parName="root",ZOrder="0",fileName="#v1_btn_increase.png",scale9Enable="false",scale9Height="34",scale9Width="34",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="34",width="34",x="409",y="97",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1324",anchorPointX="0.5",anchorPointY="1",},
lay_btn_left1={classname="ImageView",name="lay_btn_left1",parName="root",ZOrder="0",fileName="#v1_btn_reduce.png",scale9Enable="false",scale9Height="34",scale9Width="34",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="34",width="34",x="88",y="97",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1325",anchorPointX="0.5",anchorPointY="1",},
lay_btn_right={classname="Panel",name="lay_btn_right",parName="root",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="34",width="34",x="427",y="63",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="22584",anchorPointX="0",anchorPointY="0",},
lay_btn_left={classname="Panel",name="lay_btn_left",parName="root",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="34",width="34",x="36",y="63",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="22586",anchorPointX="0",anchorPointY="0",},
lb_useback={classname="CustomLabel",name="lb_useback",parName="root",ZOrder="10",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="使用后硬币数量：",fontName="微软雅黑",fontSize="18",height="24",width="144",x="202",y="18",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="22771",anchorPointX="0.5",anchorPointY="0.5",},
lb_useback_value={classname="CustomLabel",name="lb_useback_value",parName="root",ZOrder="10",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="16k/16k",fontName="微软雅黑",fontSize="18",height="24",width="72",x="290",y="18",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="22773",anchorPointX="0",anchorPointY="0.5",},
}
tTable["index_3"] = {
lay_icon={classname="Panel",name="lay_icon",parName="lay_stuffinfo",ZOrder="11",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="20",y="13",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="809",anchorPointX="0",anchorPointY="0",},
lb_name={classname="Label",name="lb_name",parName="lay_stuffinfo",ZOrder="11",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="物品名称",fontName="微软雅黑",fontSize="22",height="30",width="88",x="154",y="107",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="810",anchorPointX="0",anchorPointY="0.5",},
lb_expline={classname="Label",name="lb_expline",parName="lay_stuffinfo",ZOrder="11",colorB="255",colorG="255",colorR="255",areaHeight="81",areaWidth="280",hAlignment="0",vAlignment="0",text="你好你还你好你还你好你还你阿斯达所阿萨德按时的",fontName="微软雅黑",fontSize="20",height="81",width="280",x="154",y="50",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="811",anchorPointX="0",anchorPointY="0.5",},
lay_bg={classname="Panel",name="lay_bg",parName="lay_stuffinfo",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen6_b.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="175",capInsetsY="9",height="129",width="350",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="22675",anchorPointX="0",anchorPointY="0",},
}

return tTable