local tTable = {}

tTable["texturesPng"] = {"ui/v1_img_roleshade.png","ui/p1_commonse1.plist","ui/bg_hero/v1_img_role.jpg","ui/p1_commmon1_sep.plist","ui/bar/v1_bar_b2.png"}
tTable["index_1"] = {
dlg_hero_parameter={classname="Panel",name="dlg_hero_parameter",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="670",width="560",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="516",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
ly_content={classname="Panel",name="ly_content",parName="dlg_hero_parameter",childCount="27",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="82",capInsetsY="82",height="755",width="640",x="4",y="0",visible="true",touchAble="true",flipX="false",scaleX="0.86",scaleY="0.86",opacity="255",rotation="0",tag="551",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
img_bg2={classname="ImageView",name="img_bg2",parName="ly_content",ZOrder="1",fileName="ui/v1_img_roleshade.png",scale9Enable="false",scale9Height="420",scale9Width="640",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="420",width="640",x="0",y="0",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="557",anchorPointX="0",anchorPointY="0",},
Image_23={classname="ImageView",name="Image_23",parName="ly_content",ZOrder="10",fileName="#v1_img_figure.png",scale9Enable="true",scale9Height="755",scale9Width="640",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="82",capInsetsY="82",height="755",width="640",x="0",y="1",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="558",anchorPointX="0",anchorPointY="0",},
img_hero_bg={classname="ImageView",name="img_hero_bg",parName="ly_content",ZOrder="0",fileName="ui/bg_hero/v1_img_role.jpg",scale9Enable="false",scale9Height="515",scale9Width="640",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="515",width="640",x="320",y="496",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="559",anchorPointX="0.5",anchorPointY="0.5",},
ly_equip_1={classname="Panel",name="ly_equip_1",parName="ly_content",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="148",width="108",x="5",y="288",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="560",anchorPointX="0",anchorPointY="0",},
ly_equip_2={classname="Panel",name="ly_equip_2",parName="ly_content",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="148",width="108",x="106",y="223",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="561",anchorPointX="0",anchorPointY="0",},
ly_equip_3={classname="Panel",name="ly_equip_3",parName="ly_content",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="148",width="108",x="208",y="168",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="562",anchorPointX="0",anchorPointY="0",},
ly_equip_4={classname="Panel",name="ly_equip_4",parName="ly_content",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="148",width="108",x="325",y="168",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="563",anchorPointX="0",anchorPointY="0",},
ly_equip_5={classname="Panel",name="ly_equip_5",parName="ly_content",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="148",width="108",x="427",y="223",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="564",anchorPointX="0",anchorPointY="0",},
ly_equip_6={classname="Panel",name="ly_equip_6",parName="ly_content",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="148",width="104",x="529",y="288",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="565",anchorPointX="0",anchorPointY="0",},
img_shuxing={classname="ImageView",name="img_shuxing",parName="ly_content",ZOrder="2",fileName="ui/big_img_sep/v1_img_shuxingtu.png",scale9Enable="false",scale9Height="111",scale9Width="129",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="111",width="129",x="231",y="92",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="566",anchorPointX="0.5",anchorPointY="0.5",},
lb_l_1={classname="CustomLabel",name="lb_l_1",parName="ly_content",ZOrder="2",colorB="218",colorG="199",colorR="198",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="资质",fontName="微软雅黑",fontSize="20",height="27",width="40",x="29",y="165",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="567",anchorPointX="0",anchorPointY="0.5",},
lb_l_2={classname="CustomLabel",name="lb_l_2",parName="ly_content",ZOrder="2",colorB="218",colorG="199",colorR="198",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="攻",fontName="微软雅黑",fontSize="20",height="27",width="20",x="30",y="126",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="568",anchorPointX="0",anchorPointY="0.5",},
lb_l_3={classname="CustomLabel",name="lb_l_3",parName="ly_content",ZOrder="2",colorB="218",colorG="199",colorR="198",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="防",fontName="微软雅黑",fontSize="20",height="27",width="20",x="30",y="87",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="569",anchorPointX="0",anchorPointY="0.5",},
lb_l_4={classname="CustomLabel",name="lb_l_4",parName="ly_content",ZOrder="2",colorB="218",colorG="199",colorR="198",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="兵",fontName="微软雅黑",fontSize="20",height="27",width="20",x="30",y="48",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="570",anchorPointX="0",anchorPointY="0.5",},
lb_r_1={classname="CustomLabel",name="lb_r_1",parName="ly_content",ZOrder="2",colorB="218",colorG="199",colorR="198",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="等级",fontName="微软雅黑",fontSize="20",height="27",width="40",x="347",y="165",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="571",anchorPointX="0",anchorPointY="0.5",},
ly_bar_1={classname="Panel",name="ly_bar_1",parName="ly_content",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v1_bar_b2.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="41",capInsetsY="6",height="12",width="112",x="398",y="159",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="572",anchorPointX="0",anchorPointY="0",},
lb_hero_name={classname="CustomLabel",name="lb_hero_name",parName="ly_content",ZOrder="12",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="嬴政",fontName="微软雅黑",fontSize="20",height="27",width="40",x="320",y="743",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="574",anchorPointX="0.5",anchorPointY="0.5",},
Image_60={classname="ImageView",name="Image_60",parName="ly_content",ZOrder="11",fileName="#v1_img_mingzidi.png",scale9Enable="false",scale9Height="49",scale9Width="186",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="49",width="186",x="320",y="741",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="575",anchorPointX="0.5",anchorPointY="0.5",},
lb_at={classname="CustomLabel",name="lb_at",parName="ly_content",ZOrder="5",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="攻",fontName="微软雅黑",fontSize="20",height="27",width="20",x="230",y="157",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="576",anchorPointX="0.5",anchorPointY="0.5",},
lb_de={classname="CustomLabel",name="lb_de",parName="ly_content",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="防",fontName="微软雅黑",fontSize="20",height="27",width="20",x="158",y="35",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="577",anchorPointX="0.5",anchorPointY="0.5",},
lb_so={classname="CustomLabel",name="lb_so",parName="ly_content",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="兵",fontName="微软雅黑",fontSize="20",height="27",width="20",x="302",y="35",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="578",anchorPointX="0.5",anchorPointY="0.5",},
lb_m_1={classname="CustomLabel",name="lb_m_1",parName="ly_content",ZOrder="3",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="999",fontName="微软雅黑",fontSize="20",height="27",width="36",x="95",y="126",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="579",anchorPointX="0",anchorPointY="0.5",},
lb_m_2={classname="CustomLabel",name="lb_m_2",parName="ly_content",ZOrder="3",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="999",fontName="微软雅黑",fontSize="20",height="27",width="36",x="95",y="87",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="580",anchorPointX="0",anchorPointY="0.5",},
lb_m_3={classname="CustomLabel",name="lb_m_3",parName="ly_content",ZOrder="3",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="999",fontName="微软雅黑",fontSize="20",height="27",width="36",x="95",y="48",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="581",anchorPointX="0",anchorPointY="0.5",},
ly_att_1={classname="Panel",name="ly_att_1",parName="ly_content",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="170",x="347",y="112",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="582",anchorPointX="0",anchorPointY="0",},
ly_att_2={classname="Panel",name="ly_att_2",parName="ly_content",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="170",x="347",y="73",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="583",anchorPointX="0",anchorPointY="0",},
ly_att_3={classname="Panel",name="ly_att_3",parName="ly_content",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="170",x="347",y="34",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="584",anchorPointX="0",anchorPointY="0",},
}

return tTable