local tTable = {}


tTable["index_1"] = {
default={classname="Panel",name="default@fill_layout",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1060",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
view={classname="Panel",name="view@fill_layout",parName="default",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1060",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_top={classname="Panel",name="lay_top",parName="view",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="65",capInsetsY="65",height="270",width="640",x="0",y="790",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8",anchorPointX="0",anchorPointY="0",},
lay_space={classname="Panel",name="lay_space",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="10",width="640",x="0",y="780",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="68",anchorPointX="0",anchorPointY="0",},
lay_content={classname="Panel",name="lay_content@fill_layout",parName="view",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="780",width="600",x="20",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="28",anchorPointX="0",anchorPointY="0",},
lay_bottom={classname="Panel",name="lay_bottom",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="20",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="69",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lay_top_inner={classname="Panel",name="lay_top_inner",parName="lay_top",childCount="7",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="27",capInsetsY="127",height="254",width="584",x="28",y="6",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9",anchorPointX="0",anchorPointY="0",},
lay_banner_bg={classname="Panel",name="lay_banner_bg",parName="lay_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="270",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="57",anchorPointX="0",anchorPointY="0",},
lay_progress={classname="Panel",name="lay_progress",parName="lay_content",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="120",width="600",x="0",y="660",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="70",anchorPointX="0",anchorPointY="0",},
lay_items={classname="Panel",name="lay_items@fill_layout",parName="lay_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="660",width="600",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="33",anchorPointX="0",anchorPointY="0",},
}
tTable["index_5"] = {
lay_time={classname="Panel",name="lay_time",parName="lay_top_inner",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="28",width="484",x="0",y="224",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="10",anchorPointX="0",anchorPointY="0",},
lay_country1={classname="Panel",name="lay_country1",parName="lay_top_inner",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="350",x="13",y="174",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="16",anchorPointX="0",anchorPointY="0",},
lay_country2={classname="Panel",name="lay_country2",parName="lay_top_inner",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="350",x="13",y="133",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="17",anchorPointX="0",anchorPointY="0",},
lay_country3={classname="Panel",name="lay_country3",parName="lay_top_inner",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="350",x="13",y="91",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="18",anchorPointX="0",anchorPointY="0",},
lay_desc={classname="Panel",name="lay_desc",parName="lay_top_inner",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_black50.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="10",height="92",width="426",x="1",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="19",anchorPointX="0",anchorPointY="0",},
txt_desc={classname="Label",name="txt_desc",parName="lay_top_inner",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="90",areaWidth="426",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="90",width="426",x="0",y="88",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="40",anchorPointX="0",anchorPointY="1",},
lay_gift={classname="Panel",name="lay_gift",parName="lay_top_inner",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen2.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="59",capInsetsY="18",height="202",width="136",x="442",y="13",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="20",anchorPointX="0",anchorPointY="0",},
lay_line2={classname="Panel",name="lay_line2",parName="lay_progress",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_line_blue1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="1",height="2",width="488",x="54",y="9",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="32",anchorPointX="0",anchorPointY="0",},
lay_bar={classname="Panel",name="lay_bar",parName="lay_progress",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v1_bar_b3.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="18",width="570",x="12",y="64",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="29",anchorPointX="0",anchorPointY="0",},
}
tTable["index_6"] = {
img_effect={classname="CustomImageView",name="img_effect",parName="lay_gift",ZOrder="2",fileName="#v1_img_jianbian3.png",scale9Enable="false",scale9Height="39",scale9Width="108",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="39",width="108",x="70",y="181",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="22",anchorPointX="0.5",anchorPointY="0.5",},
img_effect2={classname="CustomImageView",name="img_effect2",parName="lay_gift",ZOrder="3",fileName="#v1_img_jianbian3.png",scale9Enable="false",scale9Height="39",scale9Width="108",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="39",width="108",x="70",y="21",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="23",anchorPointX="0.5",anchorPointY="0.5",},
lay_icon={classname="Panel",name="lay_icon",parName="lay_gift",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="86",width="86",x="27",y="104",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="24",anchorPointX="0",anchorPointY="0",},
lay_btn_recharge={classname="Panel",name="lay_btn_recharge",parName="lay_gift",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="110",x="15",y="18",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="25",anchorPointX="0",anchorPointY="0",},
txt_gift_name={classname="CustomLabel",name="txt_gift_name",parName="lay_gift",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="70",y="86",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="26",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable