local tTable = {}

tTable["texturesPng"] = {"ui/p1_commmon1_sep.plist","ui/p1_commonse2.plist","ui/p1_commonse1.plist","ui/bg_base/v2_bg_tiejiangpu.jpg","ui/p2_commonse1.plist","ui/p2_commmon1_sep.plist","ui/p1_commmon4_sep.plist"}
tTable["index_1"] = {
default={classname="Panel",name="default@fill_layout",parName="root",childCount="7",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1060",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_top={classname="Panel",name="lay_top",parName="default",childCount="2",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="192",width="640",x="0",y="821",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="399",anchorPointX="0",anchorPointY="0",},
lay_banner={classname="Panel",name="lay_banner",parName="default",ZOrder="6",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="25",capInsetsY="23",height="50",width="640",x="0",y="771",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9",anchorPointX="0",anchorPointY="0",},
lay_tab_view={classname="Panel",name="lay_tab_view",parName="default",childCount="3",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="62",width="640",x="0",y="709",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="11",anchorPointX="0",anchorPointY="0",},
img_line_blue={classname="ImageView",name="img_line_blue",parName="default",ZOrder="10",fileName="#v1_line_blue1.png",scale9Enable="true",scale9Height="2",scale9Width="640",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="0",height="2",width="640",x="320",y="709",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="214",anchorPointX="0.5",anchorPointY="0.5",},
lay_content={classname="Panel",name="lay_content",parName="default",childCount="16",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="558",width="640",x="0",y="150",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="12",anchorPointX="0",anchorPointY="0",},
lay_span={classname="Panel",name="lay_span@fill_layout",parName="default",ZOrder="99999",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="0.01",width="640",x="0",y="150",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="556",anchorPointX="0",anchorPointY="0",},
lay_bottom_container={classname="Panel",name="lay_bottom_container",parName="default",childCount="1",ZOrder="6",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="150",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_banner_bg={classname="Panel",name="lay_banner_bg",parName="lay_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="192",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="336",anchorPointX="0",anchorPointY="0",},
lay_top_tip={classname="Panel",name="lay_top_tip",parName="lay_top",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_black50.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="10",height="52",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="209",anchorPointX="0",anchorPointY="0",},
lay_tab={classname="Panel",name="lay_tab",parName="lay_tab_view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="56",width="520",x="60",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="20",anchorPointX="0",anchorPointY="0",},
img_left_arrow={classname="CustomImageView",name="img_left_arrow",parName="lay_tab_view",ZOrder="0",fileName="#v1_btn_jiantou.png",scale9Enable="false",scale9Height="44",scale9Width="36",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="44",width="36",x="30",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="21",anchorPointX="0.5",anchorPointY="0.5",},
img_right_arrow={classname="CustomImageView",name="img_right_arrow",parName="lay_tab_view",ZOrder="0",fileName="#v1_btn_jiantou.png",scale9Enable="false",scale9Height="44",scale9Width="36",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="44",width="36",x="610",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="180",tag="22",anchorPointX="0.5",anchorPointY="0.5",},
img_bg={classname="ImageView",name="img_bg",parName="lay_content",ZOrder="0",fileName="ui/bg_base/v2_bg_tiejiangpu.jpg",scale9Enable="false",scale9Height="648",scale9Width="640",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="648",width="640",x="0",y="0",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="208",anchorPointX="0",anchorPointY="0",},
lay_equip1={classname="Panel",name="lay_equip1",parName="lay_content",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="86",width="86",x="35",y="460",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="13",anchorPointX="0",anchorPointY="0",},
lay_equip2={classname="Panel",name="lay_equip2",parName="lay_content",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="86",width="86",x="132",y="460",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="14",anchorPointX="0",anchorPointY="0",},
lay_equip3={classname="Panel",name="lay_equip3",parName="lay_content",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="86",width="86",x="229",y="460",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="15",anchorPointX="0",anchorPointY="0",},
lay_equip4={classname="Panel",name="lay_equip4",parName="lay_content",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="86",width="86",x="326",y="460",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="16",anchorPointX="0",anchorPointY="0",},
lay_equip5={classname="Panel",name="lay_equip5",parName="lay_content",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="86",width="86",x="423",y="460",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="17",anchorPointX="0",anchorPointY="0",},
lay_equip6={classname="Panel",name="lay_equip6",parName="lay_content",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="86",width="86",x="520",y="460",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="18",anchorPointX="0",anchorPointY="0",},
lay_curr_equip={classname="Panel",name="lay_curr_equip",parName="lay_content",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_hechengmingzidi.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="15",capInsetsY="15",height="40",width="212",x="214",y="185",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="19",anchorPointX="0",anchorPointY="0",},
txt_content_tip={classname="CustomLabel",name="txt_content_tip",parName="lay_content",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="320",y="99",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="27",anchorPointX="0.5",anchorPointY="0.5",},
lay_btn_bag={classname="Panel",name="lay_btn_bag",parName="lay_content",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="60",width="150",x="244",y="70",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="39",anchorPointX="0",anchorPointY="0",},
lay_autorefinelb={classname="Panel",name="lay_autorefinelb",parName="lay_content",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_jinduyanjiudi.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="138",capInsetsY="21",height="70",width="640",x="0",y="378",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="96",anchorPointX="0",anchorPointY="0",},
img_left={classname="ImageView",name="img_left",parName="lay_content",ZOrder="1",fileName="#v1_btn_left.png",scale9Enable="false",scale9Height="21",scale9Width="42",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="21",width="42",x="15",y="502",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="90",tag="204",anchorPointX="0.5",anchorPointY="0.5",},
img_right={classname="ImageView",name="img_right",parName="lay_content",ZOrder="1",fileName="#v1_btn_left.png",scale9Enable="false",scale9Height="21",scale9Width="42",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="21",width="42",x="625",y="502",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="-90",tag="206",anchorPointX="0.5",anchorPointY="0.5",},
img_curequip={classname="ImageView",name="img_curequip",parName="lay_content",ZOrder="1",fileName="#v1_btn_tianjia.png",scale9Enable="false",scale9Height="108",scale9Width="108",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="108",width="108",x="320",y="305",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="211",anchorPointX="0.5",anchorPointY="0.5",},
lb_not_wear={classname="Label",name="lb_not_wear",parName="lay_content",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="未穿戴装备",fontName="微软雅黑",fontSize="20",height="27",width="100",x="320",y="305",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="313",anchorPointX="0.5",anchorPointY="0.5",},
lay_bag={classname="Panel",name="lay_bag",parName="lay_content",ZOrder="20",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="90",width="571",x="35",y="457",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="383",anchorPointX="0",anchorPointY="0",},
lay_bottom={classname="Panel",name="lay_bottom",parName="lay_bottom_container",childCount="5",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="150",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="26",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lb_toptip={classname="Label",name="lb_toptip",parName="lay_top_tip",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="320",y="26",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="210",anchorPointX="0.5",anchorPointY="0.5",},
lb_cureq_info={classname="Label",name="lb_cureq_info",parName="lay_curr_equip",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="106",y="20",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="213",anchorPointX="0.5",anchorPointY="0.5",},
img_add={classname="CustomImageView",name="img_add",parName="lay_bottom",ZOrder="0",fileName="#v1_btn_tianjia.png",scale9Enable="false",scale9Height="108",scale9Width="108",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="108",width="108",x="437",y="273",visible="true",touchAble="false",flipX="false",scaleX="0.6999999",scaleY="0.6999999",opacity="255",rotation="0",tag="31",anchorPointX="0.5",anchorPointY="0.5",},
txt_cd={classname="CustomLabel",name="txt_cd",parName="lay_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="119",y="130",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="34",anchorPointX="0.5",anchorPointY="0.5",},
lay_btn_refine={classname="Panel",name="lay_btn_refine",parName="lay_bottom",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="40",y="28",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="35",anchorPointX="0",anchorPointY="0",},
txt_bottom_tip={classname="CustomLabel",name="txt_bottom_tip",parName="lay_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="618",y="133",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="36",anchorPointX="1",anchorPointY="0.5",},
lay_btn2={classname="Panel",name="lay_btn2",parName="lay_bottom",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="445",y="28",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="37",anchorPointX="0",anchorPointY="0",},
}

return tTable