local tTable = {}


tTable["index_1"] = {
root={classname="Panel",name="root@fill_layout",parName="root",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1066",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="170",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
ly_tab={classname="Panel",name="ly_tab@fill_layout_height",parName="root",childCount="3",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_huodongbiaoqiandi.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="19",capInsetsY="19",height="1012",width="122",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="336",anchorPointX="0",anchorPointY="0",},
ly_content={classname="Panel",name="ly_content@fill_layout_height",parName="root",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="1012",width="522",x="118",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="340",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
img_top={classname="ImageView",name="img_top",parName="ly_tab",ZOrder="0",fileName="#v2_img_huodongshangxiafanjiantou.png",scale9Enable="false",scale9Height="24",scale9Width="116",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="24",width="116",x="0",y="988",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="338",anchorPointX="0",anchorPointY="0",},
ly_tab_list={classname="Panel",name="ly_tab_list@fill_layout",parName="ly_tab",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="19",capInsetsY="19",height="958",width="128",x="0",y="29",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="337",anchorPointX="0",anchorPointY="0",},
img_bot={classname="ImageView",name="img_bot",parName="ly_tab",ZOrder="0",fileName="#v2_img_huodongshangxiafanjiantou.png",scale9Enable="false",scale9Height="24",scale9Width="116",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="24",width="116",x="0",y="0",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="362",anchorPointX="0",anchorPointY="0",},
lay_top={classname="Panel",name="lay_top",parName="ly_content",childCount="5",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="261",capInsetsY="230",height="370",width="522",x="0",y="641",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="342",anchorPointX="0",anchorPointY="0",},
lay_bot={classname="Panel",name="lay_bot@fill_layout",parName="ly_content",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="588",width="522",x="0",y="54",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="341",anchorPointX="0",anchorPointY="0",},
lay_bottom={classname="Panel",name="lay_bottom",parName="ly_content",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="54",width="522",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="421",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lb_tip_2={classname="Label",name="lb_tip_2",parName="lay_top",ZOrder="5",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="当前等级：",fontName="微软雅黑",fontSize="20",height="27",width="100",x="27",y="296",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="175",anchorPointX="0",anchorPointY="0.5",},
lb_tip_1={classname="Label",name="lb_tip_1",parName="lay_top",ZOrder="5",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="我当前排名：",fontName="微软雅黑",fontSize="20",height="27",width="120",x="27",y="326",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="173",anchorPointX="0",anchorPointY="0.5",},
lb_tip_3={classname="Label",name="lb_tip_3",parName="lay_top",ZOrder="5",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="当前战斗力：",fontName="微软雅黑",fontSize="20",height="27",width="120",x="172",y="296",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="176",anchorPointX="0",anchorPointY="0.5",},
lay_btn_share={classname="Panel",name="lay_btn_share",parName="lay_top",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="368",y="280",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="177",anchorPointX="0",anchorPointY="0",},
lay_banner_bg={classname="Panel",name="lay_banner_bg",parName="lay_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="370",width="522",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="382",anchorPointX="0",anchorPointY="0",},
lay_cont={classname="Panel",name="lay_cont@fill_layout",parName="lay_bot",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="588",width="522",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="345",anchorPointX="0",anchorPointY="0",},
lb_tip_4={classname="Label",name="lb_tip_4",parName="lay_bottom",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="256",y="32",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="316",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable