local tTable = {}


tTable["index_1"] = {
root={classname="Panel",name="root@fill_layout",parName="root",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1060",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="3",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_top={classname="Panel",name="lay_top",parName="root",childCount="7",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="390",width="640",x="0",y="670",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7028",anchorPointX="0",anchorPointY="0",},
lay_cont={classname="Panel",name="lay_cont@fill_layout",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="585",width="640",x="0",y="82",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6472",anchorPointX="0",anchorPointY="0",},
lay_bottom={classname="Panel",name="lay_bottom",parName="root",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="82",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7213",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_banner={classname="Panel",name="lay_banner",parName="lay_top",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="ui/banner_ui/v2_img_wg.jpg",height="265",width="640",x="0",y="133",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7206",anchorPointX="0",anchorPointY="0",},
lay_icon_1={classname="Panel",name="lay_icon_1",parName="lay_top",childCount="2",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="86",width="86",x="277",y="240",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6474",anchorPointX="0",anchorPointY="0",},
lay_icon_2={classname="Panel",name="lay_icon_2",parName="lay_top",childCount="2",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="86",width="86",x="96",y="230",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6475",anchorPointX="0",anchorPointY="0",},
lay_icon_3={classname="Panel",name="lay_icon_3",parName="lay_top",childCount="2",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="86",width="86",x="457",y="230",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6476",anchorPointX="0",anchorPointY="0",},
lay_shengzhi={classname="Panel",name="lay_shengzhi",parName="lay_top",childCount="4",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="ui/big_img/v2_img_shengzi.png",height="199",width="578",x="27",y="2",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6648",anchorPointX="0",anchorPointY="0",},
img_line_l={classname="ImageView",name="img_line_l",parName="lay_top",ZOrder="4",fileName="#v2_btn_zjm_s.png",scale9Enable="false",scale9Height="10",scale9Width="320",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="10",width="320",x="1",y="-7",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="-1",opacity="255",rotation="0",tag="7205",anchorPointX="0",anchorPointY="0.5",},
img_line_r={classname="ImageView",name="img_line_r",parName="lay_top",ZOrder="4",fileName="#v2_btn_zjm_s.png",scale9Enable="false",scale9Height="10",scale9Width="320",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="10",width="320",x="640",y="-7",visible="true",touchAble="false",flipX="false",scaleX="-1",scaleY="-1",opacity="255",rotation="0",tag="7208",anchorPointX="0",anchorPointY="0.5",},
lay_main={classname="Panel",name="lay_main",parName="lay_cont",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="585",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7214",anchorPointX="0",anchorPointY="0",},
lay_par_1={classname="Panel",name="lay_par_1",parName="lay_bottom",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="80",width="120",x="179",y="6",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6653",anchorPointX="0",anchorPointY="0",},
lay_par_2={classname="Panel",name="lay_par_2",parName="lay_bottom",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="80",width="120",x="339",y="6",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6655",anchorPointX="0",anchorPointY="0",},
img_line_l_b={classname="ImageView",name="img_line_l_b",parName="lay_bottom",ZOrder="0",fileName="#v2_btn_zjm_s.png",scale9Enable="false",scale9Height="10",scale9Width="320",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="10",width="320",x="0",y="82",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7210",anchorPointX="0",anchorPointY="0.5",},
img_line_r_b={classname="ImageView",name="img_line_r_b",parName="lay_bottom",ZOrder="0",fileName="#v2_btn_zjm_s.png",scale9Enable="false",scale9Height="10",scale9Width="320",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="10",width="320",x="640",y="82",visible="true",touchAble="false",flipX="false",scaleX="-1",scaleY="1",opacity="255",rotation="0",tag="7212",anchorPointX="0",anchorPointY="0.5",},
}
tTable["index_4"] = {
img_official_1={classname="ImageView",name="img_official_1",parName="lay_icon_1",ZOrder="10",fileName="#v1_img_guowang.png",scale9Enable="false",scale9Height="96",scale9Width="96",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="96",width="96",x="43",y="110",visible="true",touchAble="false",flipX="false",scaleX="0.9",scaleY="0.9",opacity="255",rotation="0",tag="6831",anchorPointX="0.5",anchorPointY="0.5",},
lb_official_1={classname="Label",name="lb_official_1",parName="lay_icon_1",ZOrder="10",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="42",y="-15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6835",anchorPointX="0.5",anchorPointY="0.5",},
img_official_2={classname="ImageView",name="img_official_2",parName="lay_icon_2",ZOrder="10",fileName="#v1_img_chengxiang.png",scale9Enable="false",scale9Height="96",scale9Width="96",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="96",width="96",x="42",y="110",visible="true",touchAble="false",flipX="false",scaleX="0.9",scaleY="0.9",opacity="255",rotation="0",tag="6832",anchorPointX="0.5",anchorPointY="0.5",},
lb_official_2={classname="Label",name="lb_official_2",parName="lay_icon_2",ZOrder="10",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="42",y="-15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6837",anchorPointX="0.5",anchorPointY="0.5",},
img_official_3={classname="ImageView",name="img_official_3",parName="lay_icon_3",ZOrder="10",fileName="#v1_img_taiwei.png",scale9Enable="false",scale9Height="96",scale9Width="96",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="96",width="96",x="43",y="110",visible="true",touchAble="false",flipX="false",scaleX="0.9",scaleY="0.9",opacity="255",rotation="0",tag="6833",anchorPointX="0.5",anchorPointY="0.5",},
lb_official_3={classname="Label",name="lb_official_3",parName="lay_icon_3",ZOrder="10",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="43",y="-15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6842",anchorPointX="0.5",anchorPointY="0.5",},
lb_cont={classname="Label",name="lb_cont",parName="lay_shengzhi",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="63",areaWidth="470",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="63",width="470",x="55",y="140",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6650",anchorPointX="0",anchorPointY="1",},
lb_kingname={classname="Label",name="lb_kingname",parName="lay_shengzhi",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="16",height="21",width="77",x="435",y="60",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6651",anchorPointX="1",anchorPointY="0.5",},
lb_time={classname="Label",name="lb_time",parName="lay_shengzhi",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="16",height="21",width="77",x="524",y="60",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6652",anchorPointX="1",anchorPointY="0.5",},
lb_tip={classname="Label",name="lb_tip",parName="lay_shengzhi",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="16",height="21",width="77",x="56",y="60",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7408",anchorPointX="0",anchorPointY="0.5",},
img_guanyaun={classname="ImageView",name="img_guanyaun",parName="lay_par_1",ZOrder="0",fileName="#v2_img_guojia_guanyuan.png",scale9Enable="false",scale9Height="84",scale9Width="64",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="84",width="64",x="60",y="40",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6829",anchorPointX="0.5",anchorPointY="0.5",},
lay_official_red={classname="Panel",name="lay_official_red",parName="lay_par_1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="20",width="20",x="63",y="49",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7596",anchorPointX="0",anchorPointY="0",},
img_rizhi={classname="ImageView",name="img_rizhi",parName="lay_par_2",ZOrder="0",fileName="#v1_img_guojia_rizhi.png",scale9Enable="false",scale9Height="71",scale9Width="76",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="71",width="76",x="60",y="35",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6830",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable