local tTable = {}


tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1000",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="14",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_bg={classname="Panel",name="lay_bg",parName="default",childCount="12",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="ui/v2_bg_shouci.jpg",height="1000",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="17",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
img_btn={classname="ImageView",name="img_btn",parName="lay_bg",ZOrder="2",fileName="#v2_btn_qianwang.png",scale9Enable="false",scale9Height="63",scale9Width="250",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="63",width="250",x="320",y="87",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="19",anchorPointX="0.5",anchorPointY="0.5",},
txt_tip={classname="Label",name="txt_tip",parName="lay_bg",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="320",y="158",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="18",anchorPointX="0.5",anchorPointY="0.5",},
lay_reward={classname="Panel",name="lay_reward",parName="lay_bg",childCount="1",ZOrder="4",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="96",width="96",x="517",y="883",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="218",anchorPointX="0",anchorPointY="0",},
lay_slot1={classname="Panel",name="lay_slot1",parName="lay_bg",childCount="1",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="106",width="106",x="42",y="248",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="21",anchorPointX="0",anchorPointY="0",},
lay_slot2={classname="Panel",name="lay_slot2",parName="lay_bg",childCount="1",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="106",width="106",x="192",y="248",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="23",anchorPointX="0",anchorPointY="0",},
lay_slot3={classname="Panel",name="lay_slot3",parName="lay_bg",childCount="1",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="106",width="106",x="341",y="248",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="24",anchorPointX="0",anchorPointY="0",},
lay_slot4={classname="Panel",name="lay_slot4",parName="lay_bg",childCount="1",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="106",width="106",x="491",y="248",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="25",anchorPointX="0",anchorPointY="0",},
lb_item_name1={classname="Label",name="lb_item_name1",parName="lay_bg",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="95",y="231",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="33",anchorPointX="0.5",anchorPointY="0.5",},
lb_item_name2={classname="Label",name="lb_item_name2",parName="lay_bg",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="245",y="231",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="35",anchorPointX="0.5",anchorPointY="0.5",},
lb_item_name3={classname="Label",name="lb_item_name3",parName="lay_bg",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="394",y="231",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="36",anchorPointX="0.5",anchorPointY="0.5",},
lb_item_name4={classname="Label",name="lb_item_name4",parName="lay_bg",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="544",y="231",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="37",anchorPointX="0.5",anchorPointY="0.5",},
img_state={classname="ImageView",name="img_state",parName="lay_bg",ZOrder="0",fileName="#v2_fonts_yilingqu.png",scale9Enable="false",scale9Height="46",scale9Width="140",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="46",width="140",x="320",y="87",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="395",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_4"] = {
img_reward={classname="ImageView",name="img_reward",parName="lay_reward",ZOrder="3",fileName="#v1_img_guojia_renwubaoxiang1.png",scale9Enable="false",scale9Height="96",scale9Width="96",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="96",width="96",x="47",y="49",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="20",anchorPointX="0.5",anchorPointY="0.5",},
lay_num_bg1={classname="Panel",name="lay_num_bg1",parName="lay_slot1",childCount="1",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_black50.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="10",height="24",width="40",x="66",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="28",anchorPointX="0",anchorPointY="0",},
lay_num_bg2={classname="Panel",name="lay_num_bg2",parName="lay_slot2",childCount="1",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_black50.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="10",height="24",width="40",x="66",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="30",anchorPointX="0",anchorPointY="0",},
lay_num_bg3={classname="Panel",name="lay_num_bg3",parName="lay_slot3",childCount="1",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_black50.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="10",height="24",width="40",x="66",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="31",anchorPointX="0",anchorPointY="0",},
lay_num_bg4={classname="Panel",name="lay_num_bg4",parName="lay_slot4",childCount="1",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_black50.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="10",height="24",width="40",x="66",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="32",anchorPointX="0",anchorPointY="0",},
}
tTable["index_5"] = {
lb_num1={classname="Label",name="lb_num1",parName="lay_num_bg1",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="20",fontName="微软雅黑",fontSize="18",height="24",width="22",x="20",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="38",anchorPointX="0.5",anchorPointY="0.5",},
lb_num2={classname="Label",name="lb_num2",parName="lay_num_bg2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="20",fontName="微软雅黑",fontSize="18",height="24",width="22",x="20",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="40",anchorPointX="0.5",anchorPointY="0.5",},
lb_num3={classname="Label",name="lb_num3",parName="lay_num_bg3",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="20",fontName="微软雅黑",fontSize="18",height="24",width="22",x="20",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="41",anchorPointX="0.5",anchorPointY="0.5",},
lb_num4={classname="Label",name="lb_num4",parName="lay_num_bg4",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="20",fontName="微软雅黑",fontSize="18",height="24",width="22",x="20",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="42",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable