local tTable = {}

tTable["texturesPng"] = {"ui/language/cn/p2_font1.plist","ui/p2_commmon1_sep.plist","ui/p2_commonse1.plist"}
tTable["index_1"] = {
home_task_layer={classname="Panel",name="home_task_layer",parName="root",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="80",width="590",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="164",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
root={classname="Panel",name="root",parName="home_task_layer",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="80",width="590",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="3867",anchorPointX="0",anchorPointY="0",},
lay_red={classname="Panel",name="lay_red",parName="home_task_layer",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="20",width="20",x="82",y="57",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4029",anchorPointX="0",anchorPointY="0",},
lay_blue={classname="Panel",name="lay_blue",parName="home_task_layer",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v2_img_hongdiantishi02.png",height="20",width="20",x="82",y="57",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4191",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
img_btn_task={classname="ImageView",name="img_btn_task",parName="root",ZOrder="2",fileName="#v2_btn_zjm_zxrw.png",scale9Enable="false",scale9Height="88",scale9Width="82",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="88",width="82",x="61",y="40",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="479",anchorPointX="0.5",anchorPointY="0.5",},
lay_right={classname="Panel",name="lay_right",parName="root",childCount="3",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="162",capInsetsY="28",height="56",width="323",x="152",y="12",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="167",anchorPointX="0",anchorPointY="0",},
img_task_type={classname="ImageView",name="img_task_type",parName="root",ZOrder="10",fileName="#v2_btn__zjm_zhixian.png",scale9Enable="false",scale9Height="66",scale9Width="66",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="66",width="66",x="138",y="40",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="3951",anchorPointX="0.5",anchorPointY="0.5",},
img_task_type_tx={classname="ImageView",name="img_task_type_tx",parName="root",ZOrder="11",fileName="#v2_btn__zjm_zhixian.png",scale9Enable="false",scale9Height="66",scale9Width="66",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="66",width="66",x="138",y="40",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4109",anchorPointX="0.5",anchorPointY="0.5",},
lay_click={classname="Panel",name="lay_click",parName="root",ZOrder="50",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="80",width="370",x="106",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4270",anchorPointX="0",anchorPointY="0",},
lb_blue_num={classname="Label",name="lb_blue_num",parName="lay_blue",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="10",y="10",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4192",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_4"] = {
img_rwxq_bot={classname="ImageView",name="img_rwxq_bot",parName="lay_right",ZOrder="1",fileName="#v2_img_zjm_rwxqsrk.png",scale9Enable="false",scale9Height="56",scale9Width="323",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="56",width="323",x="0",y="28",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4108",anchorPointX="0",anchorPointY="0.5",},
img_rwxq_top={classname="ImageView",name="img_rwxq_top",parName="lay_right",ZOrder="2",fileName="#v2_img_zjm_rwxqsrk.png",scale9Enable="false",scale9Height="56",scale9Width="323",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="56",width="323",x="0",y="28",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4107",anchorPointX="0",anchorPointY="0.5",},
lb_taskname={classname="Label",name="lb_taskname",parName="lay_right",ZOrder="100",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="任务名称",fontName="微软雅黑",fontSize="20",height="27",width="80",x="25",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="168",anchorPointX="0",anchorPointY="0.5",},
}

return tTable