local tTable = {}

tTable["texturesPng"] = {"ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commonse1.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","icon/p1_icon_ui.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","ui/bg_world/v1_img_shijieditu.jpg","ui/p1_commmon1_sep.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","ui/p1_button1.plist","ui/p1_commonse1.plist","ui/bar/v1_bar_b1.png","ui/p1_commonse1.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commonse1.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","icon/p1_icon_ui.plist","ui/p1_commonse1.plist","icon/p1_icon_ui.plist","ui/p1_commonse1.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commmon1_sep.plist","icon/p1_icon_font.plist","ui/language/cn/p1_font1.plist","icon/p1_icon_ui.plist","ui/p1_commonse1.plist","ui/p1_button1.plist","icon/p1_icon_font.plist","ui/p1_commmon1_sep.plist","ui/language/cn/p1_font1.plist","ui/p1_commonse1.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist"}
tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="540",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="5159",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
txt_next={classname="CustomLabel",name="txt_next",parName="default",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="点击显示下面10行",fontName="微软雅黑",fontSize="20",height="27",width="164",x="277",y="21",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="5160",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable