local tTable = {}


tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="50",height="180",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="131",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
view={classname="Panel",name="view",parName="default",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="50",height="180",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="132",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
txt_time={classname="CustomLabel",name="txt_time",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="320",y="155",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="134",anchorPointX="0.5",anchorPointY="0.5",},
lay_left={classname="Panel",name="lay_left",parName="view",childCount="10",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="180",width="320",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1873",anchorPointX="0",anchorPointY="0",},
lay_line={classname="Panel",name="lay_line",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_line_blue1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="1",height="1",width="540",x="15",y="130",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="136",anchorPointX="0",anchorPointY="0",},
lay_right={classname="Panel",name="lay_right",parName="view",childCount="10",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="180",width="320",x="321",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1874",anchorPointX="0",anchorPointY="0",},
lay_line_bottom={classname="Panel",name="lay_line_bottom",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_line_blue1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="1",height="2",width="620",x="10",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="3096",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
img_atk_result={classname="CustomImageView",name="img_atk_result",parName="lay_left",ZOrder="0",fileName="#v1_img_sheng_yx.png",scale9Enable="false",scale9Height="38",scale9Width="34",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="38",width="34",x="70",y="156",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="133",anchorPointX="0.5",anchorPointY="0.5",},
txt_atk_country={classname="CustomLabel",name="txt_atk_country",parName="lay_left",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="114",y="111",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="137",anchorPointX="0",anchorPointY="0.5",},
lay_atk_icon={classname="Panel",name="lay_atk_icon",parName="lay_left",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="80",width="80",x="14",y="38",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="138",anchorPointX="0",anchorPointY="0",},
txt_atk_name={classname="CustomLabel",name="txt_atk_name",parName="lay_left",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="213",y="111",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="139",anchorPointX="0",anchorPointY="0.5",},
txt_atk_power_title={classname="CustomLabel",name="txt_atk_power_title",parName="lay_left",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="战功：",fontName="微软雅黑",fontSize="18",height="24",width="54",x="114",y="85",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="140",anchorPointX="0",anchorPointY="0.5",},
txt_atk_power={classname="CustomLabel",name="txt_atk_power",parName="lay_left",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="999",fontName="微软雅黑",fontSize="18",height="24",width="33",x="173",y="85",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="141",anchorPointX="0",anchorPointY="0.5",},
txt_atk_troops_title={classname="CustomLabel",name="txt_atk_troops_title",parName="lay_left",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="兵力：",fontName="微软雅黑",fontSize="18",height="24",width="54",x="114",y="62",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="142",anchorPointX="0",anchorPointY="0.5",},
txt_atk_troops={classname="CustomLabel",name="txt_atk_troops",parName="lay_left",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="999",fontName="微软雅黑",fontSize="18",height="24",width="33",x="173",y="62",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="143",anchorPointX="0",anchorPointY="0.5",},
txt_atk_lose_title={classname="CustomLabel",name="txt_atk_lose_title",parName="lay_left",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="损兵：",fontName="微软雅黑",fontSize="18",height="24",width="54",x="114",y="37",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="144",anchorPointX="0",anchorPointY="0.5",},
txt_atk_lose={classname="CustomLabel",name="txt_atk_lose",parName="lay_left",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="999",fontName="微软雅黑",fontSize="18",height="24",width="33",x="173",y="37",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="145",anchorPointX="0",anchorPointY="0.5",},
txt_def_name={classname="CustomLabel",name="txt_def_name",parName="lay_right",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="206",y="111",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="146",anchorPointX="1",anchorPointY="0.5",},
lay_def_icon={classname="Panel",name="lay_def_icon",parName="lay_right",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="80",width="80",x="226",y="38",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="147",anchorPointX="0",anchorPointY="0",},
txt_def_country={classname="CustomLabel",name="txt_def_country",parName="lay_right",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="104",y="111",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="148",anchorPointX="1",anchorPointY="0.5",},
txt_def_power={classname="CustomLabel",name="txt_def_power",parName="lay_right",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="999",fontName="微软雅黑",fontSize="18",height="24",width="33",x="206",y="85",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="149",anchorPointX="1",anchorPointY="0.5",},
txt_def_troops={classname="CustomLabel",name="txt_def_troops",parName="lay_right",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="999",fontName="微软雅黑",fontSize="18",height="24",width="33",x="206",y="62",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="151",anchorPointX="1",anchorPointY="0.5",},
txt_def_troops_title={classname="CustomLabel",name="txt_def_troops_title",parName="lay_right",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="兵力：",fontName="微软雅黑",fontSize="18",height="24",width="54",x="167",y="62",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="152",anchorPointX="1",anchorPointY="0.5",},
txt_def_lose={classname="CustomLabel",name="txt_def_lose",parName="lay_right",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="999",fontName="微软雅黑",fontSize="18",height="24",width="33",x="206",y="37",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="153",anchorPointX="1",anchorPointY="0.5",},
txt_def_lose_title={classname="CustomLabel",name="txt_def_lose_title",parName="lay_right",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="损兵：",fontName="微软雅黑",fontSize="18",height="24",width="54",x="167",y="37",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="154",anchorPointX="1",anchorPointY="0.5",},
txt_def_power_title={classname="CustomLabel",name="txt_def_power_title",parName="lay_right",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="战攻：",fontName="微软雅黑",fontSize="18",height="24",width="54",x="167",y="85",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="155",anchorPointX="1",anchorPointY="0.5",},
img_def_result={classname="CustomImageView",name="img_def_result",parName="lay_right",ZOrder="0",fileName="#v1_img_sheng_yx.png",scale9Enable="false",scale9Height="38",scale9Width="34",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="38",width="34",x="250",y="153",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="135",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable