local tTable = {}

tTable["texturesPng"] = {"ui/p2_commmon2_sep.plist","ui/p2_commonse1.plist","ui/p1_commonse2.plist","ui/p2_commmon1_sep.plist"}
tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="170",width="600",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1154",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_icon={classname="Panel",name="lay_icon",parName="default",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="87",width="87",x="522",y="95",visible="true",touchAble="true",flipX="false",scaleX="0.88",scaleY="0.88",opacity="255",rotation="0",tag="1175",anchorPointX="0",anchorPointY="0",},
lay_content={classname="Panel",name="lay_content",parName="default",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="94",width="263",x="236",y="37",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1174",anchorPointX="0",anchorPointY="0",},
lay_name={classname="Panel",name="lay_name",parName="default",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="460",x="40",y="136",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1176",anchorPointX="0",anchorPointY="0",},
lay_rp_status={classname="Panel",name="lay_rp_status",parName="default",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_bg_black_xaqnyqa.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="11",capInsetsY="11",height="24",width="236",x="263",y="5",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1220",anchorPointX="0",anchorPointY="0",},
ly_pos={classname="Panel",name="ly_pos",parName="default",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="460",x="106",y="-15",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1294",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
img_bg={classname="ImageView",name="img_bg",parName="lay_content",ZOrder="0",fileName="#v2_btn_xaqnwybc.png",scale9Enable="false",scale9Height="94",scale9Width="270",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="94",width="270",x="135",y="47",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1155",anchorPointX="0.5",anchorPointY="0.5",},
img_title={classname="ImageView",name="img_title",parName="lay_content",ZOrder="1",fileName="#v2_bg_black_xaqnyqa02.png",scale9Enable="false",scale9Height="50",scale9Width="41",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="50",width="41",x="36",y="59",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1157",anchorPointX="0.5",anchorPointY="0.5",},
lb_tip={classname="Label",name="lb_tip",parName="lay_content",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="243",y="13",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1285",anchorPointX="1",anchorPointY="0.5",},
lb_detail={classname="Label",name="lb_detail",parName="lay_content",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="目标：",fontName="微软雅黑",fontSize="18",height="24",width="54",x="69",y="58",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1170",anchorPointX="0",anchorPointY="0.5",},
img_laba={classname="ImageView",name="img_laba",parName="lay_name",ZOrder="0",fileName="#v1_img_headlaba.png",scale9Enable="false",scale9Height="72",scale9Width="72",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="72",width="72",x="345",y="14",visible="true",touchAble="false",flipX="false",scaleX="0.39999992",scaleY="0.39999992",opacity="255",rotation="0",tag="1179",anchorPointX="0.5",anchorPointY="0.5",},
img_rp={classname="ImageView",name="img_rp",parName="lay_rp_status",ZOrder="0",fileName="#v2_bg_black_xaqnyqa02.png",scale9Enable="false",scale9Height="50",scale9Width="41",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="50",width="41",x="17",y="12",visible="true",touchAble="false",flipX="false",scaleX="0.4",scaleY="0.4",opacity="255",rotation="0",tag="1221",anchorPointX="0.5",anchorPointY="0.5",},
lb_rp_desc={classname="Label",name="lb_rp_desc",parName="lay_rp_status",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="31",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1222",anchorPointX="0",anchorPointY="0.5",},
lb_pos={classname="Label",name="lb_pos",parName="ly_pos",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="14",height="20",width="68",x="30",y="20",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1295",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable