local tTable = {}


tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="384",width="131",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="20",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
img_boss_bg={classname="ImageView",name="img_boss_bg",parName="default",ZOrder="0",fileName="ui/hero_boss/v1_img_baiqi.jpg",scale9Enable="false",scale9Height="313",scale9Width="115",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="313",width="115",x="66",y="222",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="152",anchorPointX="0.5",anchorPointY="0.5",},
lay_content={classname="Panel",name="lay_content",parName="default",childCount="4",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="384",width="131",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="23",anchorPointX="0",anchorPointY="0",},
lay_border={classname="Panel",name="lay_border",parName="default",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_bannaerkuang.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="65",capInsetsY="65",height="384",width="131",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="22",anchorPointX="0",anchorPointY="0",},
img_faild={classname="CustomImageView",name="img_faild",parName="default",ZOrder="3",fileName="#v1_fonts_yijbai.png",scale9Enable="false",scale9Height="72",scale9Width="111",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="72",width="111",x="66",y="207",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="39",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_3"] = {
lay_lv={classname="Panel",name="lay_lv",parName="lay_content",childCount="1",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_black50.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="10",height="20",width="116",x="8",y="66",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="248",anchorPointX="0",anchorPointY="0",},
img_name_bg={classname="CustomImageView",name="img_name_bg",parName="lay_content",ZOrder="2",fileName="#v1_img_zhanli02.png",scale9Enable="false",scale9Height="82",scale9Width="20",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="82",width="20",x="21",y="335",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="27",anchorPointX="0.5",anchorPointY="0.5",},
txt_name={classname="CustomLabel",name="txt_name",parName="lay_content",ZOrder="3",colorB="255",colorG="255",colorR="255",areaHeight="90",areaWidth="18",hAlignment="0",vAlignment="0",text="X",fontName="微软雅黑",fontSize="18",height="90",width="18",x="11",y="368",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="28",anchorPointX="0",anchorPointY="1",},
lay_bottom={classname="Panel",name="lay_bottom",parName="lay_content",childCount="3",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_img_saod.png",height="59",width="115",x="7",y="6",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="30",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
txt_lv={classname="CustomLabel",name="txt_lv",parName="lay_lv",ZOrder="3",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Lv100",fontName="微软雅黑",fontSize="18",height="24",width="51",x="54",y="11",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="29",anchorPointX="0.5",anchorPointY="0.5",},
img_troops={classname="CustomImageView",name="img_troops",parName="lay_bottom",ZOrder="2",fileName="#v1_img_bujiang.png",scale9Enable="false",scale9Height="34",scale9Width="34",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="34",width="34",x="38",y="42",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="31",anchorPointX="0.5",anchorPointY="0.5",},
txt_troops_title={classname="CustomLabel",name="txt_troops_title",parName="lay_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="兵力",fontName="微软雅黑",fontSize="18",height="24",width="36",x="57",y="42",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="32",anchorPointX="0",anchorPointY="0.5",},
txt_troops={classname="CustomLabel",name="txt_troops",parName="lay_bottom",ZOrder="3",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="16",height="21",width="77",x="59",y="15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="33",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable