local tTable = {}

tTable["texturesPng"] = {"ui/p1_commmon2_sep.plist","ui/p1_commonse2.plist"}
tTable["index_1"] = {
item_recent_chat_player={classname="Panel",name="item_recent_chat_player",parName="root",childCount="8",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen6.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="50",height="110",width="512",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="871",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
ly_icon={classname="Panel",name="ly_icon",parName="item_recent_chat_player",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="87",width="87",x="15",y="11",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="872",anchorPointX="0",anchorPointY="0",},
img_jiantou={classname="ImageView",name="img_jiantou",parName="item_recent_chat_player",ZOrder="1",fileName="#v1_btn_jiantou.png",scale9Enable="false",scale9Height="44",scale9Width="36",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="44",width="36",x="477",y="55",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="180",tag="873",anchorPointX="0.5",anchorPointY="0.5",},
lb_name={classname="CustomLabel",name="lb_name",parName="item_recent_chat_player",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="115",y="80",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="874",anchorPointX="0",anchorPointY="0.5",},
lb_ct_t={classname="CustomLabel",name="lb_ct_t",parName="item_recent_chat_player",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="国家",fontName="微软雅黑",fontSize="18",height="24",width="36",x="115",y="48",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="875",anchorPointX="0",anchorPointY="0.5",},
lb_fg_t={classname="CustomLabel",name="lb_fg_t",parName="item_recent_chat_player",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="国家",fontName="微软雅黑",fontSize="18",height="24",width="36",x="115",y="20",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="876",anchorPointX="0",anchorPointY="0.5",},
lb_ct_n={classname="CustomLabel",name="lb_ct_n",parName="item_recent_chat_player",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="秦",fontName="微软雅黑",fontSize="18",height="24",width="18",x="163",y="36",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="877",anchorPointX="0",anchorPointY="0",},
lb_fg_n={classname="CustomLabel",name="lb_fg_n",parName="item_recent_chat_player",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="29.4M",fontName="微软雅黑",fontSize="18",height="24",width="55",x="163",y="20",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="878",anchorPointX="0",anchorPointY="0.5",},
lb_recent_time={classname="CustomLabel",name="lb_recent_time",parName="item_recent_chat_player",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="最近登录: 10小时内",fontName="微软雅黑",fontSize="18",height="24",width="157",x="290",y="55",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="879",anchorPointX="0",anchorPointY="0.5",},
}

return tTable