local tTable = {}

tTable["texturesPng"] = {"ui/p2_commmon2_sep.plist","ui/daitu.png","ui/p1_commonse1.plist"}
tTable["index_1"] = {
item_fuben_army={classname="Panel",name="item_fuben_army",parName="root",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="116",width="320",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
ly_main={classname="Panel",name="ly_main",parName="item_fuben_army",childCount="7",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_wujiangqiehuandi.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="26",capInsetsY="25",height="116",width="320",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="10",anchorPointX="0",anchorPointY="0",},
ly_relation={classname="Panel",name="ly_relation",parName="item_fuben_army",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="41",width="65",x="269",y="36",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="135",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lb_name={classname="CustomLabel",name="lb_name",parName="ly_main",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="司马懿",fontName="微软雅黑",fontSize="20",height="27",width="60",x="116",y="82",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="103",anchorPointX="0",anchorPointY="0.5",},
img_sel={classname="ImageView",name="img_sel",parName="ly_main",ZOrder="4",fileName="ui/daitu.png",scale9Enable="false",scale9Height="10",scale9Width="10",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="10",width="10",x="149",y="60",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="20",anchorPointX="0.5",anchorPointY="0.5",},
ly_icon={classname="Panel",name="ly_icon",parName="ly_main",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="86",width="86",x="15",y="14",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="102",anchorPointX="0",anchorPointY="0",},
img_hero_type={classname="ImageView",name="img_hero_type",parName="ly_main",ZOrder="0",fileName="#v1_img_bujiang.png",scale9Enable="false",scale9Height="34",scale9Width="34",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="34",width="34",x="133",y="40",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="133",anchorPointX="0.5",anchorPointY="0.5",},
lb_detail={classname="CustomLabel",name="lb_detail",parName="ly_main",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="兵力",fontName="微软雅黑",fontSize="20",height="27",width="40",x="156",y="40",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="134",anchorPointX="0",anchorPointY="0.5",},
lb_lv={classname="CustomLabel",name="lb_lv",parName="ly_main",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Lv.9",fontName="微软雅黑",fontSize="20",height="27",width="38",x="191",y="82",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="371",anchorPointX="0",anchorPointY="0.5",},
lb_num={classname="CustomLabel",name="lb_num",parName="ly_main",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="999",fontName="微软雅黑",fontSize="20",height="27",width="36",x="204",y="40",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="372",anchorPointX="0",anchorPointY="0.5",},
img_arrow={classname="ImageView",name="img_arrow",parName="ly_relation",ZOrder="0",fileName="#v1_img_bukezhi.png",scale9Enable="false",scale9Height="45",scale9Width="63",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="45",width="63",x="32",y="22",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="136",anchorPointX="0.5",anchorPointY="0.5",},
lb_arrow={classname="CustomLabel",name="lb_arrow",parName="ly_relation",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="克制",fontName="微软雅黑",fontSize="18",height="24",width="36",x="32",y="22",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="137",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable