local tTable = {}


tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="140",width="270",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="159",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
view={classname="Panel",name="view",parName="default",childCount="12",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="50",height="140",width="270",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="160",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_player_bg={classname="Panel",name="lay_player_bg",parName="view",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="50",height="140",width="270",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="393",anchorPointX="0",anchorPointY="0",},
lay_hero_bg={classname="Panel",name="lay_hero_bg",parName="view",childCount="1",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="42",capInsetsY="40",height="140",width="270",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="394",anchorPointX="0",anchorPointY="0",},
img_result={classname="CustomImageView",name="img_result",parName="view",ZOrder="4",fileName="#v1_img_sheng_yx.png",scale9Enable="false",scale9Height="38",scale9Width="34",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="38",width="34",x="29",y="114",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="161",anchorPointX="0.5",anchorPointY="0.5",},
txt_country={classname="CustomLabel",name="txt_country",parName="view",ZOrder="4",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="[国]",fontName="微软雅黑",fontSize="20",height="27",width="34",x="108",y="112",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="162",anchorPointX="0",anchorPointY="0.5",},
txt_name={classname="CustomLabel",name="txt_name",parName="view",ZOrder="4",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="150",y="112",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="163",anchorPointX="0",anchorPointY="0.5",},
lay_city_icon={classname="Panel",name="lay_city_icon",parName="view",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="75",width="110",x="-5",y="35",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1544",anchorPointX="0",anchorPointY="0",},
lay_icon={classname="Panel",name="lay_icon",parName="view",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="80",width="80",x="10",y="35",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="164",anchorPointX="0",anchorPointY="0",},
lay_hero_icon={classname="Panel",name="lay_hero_icon",parName="view",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="80",width="80",x="10",y="35",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1545",anchorPointX="0",anchorPointY="0",},
txt_troops_title={classname="CustomLabel",name="txt_troops_title",parName="view",ZOrder="4",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="兵力：",fontName="微软雅黑",fontSize="18",height="24",width="54",x="108",y="51",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="165",anchorPointX="0",anchorPointY="0.5",},
txt_troops={classname="CustomLabel",name="txt_troops",parName="view",ZOrder="4",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="18",height="24",width="44",x="160",y="51",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="166",anchorPointX="0",anchorPointY="0.5",},
txt_lose_title={classname="CustomLabel",name="txt_lose_title",parName="view",ZOrder="4",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="损兵：",fontName="微软雅黑",fontSize="18",height="24",width="54",x="108",y="23",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="167",anchorPointX="0",anchorPointY="0.5",},
txt_lose={classname="CustomLabel",name="txt_lose",parName="view",ZOrder="4",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="-9999",fontName="微软雅黑",fontSize="18",height="24",width="52",x="160",y="23",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="168",anchorPointX="0",anchorPointY="0.5",},
}
tTable["index_4"] = {
txt_hero_name={classname="CustomLabel",name="txt_hero_name",parName="lay_hero_bg",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="英雄名",fontName="微软雅黑",fontSize="20",height="27",width="60",x="108",y="65",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="395",anchorPointX="0",anchorPointY="0",},
}

return tTable