local tTable = {}


tTable["index_1"] = {
item_fuben_chapter={classname="Panel",name="item_fuben_chapter",parName="root",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="166",width="286",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1112",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_star={classname="Panel",name="lay_star",parName="item_fuben_chapter",childCount="3",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="80",x="94",y="128",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1119",anchorPointX="0",anchorPointY="0",},
lay_unlock={classname="Panel",name="lay_unlock",parName="item_fuben_chapter",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="166",width="286",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1133",anchorPointX="0",anchorPointY="0",},
lay_locked={classname="Panel",name="lay_locked",parName="item_fuben_chapter",childCount="1",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_black30.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="1",capInsetsY="1",height="166",width="286",x="0",y="0",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1121",anchorPointX="0",anchorPointY="0",},
img_pass={classname="ImageView",name="img_pass",parName="item_fuben_chapter",ZOrder="1",fileName="#v1_fonts_yitongguan.png",scale9Enable="false",scale9Height="31",scale9Width="84",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="31",width="84",x="50",y="142",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1968",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_3"] = {
img_star_1={classname="ImageView",name="img_star_1",parName="lay_star",ZOrder="2",fileName="#v1_img_star5.png",scale9Enable="false",scale9Height="38",scale9Width="40",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="38",width="40",x="15",y="16",visible="true",touchAble="false",flipX="false",scaleX="0.65",scaleY="0.65",opacity="255",rotation="0",tag="1124",anchorPointX="0.5",anchorPointY="0.5",},
img_star_2={classname="ImageView",name="img_star_2",parName="lay_star",ZOrder="2",fileName="#v1_img_star5.png",scale9Enable="false",scale9Height="38",scale9Width="40",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="38",width="40",x="40",y="16",visible="true",touchAble="false",flipX="false",scaleX="0.65",scaleY="0.65",opacity="255",rotation="0",tag="1125",anchorPointX="0.5",anchorPointY="0.5",},
img_star_3={classname="ImageView",name="img_star_3",parName="lay_star",ZOrder="2",fileName="#v2_img_star5b.png",scale9Enable="false",scale9Height="38",scale9Width="40",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="38",width="40",x="66",y="16",visible="true",touchAble="false",flipX="false",scaleX="0.65",scaleY="0.65",opacity="255",rotation="0",tag="1126",anchorPointX="0.5",anchorPointY="0.5",},
img_bg={classname="ImageView",name="img_bg",parName="lay_unlock",ZOrder="0",fileName="#v2_img_fubenzhangjie.png",scale9Enable="false",scale9Height="166",scale9Width="286",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="166",width="286",x="143",y="83",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1134",anchorPointX="0.5",anchorPointY="0.5",},
lb_chap_name={classname="Label",name="lb_chap_name",parName="lay_unlock",ZOrder="10",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="章节名称",fontName="微软雅黑",fontSize="20",height="27",width="80",x="142",y="16",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1118",anchorPointX="0.5",anchorPointY="0.5",},
lay_challenge={classname="Panel",name="lay_challenge",parName="lay_unlock",childCount="1",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="166",width="286",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4205",anchorPointX="0",anchorPointY="0",},
ly_rewards={classname="Panel",name="ly_rewards",parName="lay_unlock",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="166",width="286",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4322",anchorPointX="0",anchorPointY="0",},
img_lock={classname="ImageView",name="img_lock",parName="lay_locked",ZOrder="0",fileName="#v1_weijiesuo_fb.png",scale9Enable="false",scale9Height="118",scale9Width="118",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="118",width="118",x="143",y="83",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1120",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_4"] = {
img_challenge={classname="CustomImageView",name="img_challenge",parName="lay_challenge",ZOrder="0",fileName="#v2_img_dangqianzdzj.png",scale9Enable="false",scale9Height="94",scale9Width="114",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="94",width="114",x="143",y="87",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4206",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable