local tTable = {}

tTable["texturesPng"] = {"ui/p1_commonse2.plist","ui/p1_commmon2_sep.plist","ui/daitu.png"}
tTable["index_1"] = {
item_chat={classname="Panel",name="item_chat",parName="root",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="30",capInsetsY="63",height="165",width="512",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="30",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_name={classname="Panel",name="lay_name",parName="item_chat",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="460",x="20",y="99",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="32",anchorPointX="0",anchorPointY="0",},
lay_con={classname="Panel",name="lay_con",parName="item_chat",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_liaotiankuang1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="43",capInsetsY="30",height="60",width="460",x="20",y="37",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="37",anchorPointX="0",anchorPointY="0",},
lay_top_time={classname="Panel",name="lay_top_time",parName="item_chat",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_yuanjiaotishikuang.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="45",capInsetsY="17",height="25",width="300",x="90",y="130",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="118",anchorPointX="0",anchorPointY="0",},
ly_pos={classname="Panel",name="ly_pos",parName="item_chat",childCount="5",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="10",height="35",width="460",x="20",y="1",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="564",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
img_laba={classname="ImageView",name="img_laba",parName="lay_name",ZOrder="0",fileName="#v1_img_headlaba.png",scale9Enable="false",scale9Height="72",scale9Width="72",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="72",width="72",x="347",y="14",visible="true",touchAble="false",flipX="false",scaleX="0.4",scaleY="0.4",opacity="255",rotation="0",tag="870",anchorPointX="0.5",anchorPointY="0.5",},
txt_con={classname="CustomLabel",name="txt_con",parName="lay_con",ZOrder="0",colorB="224",colorG="208",colorR="177",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="聊天内容",fontName="微软雅黑",fontSize="20",height="27",width="80",x="34",y="48",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="38",anchorPointX="0",anchorPointY="1",},
txt_top_time={classname="CustomLabel",name="txt_top_time",parName="lay_top_time",ZOrder="2",colorB="182",colorG="182",colorR="182",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="今天 00:00",fontName="微软雅黑",fontSize="14",height="20",width="67",x="150",y="13",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="119",anchorPointX="0.5",anchorPointY="0.5",},
lb_pos={classname="CustomLabel",name="lb_pos",parName="ly_pos",ZOrder="0",colorB="178",colorG="178",colorR="178",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="广东",fontName="微软雅黑",fontSize="14",height="20",width="28",x="30",y="20",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="563",anchorPointX="0",anchorPointY="0.5",},
img_pos={classname="ImageView",name="img_pos",parName="ly_pos",ZOrder="0",fileName="#v1_img_dingwei2.png",scale9Enable="false",scale9Height="28",scale9Width="23",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="28",width="23",x="17",y="17",visible="true",touchAble="false",flipX="false",scaleX="0.8",scaleY="0.8",opacity="255",rotation="0",tag="616",anchorPointX="0.5",anchorPointY="0.5",},
lb_tran={classname="CustomLabel",name="lb_tran",parName="ly_pos",ZOrder="0",colorB="178",colorG="178",colorR="178",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="的撒旦",fontName="微软雅黑",fontSize="16",height="21",width="48",x="51",y="23",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="672",anchorPointX="0",anchorPointY="0.5",},
btn_tran={classname="Button",name="btn_tran",parName="ly_pos",ZOrder="0",fontName="微软雅黑",fontSize="14",scale9Enable="false",scale9Height="10",scale9Width="10",textColorB="255",textColorG="255",textColorR="255",normal="ui/daitu.png",height="10",width="10",x="27",y="25",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="728",anchorPointX="0.5",anchorPointY="0.5",},
img_tran={classname="ImageView",name="img_tran",parName="ly_pos",ZOrder="0",fileName="ui/daitu.png",scale9Enable="false",scale9Height="10",scale9Width="10",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="10",width="10",x="27",y="25",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="671",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable