local tTable = {}

tTable["texturesPng"] = {"ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commonse1.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","icon/p1_icon_ui.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","ui/bg_world/v1_img_shijieditu.jpg","ui/p1_commmon1_sep.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","ui/p1_button1.plist","ui/p1_commonse1.plist","ui/bar/v1_bar_b1.png","ui/p1_commonse1.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commonse1.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","icon/p1_icon_ui.plist","ui/p1_commonse1.plist","icon/p1_icon_ui.plist","ui/p1_commonse1.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commmon1_sep.plist","icon/p1_icon_font.plist","ui/language/cn/p1_font1.plist","icon/p1_icon_ui.plist","ui/p1_commonse1.plist","ui/p1_button1.plist","icon/p1_icon_font.plist","ui/p1_commmon1_sep.plist","ui/language/cn/p1_font1.plist","ui/p1_commonse1.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","ui/bar/v1_bar_b1.png","ui/p1_commmon1_sep.plist","ui/bar/v1_bar_b1.png","ui/p1_commonse2.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist"}
tTable["index_1"] = {
defalut={classname="Panel",name="defalut",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="63",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7158",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
view={classname="Panel",name="view",parName="defalut",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_xitongtishi.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="133",capInsetsY="32",height="63",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7159",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
txt_tip={classname="CustomLabel",name="txt_tip",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="320",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7160",anchorPointX="0.5",anchorPointY="0.5",},
img_warning={classname="CustomImageView",name="img_warning",parName="view",ZOrder="0",fileName="#v1_img_hongsetishi.png",scale9Enable="false",scale9Height="41",scale9Width="40",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="41",width="40",x="34",y="31",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7405",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable