local tTable = {}

tTable["texturesPng"] = {"ui/p2_commmon3_sep.plist","ui/p2_commonse1.plist","ui/p1_commmon2_sep.plist","ui/p1_commonse1.plist"}
tTable["index_1"] = {
item_level_preview={classname="Panel",name="item_level_preview",parName="root",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="345",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="25",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_left={classname="Panel",name="lay_left",parName="item_level_preview",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_zgdj.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="300",height="345",width="257",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="26",anchorPointX="0",anchorPointY="0",},
lay_right={classname="Panel",name="lay_right",parName="item_level_preview",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="345",width="383",x="257",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="35",anchorPointX="0",anchorPointY="0",},
img_arrow={classname="ImageView",name="img_arrow",parName="item_level_preview",ZOrder="2",fileName="#v1_img_lanjiantou.png",scale9Enable="false",scale9Height="41",scale9Width="65",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="41",width="65",x="127",y="361",visible="false",touchAble="false",flipX="false",scaleX="0.79999995",scaleY="0.79999995",opacity="255",rotation="90",tag="54",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_3"] = {
Image_2={classname="ImageView",name="Image_2",parName="lay_left",ZOrder="1",fileName="#v2_img_daitu.png",scale9Enable="false",scale9Height="202",scale9Width="158",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="202",width="158",x="128",y="140",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="27",anchorPointX="0.5",anchorPointY="0",},
lb_level={classname="Label",name="lb_level",parName="lay_left",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="60",fontName="微软雅黑",fontSize="48",height="62",width="56",x="128",y="267",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="28",anchorPointX="0.5",anchorPointY="0.5",},
txt_level={classname="Label",name="txt_level",parName="lay_left",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="主公等级",fontName="微软雅黑",fontSize="18",height="24",width="72",x="128",y="172",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="30",anchorPointX="0.5",anchorPointY="0",},
lb_desc={classname="Label",name="lb_desc",parName="lay_left",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="王宫可升至",fontName="微软雅黑",fontSize="20",height="27",width="100",x="128",y="79",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="33",anchorPointX="0.5",anchorPointY="0.5",},
lay_r_up={classname="Panel",name="lay_r_up",parName="lay_right",childCount="2",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="173",width="383",x="0",y="172",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="36",anchorPointX="0",anchorPointY="0",},
img_line={classname="ImageView",name="img_line",parName="lay_right",ZOrder="2",fileName="#v1_line_blue1.png",scale9Enable="true",scale9Height="2",scale9Width="384",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="1",height="2",width="384",x="-1",y="172",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="39",anchorPointX="0",anchorPointY="0.5",},
lay_r_down={classname="Panel",name="lay_r_down",parName="lay_right",childCount="2",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="173",width="383",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="50",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lay_title_1={classname="Panel",name="lay_title_1",parName="lay_r_up",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen6_b.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="300",capInsetsY="9",height="41",width="383",x="0",y="132",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="42",anchorPointX="0",anchorPointY="0",},
lay_build_1={classname="Panel",name="lay_build_1",parName="lay_r_up",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen6.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="50",height="132",width="383",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="40",anchorPointX="0",anchorPointY="0",},
lay_title_2={classname="Panel",name="lay_title_2",parName="lay_r_down",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen6_b.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="300",capInsetsY="9",height="41",width="383",x="0",y="132",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="51",anchorPointX="0",anchorPointY="0",},
lay_build_2={classname="Panel",name="lay_build_2",parName="lay_r_down",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen6.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="50",height="132",width="383",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="53",anchorPointX="0",anchorPointY="0",},
}
tTable["index_5"] = {
lb_title_1={classname="Label",name="lb_title_1",parName="lay_title_1",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="开启建筑",fontName="微软雅黑",fontSize="20",height="27",width="80",x="16",y="20",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="43",anchorPointX="0",anchorPointY="0.5",},
lb_title_2={classname="Label",name="lb_title_2",parName="lay_title_2",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="王宫12级开启",fontName="微软雅黑",fontSize="20",height="27",width="124",x="16",y="20",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="52",anchorPointX="0",anchorPointY="0.5",},
}

return tTable