local tTable = {}

tTable["texturesPng"] = {"ui/p1_commmon2_sep.plist","ui/bar/v1_bar_b1.png","ui/language/cn/p2_font1.plist"}
tTable["index_1"] = {
item_hero_line_up={classname="Panel",name="item_hero_line_up",parName="root",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen6.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="50",height="130",width="600",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="504",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
ly_icon={classname="Panel",name="ly_icon",parName="item_hero_line_up",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="15",y="11",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="-0.73307794",tag="505",anchorPointX="0",anchorPointY="0",},
ly_have_hero={classname="Panel",name="ly_have_hero",parName="item_hero_line_up",childCount="8",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="130",width="465",x="133",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="585",anchorPointX="0",anchorPointY="0",},
lb_account={classname="CustomLabel",name="lb_account",parName="item_hero_line_up",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="135",y="65",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="586",anchorPointX="0",anchorPointY="0.5",},
bg={classname="Panel",name="bg",parName="item_hero_line_up",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen6_b.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="175",capInsetsY="9",height="130",width="600",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1222",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
ly_tl_2={classname="Panel",name="ly_tl_2",parName="ly_have_hero",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="27",width="100",x="150",y="47",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="508",anchorPointX="0",anchorPointY="0",},
ly_tl_1={classname="Panel",name="ly_tl_1",parName="ly_have_hero",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="27",width="100",x="5",y="47",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="506",anchorPointX="0",anchorPointY="0",},
lb_state={classname="CustomLabel",name="lb_state",parName="ly_have_hero",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="闲",fontName="微软雅黑",fontSize="22",height="30",width="22",x="390",y="94",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="510",anchorPointX="0.5",anchorPointY="0.5",},
ly_btn={classname="Panel",name="ly_btn",parName="ly_have_hero",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="319",y="15",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="511",anchorPointX="0",anchorPointY="0",},
lb_soldier_n={classname="CustomLabel",name="lb_soldier_n",parName="ly_have_hero",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="兵力",fontName="微软雅黑",fontSize="20",height="27",width="40",x="5",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="512",anchorPointX="0",anchorPointY="0.5",},
ly_bar={classname="Panel",name="ly_bar",parName="ly_have_hero",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v1_bar_b1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="45",capInsetsY="9",height="18",width="146",x="52",y="20",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="515",anchorPointX="0",anchorPointY="0",},
img_state={classname="ImageView",name="img_state",parName="ly_have_hero",ZOrder="0",fileName="#v2_img_xian.png",scale9Enable="false",scale9Height="40",scale9Width="29",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="40",width="29",x="390",y="110",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="862",anchorPointX="0.5",anchorPointY="0.5",},
lay_btn_add={classname="Panel",name="lay_btn_add",parName="ly_have_hero",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="40",x="220",y="10",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8623",anchorPointX="0",anchorPointY="0",},
}

return tTable