local tTable = {}

tTable["texturesPng"] = {"ui/p1_commmon2_sep.plist","ui/bar/v1_bar_b2.png"}
tTable["index_1"] = {
root={classname="Panel",name="root",parName="root",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen6.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="50",height="130",width="600",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="863",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_icon={classname="Panel",name="lay_icon",parName="root",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="15",y="11",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="864",anchorPointX="0",anchorPointY="0",},
lay_status_1={classname="Panel",name="lay_status_1",parName="root",childCount="2",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="130",width="464",x="136",y="0",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="866",anchorPointX="0",anchorPointY="0",},
lay_status_2={classname="Panel",name="lay_status_2",parName="root",childCount="5",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="130",width="464",x="136",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="869",anchorPointX="0",anchorPointY="0",},
Image_13={classname="ImageView",name="Image_13",parName="root",ZOrder="0",fileName="#v1_img_kelashen6_b.png",scale9Enable="true",scale9Height="128",scale9Width="350",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="175",capInsetsY="9",height="128",width="350",x="0",y="1",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1258",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lb_tip_1={classname="Label",name="lb_tip_1",parName="lay_status_1",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="永久扩充生产线",fontName="微软雅黑",fontSize="22",height="30",width="154",x="110",y="65",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="867",anchorPointX="0.5",anchorPointY="0.5",},
lay_right_btn={classname="Panel",name="lay_right_btn",parName="lay_status_1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="314",y="40",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="868",anchorPointX="0",anchorPointY="0",},
lb_name={classname="Label",name="lb_name",parName="lay_status_2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="材料名称",fontName="微软雅黑",fontSize="22",height="30",width="88",x="5",y="100",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="870",anchorPointX="0",anchorPointY="0.5",},
lb_num_p={classname="Label",name="lb_num_p",parName="lay_status_2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="参与生产百姓：",fontName="微软雅黑",fontSize="20",height="27",width="140",x="5",y="63",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="871",anchorPointX="0",anchorPointY="0.5",},
lb_timer={classname="Label",name="lb_timer",parName="lay_status_2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="55:55:55",fontName="微软雅黑",fontSize="20",height="27",width="82",x="6",y="28",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="875",anchorPointX="0",anchorPointY="0.5",},
lay_in_production={classname="Panel",name="lay_in_production",parName="lay_status_2",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="130",width="140",x="323",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="877",anchorPointX="0",anchorPointY="0",},
lay_over={classname="Panel",name="lay_over",parName="lay_status_2",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="130",width="140",x="310",y="0",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="883",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lay_bar={classname="Panel",name="lay_bar",parName="lay_in_production",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v1_bar_b2.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="42",capInsetsY="6",height="14",width="120",x="8",y="20",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="878",anchorPointX="0",anchorPointY="0",},
lb_percent={classname="Label",name="lb_percent",parName="lay_in_production",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="32%",fontName="微软雅黑",fontSize="20",height="27",width="42",x="68",y="51",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="880",anchorPointX="0.5",anchorPointY="0.5",},
lb_tip_4={classname="Label",name="lb_tip_4",parName="lay_in_production",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="生产数：",fontName="微软雅黑",fontSize="22",height="30",width="88",x="8",y="100",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="881",anchorPointX="0",anchorPointY="0.5",},
lb_num={classname="Label",name="lb_num",parName="lay_in_production",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9",fontName="微软雅黑",fontSize="20",height="27",width="12",x="96",y="98",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="882",anchorPointX="0",anchorPointY="0.5",},
lay_get_btn={classname="Panel",name="lay_get_btn",parName="lay_over",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="5",y="22",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="885",anchorPointX="0",anchorPointY="0",},
lb_tip_5={classname="Label",name="lb_tip_5",parName="lay_over",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="生产完成",fontName="微软雅黑",fontSize="20",height="27",width="80",x="70",y="88",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="886",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable