local tTable = {}


tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="140",width="270",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2361",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
view={classname="Panel",name="view",parName="default",childCount="13",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="140",width="270",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2362",anchorPointX="0",anchorPointY="0",},
txt_tip={classname="Label",name="txt_tip",parName="default",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="22",height="30",width="106",x="135",y="70",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="22063",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_3"] = {
lay_player_bg={classname="Panel",name="lay_player_bg",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="140",width="270",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2363",anchorPointX="0",anchorPointY="0",},
lay_hero_bg={classname="Panel",name="lay_hero_bg",parName="view",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="140",width="270",x="0",y="0",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2364",anchorPointX="0",anchorPointY="0",},
lay_city_icon={classname="Panel",name="lay_city_icon",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="75",width="110",x="165",y="35",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2366",anchorPointX="0",anchorPointY="0",},
lay_hero_icon={classname="Panel",name="lay_hero_icon",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="80",width="80",x="180",y="30",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2368",anchorPointX="0",anchorPointY="0",},
lay_icon={classname="Panel",name="lay_icon",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="80",width="80",x="180",y="35",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2369",anchorPointX="0",anchorPointY="0",},
img_result={classname="ImageView",name="img_result",parName="view",ZOrder="0",fileName="#v1_img_sheng_yx.png",scale9Enable="false",scale9Height="38",scale9Width="34",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="38",width="34",x="34",y="29",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2370",anchorPointX="0.5",anchorPointY="0.5",},
txt_name={classname="Label",name="txt_name",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="164",y="97",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2373",anchorPointX="1",anchorPointY="0",},
txt_troops={classname="Label",name="txt_troops",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="164",y="70",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2375",anchorPointX="1",anchorPointY="0",},
txt_lose={classname="Label",name="txt_lose",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="164",y="45",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2378",anchorPointX="1",anchorPointY="0",},
txt_pos={classname="Label",name="txt_pos",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="164",y="23",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="3289",anchorPointX="1",anchorPointY="0",},
img_pos={classname="ImageView",name="img_pos",parName="view",ZOrder="2",fileName="#v1_img_weizhi.png",scale9Enable="false",scale9Height="40",scale9Width="34",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="40",width="34",x="70",y="29",visible="true",touchAble="false",flipX="false",scaleX="0.5999999",scaleY="0.5999999",opacity="255",rotation="0",tag="22932",anchorPointX="0.5",anchorPointY="0.5",},
lay_pos_btn={classname="Panel",name="lay_pos_btn",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="140",width="270",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="3291",anchorPointX="0",anchorPointY="0",},
txt_player_name={classname="Label",name="txt_player_name",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="164",y="70",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="22062",anchorPointX="1",anchorPointY="0",},
}
tTable["index_4"] = {
txt_hero_name={classname="Label",name="txt_hero_name",parName="lay_hero_bg",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="162",y="65",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2365",anchorPointX="1",anchorPointY="0",},
}

return tTable