local tTable = {}

tTable["texturesPng"] = {"ui/p1_commmon2_sep.plist","ui/p2_commmon3_sep.plist","ui/p1_commonse1.plist"}
tTable["index_1"] = {
lay_root={classname="Panel",name="lay_root",parName="root",childCount="8",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen6.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="50",height="130",width="600",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="23",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
img_dian={classname="ImageView",name="img_dian",parName="lay_root",ZOrder="10",fileName="#v2_img_jz_diana.png",scale9Enable="false",scale9Height="32",scale9Width="32",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="32",width="32",x="28",y="103",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="25",anchorPointX="0.5",anchorPointY="0.5",},
lay_bg={classname="Panel",name="lay_bg",parName="lay_root",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen6_b.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="175",capInsetsY="9",height="130",width="350",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="24",anchorPointX="0",anchorPointY="0",},
img_line={classname="ImageView",name="img_line",parName="lay_root",ZOrder="10",fileName="#v1_line_blue1.png",scale9Enable="true",scale9Height="2",scale9Width="406",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="1",height="2",width="406",x="571",y="80",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="27",anchorPointX="1",anchorPointY="0.5",},
lay_btn_blue={classname="Panel",name="lay_btn_blue",parName="lay_root",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="441",y="13",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="28",anchorPointX="0",anchorPointY="0",},
lb_build_name={classname="Label",name="lb_build_name",parName="lay_root",ZOrder="10",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="工坊Lv.1",fontName="微软雅黑",fontSize="22",height="30",width="85",x="170",y="104",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="29",anchorPointX="0",anchorPointY="0.5",},
lb_status={classname="Label",name="lb_status",parName="lay_root",ZOrder="10",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="启用",fontName="微软雅黑",fontSize="22",height="30",width="44",x="328",y="104",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="30",anchorPointX="0",anchorPointY="0.5",},
lb_desc={classname="Label",name="lb_desc",parName="lay_root",ZOrder="10",colorB="255",colorG="255",colorR="255",areaHeight="60",areaWidth="250",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="60",width="250",x="170",y="70",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="32",anchorPointX="0",anchorPointY="1",},
lb_index={classname="Label",name="lb_index",parName="lay_root",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="570",y="104",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="84",anchorPointX="1",anchorPointY="0.5",},
}

return tTable