local tTable = {}

tTable["texturesPng"] = {"ui/p1_commmon2_sep.plist","ui/bar/v1_bar_b1.png"}
tTable["index_1"] = {
root={classname="Panel",name="root",parName="root",childCount="6",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen6.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="50",height="130",width="600",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="504",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
ly_icon={classname="Panel",name="ly_icon",parName="root",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="15",y="11",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="505",anchorPointX="0",anchorPointY="0",},
ly_have_hero={classname="Panel",name="ly_have_hero",parName="root",childCount="4",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="130",width="465",x="133",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="585",anchorPointX="0",anchorPointY="0",},
lb_account={classname="CustomLabel",name="lb_account",parName="root",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="135",y="79",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="586",anchorPointX="0",anchorPointY="0.5",},
lb_account2={classname="CustomLabel",name="lb_account2",parName="root",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="135",y="45",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6872",anchorPointX="0",anchorPointY="0.5",},
lay_btn_unlock={classname="Panel",name="lay_btn_unlock",parName="root",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="455",y="18",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6869",anchorPointX="0",anchorPointY="0",},
bg={classname="Panel",name="bg",parName="root",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen6_b.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="175",capInsetsY="9",height="130",width="600",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1222",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
ly_btn={classname="Panel",name="ly_btn",parName="ly_have_hero",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="319",y="15",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="511",anchorPointX="0",anchorPointY="0",},
lb_soldier_n={classname="CustomLabel",name="lb_soldier_n",parName="ly_have_hero",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="兵力",fontName="微软雅黑",fontSize="20",height="27",width="40",x="5",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="512",anchorPointX="0",anchorPointY="0.5",},
ly_bar={classname="Panel",name="ly_bar",parName="ly_have_hero",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v1_bar_b1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="45",capInsetsY="9",height="18",width="146",x="52",y="20",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="515",anchorPointX="0",anchorPointY="0",},
lay_btn_add={classname="Panel",name="lay_btn_add",parName="ly_have_hero",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="40",x="220",y="10",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8625",anchorPointX="0",anchorPointY="0",},
}

return tTable