local tTable = {}


tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="7",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen6.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="50",height="130",width="600",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="97",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_top={classname="Panel",name="lay_top",parName="default",childCount="2",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_black20.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="10",height="45",width="600",x="0",y="84",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="99",anchorPointX="0",anchorPointY="0",},
lay_bg={classname="Panel",name="lay_bg",parName="default",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen6_b.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="175",capInsetsY="9",height="129",width="350",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="98",anchorPointX="0",anchorPointY="0",},
txt_tip={classname="Label",name="txt_tip",parName="default",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="514",y="43",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="105",anchorPointX="0.5",anchorPointY="0.5",},
img_state={classname="ImageView",name="img_state",parName="default",ZOrder="3",fileName="#v2_fonts_weikaiqi.png",scale9Enable="false",scale9Height="46",scale9Width="140",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="46",width="140",x="522",y="44",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="106",anchorPointX="0.5",anchorPointY="0.5",},
lay_bar={classname="Panel",name="lay_bar",parName="default",childCount="1",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v1_bar_b1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="45",capInsetsY="9",height="18",width="300",x="134",y="33",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="162",anchorPointX="0",anchorPointY="0",},
lay_btn={classname="Panel",name="lay_btn",parName="default",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="450",y="18",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="104",anchorPointX="0",anchorPointY="0",},
img_icon={classname="ImageView",name="img_icon",parName="default",ZOrder="3",fileName="#v1_btn_gongcheng.png",scale9Enable="false",scale9Height="111",scale9Width="111",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="111",width="111",x="67",y="62",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="394",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_3"] = {
txt_title={classname="Label",name="txt_title",parName="lay_top",ZOrder="5",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="140",y="22",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="100",anchorPointX="0",anchorPointY="0.5",},
txt_point={classname="Label",name="txt_point",parName="lay_top",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="514",y="23",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="103",anchorPointX="0.5",anchorPointY="0.5",},
txt_bar={classname="Label",name="txt_bar",parName="lay_bar",ZOrder="5",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="150",y="9",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="163",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable