local tTable = {}

tTable["texturesPng"] = {"ui/p1_commmon2_sep.plist","GUI/image.png","ui/language/cn/p2_font2.plist","ui/p1_commonse1.plist"}
tTable["index_1"] = {
layout_main={classname="Panel",name="layout_main",parName="root",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="150",width="140",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="889",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
layout_fk={classname="Panel",name="layout_fk",parName="layout_main",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="150",width="140",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="896",anchorPointX="0",anchorPointY="0",},
img_title={classname="ImageView",name="img_title",parName="layout_main",ZOrder="0",fileName="#v3_font_paimingshangsheng.png",scale9Enable="false",scale9Height="44",scale9Width="177",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="44",width="177",x="70",y="180",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="906",anchorPointX="0.5",anchorPointY="0.5",},
layout_rank={classname="Panel",name="layout_rank",parName="layout_main",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="44",width="200",x="-30",y="150",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="903",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
img_bg={classname="ImageView",name="img_bg",parName="layout_fk",ZOrder="0",fileName="#v1_img_tishichangtiao.png",scale9Enable="false",scale9Height="43",scale9Width="276",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="43",width="276",x="70",y="16",visible="true",touchAble="false",flipX="false",scaleX="0.55",scaleY="0.7",opacity="255",rotation="0",tag="894",anchorPointX="0.5",anchorPointY="0.5",},
txt_name={classname="Label",name="txt_name",parName="layout_fk",ZOrder="10",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="70",y="16",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="895",anchorPointX="0.5",anchorPointY="0.5",},
img_bg_light={classname="ImageView",name="img_bg_light",parName="layout_fk",ZOrder="5",fileName="#v1_img_tishichangtiao.png",scale9Enable="false",scale9Height="43",scale9Width="276",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="43",width="276",x="70",y="16",visible="true",touchAble="false",flipX="false",scaleX="0.55",scaleY="0.7",opacity="255",rotation="0",tag="901",anchorPointX="0.5",anchorPointY="0.5",},
img_head={classname="ImageView",name="img_head",parName="layout_fk",ZOrder="0",fileName="GUI/image.png",scale9Enable="false",scale9Height="80",scale9Width="80",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="80",width="80",x="70",y="93",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="900",anchorPointX="0.5",anchorPointY="0.5",},
img_orn={classname="ImageView",name="img_orn",parName="layout_fk",ZOrder="10",fileName="GUI/image.png",scale9Enable="false",scale9Height="80",scale9Width="80",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="80",width="80",x="70",y="93",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="902",anchorPointX="0.5",anchorPointY="0.5",},
img_arrow={classname="ImageView",name="img_arrow",parName="layout_rank",ZOrder="0",fileName="#v1_img_shengjilvjianto.png",scale9Enable="false",scale9Height="35",scale9Width="25",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="35",width="25",x="152",y="10",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="904",anchorPointX="0.5",anchorPointY="0",},
}

return tTable