local tTable = {}

tTable["texturesPng"] = {"ui/p1_commmon5_sep.plist","icon/p1_icon_font.plist"}
tTable["index_1"] = {
view={classname="Panel",name="view",parName="root",childCount="12",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_duizhandiyoujian.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="320",capInsetsY="9",height="140",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="522",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_player_left={classname="Panel",name="lay_player_left",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="87",width="87",x="15",y="28",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="524",anchorPointX="0",anchorPointY="0",},
lay_player_right={classname="Panel",name="lay_player_right",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="87",width="87",x="535",y="30",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="525",anchorPointX="0",anchorPointY="0",},
txt_name_left={classname="CustomLabel",name="txt_name_left",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="111",y="103",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="526",anchorPointX="0",anchorPointY="0.5",},
txt_troops_left={classname="CustomLabel",name="txt_troops_left",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="111",y="75",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="527",anchorPointX="0",anchorPointY="0.5",},
txt_lose_troops_left={classname="CustomLabel",name="txt_lose_troops_left",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="111",y="47",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="528",anchorPointX="0",anchorPointY="0.5",},
txt_name_right={classname="CustomLabel",name="txt_name_right",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="528",y="103",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="531",anchorPointX="1",anchorPointY="0.5",},
txt_troops_right={classname="CustomLabel",name="txt_troops_right",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="528",y="75",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="532",anchorPointX="1",anchorPointY="0.5",},
txt_lose_troops_right={classname="CustomLabel",name="txt_lose_troops_right",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="528",y="47",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="533",anchorPointX="1",anchorPointY="0.5",},
img_play={classname="CustomImageView",name="img_play",parName="view",ZOrder="0",fileName="#v2_btn_huifang.png",scale9Enable="false",scale9Height="72",scale9Width="72",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="72",width="72",x="317",y="70",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="536",anchorPointX="0.5",anchorPointY="0.5",},
lay_btn_replay={classname="Panel",name="lay_btn_replay",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="90",width="140",x="245",y="25",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="750",anchorPointX="0",anchorPointY="0",},
img_flag_left={classname="CustomImageView",name="img_flag_left",parName="view",ZOrder="3",fileName="#v1_img_qun.png",scale9Enable="false",scale9Height="64",scale9Width="51",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="64",width="51",x="33",y="97",visible="true",touchAble="false",flipX="false",scaleX="0.8",scaleY="0.8",opacity="255",rotation="0",tag="1086",anchorPointX="0.5",anchorPointY="0.5",},
img_flag_right={classname="CustomImageView",name="img_flag_right",parName="view",ZOrder="3",fileName="#v1_img_qun.png",scale9Enable="false",scale9Height="64",scale9Width="51",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="64",width="51",x="553",y="99",visible="true",touchAble="false",flipX="false",scaleX="0.8",scaleY="0.8",opacity="255",rotation="0",tag="1087",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable