local tTable = {}


tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_bg_guozhanliebiao.jpg",height="200",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="224",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
view={classname="Panel",name="view",parName="default",childCount="20",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="200",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2454",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
txt_atk_troops={classname="CustomLabel",name="txt_atk_troops",parName="view",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="进攻兵力：99999999",fontName="微软雅黑",fontSize="18",height="24",width="178",x="83",y="88",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2457",anchorPointX="0",anchorPointY="0.5",},
txt_def_troops={classname="CustomLabel",name="txt_def_troops",parName="view",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="防守兵力：99999999",fontName="微软雅黑",fontSize="18",height="24",width="178",x="559",y="88",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2461",anchorPointX="1",anchorPointY="0.5",},
txt_cd={classname="CustomLabel",name="txt_cd",parName="view",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="320",y="100",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="231",anchorPointX="0.5",anchorPointY="0.5",},
lay_atk_location={classname="Panel",name="lay_atk_location",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="90",width="200",x="2",y="62",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2464",anchorPointX="0",anchorPointY="0",},
img_atk_flag={classname="CustomImageView",name="img_atk_flag",parName="view",ZOrder="0",fileName="#v1_img_qun.png",scale9Enable="false",scale9Height="64",scale9Width="51",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="64",width="51",x="32",y="177",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2465",anchorPointX="0.5",anchorPointY="0.5",},
txt_atk_name={classname="CustomLabel",name="txt_atk_name",parName="view",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="83",y="120",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="227",anchorPointX="0",anchorPointY="0.5",},
txt_atk_title={classname="CustomLabel",name="txt_atk_title",parName="view",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="61",y="175",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="229",anchorPointX="0",anchorPointY="0.5",},
txt_def_name={classname="CustomLabel",name="txt_def_name",parName="view",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="559",y="120",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="228",anchorPointX="1",anchorPointY="0.5",},
txt_def_title={classname="CustomLabel",name="txt_def_title",parName="view",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="574",y="175",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="230",anchorPointX="1",anchorPointY="0.5",},
lay_def_location={classname="Panel",name="lay_def_location",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="90",width="200",x="440",y="63",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2469",anchorPointX="0",anchorPointY="0",},
img_def_flag={classname="CustomImageView",name="img_def_flag",parName="view",ZOrder="0",fileName="#v1_img_qun.png",scale9Enable="false",scale9Height="64",scale9Width="51",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="64",width="51",x="604",y="178",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2470",anchorPointX="0.5",anchorPointY="0.5",},
lay_atk_city={classname="Panel",name="lay_atk_city",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="65",width="65",x="9",y="74",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="18001",anchorPointX="0",anchorPointY="0",},
lay_def_city={classname="Panel",name="lay_def_city",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="65",width="65",x="568",y="74",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="18002",anchorPointX="0",anchorPointY="0",},
img_tilte={classname="CustomImageView",name="img_tilte",parName="view",ZOrder="0",fileName="#v1_fonts_chengzhan2.png",scale9Enable="false",scale9Height="25",scale9Width="52",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="25",width="52",x="318",y="170",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="18003",anchorPointX="0.5",anchorPointY="0.5",},
img_arrow={classname="CustomImageView",name="img_arrow",parName="view",ZOrder="0",fileName="#v1_img_jingongjiantou.png",scale9Enable="false",scale9Height="28",scale9Width="66",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="28",width="66",x="319",y="128",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="18004",anchorPointX="0.5",anchorPointY="0.5",},
img_cd_bg={classname="CustomImageView",name="img_cd_bg",parName="view",ZOrder="0",fileName="#v1_img_namebg1a.png",scale9Enable="true",scale9Height="46",scale9Width="112",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="45",capInsetsY="14",height="46",width="112",x="319",y="90",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="18007",anchorPointX="0.5",anchorPointY="0.5",},
lb_short_war_tip={classname="Label",name="lb_short_war_tip",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="320",y="28",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="24460",anchorPointX="0.5",anchorPointY="0.5",},
txt_move_time={classname="CustomLabel",name="txt_move_time",parName="view",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="320",y="80",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="25288",anchorPointX="0.5",anchorPointY="0.5",},
lay_cw_btns={classname="Panel",name="lay_cw_btns",parName="view",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="640",x="0",y="8",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="25415",anchorPointX="0",anchorPointY="0",},
lay_gw_btns={classname="Panel",name="lay_gw_btns",parName="view",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="640",x="0",y="8",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="25421",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lay_btn_support={classname="Panel",name="lay_btn_support",parName="lay_cw_btns",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="160",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="233",anchorPointX="0",anchorPointY="0",},
lay_btn_attack={classname="Panel",name="lay_btn_attack",parName="lay_cw_btns",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="160",x="160",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="234",anchorPointX="0",anchorPointY="0",},
lay_btn_citywar={classname="Panel",name="lay_btn_citywar",parName="lay_cw_btns",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="160",x="320",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="236",anchorPointX="0",anchorPointY="0",},
lay_btn_share={classname="Panel",name="lay_btn_share",parName="lay_cw_btns",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="160",x="480",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="21649",anchorPointX="0",anchorPointY="0",},
lay_btn_support_gw={classname="Panel",name="lay_btn_support_gw",parName="lay_gw_btns",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="160",x="395",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="25422",anchorPointX="0",anchorPointY="0",},
lay_btn_check={classname="Panel",name="lay_btn_check",parName="lay_gw_btns",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="160",x="85",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="25423",anchorPointX="0",anchorPointY="0",},
lb_gw_tip={classname="Label",name="lb_gw_tip",parName="lay_gw_btns",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="366",y="20",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="25426",anchorPointX="0",anchorPointY="0.5",},
}

return tTable