local tTable = {}

tTable["texturesPng"] = {"ui/p1_commmon2_sep.plist","ui/language/cn/p2_font_sep.plist","ui/p1_commonse1.plist","ui/daitu.png","ui/p1_commmon3_sep.plist","ui/p1_commmon1_sep.plist","ui/p2_commmon3_sep.plist"}
tTable["index_1"] = {
item_update_palace={classname="Panel",name="item_update_palace",parName="root",childCount="6",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen6.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="50",height="260",width="600",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="11",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
ly_title={classname="Panel",name="ly_title",parName="item_update_palace",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen6_b.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="175",capInsetsY="9",height="45",width="350",x="0",y="215",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="13",anchorPointX="0",anchorPointY="0",},
ly_btn={classname="Panel",name="ly_btn",parName="item_update_palace",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="345",y="15",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="15",anchorPointX="0",anchorPointY="0",},
img_have_get={classname="ImageView",name="img_have_get",parName="item_update_palace",ZOrder="1",fileName="#v2_fonts_yilingqu.png",scale9Enable="false",scale9Height="46",scale9Width="140",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="46",width="140",x="417",y="40",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="16",anchorPointX="0.5",anchorPointY="0.5",},
ly_list={classname="Panel",name="ly_list",parName="item_update_palace",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="128",width="325",x="249",y="73",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="17",anchorPointX="0",anchorPointY="0",},
img_line={classname="ImageView",name="img_line",parName="item_update_palace",ZOrder="0",fileName="#v1_line_blue1.png",scale9Enable="true",scale9Height="2",scale9Width="600",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="1",height="2",width="600",x="300",y="214",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="92",anchorPointX="0.5",anchorPointY="0.5",},
ly_rect={classname="Panel",name="ly_rect",parName="item_update_palace",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="99",height="197",width="180",x="32",y="8",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="21",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lb_title={classname="CustomLabel",name="lb_title",parName="ly_title",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="22",height="30",width="106",x="20",y="22",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="14",anchorPointX="0",anchorPointY="0.5",},
lay_icon_info={classname="Panel",name="lay_icon_info",parName="ly_rect",childCount="4",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="6",capInsetsY="65",height="155",width="180",x="0",y="42",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="94",anchorPointX="0",anchorPointY="0",},
lay_desc={classname="Panel",name="lay_desc",parName="ly_rect",childCount="1",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_zjm_wgcj.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="12",capInsetsY="7",height="48",width="180",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="93",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
img_icon={classname="ImageView",name="img_icon",parName="lay_icon_info",ZOrder="2",fileName="ui/daitu.png",scale9Enable="false",scale9Height="10",scale9Width="10",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="10",width="10",x="90",y="91",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="23",anchorPointX="0.5",anchorPointY="0.5",},
img_icon_bg={classname="ImageView",name="img_icon_bg",parName="lay_icon_info",ZOrder="1",fileName="#v1_img_touxiangkuangzi.png",scale9Enable="false",scale9Height="108",scale9Width="108",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="108",width="108",x="90",y="91",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="22",anchorPointX="0.5",anchorPointY="0.5",},
lb_name={classname="CustomLabel",name="lb_name",parName="lay_icon_info",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="90",y="21",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="20",anchorPointX="0.5",anchorPointY="0.5",},
img_icon_di={classname="ImageView",name="img_icon_di",parName="lay_icon_info",ZOrder="0",fileName="#v1_img_viplashen1.png",scale9Enable="true",scale9Height="155",scale9Width="180",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="6",capInsetsY="65",height="155",width="180",x="90",y="77",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="100",anchorPointX="0.5",anchorPointY="0.5",},
lb_desc={classname="CustomLabel",name="lb_desc",parName="lay_desc",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="55",areaWidth="172",hAlignment="0",vAlignment="0",text="446465",fontName="微软雅黑",fontSize="18",height="55",width="172",x="90",y="24",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="24",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable