local tTable = {}

tTable["texturesPng"] = {"ui/p1_commonse1.plist"}
tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="174",width="240",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="337",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
img_line={classname="Panel",name="img_line",parName="default",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_line_blue1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="1",height="1",width="240",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1957",anchorPointX="0",anchorPointY="0",},
lay_info={classname="Panel",name="lay_info",parName="default",childCount="9",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="174",width="240",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1965",anchorPointX="0",anchorPointY="0",},
txt_no_hero_tip={classname="CustomLabel",name="txt_no_hero_tip",parName="default",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="130",y="98",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1967",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_3"] = {
img_arrow={classname="CustomImageView",name="img_arrow",parName="lay_info",ZOrder="0",fileName="#v1_img_lvqian.png",scale9Enable="false",scale9Height="22",scale9Width="50",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="22",width="50",x="29",y="157",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1955",anchorPointX="0.5",anchorPointY="0.5",},
txt_task={classname="CustomLabel",name="txt_task",parName="lay_info",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="空闲",fontName="微软雅黑",fontSize="20",height="27",width="40",x="28",y="158",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="343",anchorPointX="0.5",anchorPointY="0.5",},
txt_cd={classname="CustomLabel",name="txt_cd",parName="lay_info",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="111",y="83",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="345",anchorPointX="0",anchorPointY="0.5",},
lay_btn1={classname="Panel",name="lay_btn1",parName="lay_info",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="80",x="24",y="13",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="346",anchorPointX="0",anchorPointY="0",},
lay_btn2={classname="Panel",name="lay_btn2",parName="lay_info",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="80",x="136",y="14",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="347",anchorPointX="0",anchorPointY="0",},
lay_icon={classname="Panel",name="lay_icon",parName="lay_info",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="80",width="80",x="20",y="66",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1956",anchorPointX="0",anchorPointY="0",},
lay_mulit_icon={classname="Panel",name="lay_mulit_icon",parName="lay_info",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="80",width="80",x="19",y="65",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1959",anchorPointX="0",anchorPointY="0",},
lay_group_name={classname="Panel",name="lay_group_name",parName="lay_info",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="27",width="95",x="111",y="123",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9069",anchorPointX="0",anchorPointY="0",},
lay_location={classname="Panel",name="lay_location",parName="lay_info",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="80",width="80",x="19",y="67",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9070",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lay_icon1={classname="Panel",name="lay_icon1",parName="lay_mulit_icon",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="40",x="0",y="40",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1960",anchorPointX="0",anchorPointY="0",},
lay_icon2={classname="Panel",name="lay_icon2",parName="lay_mulit_icon",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="40",x="40",y="40",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1961",anchorPointX="0",anchorPointY="0",},
lay_icon3={classname="Panel",name="lay_icon3",parName="lay_mulit_icon",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="40",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1962",anchorPointX="0",anchorPointY="0",},
lay_icon4={classname="Panel",name="lay_icon4",parName="lay_mulit_icon",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="40",x="40",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1963",anchorPointX="0",anchorPointY="0",},
}

return tTable