local tTable = {}

tTable["texturesPng"] = {"ui/p2_commmon1_sep.plist","ui/language/cn/p2_font1.plist","icon/p1_icon2.plist","ui/p1_commonse1.plist","ui/p1_commmon1_sep.plist"}
tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="206",width="160",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="131",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_sel={classname="Panel",name="lay_sel",parName="default",ZOrder="21",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v2_tiexiaojiantou_kjy.png",height="175",width="146",x="7",y="-32",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="132",anchorPointX="0",anchorPointY="0",},
lay_icon={classname="Panel",name="lay_icon",parName="default",childCount="4",ZOrder="20",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="152",width="136",x="12",y="5",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="134",anchorPointX="0",anchorPointY="0",},
lay_line={classname="Panel",name="lay_line",parName="default",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_line_green.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="2",capInsetsY="3",height="50",width="4",x="78",y="155",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="139",anchorPointX="0",anchorPointY="0",},
img_locked={classname="ImageView",name="img_locked",parName="default",ZOrder="99",fileName="#v2_img_suo_kjy.png",scale9Enable="false",scale9Height="86",scale9Width="86",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="86",width="86",x="81",y="90",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="153",anchorPointX="0.5",anchorPointY="0.5",},
lay_lv={classname="Panel",name="lay_lv",parName="default",childCount="1",ZOrder="100",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_black50.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="10",height="22",width="64",x="48",y="40",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="678",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_man={classname="Panel",name="lay_man",parName="lay_icon",ZOrder="100",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v2_fonts_man.png",height="50",width="50",x="0",y="75",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="136",anchorPointX="0",anchorPointY="0",},
lb_name={classname="Label",name="lb_name",parName="lay_icon",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="68",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="646",anchorPointX="0.5",anchorPointY="0.5",},
img_tnoly={classname="ImageView",name="img_tnoly",parName="lay_icon",ZOrder="1",fileName="#i3001_s.png",scale9Enable="false",scale9Height="96",scale9Width="96",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="96",width="96",x="68",y="84",visible="true",touchAble="false",flipX="false",scaleX="0.9",scaleY="0.9",opacity="255",rotation="0",tag="647",anchorPointX="0.5",anchorPointY="0.5",},
img_icon_di={classname="ImageView",name="img_icon_di",parName="lay_icon",ZOrder="0",fileName="#v2_img_kejidi.png",scale9Enable="false",scale9Height="152",scale9Width="136",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="152",width="136",x="68",y="76",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="648",anchorPointX="0.5",anchorPointY="0.5",},
lb_lv={classname="Label",name="lb_lv",parName="lay_lv",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Lv.1",fontName="微软雅黑",fontSize="18",height="24",width="33",x="32",y="11",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="679",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable