local tTable = {}


tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="8",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="50",height="130",width="600",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="19",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
img_bg={classname="ImageView",name="img_bg",parName="default",ZOrder="0",fileName="#v1_img_kelashen6.png",scale9Enable="true",scale9Height="130",scale9Width="600",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="50",height="130",width="600",x="300",y="65",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="928",anchorPointX="0.5",anchorPointY="0.5",},
lay_blue_line={classname="Panel",name="lay_blue_line",parName="default",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_line_blue1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="1",height="1",width="580",x="11",y="88",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="21",anchorPointX="0",anchorPointY="0",},
txt_title={classname="CustomLabel",name="txt_title",parName="default",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="22",height="30",width="106",x="13",y="108",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="22",anchorPointX="0",anchorPointY="0.5",},
txt_time={classname="CustomLabel",name="txt_time",parName="default",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="22",height="30",width="106",x="588",y="108",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="23",anchorPointX="1",anchorPointY="0.5",},
img_icon={classname="ImageView",name="img_icon",parName="default",ZOrder="1",fileName="#v1_img_mail.png",scale9Enable="false",scale9Height="60",scale9Width="60",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="60",width="60",x="52",y="45",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="24",anchorPointX="0.5",anchorPointY="0.5",},
lay_content={classname="Panel",name="lay_content",parName="default",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="63",width="480",x="102",y="15",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="25",anchorPointX="0",anchorPointY="0",},
img_jianbian={classname="ImageView",name="img_jianbian",parName="default",ZOrder="0",fileName="#v2_img_kelashen6youjianweidu.png",scale9Enable="false",scale9Height="42",scale9Width="600",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="42",width="600",x="300",y="109",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="21805",anchorPointX="0.5",anchorPointY="0.5",},
img_new={classname="ImageView",name="img_new",parName="default",ZOrder="0",fileName="#v2_fonts_xin.png",scale9Enable="false",scale9Height="39",scale9Width="29",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="39",width="29",x="0",y="110",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="21806",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable