local tTable = {}

tTable["texturesPng"] = {"ui/p1_commmon2_sep.plist","ui/p2_commmon2_sep.plist","ui/p2_commmon3_sep.plist","ui/p2_commmon1_sep.plist"}
tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="90",width="90",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9178",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_attr={classname="Panel",name="lay_attr",parName="default",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="24",width="90",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9204",anchorPointX="0",anchorPointY="0",},
img_liang={classname="ImageView",name="img_liang",parName="default",ZOrder="0",fileName="#v2_img_xuanzhon.png",scale9Enable="false",scale9Height="101",scale9Width="101",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="101",width="101",x="45",y="58",visible="true",touchAble="false",flipX="false",scaleX="0.6999999",scaleY="0.6999999",opacity="255",rotation="0",tag="9181",anchorPointX="0.5",anchorPointY="0.5",},
img_longtu={classname="ImageView",name="img_longtu",parName="default",ZOrder="1",fileName="#v2_img_v2_btn_longtu.png",scale9Enable="false",scale9Height="54",scale9Width="54",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="54",width="54",x="45",y="59",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9183",anchorPointX="0.5",anchorPointY="0.5",},
lay_lock={classname="Panel",name="lay_lock",parName="default",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="54",width="54",x="18",y="31",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9184",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
img_di_attr={classname="ImageView",name="img_di_attr",parName="lay_attr",ZOrder="0",fileName="#v1_img_jzmzd.png",scale9Enable="false",scale9Height="28",scale9Width="112",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="28",width="112",x="44",y="10",visible="true",touchAble="false",flipX="false",scaleX="0.79999995",scaleY="0.79999995",opacity="255",rotation="0",tag="9192",anchorPointX="0.5",anchorPointY="0.5",},
lb_attr={classname="Label",name="lb_attr",parName="lay_attr",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="攻击+99",fontName="微软雅黑",fontSize="18",height="24",width="71",x="44",y="11",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9180",anchorPointX="0.5",anchorPointY="0.5",},
img_di={classname="ImageView",name="img_di",parName="lay_lock",ZOrder="0",fileName="#v2_img_v2_btn_longtudi.png",scale9Enable="false",scale9Height="54",scale9Width="54",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="54",width="54",x="27",y="27",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9182",anchorPointX="0.5",anchorPointY="0.5",},
img_lock={classname="ImageView",name="img_lock",parName="lay_lock",ZOrder="1",fileName="#v2_img_lock_tjp.png",scale9Enable="false",scale9Height="31",scale9Width="24",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="31",width="24",x="26",y="27",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9185",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable