local tTable = {}

tTable["texturesPng"] = {"ui/daitu.png","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","ui/language/cn/p1_font1.plist"}
tTable["index_1"] = {
item_fuben_section={classname="Panel",name="item_fuben_section",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="230",width="600",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
ly_main={classname="Panel",name="ly_main",parName="item_fuben_section",childCount="6",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="230",width="600",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="10",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
img_banner={classname="ImageView",name="img_banner",parName="ly_main",ZOrder="0",fileName="ui/daitu.png",scale9Enable="false",scale9Height="10",scale9Width="10",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="10",width="10",x="300",y="115",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="12",anchorPointX="0.5",anchorPointY="0.5",},
lb_title={classname="CustomLabel",name="lb_title",parName="ly_main",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="第四章节",fontName="微软雅黑",fontSize="24",height="31",width="96",x="19",y="210",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="11",anchorPointX="0",anchorPointY="0.5",},
Image_5={classname="ImageView",name="Image_5",parName="ly_main",ZOrder="1",fileName="#v1_img_xiaobiaoti.png",scale9Enable="false",scale9Height="37",scale9Width="594",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="37",width="594",x="300",y="208",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="21",anchorPointX="0.5",anchorPointY="0.5",},
lb_seciton_plan={classname="CustomLabel",name="lb_seciton_plan",parName="ly_main",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="24",height="31",width="116",x="575",y="210",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="22",anchorPointX="1",anchorPointY="0.5",},
ly_across={classname="Panel",name="ly_across",parName="ly_main",childCount="5",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="150",width="600",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="29",anchorPointX="0",anchorPointY="0",},
ly_show_reward={classname="Panel",name="ly_show_reward",parName="ly_main",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="150",width="360",x="0",y="1",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="37",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
img_reward_bg={classname="ImageView",name="img_reward_bg",parName="ly_across",ZOrder="0",fileName="#v1_img_kelashen2.png",scale9Enable="true",scale9Height="74",scale9Width="594",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="59",capInsetsY="18",height="74",width="594",x="299",y="39",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="36",anchorPointX="0.5",anchorPointY="0.5",},
img_start_3={classname="ImageView",name="img_start_3",parName="ly_across",ZOrder="1",fileName="#v1_img_stara.png",scale9Enable="false",scale9Height="58",scale9Width="58",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="58",width="58",x="561",y="34",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="35",anchorPointX="0.5",anchorPointY="0.5",},
img_start_2={classname="ImageView",name="img_start_2",parName="ly_across",ZOrder="1",fileName="#v1_img_stara.png",scale9Enable="false",scale9Height="58",scale9Width="58",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="58",width="58",x="495",y="34",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="34",anchorPointX="0.5",anchorPointY="0.5",},
img_start_1={classname="ImageView",name="img_start_1",parName="ly_across",ZOrder="1",fileName="#v1_img_stara.png",scale9Enable="false",scale9Height="58",scale9Width="58",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="58",width="58",x="430",y="34",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="33",anchorPointX="0.5",anchorPointY="0.5",},
img_across={classname="ImageView",name="img_across",parName="ly_across",ZOrder="0",fileName="#v1_fonts_yitongguan.png",scale9Enable="false",scale9Height="31",scale9Width="84",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="31",width="84",x="520",y="128",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="28",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable