local tTable = {}

tTable["texturesPng"] = {"ui/p2_commmon2_sep.plist","ui/p2_commmon1_sep.plist","ui/language/cn/p2_font1.plist","ui/p1_commmon2_sep.plist","ui/bar/v1_bar_b1.png","ui/p1_commonse2.plist"}
tTable["index_1"] = {
item_hero_info={classname="Panel",name="item_hero_info",parName="root",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="400",width="250",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="3994",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
ly_img={classname="Panel",name="ly_img",parName="item_hero_info",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="400",width="250",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="3996",anchorPointX="0",anchorPointY="0",},
ly_frame={classname="Panel",name="ly_frame",parName="item_hero_info",childCount="7",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="400",width="250",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="3997",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
img_frame={classname="CustomImageView",name="img_frame",parName="ly_frame",ZOrder="0",fileName="#v2_img_gauqkapaibai.png",scale9Enable="true",scale9Height="400",scale9Width="250",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="60",capInsetsY="0",height="400",width="250",x="0",y="0",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4058",anchorPointX="0",anchorPointY="0",},
img_type={classname="CustomImageView",name="img_type",parName="ly_frame",ZOrder="1",fileName="#v2_img_wj_gongbing.png",scale9Enable="false",scale9Height="52",scale9Width="53",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="52",width="53",x="26",y="374",visible="true",touchAble="false",flipX="false",scaleX="0.7",scaleY="0.7",opacity="255",rotation="0",tag="3998",anchorPointX="0.5",anchorPointY="0.5",},
img_god={classname="ImageView",name="img_god",parName="ly_frame",ZOrder="1",fileName="#v2_fonts_shen.png",scale9Enable="false",scale9Height="39",scale9Width="29",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="39",width="29",x="230",y="379",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4114",anchorPointX="0.5",anchorPointY="0.5",},
lb_name={classname="CustomLabel",name="lb_name",parName="ly_frame",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="124",areaWidth="24",hAlignment="0",vAlignment="0",text="东皇太一",fontName="微软雅黑",fontSize="24",height="124",width="24",x="12",y="340",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6334",anchorPointX="0",anchorPointY="1",},
lay_stars={classname="Panel",name="lay_stars",parName="ly_frame",childCount="5",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="100",width="38",x="4",y="147",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="5895",anchorPointX="0",anchorPointY="0",},
ly_talent={classname="Panel",name="ly_talent",parName="ly_frame",childCount="4",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="131",width="250",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4806",anchorPointX="0",anchorPointY="0",},
ly_attr={classname="Panel",name="ly_attr",parName="ly_frame",childCount="3",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="131",width="250",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4807",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
img_star1={classname="CustomImageView",name="img_star1",parName="lay_stars",ZOrder="1",fileName="#v1_img_star5.png",scale9Enable="false",scale9Height="38",scale9Width="40",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="38",width="40",x="20",y="89",visible="true",touchAble="false",flipX="false",scaleX="0.6",scaleY="0.6",opacity="255",rotation="0",tag="3999",anchorPointX="0.5",anchorPointY="0.5",},
img_star2={classname="CustomImageView",name="img_star2",parName="lay_stars",ZOrder="1",fileName="#v1_img_star5.png",scale9Enable="false",scale9Height="38",scale9Width="40",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="38",width="40",x="20",y="71",visible="true",touchAble="false",flipX="false",scaleX="0.6",scaleY="0.6",opacity="255",rotation="0",tag="4001",anchorPointX="0.5",anchorPointY="0.5",},
img_star3={classname="CustomImageView",name="img_star3",parName="lay_stars",ZOrder="1",fileName="#v1_img_star5.png",scale9Enable="false",scale9Height="38",scale9Width="40",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="38",width="40",x="20",y="53",visible="true",touchAble="false",flipX="false",scaleX="0.6",scaleY="0.6",opacity="255",rotation="0",tag="4003",anchorPointX="0.5",anchorPointY="0.5",},
img_star4={classname="CustomImageView",name="img_star4",parName="lay_stars",ZOrder="1",fileName="#v1_img_star5.png",scale9Enable="false",scale9Height="38",scale9Width="40",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="38",width="40",x="20",y="35",visible="true",touchAble="false",flipX="false",scaleX="0.6",scaleY="0.6",opacity="255",rotation="0",tag="4007",anchorPointX="0.5",anchorPointY="0.5",},
img_star5={classname="CustomImageView",name="img_star5",parName="lay_stars",ZOrder="1",fileName="#v1_img_star5.png",scale9Enable="false",scale9Height="38",scale9Width="40",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="38",width="40",x="20",y="17",visible="true",touchAble="false",flipX="false",scaleX="0.6",scaleY="0.6",opacity="255",rotation="0",tag="4005",anchorPointX="0.5",anchorPointY="0.5",},
ly_bar1={classname="Panel",name="ly_bar1",parName="ly_talent",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="250",x="0",y="99",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4010",anchorPointX="0",anchorPointY="0",},
ly_bar2={classname="Panel",name="ly_bar2",parName="ly_talent",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="250",x="0",y="68",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4012",anchorPointX="0",anchorPointY="0",},
ly_bar3={classname="Panel",name="ly_bar3",parName="ly_talent",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="250",x="0",y="37",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4015",anchorPointX="0",anchorPointY="0",},
ly_bar4={classname="Panel",name="ly_bar4",parName="ly_talent",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="250",x="0",y="4",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4017",anchorPointX="0",anchorPointY="0",},
ly_attr_bar1={classname="Panel",name="ly_attr_bar1",parName="ly_attr",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="250",x="0",y="91",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4808",anchorPointX="0",anchorPointY="0",},
ly_attr_bar2={classname="Panel",name="ly_attr_bar2",parName="ly_attr",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="250",x="0",y="53",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4810",anchorPointX="0",anchorPointY="0",},
ly_attr_bar3={classname="Panel",name="ly_attr_bar3",parName="ly_attr",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="250",x="0",y="15",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4811",anchorPointX="0",anchorPointY="0",},
}
tTable["index_5"] = {
lb_info_n_1={classname="Label",name="lb_info_n_1",parName="ly_bar1",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="资质",fontName="微软雅黑",fontSize="18",height="24",width="36",x="16",y="15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4022",anchorPointX="0",anchorPointY="0.5",},
bar_1={classname="Panel",name="bar_1",parName="ly_bar1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v1_bar_b1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="45",capInsetsY="9",height="13",width="93",x="58",y="8",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4020",anchorPointX="0",anchorPointY="0",},
lb_value_1={classname="Label",name="lb_value_1",parName="ly_bar1",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="999",fontName="微软雅黑",fontSize="18",height="24",width="33",x="154",y="15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4018",anchorPointX="0",anchorPointY="0.5",},
lb_value_add_1={classname="Label",name="lb_value_add_1",parName="ly_bar1",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="+99",fontName="微软雅黑",fontSize="18",height="24",width="35",x="187",y="15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4026",anchorPointX="0",anchorPointY="0.5",},
img_arrow_1={classname="CustomImageView",name="img_arrow_1",parName="ly_bar1",ZOrder="0",fileName="#v1_img_xiangshangjiantou.png",scale9Enable="false",scale9Height="17",scale9Width="12",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="17",width="12",x="236",y="15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4027",anchorPointX="0.5",anchorPointY="0.5",},
lb_info_n_2={classname="Label",name="lb_info_n_2",parName="ly_bar2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="攻",fontName="微软雅黑",fontSize="18",height="24",width="18",x="18",y="15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4033",anchorPointX="0",anchorPointY="0.5",},
bar_2={classname="Panel",name="bar_2",parName="ly_bar2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v1_bar_b1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="45",capInsetsY="9",height="13",width="93",x="58",y="8",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4034",anchorPointX="0",anchorPointY="0",},
lb_value_2={classname="Label",name="lb_value_2",parName="ly_bar2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="999",fontName="微软雅黑",fontSize="18",height="24",width="33",x="154",y="15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4035",anchorPointX="0",anchorPointY="0.5",},
lb_value_add_2={classname="Label",name="lb_value_add_2",parName="ly_bar2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="+99",fontName="微软雅黑",fontSize="18",height="24",width="35",x="187",y="15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4036",anchorPointX="0",anchorPointY="0.5",},
img_arrow_2={classname="CustomImageView",name="img_arrow_2",parName="ly_bar2",ZOrder="0",fileName="#v1_img_xiangshangjiantou.png",scale9Enable="false",scale9Height="17",scale9Width="12",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="17",width="12",x="236",y="15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4037",anchorPointX="0.5",anchorPointY="0.5",},
img_arrow_3={classname="CustomImageView",name="img_arrow_3",parName="ly_bar3",ZOrder="0",fileName="#v1_img_xiangshangjiantou.png",scale9Enable="false",scale9Height="17",scale9Width="12",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="17",width="12",x="236",y="14",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4047",anchorPointX="0.5",anchorPointY="0.5",},
lb_info_n_3={classname="Label",name="lb_info_n_3",parName="ly_bar3",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="防",fontName="微软雅黑",fontSize="18",height="24",width="18",x="18",y="15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4043",anchorPointX="0",anchorPointY="0.5",},
bar_3={classname="Panel",name="bar_3",parName="ly_bar3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v1_bar_b1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="45",capInsetsY="9",height="13",width="93",x="58",y="8",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4044",anchorPointX="0",anchorPointY="0",},
lb_value_3={classname="Label",name="lb_value_3",parName="ly_bar3",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="999",fontName="微软雅黑",fontSize="18",height="24",width="33",x="154",y="15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4045",anchorPointX="0",anchorPointY="0.5",},
lb_value_add_3={classname="Label",name="lb_value_add_3",parName="ly_bar3",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="+99",fontName="微软雅黑",fontSize="18",height="24",width="35",x="187",y="15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4046",anchorPointX="0",anchorPointY="0.5",},
lb_info_n_4={classname="Label",name="lb_info_n_4",parName="ly_bar4",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="兵",fontName="微软雅黑",fontSize="18",height="24",width="18",x="18",y="15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4048",anchorPointX="0",anchorPointY="0.5",},
bar_4={classname="Panel",name="bar_4",parName="ly_bar4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v1_bar_b1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="45",capInsetsY="9",height="13",width="93",x="58",y="8",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4049",anchorPointX="0",anchorPointY="0",},
lb_value_4={classname="Label",name="lb_value_4",parName="ly_bar4",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="999",fontName="微软雅黑",fontSize="18",height="24",width="33",x="154",y="15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4050",anchorPointX="0",anchorPointY="0.5",},
lb_value_add_4={classname="Label",name="lb_value_add_4",parName="ly_bar4",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="+99",fontName="微软雅黑",fontSize="18",height="24",width="35",x="187",y="15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4051",anchorPointX="0",anchorPointY="0.5",},
img_arrow_4={classname="CustomImageView",name="img_arrow_4",parName="ly_bar4",ZOrder="0",fileName="#v1_img_xiangshangjiantou.png",scale9Enable="false",scale9Height="17",scale9Width="12",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="17",width="12",x="236",y="14",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4052",anchorPointX="0.5",anchorPointY="0.5",},
img_attr_1={classname="ImageView",name="img_attr_1",parName="ly_attr_bar1",ZOrder="0",fileName="#v2_img_wj_gongji.png",scale9Enable="false",scale9Height="29",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="29",width="31",x="36",y="15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4816",anchorPointX="0.5",anchorPointY="0.5",},
lb_attr_1={classname="CustomLabel",name="lb_attr_1",parName="ly_attr_bar1",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="攻击",fontName="微软雅黑",fontSize="20",height="27",width="40",x="75",y="16",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4860",anchorPointX="0.5",anchorPointY="0.5",},
lb_attr_value_1={classname="CustomLabel",name="lb_attr_value_1",parName="ly_attr_bar1",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="20",height="27",width="48",x="121",y="14",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4861",anchorPointX="0",anchorPointY="0.5",},
lb_attr_value_add_1={classname="CustomLabel",name="lb_attr_value_add_1",parName="ly_attr_bar1",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="20",height="27",width="48",x="177",y="14",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4863",anchorPointX="0",anchorPointY="0.5",},
img_attr_2={classname="CustomImageView",name="img_attr_2",parName="ly_attr_bar2",ZOrder="0",fileName="#v2_img_wj_fangyu.png",scale9Enable="false",scale9Height="29",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="29",width="31",x="36",y="15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4890",anchorPointX="0.5",anchorPointY="0.5",},
lb_attr_2={classname="CustomLabel",name="lb_attr_2",parName="ly_attr_bar2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="防御",fontName="微软雅黑",fontSize="20",height="27",width="40",x="76",y="16",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4891",anchorPointX="0.5",anchorPointY="0.5",},
lb_attr_value_2={classname="CustomLabel",name="lb_attr_value_2",parName="ly_attr_bar2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="20",height="27",width="48",x="121",y="14",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4892",anchorPointX="0",anchorPointY="0.5",},
lb_attr_value_add_2={classname="CustomLabel",name="lb_attr_value_add_2",parName="ly_attr_bar2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="20",height="27",width="48",x="178",y="14",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4893",anchorPointX="0",anchorPointY="0.5",},
img_attr_3={classname="CustomImageView",name="img_attr_3",parName="ly_attr_bar3",ZOrder="0",fileName="#v2_img_wj_bingli.png",scale9Enable="false",scale9Height="29",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="29",width="31",x="36",y="15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4894",anchorPointX="0.5",anchorPointY="0.5",},
lb_attr_3={classname="CustomLabel",name="lb_attr_3",parName="ly_attr_bar3",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="兵力",fontName="微软雅黑",fontSize="20",height="27",width="40",x="75",y="15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4895",anchorPointX="0.5",anchorPointY="0.5",},
lb_attr_value_3={classname="CustomLabel",name="lb_attr_value_3",parName="ly_attr_bar3",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="20",height="27",width="48",x="121",y="14",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4896",anchorPointX="0",anchorPointY="0.5",},
lb_attr_value_add_3={classname="CustomLabel",name="lb_attr_value_add_3",parName="ly_attr_bar3",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="20",height="27",width="48",x="178",y="14",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="4897",anchorPointX="0",anchorPointY="0.5",},
}

return tTable