local tTable = {}


tTable["index_1"] = {
root={classname="Panel",name="root",parName="root",childCount="7",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="50",height="120",width="526",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="824",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_civil_kuang={classname="Panel",name="lay_civil_kuang",parName="root",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="88",width="88",x="19",y="17",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="840",anchorPointX="0",anchorPointY="0",},
lay_civil_value={classname="Panel",name="lay_civil_value",parName="root",childCount="6",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="120",width="270",x="108",y="0",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="841",anchorPointX="0",anchorPointY="0",},
lay_locked={classname="Panel",name="lay_locked",parName="root",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_black50.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="10",height="120",width="526",x="0",y="0",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="855",anchorPointX="0",anchorPointY="0",},
lb_status={classname="Label",name="lb_status",parName="root",ZOrder="1",colorB="40",colorG="37",colorR="245",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="王宫等级Lv.60解锁",fontName="微软雅黑",fontSize="20",height="27",width="170",x="433",y="60",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="851",anchorPointX="0.5",anchorPointY="0.5",},
lay_btn_employ={classname="Panel",name="lay_btn_employ",parName="root",ZOrder="4",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="388",y="17",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="848",anchorPointX="0",anchorPointY="0",},
lay_researcher_value={classname="Panel",name="lay_researcher_value",parName="root",childCount="4",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="120",width="270",x="108",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="892",anchorPointX="0",anchorPointY="0",},
img_line={classname="ImageView",name="img_line",parName="root",ZOrder="4",fileName="#v1_line_blue1.png",scale9Enable="true",scale9Height="2",scale9Width="514",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="1",height="2",width="514",x="263",y="0",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1788",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_3"] = {
lb_civil_name={classname="Label",name="lb_civil_name",parName="lay_civil_value",ZOrder="0",colorB="64",colorG="216",colorR="49",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="文官名字",fontName="微软雅黑",fontSize="20",height="27",width="80",x="14",y="90",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="842",anchorPointX="0",anchorPointY="0.5",},
lb_civil_lv={classname="Label",name="lb_civil_lv",parName="lay_civil_value",ZOrder="0",colorB="253",colorG="212",colorR="119",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Lv.5",fontName="微软雅黑",fontSize="20",height="27",width="38",x="193",y="90",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="843",anchorPointX="0.5",anchorPointY="0.5",},
lb_func1={classname="Label",name="lb_func1",parName="lay_civil_value",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="增加基础资源产量",fontName="微软雅黑",fontSize="18",height="24",width="144",x="14",y="45",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="844",anchorPointX="0",anchorPointY="0",},
lb_func2={classname="Label",name="lb_func2",parName="lay_civil_value",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="资源加速：",fontName="微软雅黑",fontSize="18",height="24",width="90",x="14",y="19",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="845",anchorPointX="0",anchorPointY="0",},
lb_func2_value={classname="Label",name="lb_func2_value",parName="lay_civil_value",ZOrder="0",colorB="253",colorG="212",colorR="119",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="铜钱，木，粮",fontName="微软雅黑",fontSize="18",height="24",width="108",x="110",y="19",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="846",anchorPointX="0",anchorPointY="0",},
lb_func1_value={classname="Label",name="lb_func1_value",parName="lay_civil_value",ZOrder="0",colorB="64",colorG="216",colorR="49",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="+20%",fontName="微软雅黑",fontSize="18",height="24",width="51",x="179",y="45",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="847",anchorPointX="0",anchorPointY="0",},
lb_rs_name={classname="Label",name="lb_rs_name",parName="lay_researcher_value",ZOrder="0",colorB="64",colorG="216",colorR="49",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="文官名字",fontName="微软雅黑",fontSize="22",height="30",width="88",x="14",y="97",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="893",anchorPointX="0",anchorPointY="0.5",},
lb_rs_lv={classname="Label",name="lb_rs_lv",parName="lay_researcher_value",ZOrder="0",colorB="253",colorG="212",colorR="119",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Lv.5",fontName="微软雅黑",fontSize="20",height="27",width="38",x="193",y="100",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="894",anchorPointX="0.5",anchorPointY="0.5",},
lb_func3={classname="Label",name="lb_func3",parName="lay_researcher_value",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="75",areaWidth="220",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="75",width="220",x="14",y="78",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1078",anchorPointX="0",anchorPointY="1",},
lb_time={classname="Label",name="lb_time",parName="lay_researcher_value",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="14",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1141",anchorPointX="0",anchorPointY="0",},
}

return tTable