local tTable = {}

tTable["texturesPng"] = {"ui/p1_commonse1.plist"}
tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="17",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="540",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
img_arrow={classname="CustomImageView",name="img_arrow",parName="default",ZOrder="2",fileName="#v1_img_lanbiaoqian.png",scale9Enable="false",scale9Height="22",scale9Width="50",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="22",width="50",x="29",y="96",visible="true",touchAble="false",flipX="false",scaleX="0.8",scaleY="0.8",opacity="255",rotation="0",tag="10",anchorPointX="0.5",anchorPointY="0.5",},
txt_name={classname="CustomLabel",name="txt_name",parName="default",ZOrder="3",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="139",y="79",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="12",anchorPointX="0",anchorPointY="0.5",},
txt_pos={classname="CustomLabel",name="txt_pos",parName="default",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="139",y="55",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="13",anchorPointX="0",anchorPointY="0.5",},
lay_cd={classname="Panel",name="lay_cd",parName="default",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="45",capInsetsY="9",height="18",width="146",x="134",y="18",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="14",anchorPointX="0",anchorPointY="0",},
lay_btn1={classname="Panel",name="lay_btn1",parName="default",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="35",width="77",x="352",y="29",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="15",anchorPointX="0",anchorPointY="0",},
lay_btn2={classname="Panel",name="lay_btn2",parName="default",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="35",width="77",x="442",y="29",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="16",anchorPointX="0",anchorPointY="0",},
txt_tip={classname="CustomLabel",name="txt_tip",parName="default",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="286",y="55",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="18",anchorPointX="0.5",anchorPointY="0.5",},
txt_cd={classname="CustomLabel",name="txt_cd",parName="default",ZOrder="3",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="15",height="20",width="75",x="208",y="26",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="19",anchorPointX="0.5",anchorPointY="0.5",},
txt_task={classname="CustomLabel",name="txt_task",parName="default",ZOrder="3",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="14",height="20",width="68",x="10",y="98",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="33",anchorPointX="0",anchorPointY="0.5",},
lay_location={classname="Panel",name="lay_location",parName="default",ZOrder="4",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="87",width="87",x="20",y="8",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="34",anchorPointX="0",anchorPointY="0",},
lay_icon={classname="Panel",name="lay_icon",parName="default",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="87",width="87",x="20",y="8",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="11",anchorPointX="0",anchorPointY="0",},
lay_city_icon={classname="Panel",name="lay_city_icon",parName="default",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="75",width="120",x="3",y="17",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="52",anchorPointX="0",anchorPointY="0",},
lay_mulit_icon={classname="Panel",name="lay_mulit_icon",parName="default",childCount="4",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="87",width="87",x="20",y="8",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="35",anchorPointX="0",anchorPointY="0",},
lay_head_icon={classname="Panel",name="lay_head_icon",parName="default",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="86",width="86",x="20",y="8",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="80",anchorPointX="0",anchorPointY="0",},
lay_bg={classname="Panel",name="lay_bg",parName="default",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="540",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="97",anchorPointX="0",anchorPointY="0",},
lay_collect_hero_lock={classname="Panel",name="lay_collect_hero_lock",parName="default",childCount="4",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="540",x="0",y="0",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="98",anchorPointX="0",anchorPointY="0",},
img_line={classname="ImageView",name="img_line",parName="default",ZOrder="10",fileName="#v1_line_blue1.png",scale9Enable="true",scale9Height="2",scale9Width="510",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="1",height="2",width="510",x="285",y="0",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="115",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_3"] = {
lay_icon1={classname="Panel",name="lay_icon1",parName="lay_mulit_icon",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="36",width="36",x="0",y="39",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="36",anchorPointX="0",anchorPointY="0",},
lay_icon2={classname="Panel",name="lay_icon2",parName="lay_mulit_icon",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="36",width="36",x="37",y="38",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="37",anchorPointX="0",anchorPointY="0",},
lay_icon3={classname="Panel",name="lay_icon3",parName="lay_mulit_icon",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="36",width="36",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="38",anchorPointX="0",anchorPointY="0",},
lay_icon4={classname="Panel",name="lay_icon4",parName="lay_mulit_icon",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="36",width="36",x="37",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="39",anchorPointX="0",anchorPointY="0",},
lay_btn_unlock={classname="Panel",name="lay_btn_unlock",parName="lay_collect_hero_lock",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="35",width="77",x="442",y="16",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="96",anchorPointX="0",anchorPointY="0",},
txt_unlock_tip2={classname="CustomLabel",name="txt_unlock_tip2",parName="lay_collect_hero_lock",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="149",y="38",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="94",anchorPointX="0",anchorPointY="0.5",},
txt_unlock_tip1={classname="CustomLabel",name="txt_unlock_tip1",parName="lay_collect_hero_lock",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="151",y="70",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="93",anchorPointX="0",anchorPointY="0.5",},
lay_lock_icon={classname="Panel",name="lay_lock_icon",parName="lay_collect_hero_lock",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="87",width="87",x="30",y="13",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="99",anchorPointX="0",anchorPointY="0",},
}

return tTable