local tTable = {}

tTable["texturesPng"] = {"ui/p1_commmon2_sep.plist","ui/p1_commonse1.plist","ui/language/cn/p2_font_sep.plist"}
tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen6.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="50",height="180",width="600",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="17",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_up={classname="Panel",name="lay_up",parName="default",childCount="3",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="44",width="600",x="0",y="136",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="18",anchorPointX="0",anchorPointY="0",},
img_line={classname="ImageView",name="img_line",parName="default",ZOrder="2",fileName="#v1_line_blue1.png",scale9Enable="true",scale9Height="2",scale9Width="600",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="1",height="2",width="600",x="300",y="135",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="21",anchorPointX="0.5",anchorPointY="0.5",},
lay_down={classname="Panel",name="lay_down",parName="default",childCount="4",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="135",width="600",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="20",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
img_up={classname="ImageView",name="img_up",parName="lay_up",ZOrder="1",fileName="#v1_img_kelashen6_b.png",scale9Enable="true",scale9Height="44",scale9Width="350",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="200",capInsetsY="9",height="44",width="350",x="175",y="22",visible="true",touchAble="false",flipX="true",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="22",anchorPointX="0.5",anchorPointY="0.5",},
lb_day={classname="Label",name="lb_day",parName="lay_up",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="第5天：",fontName="微软雅黑",fontSize="20",height="27",width="72",x="10",y="22",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="33",anchorPointX="0",anchorPointY="0.5",},
lb_task={classname="Label",name="lb_task",parName="lay_up",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="81",y="22",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="25",anchorPointX="0",anchorPointY="0.5",},
lay_awards={classname="Panel",name="lay_awards",parName="lay_down",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="125",width="427",x="10",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="26",anchorPointX="0",anchorPointY="0",},
lay_btn={classname="Panel",name="lay_btn",parName="lay_down",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="455",y="42",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="27",anchorPointX="0",anchorPointY="0",},
lb_progress={classname="Label",name="lb_progress",parName="lay_down",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="520",y="105",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="28",anchorPointX="0.5",anchorPointY="0",},
img_state={classname="ImageView",name="img_state",parName="lay_down",ZOrder="0",fileName="#v2_fonts_weidadao.png",scale9Enable="false",scale9Height="46",scale9Width="140",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="46",width="140",x="528",y="65",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="29",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable