local tTable = {}

tTable["texturesPng"] = {"ui/p1_commmon5_sep.plist","ui/language/cn/p2_font1.plist","icon/p1_icon_font.plist","ui/p1_commonse2.plist"}
tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="180",width="600",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1154",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_icon={classname="Panel",name="lay_icon",parName="default",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="87",width="87",x="522",y="97",visible="true",touchAble="true",flipX="false",scaleX="0.88",scaleY="0.88",opacity="255",rotation="0",tag="1175",anchorPointX="0",anchorPointY="0",},
lay_content={classname="Panel",name="lay_content",parName="default",childCount="7",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="124",width="335",x="159",y="16",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1174",anchorPointX="0",anchorPointY="0",},
lay_name={classname="Panel",name="lay_name",parName="default",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="460",x="35",y="147",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1176",anchorPointX="0",anchorPointY="0",},
ly_pos={classname="Panel",name="ly_pos",parName="default",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="460",x="106",y="5",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1178",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
img_bg={classname="ImageView",name="img_bg",parName="lay_content",ZOrder="0",fileName="#v2_img_liaotiankapian2.png",scale9Enable="false",scale9Height="124",scale9Width="335",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="124",width="335",x="168",y="62",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1155",anchorPointX="0.5",anchorPointY="0.5",},
img_title={classname="ImageView",name="img_title",parName="lay_content",ZOrder="1",fileName="#v2_fonts_guozhan_lt.png",scale9Enable="false",scale9Height="47",scale9Width="21",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="47",width="21",x="20",y="62",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1157",anchorPointX="0.5",anchorPointY="0.5",},
lay_target={classname="Panel",name="lay_target",parName="lay_content",childCount="2",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="27",width="150",x="48",y="81",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1158",anchorPointX="0",anchorPointY="0",},
lay_pos={classname="Panel",name="lay_pos",parName="lay_content",childCount="2",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="27",width="150",x="48",y="49",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1166",anchorPointX="0",anchorPointY="0",},
lb_detail={classname="Label",name="lb_detail",parName="lay_content",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="目标：",fontName="微软雅黑",fontSize="20",height="27",width="60",x="48",y="13",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1170",anchorPointX="0",anchorPointY="0",},
lay_build_icon={classname="Panel",name="lay_build_icon",parName="lay_content",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="80",width="80",x="230",y="17",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1172",anchorPointX="0",anchorPointY="0",},
img_country={classname="ImageView",name="img_country",parName="lay_content",ZOrder="2",fileName="#v1_img_han.png",scale9Enable="false",scale9Height="64",scale9Width="51",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="64",width="51",x="311",y="102",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1173",anchorPointX="0.5",anchorPointY="0.5",},
img_laba={classname="ImageView",name="img_laba",parName="lay_name",ZOrder="0",fileName="#v1_img_headlaba.png",scale9Enable="false",scale9Height="72",scale9Width="72",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="72",width="72",x="345",y="14",visible="true",touchAble="false",flipX="false",scaleX="0.39999992",scaleY="0.39999992",opacity="255",rotation="0",tag="1179",anchorPointX="0.5",anchorPointY="0.5",},
lb_pos={classname="Label",name="lb_pos",parName="ly_pos",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="14",height="20",width="68",x="30",y="20",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1180",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_4"] = {
lb_target_title={classname="Label",name="lb_target_title",parName="lay_target",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="目标：",fontName="微软雅黑",fontSize="20",height="27",width="60",x="0",y="0",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1159",anchorPointX="0",anchorPointY="0",},
lb_target={classname="Label",name="lb_target",parName="lay_target",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="59",y="0",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1162",anchorPointX="0",anchorPointY="0",},
lb_pos_title={classname="Label",name="lb_pos_title",parName="lay_pos",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="坐标：",fontName="微软雅黑",fontSize="20",height="27",width="60",x="0",y="0",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1167",anchorPointX="0",anchorPointY="0",},
lb_target_pos={classname="Label",name="lb_target_pos",parName="lay_pos",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="59",y="0",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1168",anchorPointX="0",anchorPointY="0",},
}

return tTable