local tTable = {}

tTable["texturesPng"] = {"ui/p1_commmon5_sep.plist","ui/p1_commmon3_sep.plist","ui/bar/v1_bar_b2.png","ui/language/cn/p1_font1.plist"}
tTable["index_1"] = {
item_fuben_buy_hero={classname="Panel",name="item_fuben_buy_hero",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="448",width="238",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="174",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
ly_main={classname="Panel",name="ly_main",parName="item_fuben_buy_hero",childCount="15",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="448",width="238",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="176",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
img_bg={classname="ImageView",name="img_bg",parName="ly_main",ZOrder="0",fileName="#v1_img_gauqkapaicheng.png",scale9Enable="true",scale9Height="448",scale9Width="238",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="59",capInsetsY="179",height="448",width="238",x="0",y="0",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="186",anchorPointX="0",anchorPointY="0",},
ly_hero={classname="Panel",name="ly_hero",parName="ly_main",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kapai.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="25",capInsetsY="25",height="235",width="182",x="28",y="188",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="177",anchorPointX="0",anchorPointY="0",},
lb_ex={classname="CustomLabel",name="lb_ex",parName="ly_main",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="1",fontName="微软雅黑",fontSize="20",height="27",width="12",x="204",y="215",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="668",anchorPointX="0",anchorPointY="0.5",},
ly_bar_1={classname="Panel",name="ly_bar_1",parName="ly_main",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="ui/bar/v1_bar_b2.png",height="12",width="83",x="68",y="155",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="192",anchorPointX="0",anchorPointY="0",},
ly_bar_2={classname="Panel",name="ly_bar_2",parName="ly_main",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="ui/bar/v1_bar_b2.png",height="12",width="83",x="68",y="114",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="193",anchorPointX="0",anchorPointY="0",},
ly_bar_3={classname="Panel",name="ly_bar_3",parName="ly_main",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="ui/bar/v1_bar_b2.png",height="12",width="83",x="68",y="75",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="194",anchorPointX="0",anchorPointY="0",},
ly_bar_4={classname="Panel",name="ly_bar_4",parName="ly_main",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="ui/bar/v1_bar_b2.png",height="12",width="83",x="68",y="35",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="195",anchorPointX="0",anchorPointY="0",},
Image_8={classname="ImageView",name="Image_8",parName="ly_main",ZOrder="1",fileName="#v1_fonts_bing.png",scale9Enable="false",scale9Height="18",scale9Width="20",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="18",width="20",x="26",y="41",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="196",anchorPointX="0.5",anchorPointY="0.5",},
Image_8_0={classname="ImageView",name="Image_8_0",parName="ly_main",ZOrder="1",fileName="#v1_fonts_gong.png",scale9Enable="false",scale9Height="19",scale9Width="20",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="19",width="20",x="26",y="121",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="198",anchorPointX="0.5",anchorPointY="0.5",},
Image_8_1={classname="ImageView",name="Image_8_1",parName="ly_main",ZOrder="1",fileName="#v1_fonts_zizhi.png",scale9Enable="false",scale9Height="19",scale9Width="45",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="19",width="45",x="38",y="161",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="199",anchorPointX="0.5",anchorPointY="0.5",},
Image_8_2={classname="ImageView",name="Image_8_2",parName="ly_main",ZOrder="1",fileName="#v1_fonts_fang.png",scale9Enable="false",scale9Height="20",scale9Width="19",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="20",width="19",x="26",y="81",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="200",anchorPointX="0.5",anchorPointY="0.5",},
lb_baseinfo_1={classname="CustomLabel",name="lb_baseinfo_1",parName="ly_main",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="100",fontName="微软雅黑",fontSize="20",height="27",width="36",x="160",y="161",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="204",anchorPointX="0",anchorPointY="0.5",},
lb_baseinfo_4={classname="CustomLabel",name="lb_baseinfo_4",parName="ly_main",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="100",fontName="微软雅黑",fontSize="20",height="27",width="36",x="160",y="41",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="205",anchorPointX="0",anchorPointY="0.5",},
lb_baseinfo_3={classname="CustomLabel",name="lb_baseinfo_3",parName="ly_main",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="100",fontName="微软雅黑",fontSize="20",height="27",width="36",x="160",y="81",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="206",anchorPointX="0",anchorPointY="0.5",},
lb_baseinfo_2={classname="CustomLabel",name="lb_baseinfo_2",parName="ly_main",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="100",fontName="微软雅黑",fontSize="20",height="27",width="36",x="160",y="121",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="207",anchorPointX="0",anchorPointY="0.5",},
}

return tTable