local tTable = {}

tTable["texturesPng"] = {"ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commonse1.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","icon/p1_icon_ui.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","ui/bg_world/v1_img_shijieditu.jpg","ui/p1_commmon1_sep.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","ui/p1_button1.plist","ui/p1_commonse1.plist","ui/bar/v1_bar_b1.png"}
tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="80",width="560",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="300",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
txt_level={classname="CustomLabel",name="txt_level",parName="default",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="51",y="42",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="301",anchorPointX="0.5",anchorPointY="0.5",},
txt_name={classname="CustomLabel",name="txt_name",parName="default",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="155",y="42",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="302",anchorPointX="0.5",anchorPointY="0.5",},
txt_hero_name={classname="CustomLabel",name="txt_hero_name",parName="default",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="260",y="42",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="303",anchorPointX="0.5",anchorPointY="0.5",},
txt_troops={classname="CustomLabel",name="txt_troops",parName="default",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="364",y="41",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="304",anchorPointX="0.5",anchorPointY="0.5",},
lay_btn_cancel={classname="Panel",name="lay_btn_cancel",parName="default",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="80",x="420",y="22",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="305",anchorPointX="0",anchorPointY="0",},
}

return tTable