local tTable = {}

tTable["texturesPng"] = {"ui/big_img_sep/v2_img_duizhandiyoujian_jzhc.png","ui/language/cn/p2_font2.plist","ui/p1_commmon5_sep.plist","icon/p1_icon_font.plist"}
tTable["index_1"] = {
view={classname="Panel",name="view",parName="root",childCount="17",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/big_img_sep/v2_img_duizhandiyoujian_jzhc.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="278",capInsetsY="6",height="110",width="556",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="522",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_player_left={classname="Panel",name="lay_player_left",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="87",width="87",x="9",y="12",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="524",anchorPointX="0",anchorPointY="0",},
lay_player_right={classname="Panel",name="lay_player_right",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="87",width="87",x="460",y="14",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="525",anchorPointX="0",anchorPointY="0",},
txt_name_left={classname="CustomLabel",name="txt_name_left",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="105",y="87",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="526",anchorPointX="0",anchorPointY="0.5",},
txt_troops_left={classname="CustomLabel",name="txt_troops_left",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="105",y="66",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="527",anchorPointX="0",anchorPointY="0.5",},
txt_kill_left={classname="CustomLabel",name="txt_kill_left",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="105",y="44",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="528",anchorPointX="0",anchorPointY="0.5",},
txt_score_left={classname="CustomLabel",name="txt_score_left",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="105",y="22",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="529",anchorPointX="0",anchorPointY="0.5",},
img_win_left={classname="CustomImageView",name="img_win_left",parName="view",ZOrder="1",fileName="#v2_img_shengli_jzhc.png",scale9Enable="false",scale9Height="26",scale9Width="48",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="26",width="48",x="52",y="11",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="530",anchorPointX="0.5",anchorPointY="0.5",},
txt_name_right={classname="CustomLabel",name="txt_name_right",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="453",y="87",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="531",anchorPointX="1",anchorPointY="0.5",},
txt_troops_right={classname="CustomLabel",name="txt_troops_right",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="453",y="66",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="532",anchorPointX="1",anchorPointY="0.5",},
txt_kill_right={classname="CustomLabel",name="txt_kill_right",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="453",y="44",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="533",anchorPointX="1",anchorPointY="0.5",},
txt_score_right={classname="CustomLabel",name="txt_score_right",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="453",y="20",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="534",anchorPointX="1",anchorPointY="0.5",},
img_win_right={classname="CustomImageView",name="img_win_right",parName="view",ZOrder="1",fileName="#v2_img_shengli_jzhc.png",scale9Enable="false",scale9Height="26",scale9Width="48",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="26",width="48",x="504",y="11",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="535",anchorPointX="0.5",anchorPointY="0.5",},
img_play={classname="CustomImageView",name="img_play",parName="view",ZOrder="0",fileName="#v2_btn_huifang.png",scale9Enable="false",scale9Height="72",scale9Width="72",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="72",width="72",x="279",y="44",visible="true",touchAble="false",flipX="false",scaleX="0.6",scaleY="0.6",opacity="255",rotation="0",tag="536",anchorPointX="0.5",anchorPointY="0.5",},
lay_btn_replay={classname="Panel",name="lay_btn_replay",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="80",width="100",x="229",y="15",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="750",anchorPointX="0",anchorPointY="0",},
img_flag_left={classname="CustomImageView",name="img_flag_left",parName="view",ZOrder="3",fileName="#v1_img_qun.png",scale9Enable="false",scale9Height="64",scale9Width="51",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="64",width="51",x="26",y="81",visible="true",touchAble="false",flipX="false",scaleX="0.8",scaleY="0.8",opacity="255",rotation="0",tag="1086",anchorPointX="0.5",anchorPointY="0.5",},
img_flag_right={classname="CustomImageView",name="img_flag_right",parName="view",ZOrder="3",fileName="#v1_img_qun.png",scale9Enable="false",scale9Height="64",scale9Width="51",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="64",width="51",x="478",y="83",visible="true",touchAble="false",flipX="false",scaleX="0.8",scaleY="0.8",opacity="255",rotation="0",tag="1087",anchorPointX="0.5",anchorPointY="0.5",},
lay_light={classname="Panel",name="lay_light",parName="view",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="13",capInsetsY="30",height="110",width="556",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="570",anchorPointX="0",anchorPointY="0",},
}

return tTable