local tTable = {}

tTable["texturesPng"] = {"ui/p1_commmon2_sep.plist"}
tTable["index_1"] = {
root={classname="Panel",name="root",parName="root",childCount="6",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen6.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="63",capInsetsY="65",height="130",width="526",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="33",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_civil_kuang={classname="Panel",name="lay_civil_kuang",parName="root",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="15",y="10",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="205",anchorPointX="0",anchorPointY="0",},
lay_civil_value={classname="Panel",name="lay_civil_value",parName="root",childCount="6",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="130",width="270",x="120",y="0",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="212",anchorPointX="0",anchorPointY="0",},
lay_civil_nil={classname="Panel",name="lay_civil_nil",parName="root",childCount="2",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="130",width="390",x="120",y="0",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="219",anchorPointX="0",anchorPointY="0",},
lay_status={classname="Panel",name="lay_status",parName="root",childCount="2",ZOrder="6",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="130",width="200",x="324",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="343",anchorPointX="0",anchorPointY="0",},
lay_researcher_value={classname="Panel",name="lay_researcher_value",parName="root",childCount="4",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="130",width="270",x="120",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="877",anchorPointX="0",anchorPointY="0",},
img_bg={classname="ImageView",name="img_bg",parName="root",ZOrder="0",fileName="#v1_img_kelashen6_b.png",scale9Enable="true",scale9Height="130",scale9Width="350",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="175",capInsetsY="9",height="130",width="350",x="0",y="0",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1630",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lb_civil_name={classname="Label",name="lb_civil_name",parName="lay_civil_value",ZOrder="0",colorB="64",colorG="216",colorR="49",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="文官名字",fontName="微软雅黑",fontSize="22",height="30",width="88",x="14",y="99",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="207",anchorPointX="0",anchorPointY="0.5",},
lb_civil_lv={classname="Label",name="lb_civil_lv",parName="lay_civil_value",ZOrder="0",colorB="253",colorG="212",colorR="119",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Lv.5",fontName="微软雅黑",fontSize="22",height="30",width="41",x="193",y="99",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="208",anchorPointX="0.5",anchorPointY="0.5",},
lb_func1={classname="Label",name="lb_func1",parName="lay_civil_value",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="增加基础资源产量",fontName="微软雅黑",fontSize="20",height="27",width="160",x="14",y="58",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="209",anchorPointX="0",anchorPointY="0.5",},
lb_func2={classname="Label",name="lb_func2",parName="lay_civil_value",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="资源加速：",fontName="微软雅黑",fontSize="20",height="27",width="100",x="14",y="24",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="210",anchorPointX="0",anchorPointY="0.5",},
lb_func2_value={classname="Label",name="lb_func2_value",parName="lay_civil_value",ZOrder="0",colorB="253",colorG="212",colorR="119",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="铜钱，木，粮",fontName="微软雅黑",fontSize="20",height="27",width="120",x="110",y="24",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="224",anchorPointX="0",anchorPointY="0.5",},
lb_func1_value={classname="Label",name="lb_func1_value",parName="lay_civil_value",ZOrder="0",colorB="64",colorG="216",colorR="49",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="+20%",fontName="微软雅黑",fontSize="20",height="27",width="57",x="179",y="58",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="225",anchorPointX="0",anchorPointY="0.5",},
lb_explain={classname="Label",name="lb_explain",parName="lay_civil_nil",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="60",areaWidth="310",hAlignment="0",vAlignment="1",text="点击左侧加号雇用文官，文官可以增加资源产量",fontName="微软雅黑",fontSize="20",height="60",width="310",x="14",y="65",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="222",anchorPointX="0",anchorPointY="0.5",},
lb_status2={classname="Label",name="lb_status2",parName="lay_civil_nil",ZOrder="0",colorB="40",colorG="37",colorR="245",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="未雇佣",fontName="微软雅黑",fontSize="20",height="27",width="60",x="345",y="65",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="228",anchorPointX="0.5",anchorPointY="0.5",},
lb_relaytime={classname="Label",name="lb_relaytime",parName="lay_status",ZOrder="0",colorB="40",colorG="37",colorR="245",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="2d  11:11:11",fontName="微软雅黑",fontSize="20",height="27",width="119",x="124",y="50",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="227",anchorPointX="0.5",anchorPointY="0.5",},
lb_status1={classname="Label",name="lb_status1",parName="lay_status",ZOrder="0",colorB="40",colorG="37",colorR="245",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="雇用中",fontName="微软雅黑",fontSize="20",height="27",width="60",x="124",y="80",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="271",anchorPointX="0.5",anchorPointY="0.5",},
lb_rs_name={classname="Label",name="lb_rs_name",parName="lay_researcher_value",ZOrder="0",colorB="64",colorG="216",colorR="49",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="文官名字",fontName="微软雅黑",fontSize="22",height="30",width="88",x="14",y="91",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="884",anchorPointX="0",anchorPointY="0",},
lb_rs_lv={classname="Label",name="lb_rs_lv",parName="lay_researcher_value",ZOrder="0",colorB="253",colorG="212",colorR="119",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Lv.5",fontName="微软雅黑",fontSize="22",height="30",width="41",x="193",y="91",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="885",anchorPointX="0.5",anchorPointY="0",},
lb_func3={classname="Label",name="lb_func3",parName="lay_researcher_value",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="85",areaWidth="240",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="85",width="240",x="14",y="85",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1079",anchorPointX="0",anchorPointY="1",},
lb_time={classname="Label",name="lb_time",parName="lay_researcher_value",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="14",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1142",anchorPointX="0",anchorPointY="0",},
}

return tTable