local tTable = {}


tTable["index_1"] = {
item_shogun_sigle_hero={classname="Panel",name="item_shogun_sigle_hero",parName="root",childCount="7",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="235",width="182",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="99",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lb_start={classname="CustomLabel",name="lb_start",parName="item_shogun_sigle_hero",ZOrder="3",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="5",fontName="微软雅黑",fontSize="20",height="27",width="12",x="22",y="216",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="102",anchorPointX="0.5",anchorPointY="0.5",},
img_bing_type={classname="ImageView",name="img_bing_type",parName="item_shogun_sigle_hero",ZOrder="3",fileName="#v1_img_bujiang02.png",scale9Enable="false",scale9Height="34",scale9Width="34",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="34",width="34",x="3",y="232",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="105",anchorPointX="0",anchorPointY="1",},
ly_down={classname="Panel",name="ly_down",parName="item_shogun_sigle_hero",childCount="1",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_black70.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="10",height="54",width="178",x="2",y="2",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="104",anchorPointX="0",anchorPointY="0",},
ly_cover={classname="Panel",name="ly_cover",parName="item_shogun_sigle_hero",childCount="1",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_black50.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="10",height="235",width="182",x="0",y="0",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="127",anchorPointX="0",anchorPointY="0",},
ly_hero={classname="Panel",name="ly_hero",parName="item_shogun_sigle_hero",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="229",width="177",x="3",y="3",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="174",anchorPointX="0",anchorPointY="0",},
ly_qulity_kuang={classname="Panel",name="ly_qulity_kuang",parName="item_shogun_sigle_hero",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kapailan.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="25",capInsetsY="25",height="237",width="182",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="196",anchorPointX="0",anchorPointY="0",},
img_ig={classname="CustomImageView",name="img_ig",parName="item_shogun_sigle_hero",ZOrder="10",fileName="#v2_fonts_shen.png",scale9Enable="false",scale9Height="39",scale9Width="29",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="39",width="29",x="164",y="212",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="228",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_3"] = {
lb_hero_info={classname="CustomLabel",name="lb_hero_info",parName="ly_down",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="91",y="27",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="106",anchorPointX="0.5",anchorPointY="0.5",},
lb_info={classname="CustomLabel",name="lb_info",parName="ly_cover",ZOrder="11",colorB="255",colorG="255",colorR="255",areaHeight="0.01",areaWidth="0.01",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="16",height="0.01",width="0.01",x="26",y="166",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="142",anchorPointX="0",anchorPointY="1",},
}

return tTable