local tTable = {}

tTable["texturesPng"] = {"ui/p1_commonse1.plist"}
tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="370",capInsetsY="48",height="130",width="600",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="277",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_hero_info={classname="Panel",name="lay_hero_info",parName="default",childCount="10",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="130",width="600",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="18505",anchorPointX="0",anchorPointY="0",},
lay_hero_null={classname="Panel",name="lay_hero_null",parName="default",childCount="2",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="130",width="600",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="18507",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
txt_name={classname="CustomLabel",name="txt_name",parName="lay_hero_info",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="22",height="30",width="106",x="135",y="91",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="286",anchorPointX="0",anchorPointY="0.5",},
txt_state={classname="CustomLabel",name="txt_state",parName="lay_hero_info",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="54",areaWidth="95",hAlignment="0",vAlignment="0",text="兵力不足无法出征",fontName="微软雅黑",fontSize="20",height="54",width="95",x="536",y="64",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="287",anchorPointX="0.5",anchorPointY="0.5",},
txt_troops_title={classname="CustomLabel",name="txt_troops_title",parName="lay_hero_info",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="兵力",fontName="微软雅黑",fontSize="20",height="27",width="40",x="135",y="33",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="290",anchorPointX="0",anchorPointY="0.5",},
lay_bar_troops={classname="Panel",name="lay_bar_troops",parName="lay_hero_info",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="45",capInsetsY="9",height="24",width="216",x="185",y="21",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1443",anchorPointX="0",anchorPointY="0",},
txt_troops={classname="CustomLabel",name="txt_troops",parName="lay_hero_info",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="22",height="30",width="52",x="290",y="33",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="14190",anchorPointX="1",anchorPointY="0.5",},
img_selected={classname="CustomImageView",name="img_selected",parName="lay_hero_info",ZOrder="1",fileName="#v1_img_gouxuan.png",scale9Enable="false",scale9Height="40",scale9Width="41",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="40",width="41",x="569",y="67",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="14192",anchorPointX="0.5",anchorPointY="0.5",},
lay_btn_fill={classname="Panel",name="lay_btn_fill",parName="lay_hero_info",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="40",x="412",y="15",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="17191",anchorPointX="0",anchorPointY="0",},
lay_icon={classname="Panel",name="lay_icon",parName="lay_hero_info",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="15",y="11",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1441",anchorPointX="0",anchorPointY="0",},
txt_selected={classname="CustomLabel",name="txt_selected",parName="lay_hero_info",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="已选择",fontName="微软雅黑",fontSize="20",height="27",width="60",x="535",y="64",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="22572",anchorPointX="1",anchorPointY="0.5",},
txt_troops_max={classname="CustomLabel",name="txt_troops_max",parName="lay_hero_info",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="/9999",fontName="微软雅黑",fontSize="22",height="30",width="61",x="291",y="33",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="23487",anchorPointX="0",anchorPointY="0.5",},
txt_null_tip={classname="CustomLabel",name="txt_null_tip",parName="lay_hero_null",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="136",y="67",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="18506",anchorPointX="0",anchorPointY="0.5",},
lay_null_icon={classname="Panel",name="lay_null_icon",parName="lay_hero_null",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="15",y="11",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="18508",anchorPointX="0",anchorPointY="0",},
}

return tTable