local tTable = {}

tTable["texturesPng"] = {"ui/p1_commonse1.plist","ui/bg_base/v2_bg_guojiarenwu.jpg","ui/p1_commmon3_sep.plist"}
tTable["index_1"] = {
lay_box_view={classname="Panel",name="lay_box_view@fill_layout",parName="root",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1000",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="350",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_prev_box={classname="Panel",name="lay_prev_box",parName="lay_box_view",childCount="10",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="244",width="640",x="0",y="755",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="380",anchorPointX="0",anchorPointY="0",},
lay_box={classname="Panel",name="lay_box@fill_layout",parName="lay_box_view",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="656",width="640",x="0",y="100",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="355",anchorPointX="0",anchorPointY="0",},
lay_btn_bot={classname="Panel",name="lay_btn_bot",parName="lay_box_view",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="100",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="353",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
img_arrow={classname="ImageView",name="img_arrow",parName="lay_prev_box",ZOrder="1",fileName="#v1_img_lanjiantou.png",scale9Enable="false",scale9Height="41",scale9Width="65",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="41",width="65",x="320",y="133",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="381",anchorPointX="0.5",anchorPointY="0.5",},
img_bg={classname="ImageView",name="img_bg",parName="lay_prev_box",ZOrder="0",fileName="ui/bg_base/v2_bg_guojiarenwu.jpg",scale9Enable="false",scale9Height="318",scale9Width="640",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="318",width="640",x="0",y="-74",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="382",anchorPointX="0",anchorPointY="0",},
lay_icon_1={classname="Panel",name="lay_icon_1",parName="lay_prev_box",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="100",y="86",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="383",anchorPointX="0",anchorPointY="0",},
lb_pa_1={classname="Label",name="lb_pa_1",parName="lay_prev_box",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="154",y="215",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="384",anchorPointX="0.5",anchorPointY="0.5",},
lb_pa_2={classname="Label",name="lb_pa_2",parName="lay_prev_box",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="154",y="69",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="385",anchorPointX="0.5",anchorPointY="0.5",},
lb_pa_3={classname="Label",name="lb_pa_3",parName="lay_prev_box",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="154",y="40",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="386",anchorPointX="0.5",anchorPointY="0.5",},
lay_icon_2={classname="Panel",name="lay_icon_2",parName="lay_prev_box",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="433",y="85",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="387",anchorPointX="0",anchorPointY="0",},
lb_pa_4={classname="Label",name="lb_pa_4",parName="lay_prev_box",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="487",y="214",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="388",anchorPointX="0.5",anchorPointY="0.5",},
lb_pa_5={classname="Label",name="lb_pa_5",parName="lay_prev_box",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="487",y="68",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="389",anchorPointX="0.5",anchorPointY="0.5",},
lb_pa_6={classname="Label",name="lb_pa_6",parName="lay_prev_box",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="487",y="40",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="390",anchorPointX="0.5",anchorPointY="0.5",},
lay_btn={classname="Panel",name="lay_btn",parName="lay_btn_bot",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="243",y="20",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="354",anchorPointX="0",anchorPointY="0",},
}

return tTable