local tTable = {}

tTable["texturesPng"] = {"ui/big_img_sep/v2_img_duihuanshangdi.jpg","ui/p1_commonse1.plist"}
tTable["index_1"] = {
default={classname="Panel",name="default@fill_layout",parName="root",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="763",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="742",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_main={classname="Panel",name="lay_main",parName="default",childCount="9",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="763",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="826",anchorPointX="0",anchorPointY="0",},
lay_bot={classname="Panel",name="lay_bot@fill_layout",parName="default",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="827",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_title={classname="Panel",name="lay_title",parName="lay_main",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="640",x="0",y="710",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="744",anchorPointX="0",anchorPointY="0",},
lay_b_left={classname="Panel",name="lay_b_left",parName="lay_main",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="62",y="85",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="778",anchorPointX="0",anchorPointY="0",},
lay_b_right={classname="Panel",name="lay_b_right",parName="lay_main",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="426",y="85",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="779",anchorPointX="0",anchorPointY="0",},
img_bg={classname="ImageView",name="img_bg",parName="lay_main",ZOrder="0",fileName="ui/big_img_sep/v2_img_duihuanshangdi.jpg",scale9Enable="false",scale9Height="668",scale9Width="640",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="668",width="640",x="0",y="69",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="780",anchorPointX="0",anchorPointY="0",},
lay_res1={classname="Panel",name="lay_res1",parName="lay_main",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="150",width="120",x="259",y="323",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="781",anchorPointX="0",anchorPointY="0",},
lay_res2={classname="Panel",name="lay_res2",parName="lay_main",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="150",width="120",x="85",y="217",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="783",anchorPointX="0",anchorPointY="0",},
lay_res3={classname="Panel",name="lay_res3",parName="lay_main",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="150",width="120",x="436",y="217",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="784",anchorPointX="0",anchorPointY="0",},
img_line={classname="ImageView",name="img_line",parName="lay_main",ZOrder="0",fileName="#v1_line_blue1.png",scale9Enable="true",scale9Height="2",scale9Width="640",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="1",height="2",width="640",x="320",y="709",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="808",anchorPointX="0.5",anchorPointY="0.5",},
lb_bot_tip={classname="Label",name="lb_bot_tip",parName="lay_main",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="320",y="42",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="809",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable