local tTable = {}

tTable["texturesPng"] = {"ui/bg_base/v2_img_honbaoab.png","ui/language/cn/p2_font1.plist","ui/p1_commmon1_sep.plist","ui/p2_commmon1_sep.plist","ui/p1_commonse1.plist"}
tTable["index_1"] = {
lay_default={classname="Panel",name="lay_default",parName="root",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="ui/bg_base/v2_img_honbaoab.png",height="596",width="480",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
img_title={classname="ImageView",name="img_title",parName="lay_default",ZOrder="0",fileName="#v2_fonts_fhonbao.png",scale9Enable="false",scale9Height="33",scale9Width="102",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="33",width="102",x="240",y="560",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="10",anchorPointX="0.5",anchorPointY="0.5",},
img_top_line={classname="ImageView",name="img_top_line",parName="lay_default",ZOrder="0",fileName="#v1_line_jianbian02.png",scale9Enable="true",scale9Height="1",scale9Width="460",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="143",capInsetsY="1",height="1",width="460",x="240",y="526",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="11",anchorPointX="0.5",anchorPointY="0.5",},
lay_catch={classname="Panel",name="lay_catch",parName="lay_default",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_bg_kelashenhuang.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="25",capInsetsY="25",height="130",width="440",x="20",y="351",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="12",anchorPointX="0",anchorPointY="0",},
lay_send={classname="Panel",name="lay_send",parName="lay_default",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_bg_kelashenhuang.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="25",capInsetsY="25",height="130",width="440",x="20",y="196",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="13",anchorPointX="0",anchorPointY="0",},
lay_btn_close={classname="Panel",name="lay_btn_close",parName="lay_default",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="70",width="150",x="330",y="526",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="203",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
img_para_1={classname="ImageView",name="img_para_1",parName="lay_catch",ZOrder="0",fileName="#v2_fonts_honbaochd.png",scale9Enable="false",scale9Height="21",scale9Width="89",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="21",width="89",x="20",y="110",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="15",anchorPointX="0",anchorPointY="1",},
lb_des_1={classname="Label",name="lb_des_1",parName="lay_catch",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="50",areaWidth="260",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="50",width="260",x="20",y="69",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="17",anchorPointX="0",anchorPointY="1",},
lay_btn_catch={classname="Panel",name="lay_btn_catch",parName="lay_catch",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="300",y="20",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="18",anchorPointX="0",anchorPointY="0",},
img_para_2={classname="ImageView",name="img_para_2",parName="lay_send",ZOrder="0",fileName="#v2_fonts_honbaomuud.png",scale9Enable="false",scale9Height="21",scale9Width="88",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="21",width="88",x="20",y="110",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="16",anchorPointX="0",anchorPointY="1",},
lb_des_2={classname="Label",name="lb_des_2",parName="lay_send",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="50",areaWidth="260",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="50",width="260",x="20",y="69",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="21",anchorPointX="0",anchorPointY="1",},
lay_btn_send={classname="Panel",name="lay_btn_send",parName="lay_send",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="300",y="20",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="23",anchorPointX="0",anchorPointY="0",},
img_btn_close={classname="ImageView",name="img_btn_close",parName="lay_btn_close",ZOrder="0",fileName="#v1_btn_close.png",scale9Enable="false",scale9Height="32",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="32",width="31",x="135",y="56",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8",anchorPointX="1",anchorPointY="1",},
}

return tTable