local tTable = {}

tTable["texturesPng"] = {"ui/p1_commonse1.plist","icon/p1_icon_font.plist"}
tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="160",width="520",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7431",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
view={classname="Panel",name="view",parName="default",childCount="15",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="63",capInsetsY="65",height="160",width="520",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7434",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_icon={classname="Panel",name="lay_icon",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="130",width="150",x="8",y="18",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7436",anchorPointX="0",anchorPointY="0",},
txt_name={classname="CustomLabel",name="txt_name",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="164",y="142",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7437",anchorPointX="0",anchorPointY="0.5",},
txt_pos_title={classname="CustomLabel",name="txt_pos_title",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="坐标：",fontName="微软雅黑",fontSize="20",height="27",width="60",x="164",y="116",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7438",anchorPointX="0",anchorPointY="0.5",},
txt_owner_title={classname="CustomLabel",name="txt_owner_title",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="城主：",fontName="微软雅黑",fontSize="20",height="27",width="60",x="164",y="91",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7439",anchorPointX="0",anchorPointY="0.5",},
txt_owner_name={classname="CustomLabel",name="txt_owner_name",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="223",y="91",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7440",anchorPointX="0",anchorPointY="0.5",},
txt_people_title={classname="CustomLabel",name="txt_people_title",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="人口：",fontName="微软雅黑",fontSize="20",height="27",width="60",x="164",y="65",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7441",anchorPointX="0",anchorPointY="0.5",},
txt_troops_title={classname="CustomLabel",name="txt_troops_title",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="城防兵力：",fontName="微软雅黑",fontSize="20",height="27",width="100",x="164",y="40",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7443",anchorPointX="0",anchorPointY="0.5",},
img_rename={classname="CustomImageView",name="img_rename",parName="view",ZOrder="0",fileName="#v1_img_shuxie.png",scale9Enable="false",scale9Height="49",scale9Width="51",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="49",width="51",x="415",y="127",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7444",anchorPointX="0.5",anchorPointY="0.5",},
img_flag={classname="CustomImageView",name="img_flag",parName="view",ZOrder="2",fileName="#v1_img_qun.png",scale9Enable="false",scale9Height="64",scale9Width="51",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="64",width="51",x="19",y="139",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7445",anchorPointX="0.5",anchorPointY="0.5",},
txt_remain_cd_title={classname="CustomLabel",name="txt_remain_cd_title",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="剩余任期：",fontName="微软雅黑",fontSize="20",height="27",width="100",x="164",y="15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7470",anchorPointX="0",anchorPointY="0.5",},
txt_people={classname="CustomLabel",name="txt_people",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="222",y="65",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7487",anchorPointX="0",anchorPointY="0.5",},
txt_pos={classname="CustomLabel",name="txt_pos",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="223",y="116",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7488",anchorPointX="0",anchorPointY="0.5",},
lay_richtext_troops={classname="Panel",name="lay_richtext_troops",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="27",width="95",x="263",y="26",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7489",anchorPointX="0",anchorPointY="0",},
txt_remain_cd={classname="CustomLabel",name="txt_remain_cd",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="264",y="15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7490",anchorPointX="0",anchorPointY="0.5",},
lay_btn_rename={classname="Panel",name="lay_btn_rename",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="110",x="378",y="100",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="24460",anchorPointX="0",anchorPointY="0",},
}

return tTable