local tTable = {}

tTable["texturesPng"] = {"ui/bg_base/v2_img_honbaodi.jpg","ui/p1_commonse1.plist","ui/language/cn/p2_font1.plist","ui/p2_commmon1_sep.plist","ui/p2_commonse1.plist"}
tTable["index_1"] = {
lay_default={classname="Panel",name="lay_default",parName="root",childCount="12",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="ui/bg_base/v2_img_honbaodi.jpg",height="671",width="480",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_btn_close={classname="Panel",name="lay_btn_close",parName="lay_default",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="70",width="150",x="330",y="601",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="204",anchorPointX="0",anchorPointY="0",},
lay_icon_1={classname="Panel",name="lay_icon_1",parName="lay_default",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="88",width="88",x="196",y="523",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="37",anchorPointX="0",anchorPointY="0",},
lb_par_1={classname="Label",name="lb_par_1",parName="lay_default",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="240",y="508",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="38",anchorPointX="0.5",anchorPointY="1",},
lb_par_2={classname="Label",name="lb_par_2",parName="lay_default",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="240",y="474",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="39",anchorPointX="0.5",anchorPointY="1",},
img_tip={classname="ImageView",name="img_tip",parName="lay_default",ZOrder="1",fileName="#v2_fonts_awxivch.png",scale9Enable="false",scale9Height="36",scale9Width="288",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="36",width="288",x="240",y="387",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="76",anchorPointX="0.5",anchorPointY="0.5",},
img_arrow_l={classname="ImageView",name="img_arrow_l",parName="lay_default",ZOrder="1",fileName="#v2_img_xsfuduqdd02a.png",scale9Enable="false",scale9Height="13",scale9Width="162",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="13",width="162",x="230",y="354",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="78",anchorPointX="1",anchorPointY="0.5",},
img_arrow_r={classname="ImageView",name="img_arrow_r",parName="lay_default",ZOrder="1",fileName="#v2_img_xsfuduqdd02a.png",scale9Enable="false",scale9Height="13",scale9Width="162",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="13",width="162",x="250",y="354",visible="true",touchAble="false",flipX="true",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="79",anchorPointX="0",anchorPointY="0.5",},
img_btn_open={classname="ImageView",name="img_btn_open",parName="lay_default",ZOrder="2",fileName="#v2_btn_ki.png",scale9Enable="false",scale9Height="165",scale9Width="214",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="165",width="214",x="240",y="216",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="81",anchorPointX="0.5",anchorPointY="0.5",},
lb_tip={classname="Label",name="lb_tip",parName="lay_default",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="213",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="80",anchorPointX="1",anchorPointY="0.5",},
img_qianbi={classname="ImageView",name="img_qianbi",parName="lay_default",ZOrder="0",fileName="#v1_img_huangjin.png",scale9Enable="false",scale9Height="24",scale9Width="29",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="24",width="29",x="214",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="82",anchorPointX="0",anchorPointY="0.5",},
lb_num={classname="Label",name="lb_num",parName="lay_default",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="251",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="83",anchorPointX="0",anchorPointY="0.5",},
lay_top_bg={classname="Panel",name="lay_top_bg",parName="lay_default",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/big_img/v2_img_honbaotou.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="240",capInsetsY="10",height="490",width="480",x="0",y="188",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="180",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
img_btn_close={classname="ImageView",name="img_btn_close",parName="lay_btn_close",ZOrder="1",fileName="#v1_btn_close.png",scale9Enable="false",scale9Height="32",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="32",width="31",x="141",y="60",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8",anchorPointX="1",anchorPointY="1",},
}

return tTable