local tTable = {}


tTable["index_1"] = {
all={classname="Panel",name="all",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="325",width="540",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
content={classname="Panel",name="content",parName="all",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="325",width="540",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
middle={classname="Panel",name="middle",parName="content",childCount="12",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/big_img/v1_bg_shijiezhidao.jpg",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="270",capInsetsY="200",height="325",width="540",x="-1",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="15",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
img_my_blue_0={classname="ImageView",name="img_my_blue_0",parName="middle",ZOrder="0",fileName="#v1_line_sj_blue.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="101",y="223",visible="true",touchAble="false",flipX="false",scaleX="0.25",scaleY="0.25",opacity="255",rotation="0",tag="717",anchorPointX="0",anchorPointY="1",},
img_my_blue_1={classname="ImageView",name="img_my_blue_1",parName="middle",ZOrder="0",fileName="#v1_line_sj_blue.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="101",y="223",visible="true",touchAble="false",flipX="false",scaleX="-0.25",scaleY="0.25",opacity="255",rotation="0",tag="718",anchorPointX="0",anchorPointY="1",},
img_my_blue_2={classname="ImageView",name="img_my_blue_2",parName="middle",ZOrder="0",fileName="#v1_line_sj_blue.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="101",y="223",visible="true",touchAble="false",flipX="false",scaleX="-0.25",scaleY="-0.25",opacity="255",rotation="0",tag="719",anchorPointX="0",anchorPointY="1",},
img_my_blue_3={classname="ImageView",name="img_my_blue_3",parName="middle",ZOrder="0",fileName="#v1_line_sj_blue.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="101",y="223",visible="true",touchAble="false",flipX="false",scaleX="0.25",scaleY="-0.25",opacity="255",rotation="0",tag="720",anchorPointX="0",anchorPointY="1",},
img_lj_red_0={classname="ImageView",name="img_lj_red_0",parName="middle",ZOrder="0",fileName="#v1_line_sj_red.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="440",y="67",visible="true",touchAble="false",flipX="false",scaleX="0.25",scaleY="0.25",opacity="255",rotation="0",tag="722",anchorPointX="0",anchorPointY="1",},
img_lj_red_1={classname="ImageView",name="img_lj_red_1",parName="middle",ZOrder="0",fileName="#v1_line_sj_red.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="440",y="67",visible="true",touchAble="false",flipX="false",scaleX="-0.25",scaleY="0.25",opacity="255",rotation="0",tag="723",anchorPointX="0",anchorPointY="1",},
img_lj_red_2={classname="ImageView",name="img_lj_red_2",parName="middle",ZOrder="0",fileName="#v1_line_sj_red.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="440",y="67",visible="true",touchAble="false",flipX="false",scaleX="-0.25",scaleY="-0.25",opacity="255",rotation="0",tag="724",anchorPointX="0",anchorPointY="1",},
img_lj_red_3={classname="ImageView",name="img_lj_red_3",parName="middle",ZOrder="0",fileName="#v1_line_sj_red.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="440",y="67",visible="true",touchAble="false",flipX="false",scaleX="0.25",scaleY="-0.25",opacity="255",rotation="0",tag="725",anchorPointX="0",anchorPointY="1",},
img_my={classname="ImageView",name="img_my",parName="middle",ZOrder="1",fileName="#v1_img_lan03.png",scale9Enable="false",scale9Height="397",scale9Width="772",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="397",width="772",x="103",y="228",visible="true",touchAble="false",flipX="false",scaleX="0.5",scaleY="0.5",opacity="255",rotation="0",tag="253",anchorPointX="0.5",anchorPointY="0.5",},
img_lj={classname="ImageView",name="img_lj",parName="middle",ZOrder="1",fileName="#v1_img_luanjun_lv19_22.png",scale9Enable="false",scale9Height="129",scale9Width="167",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="129",width="167",x="439",y="81",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="42",anchorPointX="0.5",anchorPointY="0.5",},
lay_name2={classname="Panel",name="lay_name2",parName="middle",childCount="3",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_img_namebg3.png",height="24",width="120",x="384",y="10",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="157",anchorPointX="0",anchorPointY="0",},
lay_name1={classname="Panel",name="lay_name1",parName="middle",childCount="3",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_img_namebg3.png",height="24",width="120",x="38",y="163",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="165",anchorPointX="0",anchorPointY="0",},
}
tTable["index_5"] = {
img_icon2={classname="ImageView",name="img_icon2",parName="lay_name2",ZOrder="3",fileName="#v1_img_dengjidi2.png",scale9Enable="false",scale9Height="44",scale9Width="44",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="44",width="44",x="2",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="158",anchorPointX="0.5",anchorPointY="0.5",},
txt_name2={classname="Label",name="txt_name2",parName="lay_name2",ZOrder="3",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="乱军",fontName="微软雅黑",fontSize="20",height="27",width="40",x="52",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="159",anchorPointX="0.5",anchorPointY="0.5",},
txt_lv2={classname="Label",name="txt_lv2",parName="lay_name2",ZOrder="4",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="20",fontName="微软雅黑",fontSize="18",height="24",width="22",x="2",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="160",anchorPointX="0.5",anchorPointY="0.5",},
img_icon1={classname="ImageView",name="img_icon1",parName="lay_name1",ZOrder="3",fileName="#v1_img_dengjidi2.png",scale9Enable="false",scale9Height="44",scale9Width="44",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="44",width="44",x="2",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="166",anchorPointX="0.5",anchorPointY="0.5",},
txt_name1={classname="Label",name="txt_name1",parName="lay_name1",ZOrder="3",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="我的城池",fontName="微软雅黑",fontSize="20",height="27",width="80",x="60",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="167",anchorPointX="0.5",anchorPointY="0.5",},
txt_lv1={classname="Label",name="txt_lv1",parName="lay_name1",ZOrder="4",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="20",fontName="微软雅黑",fontSize="18",height="24",width="22",x="2",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="168",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable