local tTable = {}

tTable["texturesPng"] = {"ui/bg_base/v2_img_honbaodi.jpg","ui/p1_commonse1.plist","ui/p2_commmon1_sep.plist","ui/p2_commonse1.plist"}
tTable["index_1"] = {
lay_default={classname="Panel",name="lay_default",parName="root",childCount="8",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="ui/bg_base/v2_img_honbaodi.jpg",height="671",width="480",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_btn_close={classname="Panel",name="lay_btn_close",parName="lay_default",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="70",width="150",x="330",y="601",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="205",anchorPointX="0",anchorPointY="0",},
lay_icon={classname="Panel",name="lay_icon",parName="lay_default",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="88",width="88",x="196",y="558",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="37",anchorPointX="0",anchorPointY="0",},
lb_par_1={classname="Label",name="lb_par_1",parName="lay_default",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="240",y="543",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="38",anchorPointX="0.5",anchorPointY="1",},
lb_par_2={classname="Label",name="lb_par_2",parName="lay_default",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="240",y="509",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="39",anchorPointX="0.5",anchorPointY="1",},
lay_list={classname="Panel",name="lay_list",parName="lay_default",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_bg_kelashenhuang.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="25",capInsetsY="25",height="422",width="440",x="20",y="15",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="98",anchorPointX="0",anchorPointY="0",},
lb_num={classname="Label",name="lb_num",parName="lay_default",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="20",y="455",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="99",anchorPointX="0",anchorPointY="0.5",},
lb_time={classname="Label",name="lb_time",parName="lay_default",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="460",y="455",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="100",anchorPointX="1",anchorPointY="0.5",},
lay_top_bg={classname="Panel",name="lay_top_bg",parName="lay_default",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/big_img/v2_img_honbaotou.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="240",capInsetsY="10",height="230",width="480",x="0",y="448",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="181",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
img_btn_close={classname="ImageView",name="img_btn_close",parName="lay_btn_close",ZOrder="1",fileName="#v1_btn_close.png",scale9Enable="false",scale9Height="32",scale9Width="31",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="32",width="31",x="140",y="61",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8",anchorPointX="1",anchorPointY="1",},
}

return tTable