local tTable = {}


tTable["index_1"] = {
all={classname="Panel",name="all",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="325",width="540",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
content={classname="Panel",name="content",parName="all",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="325",width="540",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
middle={classname="Panel",name="middle",parName="content",childCount="19",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/big_img/v1_bg_shijiezhidao.jpg",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="270",capInsetsY="200",height="325",width="540",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="15",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
img_my_blue1_0={classname="ImageView",name="img_my_blue1_0",parName="middle",ZOrder="0",fileName="#v1_line_sj_blue.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="102",y="223",visible="true",touchAble="false",flipX="false",scaleX="0.25",scaleY="0.25",opacity="255",rotation="0",tag="685",anchorPointX="0",anchorPointY="1",},
img_my_blue1_1={classname="ImageView",name="img_my_blue1_1",parName="middle",ZOrder="0",fileName="#v1_line_sj_blue.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="102",y="223",visible="true",touchAble="false",flipX="false",scaleX="-0.25",scaleY="0.25",opacity="255",rotation="0",tag="687",anchorPointX="0",anchorPointY="1",},
img_my_blue1_2={classname="ImageView",name="img_my_blue1_2",parName="middle",ZOrder="0",fileName="#v1_line_sj_blue.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="102",y="223",visible="true",touchAble="false",flipX="false",scaleX="-0.25",scaleY="-0.25",opacity="255",rotation="0",tag="688",anchorPointX="0",anchorPointY="1",},
img_my_blue1_3={classname="ImageView",name="img_my_blue1_3",parName="middle",ZOrder="0",fileName="#v1_line_sj_blue.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="102",y="223",visible="true",touchAble="false",flipX="false",scaleX="0.25",scaleY="-0.25",opacity="255",rotation="0",tag="689",anchorPointX="0",anchorPointY="1",},
img_my_blue2_0={classname="ImageView",name="img_my_blue2_0",parName="middle",ZOrder="0",fileName="#v1_line_sj_blue.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="102",y="55",visible="true",touchAble="false",flipX="false",scaleX="0.25",scaleY="0.25",opacity="255",rotation="0",tag="691",anchorPointX="0",anchorPointY="1",},
img_my_blue2_1={classname="ImageView",name="img_my_blue2_1",parName="middle",ZOrder="0",fileName="#v1_line_sj_blue.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="102",y="55",visible="true",touchAble="false",flipX="false",scaleX="-0.25",scaleY="0.25",opacity="255",rotation="0",tag="692",anchorPointX="0",anchorPointY="1",},
img_my_blue2_2={classname="ImageView",name="img_my_blue2_2",parName="middle",ZOrder="0",fileName="#v1_line_sj_blue.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="102",y="55",visible="true",touchAble="false",flipX="false",scaleX="-0.25",scaleY="-0.25",opacity="255",rotation="0",tag="693",anchorPointX="0",anchorPointY="1",},
img_my_blue2_3={classname="ImageView",name="img_my_blue2_3",parName="middle",ZOrder="0",fileName="#v1_line_sj_blue.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="102",y="55",visible="true",touchAble="false",flipX="false",scaleX="0.25",scaleY="-0.25",opacity="255",rotation="0",tag="694",anchorPointX="0",anchorPointY="1",},
img_lj_0={classname="ImageView",name="img_lj_0",parName="middle",ZOrder="0",fileName="#v1_line_sj_red.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="440",y="140",visible="true",touchAble="false",flipX="false",scaleX="0.25",scaleY="0.25",opacity="255",rotation="0",tag="696",anchorPointX="0",anchorPointY="1",},
img_lj_1={classname="ImageView",name="img_lj_1",parName="middle",ZOrder="0",fileName="#v1_line_sj_red.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="440",y="140",visible="true",touchAble="false",flipX="false",scaleX="-0.25",scaleY="0.25",opacity="255",rotation="0",tag="697",anchorPointX="0",anchorPointY="1",},
img_lj_2={classname="ImageView",name="img_lj_2",parName="middle",ZOrder="0",fileName="#v1_line_sj_red.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="440",y="140",visible="true",touchAble="false",flipX="false",scaleX="-0.25",scaleY="-0.25",opacity="255",rotation="0",tag="698",anchorPointX="0",anchorPointY="1",},
img_lj_3={classname="ImageView",name="img_lj_3",parName="middle",ZOrder="0",fileName="#v1_line_sj_red.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="440",y="140",visible="true",touchAble="false",flipX="false",scaleX="0.25",scaleY="-0.25",opacity="255",rotation="0",tag="699",anchorPointX="0",anchorPointY="1",},
img_my1={classname="ImageView",name="img_my1",parName="middle",ZOrder="1",fileName="#v1_img_lan03.png",scale9Enable="false",scale9Height="397",scale9Width="772",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="397",width="772",x="102",y="226",visible="true",touchAble="false",flipX="false",scaleX="0.5",scaleY="0.4999999",opacity="255",rotation="0",tag="339",anchorPointX="0.5",anchorPointY="0.5",},
img_my2={classname="ImageView",name="img_my2",parName="middle",ZOrder="1",fileName="#v1_img_lan03.png",scale9Enable="false",scale9Height="397",scale9Width="772",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="397",width="772",x="103",y="63",visible="true",touchAble="false",flipX="false",scaleX="0.4999999",scaleY="0.4999999",opacity="255",rotation="0",tag="53",anchorPointX="0.5",anchorPointY="0.5",},
img_enenmy={classname="ImageView",name="img_enenmy",parName="middle",ZOrder="1",fileName="#v1_img_lan03.png",scale9Enable="false",scale9Height="397",scale9Width="772",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="178",capInsetsY="99",height="397",width="772",x="440",y="146",visible="true",touchAble="false",flipX="false",scaleX="0.4999999",scaleY="0.4999999",opacity="255",rotation="0",tag="42",anchorPointX="0.5",anchorPointY="0.5",},
lay_name1={classname="Panel",name="lay_name1",parName="middle",childCount="3",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_img_namebg5.png",height="24",width="150",x="17",y="162",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="113",anchorPointX="0",anchorPointY="0",},
lay_name2={classname="Panel",name="lay_name2",parName="middle",childCount="3",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_img_namebg5.png",height="24",width="150",x="17",y="4",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="121",anchorPointX="0",anchorPointY="0",},
lay_name3={classname="Panel",name="lay_name3",parName="middle",childCount="3",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_img_namebg5.png",height="24",width="150",x="382",y="80",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="125",anchorPointX="0",anchorPointY="0",},
Image_20={classname="ImageView",name="Image_20",parName="middle",ZOrder="2",fileName="ui/daitu.png",scale9Enable="false",scale9Height="10",scale9Width="10",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="10",width="10",x="181",y="231",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="480",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_5"] = {
img_icon1={classname="ImageView",name="img_icon1",parName="lay_name1",ZOrder="3",fileName="#v1_img_dengjidi2.png",scale9Enable="false",scale9Height="44",scale9Width="44",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="44",width="44",x="2",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="114",anchorPointX="0.5",anchorPointY="0.5",},
txt_name1={classname="Label",name="txt_name1",parName="lay_name1",ZOrder="3",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="我的城池",fontName="微软雅黑",fontSize="20",height="27",width="80",x="76",y="11",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="115",anchorPointX="0.5",anchorPointY="0.5",},
txt_lv1={classname="Label",name="txt_lv1",parName="lay_name1",ZOrder="5",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="20",fontName="微软雅黑",fontSize="18",height="24",width="22",x="2",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="116",anchorPointX="0.5",anchorPointY="0.5",},
img_icon2={classname="ImageView",name="img_icon2",parName="lay_name2",ZOrder="3",fileName="#v1_img_dengjidi2.png",scale9Enable="false",scale9Height="44",scale9Width="44",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="44",width="44",x="2",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="122",anchorPointX="0.5",anchorPointY="0.5",},
txt_name2={classname="Label",name="txt_name2",parName="lay_name2",ZOrder="3",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="友军城池",fontName="微软雅黑",fontSize="20",height="27",width="80",x="76",y="11",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="123",anchorPointX="0.5",anchorPointY="0.5",},
txt_lv2={classname="Label",name="txt_lv2",parName="lay_name2",ZOrder="5",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="20",fontName="微软雅黑",fontSize="18",height="24",width="22",x="2",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="124",anchorPointX="0.5",anchorPointY="0.5",},
img_icon3={classname="ImageView",name="img_icon3",parName="lay_name3",ZOrder="3",fileName="#v1_img_dengjidi2.png",scale9Enable="false",scale9Height="44",scale9Width="44",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="44",width="44",x="2",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="126",anchorPointX="0.5",anchorPointY="0.5",},
txt_name3={classname="Label",name="txt_name3",parName="lay_name3",ZOrder="3",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="敌方城池",fontName="微软雅黑",fontSize="20",height="27",width="80",x="76",y="11",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="127",anchorPointX="0.5",anchorPointY="0.5",},
txt_lv3={classname="Label",name="txt_lv3",parName="lay_name3",ZOrder="5",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="20",fontName="微软雅黑",fontSize="18",height="24",width="22",x="2",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="128",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable