local tTable = {}


tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="10",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="544",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
txt_power_title={classname="CustomLabel",name="txt_power_title",parName="default",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="战斗力：",fontName="微软雅黑",fontSize="20",height="27",width="80",x="20",y="71",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="545",anchorPointX="0",anchorPointY="0.5",},
txt_power={classname="CustomLabel",name="txt_power",parName="default",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="100",y="71",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="546",anchorPointX="0",anchorPointY="0.5",},
txt_wall_lv_title={classname="CustomLabel",name="txt_wall_lv_title",parName="default",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="城墙等级：",fontName="微软雅黑",fontSize="20",height="27",width="100",x="457",y="71",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="547",anchorPointX="0.5",anchorPointY="0.5",},
txt_wall_lv={classname="CustomLabel",name="txt_wall_lv",parName="default",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="508",y="71",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="548",anchorPointX="0",anchorPointY="0.5",},
img_infantry={classname="CustomImageView",name="img_infantry",parName="default",ZOrder="0",fileName="#v1_img_bujiang02b.png",scale9Enable="false",scale9Height="112",scale9Width="98",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="112",width="98",x="20",y="31",visible="true",touchAble="false",flipX="false",scaleX="0.4",scaleY="0.4",opacity="255",rotation="0",tag="549",anchorPointX="0",anchorPointY="0.5",},
img_archer={classname="CustomImageView",name="img_archer",parName="default",ZOrder="0",fileName="#v1_img_gongjiang02b.png",scale9Enable="false",scale9Height="112",scale9Width="98",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="112",width="98",x="478",y="31",visible="true",touchAble="false",flipX="false",scaleX="0.4",scaleY="0.4",opacity="255",rotation="0",tag="550",anchorPointX="0.5",anchorPointY="0.5",},
img_cavalry={classname="CustomImageView",name="img_cavalry",parName="default",ZOrder="0",fileName="#v1_img_qibing02bb.png",scale9Enable="false",scale9Height="112",scale9Width="98",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="112",width="98",x="272",y="31",visible="true",touchAble="false",flipX="false",scaleX="0.4",scaleY="0.4",opacity="255",rotation="0",tag="551",anchorPointX="0",anchorPointY="0.5",},
txt_infantry={classname="CustomLabel",name="txt_infantry",parName="default",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="67",y="33",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="552",anchorPointX="0",anchorPointY="0.5",},
txt_cavalry={classname="CustomLabel",name="txt_cavalry",parName="default",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="320",y="33",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="553",anchorPointX="0",anchorPointY="0.5",},
txt_archer={classname="CustomLabel",name="txt_archer",parName="default",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="508",y="33",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="554",anchorPointX="0",anchorPointY="0.5",},
}

return tTable