local tTable = {}


tTable["index_1"] = {
lay_treasure_tab={classname="Panel",name="lay_treasure_tab@fill_layout",parName="root",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1066",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="716",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_icon={classname="Panel",name="lay_icon",parName="lay_treasure_tab",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="640",width="640",x="0",y="413",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="721",anchorPointX="0",anchorPointY="0",},
lay_bottom={classname="Panel",name="lay_bottom",parName="lay_treasure_tab",childCount="9",ZOrder="20",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="413",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="730",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
img_icon={classname="CustomImageView",name="img_icon",parName="lay_icon",ZOrder="5",fileName="ui/big_img_sep/v2_bg_xunfangbaozang_liubang.jpg",scale9Enable="false",scale9Height="611",scale9Width="640",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="611",width="640",x="0",y="29",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="722",anchorPointX="0",anchorPointY="0",},
Image_15={classname="CustomImageView",name="Image_15",parName="lay_icon",ZOrder="8",fileName="#v2_fonts_xunfangbaozang.png",scale9Enable="false",scale9Height="253",scale9Width="70",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="253",width="70",x="555",y="315",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="738",anchorPointX="0.5",anchorPointY="0.5",},
lay_tips={classname="Panel",name="lay_tips",parName="lay_icon",childCount="3",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_black50.png",capInsetsHeight="5",capInsetsWidth="5",capInsetsX="5",capInsetsY="5",height="170",width="640",x="0",y="1",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="725",anchorPointX="0",anchorPointY="0",},
img_arr_l={classname="CustomImageView",name="img_arr_l",parName="lay_bottom",ZOrder="5",fileName="#v2_img_xsfuduqdd02a.png",scale9Enable="true",scale9Height="13",scale9Width="257",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="100",capInsetsY="2",height="13",width="257",x="0",y="414",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="731",anchorPointX="0",anchorPointY="0.5",},
img_arr_r={classname="CustomImageView",name="img_arr_r",parName="lay_bottom",ZOrder="0",fileName="#v2_img_xsfuduqdd02a.png",scale9Enable="true",scale9Height="13",scale9Width="257",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="100",capInsetsY="0",height="13",width="257",x="510",y="414",visible="true",touchAble="false",flipX="true",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="732",anchorPointX="0.5",anchorPointY="0.5",},
img_title={classname="CustomImageView",name="img_title",parName="lay_bottom",ZOrder="0",fileName="#v2_fonts_suijituzhi.png",scale9Enable="false",scale9Height="24",scale9Width="95",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="24",width="95",x="320",y="415",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="733",anchorPointX="0.5",anchorPointY="0.5",},
lb_title_1={classname="CustomLabel",name="lb_title_1",parName="lay_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="320",y="370",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="734",anchorPointX="0.5",anchorPointY="0.5",},
lb_title_2={classname="CustomLabel",name="lb_title_2",parName="lay_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="111111111111111111111111111111111111111",fontName="微软雅黑",fontSize="20",height="27",width="468",x="319",y="94",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="736",anchorPointX="0.5",anchorPointY="0.5",},
lb_title_3={classname="CustomLabel",name="lb_title_3",parName="lay_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="320",y="147",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="752",anchorPointX="0.5",anchorPointY="0.5",},
ly_items={classname="Panel",name="ly_items",parName="lay_bottom",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="150",width="620",x="10",y="197",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="735",anchorPointX="0",anchorPointY="0",},
lay_btn={classname="Panel",name="lay_btn",parName="lay_bottom",childCount="2",ZOrder="20",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="70",width="233",x="200",y="50",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="761",anchorPointX="0",anchorPointY="0",},
lay_cost={classname="Panel",name="lay_cost",parName="lay_bottom",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="640",x="0",y="125",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="756",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lb_items={classname="CustomLabel",name="lb_items",parName="lay_tips",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="22",height="30",width="106",x="320",y="149",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="726",anchorPointX="0.5",anchorPointY="0.5",},
lb_desc={classname="CustomLabel",name="lb_desc",parName="lay_tips",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="120",areaWidth="620",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="120",width="620",x="10",y="130",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="727",anchorPointX="0",anchorPointY="1",},
ly_list={classname="Panel",name="ly_list",parName="lay_tips",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="120",width="620",x="10",y="9",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="728",anchorPointX="0",anchorPointY="0",},
img_btn={classname="CustomImageView",name="img_btn",parName="lay_btn",ZOrder="11",fileName="#v2_btn_huodongjinse.png",scale9Enable="false",scale9Height="70",scale9Width="233",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="70",width="233",x="117",y="35",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="737",anchorPointX="0.5",anchorPointY="0.5",},
img_fonts={classname="CustomImageView",name="img_fonts",parName="lay_btn",ZOrder="20",fileName="#v2_fonts_zhuhe.png",scale9Enable="false",scale9Height="25",scale9Width="47",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="25",width="47",x="116",y="34",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="751",anchorPointX="0.5",anchorPointY="0.5",},
lb_jf={classname="CustomLabel",name="lb_jf",parName="lay_cost",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="积分:",fontName="微软雅黑",fontSize="18",height="24",width="40",x="209",y="18",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="753",anchorPointX="0.5",anchorPointY="0.5",},
lb_jf_cost={classname="CustomLabel",name="lb_jf_cost",parName="lay_cost",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="积分:",fontName="微软雅黑",fontSize="18",height="24",width="40",x="239",y="18",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="755",anchorPointX="0",anchorPointY="0.5",},
img_yb={classname="CustomImageView",name="img_yb",parName="lay_cost",ZOrder="0",fileName="#v1_img_huangjin.png",scale9Enable="false",scale9Height="24",scale9Width="29",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="24",width="29",x="356",y="17",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="757",anchorPointX="0.5",anchorPointY="0.5",},
lb_yb_cost={classname="CustomLabel",name="lb_yb_cost",parName="lay_cost",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="积分:",fontName="微软雅黑",fontSize="18",height="24",width="40",x="386",y="18",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="759",anchorPointX="0",anchorPointY="0.5",},
}

return tTable