local tTable = {}


tTable["index_1"] = {
all={classname="Panel",name="all",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="325",width="540",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
content={classname="Panel",name="content",parName="all",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="325",width="540",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
middle={classname="Panel",name="middle",parName="content",childCount="12",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/big_img/v1_bg_shijiezhidao.jpg",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="270",capInsetsY="200",height="325",width="540",x="-3",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="15",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
img_my_blue_0={classname="ImageView",name="img_my_blue_0",parName="middle",ZOrder="0",fileName="#v1_line_sj_blue.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="102",y="223",visible="true",touchAble="false",flipX="false",scaleX="0.25",scaleY="0.25",opacity="255",rotation="0",tag="665",anchorPointX="0",anchorPointY="1",},
img_my_blue_1={classname="ImageView",name="img_my_blue_1",parName="middle",ZOrder="0",fileName="#v1_line_sj_blue.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="102",y="223",visible="true",touchAble="false",flipX="false",scaleX="-0.25",scaleY="0.25",opacity="255",rotation="0",tag="666",anchorPointX="0",anchorPointY="1",},
img_my_blue_2={classname="ImageView",name="img_my_blue_2",parName="middle",ZOrder="0",fileName="#v1_line_sj_blue.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="102",y="223",visible="true",touchAble="false",flipX="false",scaleX="-0.25",scaleY="-0.25",opacity="255",rotation="0",tag="667",anchorPointX="0",anchorPointY="1",},
img_my_blue_3={classname="ImageView",name="img_my_blue_3",parName="middle",ZOrder="0",fileName="#v1_line_sj_blue.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="102",y="223",visible="true",touchAble="false",flipX="false",scaleX="0.25",scaleY="-0.25",opacity="255",rotation="0",tag="668",anchorPointX="0",anchorPointY="1",},
img_lj_red_0={classname="ImageView",name="img_lj_red_0",parName="middle",ZOrder="0",fileName="#v1_line_sj_red.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="440",y="68",visible="true",touchAble="false",flipX="false",scaleX="0.25",scaleY="0.25",opacity="255",rotation="0",tag="649",anchorPointX="0",anchorPointY="1",},
img_lj_red_1={classname="ImageView",name="img_lj_red_1",parName="middle",ZOrder="0",fileName="#v1_line_sj_red.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="440",y="68",visible="true",touchAble="false",flipX="false",scaleX="-0.25",scaleY="0.25",opacity="255",rotation="0",tag="650",anchorPointX="0",anchorPointY="1",},
img_lj_red_2={classname="ImageView",name="img_lj_red_2",parName="middle",ZOrder="0",fileName="#v1_line_sj_red.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="440",y="68",visible="true",touchAble="false",flipX="false",scaleX="-0.25",scaleY="-0.25",opacity="255",rotation="0",tag="651",anchorPointX="0",anchorPointY="1",},
img_lj_red_3={classname="ImageView",name="img_lj_red_3",parName="middle",ZOrder="0",fileName="#v1_line_sj_red.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="440",y="68",visible="true",touchAble="false",flipX="false",scaleX="0.25",scaleY="-0.25",opacity="255",rotation="0",tag="652",anchorPointX="0",anchorPointY="1",},
img_enenmy={classname="ImageView",name="img_enenmy",parName="middle",ZOrder="1",fileName="#11010_img_hd.png",scale9Enable="false",scale9Height="115",scale9Width="180",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="178",capInsetsY="99",height="115",width="180",x="439",y="81",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="42",anchorPointX="0.5",anchorPointY="0.5",},
img_my1={classname="ImageView",name="img_my1",parName="middle",ZOrder="1",fileName="#v1_img_lan03.png",scale9Enable="false",scale9Height="397",scale9Width="772",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="397",width="772",x="104",y="228",visible="true",touchAble="false",flipX="false",scaleX="0.4999999",scaleY="0.4999999",opacity="255",rotation="0",tag="39",anchorPointX="0.5",anchorPointY="0.5",},
lay_my_name={classname="Panel",name="lay_my_name",parName="middle",childCount="3",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_img_namebg5.png",height="24",width="150",x="39",y="163",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="85",anchorPointX="0",anchorPointY="0",},
lay_far_name={classname="Panel",name="lay_far_name",parName="middle",childCount="3",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_img_namebg5.png",height="24",width="150",x="379",y="16",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="93",anchorPointX="0",anchorPointY="0",},
}
tTable["index_5"] = {
txt_my_name={classname="CustomLabel",name="txt_my_name",parName="lay_my_name",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="我的城池",fontName="微软雅黑",fontSize="18",height="24",width="72",x="69",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="86",anchorPointX="0.5",anchorPointY="0.5",},
img_icon={classname="ImageView",name="img_icon",parName="lay_my_name",ZOrder="1",fileName="#v1_img_dengjidi2.png",scale9Enable="false",scale9Height="44",scale9Width="44",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="44",width="44",x="2",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="87",anchorPointX="0.5",anchorPointY="0.5",},
txt_my_lv={classname="CustomLabel",name="txt_my_lv",parName="lay_my_name",ZOrder="6",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="20",fontName="微软雅黑",fontSize="16",height="21",width="18",x="0",y="13",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="88",anchorPointX="0.5",anchorPointY="0.5",},
txt_far_name={classname="CustomLabel",name="txt_far_name",parName="lay_far_name",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="农田",fontName="微软雅黑",fontSize="18",height="24",width="36",x="69",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="94",anchorPointX="0.5",anchorPointY="0.5",},
img_farm_icon={classname="ImageView",name="img_farm_icon",parName="lay_far_name",ZOrder="1",fileName="#v1_img_dengjidi2.png",scale9Enable="false",scale9Height="44",scale9Width="44",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="44",width="44",x="2",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="95",anchorPointX="0.5",anchorPointY="0.5",},
txt_farm_lv={classname="CustomLabel",name="txt_farm_lv",parName="lay_far_name",ZOrder="5",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="20",fontName="微软雅黑",fontSize="16",height="21",width="18",x="0",y="13",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="96",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable