local tTable = {}


tTable["index_1"] = {
all={classname="Panel",name="all",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="325",width="540",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
content={classname="Panel",name="content",parName="all",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="325",width="540",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
middle={classname="Panel",name="middle",parName="content",childCount="18",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="ui/big_img/v1_bg_shijiezhidao.jpg",height="325",width="540",x="-1",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="15",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
img_my_blue1_0={classname="ImageView",name="img_my_blue1_0",parName="middle",ZOrder="0",fileName="#v1_line_sj_blue.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="101",y="236",visible="true",touchAble="false",flipX="false",scaleX="0.25",scaleY="0.25",opacity="255",rotation="0",tag="702",anchorPointX="0",anchorPointY="1",},
img_my_blue1_1={classname="ImageView",name="img_my_blue1_1",parName="middle",ZOrder="0",fileName="#v1_line_sj_blue.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="101",y="236",visible="true",touchAble="false",flipX="false",scaleX="-0.25",scaleY="0.25",opacity="255",rotation="0",tag="703",anchorPointX="0",anchorPointY="1",},
img_my_blue1_2={classname="ImageView",name="img_my_blue1_2",parName="middle",ZOrder="0",fileName="#v1_line_sj_blue.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="101",y="236",visible="true",touchAble="false",flipX="false",scaleX="-0.25",scaleY="-0.25",opacity="255",rotation="0",tag="704",anchorPointX="0",anchorPointY="1",},
img_my_blue1_3={classname="ImageView",name="img_my_blue1_3",parName="middle",ZOrder="0",fileName="#v1_line_sj_blue.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="101",y="236",visible="true",touchAble="false",flipX="false",scaleX="0.25",scaleY="-0.25",opacity="255",rotation="0",tag="705",anchorPointX="0",anchorPointY="1",},
img_my_blue2_0={classname="ImageView",name="img_my_blue2_0",parName="middle",ZOrder="0",fileName="#v1_line_sj_blue.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="101",y="52",visible="true",touchAble="false",flipX="false",scaleX="0.25",scaleY="0.25",opacity="255",rotation="0",tag="707",anchorPointX="0",anchorPointY="1",},
img_my_blue2_1={classname="ImageView",name="img_my_blue2_1",parName="middle",ZOrder="0",fileName="#v1_line_sj_blue.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="101",y="52",visible="true",touchAble="false",flipX="false",scaleX="-0.25",scaleY="0.25",opacity="255",rotation="0",tag="708",anchorPointX="0",anchorPointY="1",},
img_my_blue2_2={classname="ImageView",name="img_my_blue2_2",parName="middle",ZOrder="0",fileName="#v1_line_sj_blue.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="101",y="52",visible="true",touchAble="false",flipX="false",scaleX="-0.25",scaleY="-0.25",opacity="255",rotation="0",tag="709",anchorPointX="0",anchorPointY="1",},
img_my_blue2_3={classname="ImageView",name="img_my_blue2_3",parName="middle",ZOrder="0",fileName="#v1_line_sj_blue.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="101",y="52",visible="true",touchAble="false",flipX="false",scaleX="0.25",scaleY="-0.25",opacity="255",rotation="0",tag="710",anchorPointX="0",anchorPointY="1",},
img_lj_red_0={classname="ImageView",name="img_lj_red_0",parName="middle",ZOrder="0",fileName="#v1_line_sj_red.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="367",y="137",visible="true",touchAble="false",flipX="false",scaleX="0.35",scaleY="0.35",opacity="255",rotation="0",tag="712",anchorPointX="0",anchorPointY="1",},
img_lj_red_1={classname="ImageView",name="img_lj_red_1",parName="middle",ZOrder="0",fileName="#v1_line_sj_red.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="367",y="137",visible="true",touchAble="false",flipX="false",scaleX="-0.35",scaleY="0.35",opacity="255",rotation="0",tag="713",anchorPointX="0",anchorPointY="1",},
img_lj_red_2={classname="ImageView",name="img_lj_red_2",parName="middle",ZOrder="0",fileName="#v1_line_sj_red.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="367",y="137",visible="true",touchAble="false",flipX="false",scaleX="-0.35",scaleY="-0.35",opacity="255",rotation="0",tag="714",anchorPointX="0",anchorPointY="1",},
img_lj_red_3={classname="ImageView",name="img_lj_red_3",parName="middle",ZOrder="0",fileName="#v1_line_sj_red.png",scale9Enable="false",scale9Height="204",scale9Width="404",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="204",width="404",x="367",y="137",visible="true",touchAble="false",flipX="false",scaleX="0.35",scaleY="-0.35",opacity="255",rotation="0",tag="715",anchorPointX="0",anchorPointY="1",},
img_my1={classname="ImageView",name="img_my1",parName="middle",ZOrder="2",fileName="#v1_img_lan03.png",scale9Enable="false",scale9Height="397",scale9Width="772",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="397",width="772",x="104",y="242",visible="true",touchAble="false",flipX="false",scaleX="0.4999999",scaleY="0.4999999",opacity="255",rotation="0",tag="39",anchorPointX="0.5",anchorPointY="0.5",},
img_my2={classname="ImageView",name="img_my2",parName="middle",ZOrder="2",fileName="#v1_img_lan03.png",scale9Enable="false",scale9Height="397",scale9Width="772",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="397",width="772",x="103",y="57",visible="true",touchAble="false",flipX="false",scaleX="0.4999999",scaleY="0.4999999",opacity="255",rotation="0",tag="53",anchorPointX="0.5",anchorPointY="0.5",},
img_enenmy={classname="ImageView",name="img_enenmy",parName="middle",ZOrder="2",fileName="#v1_img_lan03.png",scale9Enable="false",scale9Height="397",scale9Width="772",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="397",width="772",x="370",y="146",visible="true",touchAble="false",flipX="false",scaleX="0.6999999",scaleY="0.6999999",opacity="255",rotation="0",tag="42",anchorPointX="0.5",anchorPointY="0.5",},
lay_name1={classname="Panel",name="lay_name1",parName="middle",childCount="3",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_img_namebg5.png",height="24",width="150",x="14",y="172",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="133",anchorPointX="0",anchorPointY="0",},
lay_name3={classname="Panel",name="lay_name3",parName="middle",childCount="3",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_img_namebg5.png",height="24",width="150",x="315",y="58",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="145",anchorPointX="0",anchorPointY="0",},
lay_name2={classname="Panel",name="lay_name2",parName="middle",childCount="3",ZOrder="3",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_img_namebg5.png",height="24",width="150",x="14",y="6",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="149",anchorPointX="0",anchorPointY="0",},
}
tTable["index_5"] = {
img_icon1={classname="ImageView",name="img_icon1",parName="lay_name1",ZOrder="3",fileName="#v1_img_dengjidi2.png",scale9Enable="false",scale9Height="44",scale9Width="44",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="44",width="44",x="2",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="134",anchorPointX="0.5",anchorPointY="0.5",},
txt_name1={classname="Label",name="txt_name1",parName="lay_name1",ZOrder="3",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="我的城池",fontName="微软雅黑",fontSize="20",height="27",width="80",x="76",y="11",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="135",anchorPointX="0.5",anchorPointY="0.5",},
txt_lv1={classname="Label",name="txt_lv1",parName="lay_name1",ZOrder="5",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="20",fontName="微软雅黑",fontSize="18",height="24",width="22",x="2",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="136",anchorPointX="0.5",anchorPointY="0.5",},
img_icon3={classname="ImageView",name="img_icon3",parName="lay_name3",ZOrder="3",fileName="#v1_img_dengjidi2.png",scale9Enable="false",scale9Height="44",scale9Width="44",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="44",width="44",x="2",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="146",anchorPointX="0.5",anchorPointY="0.5",},
txt_name3={classname="Label",name="txt_name3",parName="lay_name3",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="国家城池",fontName="微软雅黑",fontSize="20",height="27",width="80",x="76",y="11",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="147",anchorPointX="0.5",anchorPointY="0.5",},
txt_lv3={classname="Label",name="txt_lv3",parName="lay_name3",ZOrder="5",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="20",fontName="微软雅黑",fontSize="18",height="24",width="22",x="2",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="148",anchorPointX="0.5",anchorPointY="0.5",},
img_icon2={classname="ImageView",name="img_icon2",parName="lay_name2",ZOrder="3",fileName="#v1_img_dengjidi2.png",scale9Enable="false",scale9Height="44",scale9Width="44",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="44",width="44",x="2",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="150",anchorPointX="0.5",anchorPointY="0.5",},
txt_name2={classname="Label",name="txt_name2",parName="lay_name2",ZOrder="3",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="友军城池",fontName="微软雅黑",fontSize="20",height="27",width="80",x="76",y="11",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="151",anchorPointX="0.5",anchorPointY="0.5",},
txt_lv2={classname="Label",name="txt_lv2",parName="lay_name2",ZOrder="5",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="20",fontName="微软雅黑",fontSize="18",height="24",width="22",x="2",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="152",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable