local tTable = {}

tTable["texturesPng"] = {"ui/v2_bg_nianshopulaixi.jpg","ui/rwww_nstp_mmp_001.png","ui/p1_commonse1.plist","ui/p1_commmon1_sep.plist","ui/p2_button1.plist","ui/p2_commmon_ac.plist","ui/language/cn/p2_font_ac.plist","ui/p2_commmon1_sep.plist","ui/daitu.png"}
tTable["index_1"] = {
default={classname="Panel",name="default@fill_layout",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1000",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="10",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
view={classname="Panel",name="view@fill_layout",parName="default",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1000",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="13",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_bg={classname="Panel",name="lay_bg@fill_layout_height",parName="view",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1000",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="18",anchorPointX="0",anchorPointY="0",},
lay_content={classname="Panel",name="lay_content@fill_layout_height",parName="view",childCount="2",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1000",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="17",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lay_nian={classname="Panel",name="lay_nian",parName="lay_bg",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1000",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="26",anchorPointX="0",anchorPointY="0",},
lay_content_top={classname="Panel",name="lay_content_top@fill_layout",parName="lay_content",childCount="4",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="594",width="640",x="0",y="403",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="30",anchorPointX="0",anchorPointY="0",},
lay_content_bottom={classname="Panel",name="lay_content_bottom",parName="lay_content",childCount="11",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="400",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="31",anchorPointX="0",anchorPointY="0",},
}
tTable["index_5"] = {
img_nian_bg={classname="CustomImageView",name="img_nian_bg",parName="lay_nian",ZOrder="0",fileName="ui/v2_bg_nianshopulaixi.jpg",scale9Enable="false",scale9Height="1138",scale9Width="640",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="1138",width="640",x="320",y="553",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="15",anchorPointX="0.5",anchorPointY="0.5",},
img_nian={classname="CustomImageView",name="img_nian",parName="lay_nian",ZOrder="1",fileName="ui/rwww_nstp_mmp_001.png",scale9Enable="false",scale9Height="618",scale9Width="640",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="618",width="640",x="318",y="683",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="789",anchorPointX="0.5",anchorPointY="0.5",},
Panel_6={classname="Panel",name="Panel_6",parName="lay_nian",ZOrder="99",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="200",width="200",x="456",y="762",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="791",anchorPointX="0",anchorPointY="0",},
lay_middle_top={classname="Panel",name="lay_middle_top",parName="lay_content_top",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="94",width="640",x="1",y="501",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="19",anchorPointX="0",anchorPointY="0",},
lay_middle={classname="Panel",name="lay_middle@fill_layout",parName="lay_content_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="200",width="400",x="117",y="255",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="33",anchorPointX="0",anchorPointY="0",},
lay_middle_bottom={classname="Panel",name="lay_middle_bottom",parName="lay_content_top",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="200",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="34",anchorPointX="0",anchorPointY="0",},
lay_result={classname="Panel",name="lay_result@fill_layout_height",parName="lay_content_top",childCount="2",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_black50.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="10",height="594",width="640",x="0",y="0",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="36",anchorPointX="0",anchorPointY="0",},
img_bottom_bg={classname="CustomImageView",name="img_bottom_bg",parName="lay_content_bottom",ZOrder="0",fileName="#v2_img_hongbaodadi.png",scale9Enable="false",scale9Height="487",scale9Width="320",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="487",width="320",x="160",y="243",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="32",anchorPointX="0.5",anchorPointY="0.5",},
img_bottom_bg2={classname="CustomImageView",name="img_bottom_bg2",parName="lay_content_bottom",ZOrder="0",fileName="#v2_img_hongbaodadi.png",scale9Enable="false",scale9Height="487",scale9Width="320",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="487",width="320",x="480",y="243",visible="true",touchAble="false",flipX="true",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="527",anchorPointX="0.5",anchorPointY="0.5",},
img_lantern1={classname="CustomImageView",name="img_lantern1",parName="lay_content_bottom",ZOrder="1",fileName="#v2_img_denglong.png",scale9Enable="false",scale9Height="84",scale9Width="47",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="84",width="47",x="22",y="417",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="45",anchorPointX="0.5",anchorPointY="0.5",},
img_lantern2={classname="CustomImageView",name="img_lantern2",parName="lay_content_bottom",ZOrder="1",fileName="#v2_img_denglong.png",scale9Enable="false",scale9Height="84",scale9Width="47",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="84",width="47",x="617",y="417",visible="true",touchAble="false",flipX="true",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="46",anchorPointX="0.5",anchorPointY="0.5",},
img_yellow_arrow={classname="CustomImageView",name="img_yellow_arrow",parName="lay_content_bottom",ZOrder="1",fileName="#v2_img_xsfuduqdd02a.png",scale9Enable="false",scale9Height="13",scale9Width="162",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="13",width="162",x="148",y="449",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="47",anchorPointX="0.5",anchorPointY="0.5",},
img_yellow_arrow2={classname="CustomImageView",name="img_yellow_arrow2",parName="lay_content_bottom",ZOrder="1",fileName="#v2_img_xsfuduqdd02a.png",scale9Enable="false",scale9Height="13",scale9Width="162",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="13",width="162",x="489",y="449",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="48",anchorPointX="0.5",anchorPointY="0.5",},
img_hurt_reward={classname="CustomImageView",name="img_hurt_reward",parName="lay_content_bottom",ZOrder="1",fileName="#v2_fonts_grshjl.png",scale9Enable="false",scale9Height="28",scale9Width="168",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="28",width="168",x="318",y="451",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="49",anchorPointX="0.5",anchorPointY="0.5",},
txt_my_hurt={classname="CustomLabel",name="txt_my_hurt",parName="lay_content_bottom",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="320",y="419",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="51",anchorPointX="0.5",anchorPointY="0.5",},
lay_hurt_bar_bg={classname="Panel",name="lay_hurt_bar_bg",parName="lay_content_bottom",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v2_bar_nianshoush_b.png",height="25",width="618",x="12",y="252",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="52",anchorPointX="0",anchorPointY="0",},
lay_items={classname="Panel",name="lay_items",parName="lay_content_bottom",childCount="2",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_kelashen_ns.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="20",capInsetsY="20",height="152",width="610",x="15",y="40",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="53",anchorPointX="0",anchorPointY="0",},
img_triangle={classname="CustomImageView",name="img_triangle",parName="lay_content_bottom",ZOrder="3",fileName="#v2_img_keyidongshanjiao.png",scale9Enable="false",scale9Height="27",scale9Width="58",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="27",width="58",x="507",y="205",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="55",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_6"] = {
txt_cd={classname="CustomLabel",name="txt_cd",parName="lay_middle_top",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="54",y="75",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="20",anchorPointX="0",anchorPointY="0.5",},
txt_redpoket={classname="CustomLabel",name="txt_redpoket",parName="lay_middle_top",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="620",y="75",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="21",anchorPointX="1",anchorPointY="0.5",},
img_clock={classname="CustomImageView",name="img_clock",parName="lay_middle_top",ZOrder="0",fileName="#v1_img_shizhong02.png",scale9Enable="false",scale9Height="22",scale9Width="22",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="22",width="22",x="34",y="75",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="22",anchorPointX="0.5",anchorPointY="0.5",},
lay_top_bottom={classname="Panel",name="lay_top_bottom",parName="lay_middle_top",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_black30.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="10",height="54",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="23",anchorPointX="0",anchorPointY="0",},
lay_attack={classname="Panel",name="lay_attack",parName="lay_middle_bottom",childCount="9",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v2_img_hsbjb.png",height="84",width="272",x="185",y="116",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="35",anchorPointX="0",anchorPointY="0",},
lay_result_top={classname="Panel",name="lay_result_top@fill_layout",parName="lay_result",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="200",width="200",x="0",y="393",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="38",anchorPointX="0",anchorPointY="0",},
lay_reslut_bottom={classname="Panel",name="lay_reslut_bottom",parName="lay_result",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="280",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="37",anchorPointX="0",anchorPointY="0",},
lay_btn_gift={classname="Panel",name="lay_btn_gift",parName="lay_items",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="431",y="43",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="59",anchorPointX="0",anchorPointY="0",},
img_get_state={classname="CustomImageView",name="img_get_state",parName="lay_items",ZOrder="0",fileName="ui/daitu.png",scale9Enable="false",scale9Height="10",scale9Width="10",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="10",width="10",x="510",y="74",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="526",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_7"] = {
img_btn_help={classname="CustomImageView",name="img_btn_help",parName="lay_top_bottom",ZOrder="0",fileName="#v2_btn_shuoming.png",scale9Enable="false",scale9Height="34",scale9Width="34",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="34",width="34",x="554",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="27",anchorPointX="0.5",anchorPointY="0.5",},
txt_name={classname="CustomLabel",name="txt_name",parName="lay_top_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="149",y="26",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="28",anchorPointX="1",anchorPointY="0.5",},
lay_hp_bar_bg={classname="Panel",name="lay_hp_bar_bg",parName="lay_top_bottom",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v2_bar_nianshou_b.png",height="24",width="374",x="155",y="14",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="29",anchorPointX="0",anchorPointY="0",},
lay_btn_help={classname="Panel",name="lay_btn_help",parName="lay_top_bottom",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="60",x="527",y="1",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="723",anchorPointX="0",anchorPointY="0",},
img_btn_attack={classname="CustomImageView",name="img_btn_attack",parName="lay_attack",ZOrder="0",fileName="#v2_btn_dianjigongji.png",scale9Enable="false",scale9Height="114",scale9Width="114",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="114",width="114",x="-29",y="46",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="41",anchorPointX="0.5",anchorPointY="0.5",},
txt_checkbox1={classname="CustomLabel",name="txt_checkbox1",parName="lay_attack",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="十连击",fontName="微软雅黑",fontSize="20",height="27",width="60",x="80",y="24",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="43",anchorPointX="0",anchorPointY="0.5",},
txt_checkbox2={classname="CustomLabel",name="txt_checkbox2",parName="lay_attack",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="五十连击",fontName="微软雅黑",fontSize="20",height="27",width="80",x="214",y="24",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="454",anchorPointX="0",anchorPointY="0.5",},
lay_gold_cost={classname="Panel",name="lay_gold_cost",parName="lay_attack",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="30",width="120",x="67",y="51",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="44",anchorPointX="0",anchorPointY="0",},
img_checkbox1={classname="CustomImageView",name="img_checkbox1",parName="lay_attack",ZOrder="0",fileName="#v2_img_gouxuankuang.png",scale9Enable="false",scale9Height="32",scale9Width="32",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="32",width="32",x="57",y="26",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="455",anchorPointX="0.5",anchorPointY="0.5",},
img_checkbox2={classname="CustomImageView",name="img_checkbox2",parName="lay_attack",ZOrder="0",fileName="#v2_img_gouxuankuang.png",scale9Enable="false",scale9Height="32",scale9Width="32",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="32",width="32",x="190",y="26",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="456",anchorPointX="0.5",anchorPointY="0.5",},
txt_free={classname="CustomLabel",name="txt_free",parName="lay_attack",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="127",y="27",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="573",anchorPointX="0.5",anchorPointY="0.5",},
lay_btn_checkbox1={classname="Panel",name="lay_btn_checkbox1",parName="lay_attack",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="42",width="100",x="40",y="2",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="574",anchorPointX="0",anchorPointY="0",},
lay_btn_checkbox2={classname="Panel",name="lay_btn_checkbox2",parName="lay_attack",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="42",width="120",x="170",y="2",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="575",anchorPointX="0",anchorPointY="0",},
img_result_bg={classname="CustomImageView",name="img_result_bg",parName="lay_reslut_bottom",ZOrder="0",fileName="#v2_img_nianshoubeiganpaodi.png",scale9Enable="false",scale9Height="260",scale9Width="263",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="260",width="263",x="320",y="332",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="39",anchorPointX="0.5",anchorPointY="0.5",},
img_result_font={classname="CustomImageView",name="img_result_font",parName="lay_reslut_bottom",ZOrder="1",fileName="#v2_fonts_nianshouganpao.png",scale9Enable="false",scale9Height="29",scale9Width="197",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="29",width="197",x="320",y="352",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="40",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_8"] = {
txt_hp={classname="CustomLabel",name="txt_hp",parName="lay_hp_bar_bg",ZOrder="10",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="182",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="576",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable