local tTable = {}

tTable["texturesPng"] = {"ui/bg_weapon/v1_bg_shenbing.jpg","ui/p1_commonse1.plist","ui/p1_commonse3.plist","ui/p1_commmon3_sep.plist","ui/language/cn/p1_font1.plist"}
tTable["index_1"] = {
lay_weapon_info={classname="Panel",name="lay_weapon_info",parName="root",childCount="7",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="65",capInsetsY="65",height="590",width="516",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="347",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
img_bg={classname="ImageView",name="img_bg",parName="lay_weapon_info",ZOrder="0",fileName="ui/bg_weapon/v1_bg_shenbing.jpg",scale9Enable="false",scale9Height="500",scale9Width="600",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="500",width="600",x="258",y="352",visible="true",touchAble="false",flipX="false",scaleX="0.86",scaleY="0.86",opacity="255",rotation="0",tag="348",anchorPointX="0.5",anchorPointY="0.5",},
img_kuang={classname="ImageView",name="img_kuang",parName="lay_weapon_info",ZOrder="1",fileName="#v1_img_bannaerkuang.png",scale9Enable="true",scale9Height="502",scale9Width="516",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="65",capInsetsY="65",height="502",width="516",x="258",y="317",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="349",anchorPointX="0.5",anchorPointY="0.5",},
lay_attr={classname="Panel",name="lay_attr",parName="lay_weapon_info",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_shenbingjianbian.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="172",capInsetsY="21",height="73",width="516",x="0",y="66",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="350",anchorPointX="0",anchorPointY="0",},
img_name={classname="ImageView",name="img_name",parName="lay_weapon_info",ZOrder="1",fileName="#v1_img_shenbingmingzidi.png",scale9Enable="false",scale9Height="194",scale9Width="68",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="194",width="68",x="48",y="477",visible="true",touchAble="false",flipX="false",scaleX="0.86",scaleY="0.86",opacity="255",rotation="0",tag="354",anchorPointX="0.5",anchorPointY="0.5",},
lb_name={classname="Label",name="lb_name",parName="lay_weapon_info",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="名字",fontName="微软雅黑",fontSize="25",height="32",width="50",x="48",y="489",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="355",anchorPointX="0.5",anchorPointY="0.5",},
lay_jie={classname="Panel",name="lay_jie",parName="lay_weapon_info",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_img_moji.png",height="54",width="130",x="11",y="346",visible="true",touchAble="true",flipX="false",scaleX="0.86",scaleY="0.86",opacity="255",rotation="0",tag="356",anchorPointX="0",anchorPointY="0",},
img_weapon={classname="ImageView",name="img_weapon",parName="lay_weapon_info",ZOrder="11",fileName="#v1_fonts_jie.png",scale9Enable="false",scale9Height="40",scale9Width="40",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="40",width="40",x="258",y="376",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="358",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_3"] = {
lb_info_1={classname="Label",name="lb_info_1",parName="lay_attr",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="258",y="53",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="351",anchorPointX="0.5",anchorPointY="0.5",},
lb_info_2={classname="Label",name="lb_info_2",parName="lay_attr",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="258",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="353",anchorPointX="0.5",anchorPointY="0.5",},
img_jie={classname="ImageView",name="img_jie",parName="lay_jie",ZOrder="0",fileName="#v1_fonts_jie.png",scale9Enable="false",scale9Height="40",scale9Width="40",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="40",width="40",x="56",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="357",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable