local tTable = {}


tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="130",width="550",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="393",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
view={classname="Panel",name="view",parName="default",childCount="9",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="63",capInsetsY="65",height="130",width="550",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2163",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
txt_name={classname="CustomLabel",name="txt_name",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="城池名称：",fontName="微软雅黑",fontSize="20",height="27",width="100",x="187",y="110",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2164",anchorPointX="0",anchorPointY="0.5",},
txt_owner_title={classname="CustomLabel",name="txt_owner_title",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="城主：",fontName="微软雅黑",fontSize="18",height="24",width="54",x="187",y="80",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2168",anchorPointX="0",anchorPointY="0.5",},
txt_remain_cd_title={classname="CustomLabel",name="txt_remain_cd_title",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="剩余任期：",fontName="微软雅黑",fontSize="18",height="24",width="90",x="187",y="21",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2170",anchorPointX="0",anchorPointY="0.5",},
txt_remain_cd={classname="CustomLabel",name="txt_remain_cd",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="287",y="21",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2171",anchorPointX="0",anchorPointY="0.5",},
img_flag={classname="CustomImageView",name="img_flag",parName="view",ZOrder="2",fileName="#v1_img_qun.png",scale9Enable="false",scale9Height="64",scale9Width="51",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="64",width="51",x="26",y="98",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2172",anchorPointX="0.5",anchorPointY="0.5",},
txt_owner_name={classname="CustomLabel",name="txt_owner_name",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="六个字六个字",fontName="微软雅黑",fontSize="18",height="24",width="108",x="247",y="80",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2252",anchorPointX="0",anchorPointY="0.5",},
txt_troops_title={classname="CustomLabel",name="txt_troops_title",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="城防兵力：",fontName="微软雅黑",fontSize="18",height="24",width="90",x="187",y="50",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2254",anchorPointX="0",anchorPointY="0.5",},
lay_icon={classname="Panel",name="lay_icon",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="100",width="150",x="29",y="13",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="5698",anchorPointX="0",anchorPointY="0",},
txt_troops={classname="CustomLabel",name="txt_troops",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="287",y="50",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="25365",anchorPointX="0",anchorPointY="0.5",},
}

return tTable