local tTable = {}


tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="480",width="528",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="68",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_atk1={classname="Panel",name="lay_atk1",parName="default",childCount="5",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_bluekelashen.jpg",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="15",capInsetsY="15",height="335",width="145",x="19",y="125",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1394",anchorPointX="0",anchorPointY="0",},
lay_atk2={classname="Panel",name="lay_atk2",parName="default",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_bluekelashen.jpg",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="15",capInsetsY="15",height="335",width="145",x="194",y="125",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1398",anchorPointX="0",anchorPointY="0",},
lay_atk3={classname="Panel",name="lay_atk3",parName="default",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_bluekelashen.jpg",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="15",capInsetsY="15",height="335",width="145",x="366",y="125",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1401",anchorPointX="0",anchorPointY="0",},
txt_tip1={classname="CustomLabel",name="txt_tip1",parName="default",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="22",y="111",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1404",anchorPointX="0",anchorPointY="1",},
}
tTable["index_3"] = {
txt_atk_tip1={classname="CustomLabel",name="txt_atk_tip1",parName="lay_atk1",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="73",y="266",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1395",anchorPointX="0.5",anchorPointY="0.5",},
txt_atk_name1={classname="CustomLabel",name="txt_atk_name1",parName="lay_atk1",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="73",y="305",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="83",anchorPointX="0.5",anchorPointY="0.5",},
lay_icon1={classname="Panel",name="lay_icon1",parName="lay_atk1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_img_duantuzhan.png",height="100",width="100",x="21",y="139",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1397",anchorPointX="0",anchorPointY="0",},
txt_stay_time1={classname="CustomLabel",name="txt_stay_time1",parName="lay_atk1",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="72",y="111",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="213",anchorPointX="0.5",anchorPointY="0.5",},
lay_btn1={classname="Panel",name="lay_btn1",parName="lay_atk1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="100",x="21",y="10",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="87",anchorPointX="0",anchorPointY="0",},
txt_atk_name2={classname="CustomLabel",name="txt_atk_name2",parName="lay_atk2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="69",y="305",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="84",anchorPointX="0.5",anchorPointY="0.5",},
txt_atk_tip2={classname="CustomLabel",name="txt_atk_tip2",parName="lay_atk2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="69",y="266",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1399",anchorPointX="0.5",anchorPointY="0.5",},
lay_icon2={classname="Panel",name="lay_icon2",parName="lay_atk2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_img_heweizhan.png",height="100",width="100",x="20",y="139",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1400",anchorPointX="0",anchorPointY="0",},
txt_stay_time2={classname="CustomLabel",name="txt_stay_time2",parName="lay_atk2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="71",y="111",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="214",anchorPointX="0.5",anchorPointY="0.5",},
lay_btn2={classname="Panel",name="lay_btn2",parName="lay_atk2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="100",x="22",y="10",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="88",anchorPointX="0",anchorPointY="0",},
txt_atk_tip3={classname="CustomLabel",name="txt_atk_tip3",parName="lay_atk3",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="73",y="266",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1402",anchorPointX="0.5",anchorPointY="0.5",},
lay_icon3={classname="Panel",name="lay_icon3",parName="lay_atk3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_img_benxizhan.png",height="100",width="100",x="20",y="139",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1403",anchorPointX="0",anchorPointY="0",},
txt_stay_time3={classname="CustomLabel",name="txt_stay_time3",parName="lay_atk3",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="73",y="111",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="215",anchorPointX="0.5",anchorPointY="0.5",},
lay_btn3={classname="Panel",name="lay_btn3",parName="lay_atk3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="100",x="20",y="10",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="89",anchorPointX="0",anchorPointY="0",},
txt_atk_name3={classname="CustomLabel",name="txt_atk_name3",parName="lay_atk3",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="73",y="305",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="3226",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable