local tTable = {}


tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="130",width="550",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7431",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
view={classname="Panel",name="view",parName="default",childCount="13",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="63",capInsetsY="65",height="130",width="550",x="0",y="1",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7434",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_icon={classname="Panel",name="lay_icon",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="100",width="150",x="29",y="13",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7436",anchorPointX="0",anchorPointY="0",},
txt_name={classname="CustomLabel",name="txt_name",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="187",y="116",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7437",anchorPointX="0",anchorPointY="0.5",},
txt_owner_title={classname="CustomLabel",name="txt_owner_title",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="城主：",fontName="微软雅黑",fontSize="18",height="24",width="54",x="188",y="88",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7439",anchorPointX="0",anchorPointY="0.5",},
txt_owner_name={classname="CustomLabel",name="txt_owner_name",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="248",y="91",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7440",anchorPointX="0",anchorPointY="0.5",},
txt_people_title={classname="CustomLabel",name="txt_people_title",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="人口：",fontName="微软雅黑",fontSize="18",height="24",width="54",x="187",y="65",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7441",anchorPointX="0",anchorPointY="0.5",},
txt_troops_title={classname="CustomLabel",name="txt_troops_title",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="城防兵力：",fontName="微软雅黑",fontSize="18",height="24",width="90",x="187",y="40",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7443",anchorPointX="0",anchorPointY="0.5",},
img_rename={classname="CustomImageView",name="img_rename",parName="view",ZOrder="0",fileName="#v1_img_shuxie.png",scale9Enable="false",scale9Height="49",scale9Width="51",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="49",width="51",x="415",y="127",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7444",anchorPointX="0.5",anchorPointY="0.5",},
img_flag={classname="CustomImageView",name="img_flag",parName="view",ZOrder="2",fileName="#v1_img_qun.png",scale9Enable="false",scale9Height="64",scale9Width="51",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="64",width="51",x="26",y="98",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7445",anchorPointX="0.5",anchorPointY="0.5",},
txt_remain_cd_title={classname="CustomLabel",name="txt_remain_cd_title",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="剩余任期：",fontName="微软雅黑",fontSize="18",height="24",width="90",x="187",y="15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7470",anchorPointX="0",anchorPointY="0.5",},
txt_people={classname="CustomLabel",name="txt_people",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="248",y="65",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7487",anchorPointX="0",anchorPointY="0.5",},
txt_remain_cd={classname="CustomLabel",name="txt_remain_cd",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="287",y="15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7490",anchorPointX="0",anchorPointY="0.5",},
lay_btn_rename={classname="Panel",name="lay_btn_rename",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="110",x="426",y="66",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="24460",anchorPointX="0",anchorPointY="0",},
txt_troops={classname="CustomLabel",name="txt_troops",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="287",y="40",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="25366",anchorPointX="0",anchorPointY="0.5",},
}

return tTable