local tTable = {}

tTable["texturesPng"] = {"ui/p1_commmon3_sep.plist","ui/p1_commonse2.plist","ui/p1_commmon2_sep.plist","ui/language/cn/p1_font1.plist"}
tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="6",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="150",width="160",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_paper_group={classname="Panel",name="lay_paper_group",parName="default",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="150",width="160",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6630",anchorPointX="0",anchorPointY="0",},
img_exclamation={classname="CustomImageView",name="img_exclamation",parName="default",ZOrder="0",fileName="#v1_img_qipao2.png",scale9Enable="false",scale9Height="55",scale9Width="50",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="55",width="50",x="26",y="122",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6632",anchorPointX="0.5",anchorPointY="0.5",},
img_exclamation_icon={classname="CustomImageView",name="img_exclamation_icon",parName="default",ZOrder="1",fileName="#v1_btn_czdl.png",scale9Enable="false",scale9Height="51",scale9Width="41",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="51",width="41",x="26",y="125",visible="true",touchAble="false",flipX="false",scaleX="0.8",scaleY="0.8",opacity="255",rotation="0",tag="13712",anchorPointX="0.5",anchorPointY="0.5",},
img_war={classname="CustomImageView",name="img_war",parName="default",ZOrder="0",fileName="#v1_img_zjm_wzqph.png",scale9Enable="false",scale9Height="94",scale9Width="94",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="94",width="94",x="82",y="79",visible="true",touchAble="false",flipX="false",scaleX="0.7",scaleY="0.7",opacity="255",rotation="0",tag="13714",anchorPointX="0.5",anchorPointY="0.5",},
img_war_icon={classname="CustomImageView",name="img_war_icon",parName="default",ZOrder="1",fileName="#v1_btn_guozhan2.png",scale9Enable="false",scale9Height="72",scale9Width="72",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="72",width="72",x="84",y="79",visible="true",touchAble="false",flipX="false",scaleX="0.7",scaleY="0.7",opacity="255",rotation="0",tag="13823",anchorPointX="0.5",anchorPointY="0.5",},
lay_flag_effect={classname="Panel",name="lay_flag_effect",parName="default",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="50",x="57",y="52",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="13945",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
img_paper={classname="CustomImageView",name="img_paper",parName="lay_paper_group",ZOrder="0",fileName="#v1_img_qipao2.png",scale9Enable="false",scale9Height="55",scale9Width="50",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="55",width="50",x="135",y="122",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6631",anchorPointX="0.5",anchorPointY="0.5",},
img_paper_icon={classname="CustomImageView",name="img_paper_icon",parName="lay_paper_group",ZOrder="1",fileName="#v1_img_zjm_hd.png",scale9Enable="false",scale9Height="60",scale9Width="60",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="60",width="60",x="134",y="123",visible="true",touchAble="false",flipX="false",scaleX="0.8",scaleY="0.8",opacity="255",rotation="0",tag="13713",anchorPointX="0.5",anchorPointY="0.5",},
lay_paper_effect={classname="Panel",name="lay_paper_effect",parName="lay_paper_group",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="50",x="109",y="99",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="14070",anchorPointX="0",anchorPointY="0",},
lay_tt={classname="Panel",name="lay_tt",parName="lay_paper_group",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="42",width="160",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="17483",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lay_bar_cd={classname="Panel",name="lay_bar_cd",parName="lay_tt",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="26",width="132",x="26",y="14",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6626",anchorPointX="0",anchorPointY="0",},
img_hand={classname="CustomImageView",name="img_hand",parName="lay_tt",ZOrder="0",fileName="#v1_img_shengchanzhong.png",scale9Enable="false",scale9Height="38",scale9Width="34",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="38",width="34",x="9",y="22",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6627",anchorPointX="0.5",anchorPointY="0.5",},
txt_cd={classname="CustomLabel",name="txt_cd",parName="lay_tt",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="93",y="27",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="6629",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable