local tTable = {}

tTable["texturesPng"] = {"ui/p1_button1.plist","ui/p1_commonse1.plist","ui/p1_commmon3_sep.plist","ui/p1_commonse3.plist","ui/p1_commmon5_sep.plist","ui/language/cn/p1_font2.plist","ui/p2_commmon1_sep.plist"}
tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="98",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="36",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_location={classname="Panel",name="lay_location",parName="default",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_btn_location.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="21",height="42",width="180",x="450",y="18",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="68",anchorPointX="0",anchorPointY="0",},
lay_sjdt={classname="Panel",name="lay_sjdt",parName="default",childCount="2",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v2_img_touxiangdi.png",height="98",width="131",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="464",anchorPointX="0",anchorPointY="0",},
lay_t={classname="Panel",name="lay_t",parName="default",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#02.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="28",capInsetsY="30",height="59",width="640",x="0",y="39",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="465",anchorPointX="0",anchorPointY="0",},
lay_b={classname="Panel",name="lay_b",parName="default",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_zjm_ziyuandi.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="20",capInsetsY="20",height="38",width="640",x="0",y="1",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="466",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
img_wz={classname="ImageView",name="img_wz",parName="lay_location",ZOrder="0",fileName="#v1_img_weizhi.png",scale9Enable="false",scale9Height="40",scale9Width="34",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="40",width="34",x="20",y="21",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="69",anchorPointX="0.5",anchorPointY="0.5",},
lb_lo_tips={classname="Label",name="lb_lo_tips",parName="lay_location",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="我的位置:",fontName="微软雅黑",fontSize="20",height="27",width="85",x="35",y="21",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="70",anchorPointX="0",anchorPointY="0.5",},
lb_lo={classname="Label",name="lb_lo",parName="lay_location",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="荆州",fontName="微软雅黑",fontSize="20",height="27",width="40",x="170",y="21",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="71",anchorPointX="1",anchorPointY="0.5",},
img_sj={classname="ImageView",name="img_sj",parName="lay_sjdt",ZOrder="0",fileName="#v1_btn_sjdt.png",scale9Enable="false",scale9Height="45",scale9Width="44",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="45",width="44",x="55",y="60",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="483",anchorPointX="0.5",anchorPointY="0.5",},
lb_sj={classname="Label",name="lb_sj",parName="lay_sjdt",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="世界地图",fontName="微软雅黑",fontSize="20",height="27",width="80",x="55",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="484",anchorPointX="0.5",anchorPointY="0.5",},
lay_item1={classname="Panel",name="lay_item1",parName="lay_t",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="29",capInsetsY="30",height="59",width="128",x="128",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="467",anchorPointX="0",anchorPointY="0",},
lay_item2={classname="Panel",name="lay_item2",parName="lay_t",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="18",height="59",width="128",x="256",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="468",anchorPointX="0",anchorPointY="0",},
lay_item3={classname="Panel",name="lay_item3",parName="lay_t",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="18",height="59",width="128",x="384",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="469",anchorPointX="0",anchorPointY="0",},
lay_item4={classname="Panel",name="lay_item4",parName="lay_t",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v2_img_dw_sj.png",height="59",width="128",x="512",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="470",anchorPointX="0",anchorPointY="0",},
lay_all={classname="Panel",name="lay_all",parName="lay_b",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="38",width="520",x="120",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="74",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
img_cc={classname="ImageView",name="img_cc",parName="lay_item1",ZOrder="0",fileName="#v2_btn_cc.png",scale9Enable="false",scale9Height="32",scale9Width="32",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="32",width="32",x="35",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="485",anchorPointX="0.5",anchorPointY="0.5",},
lb_cc={classname="Label",name="lb_cc",parName="lay_item1",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="城池",fontName="微软雅黑",fontSize="20",height="27",width="40",x="85",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="486",anchorPointX="0.5",anchorPointY="0.5",},
img_line_cc={classname="ImageView",name="img_line_cc",parName="lay_item1",ZOrder="0",fileName="#v2_line_biaoqianfenge.png",scale9Enable="false",scale9Height="52",scale9Width="2",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="52",width="2",x="126",y="29",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1001",anchorPointX="0.5",anchorPointY="0.5",},
lay_cc_red={classname="Panel",name="lay_cc_red",parName="lay_item1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="20",width="20",x="108",y="40",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1035",anchorPointX="0",anchorPointY="0",},
img_ss={classname="ImageView",name="img_ss",parName="lay_item2",ZOrder="0",fileName="#v2_btn_ss.png",scale9Enable="false",scale9Height="32",scale9Width="32",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="32",width="32",x="35",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="487",anchorPointX="0.5",anchorPointY="0.5",},
lb_ss={classname="Label",name="lb_ss",parName="lay_item2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="搜索",fontName="微软雅黑",fontSize="20",height="27",width="40",x="85",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="488",anchorPointX="0.5",anchorPointY="0.5",},
img_line_ss={classname="ImageView",name="img_line_ss",parName="lay_item2",ZOrder="0",fileName="#v2_line_biaoqianfenge.png",scale9Enable="false",scale9Height="52",scale9Width="2",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="52",width="2",x="126",y="29",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1003",anchorPointX="0.5",anchorPointY="0.5",},
img_jj={classname="ImageView",name="img_jj",parName="lay_item3",ZOrder="0",fileName="#v2_btn_tqq.png",scale9Enable="false",scale9Height="32",scale9Width="32",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="32",width="32",x="35",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="489",anchorPointX="0.5",anchorPointY="0.5",},
lb_jj={classname="Label",name="lb_jj",parName="lay_item3",ZOrder="100",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="夏1日",fontName="微软雅黑",fontSize="20",height="27",width="52",x="85",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="490",anchorPointX="0.5",anchorPointY="0.5",},
img_dw={classname="ImageView",name="img_dw",parName="lay_item4",ZOrder="0",fileName="#v1_img_weizhi.png",scale9Enable="false",scale9Height="40",scale9Width="34",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="40",width="34",x="35",y="30",visible="true",touchAble="false",flipX="false",scaleX="0.79999995",scaleY="0.79999995",opacity="255",rotation="0",tag="491",anchorPointX="0.5",anchorPointY="0.5",},
lb_dw={classname="ImageView",name="lb_dw",parName="lay_item4",ZOrder="0",fileName="#v2_fonts_dingwei.png",scale9Enable="false",scale9Height="24",scale9Width="43",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="24",width="43",x="75",y="30",visible="true",touchAble="false",flipX="false",scaleX="0.79999995",scaleY="0.79999995",opacity="255",rotation="0",tag="976",anchorPointX="0.5",anchorPointY="0.5",},
img_tili={classname="ImageView",name="img_tili",parName="lay_all",ZOrder="0",fileName="#v2_img_zjm_tili.png",scale9Enable="false",scale9Height="26",scale9Width="13",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="26",width="13",x="16",y="20",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="493",anchorPointX="0.5",anchorPointY="0.5",},
lb_tl={classname="Label",name="lb_tl",parName="lay_all",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="100/100",fontName="微软雅黑",fontSize="18",height="24",width="74",x="35",y="20",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="494",anchorPointX="0",anchorPointY="0.5",},
lay_res={classname="Panel",name="lay_res",parName="lay_all",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="40",width="410",x="110",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="495",anchorPointX="0",anchorPointY="0",},
lay_tili={classname="Panel",name="lay_tili",parName="lay_all",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="60",x="35",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="496",anchorPointX="0",anchorPointY="0",},
}

return tTable