local tTable = {}

tTable["texturesPng"] = {"ui/p2_commmon1_sep.plist"}
tTable["index_1"] = {
view={classname="Panel",name="view",parName="root",childCount="13",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="200",width="456",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="623",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
txt_content={classname="CustomLabel",name="txt_content",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="227",y="172",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="624",anchorPointX="0.5",anchorPointY="0.5",},
txt_title1={classname="CustomLabel",name="txt_title1",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="东面烽火台",fontName="微软雅黑",fontSize="20",height="27",width="100",x="100",y="125",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="625",anchorPointX="0.5",anchorPointY="0.5",},
txt_title2={classname="CustomLabel",name="txt_title2",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="西面烽火台",fontName="微软雅黑",fontSize="20",height="27",width="100",x="317",y="125",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="626",anchorPointX="0.5",anchorPointY="0.5",},
txt_title3={classname="CustomLabel",name="txt_title3",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="南面烽火台",fontName="微软雅黑",fontSize="20",height="27",width="100",x="100",y="51",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="627",anchorPointX="0.5",anchorPointY="0.5",},
txt_title4={classname="CustomLabel",name="txt_title4",parName="view",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="北面烽火台",fontName="微软雅黑",fontSize="20",height="27",width="100",x="317",y="51",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="628",anchorPointX="0.5",anchorPointY="0.5",},
img_select1={classname="CustomImageView",name="img_select1",parName="view",ZOrder="0",fileName="#v2_img_gouxuan.png",scale9Enable="false",scale9Height="35",scale9Width="32",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="35",width="32",x="174",y="124",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="629",anchorPointX="0.5",anchorPointY="0.5",},
img_select2={classname="CustomImageView",name="img_select2",parName="view",ZOrder="0",fileName="#v2_img_gouxuankuang.png",scale9Enable="false",scale9Height="32",scale9Width="32",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="32",width="32",x="390",y="124",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="632",anchorPointX="0.5",anchorPointY="0.5",},
img_select3={classname="CustomImageView",name="img_select3",parName="view",ZOrder="0",fileName="#v2_img_gouxuankuang.png",scale9Enable="false",scale9Height="32",scale9Width="32",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="32",width="32",x="174",y="51",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="633",anchorPointX="0.5",anchorPointY="0.5",},
img_select4={classname="CustomImageView",name="img_select4",parName="view",ZOrder="0",fileName="#v2_img_gouxuankuang.png",scale9Enable="false",scale9Height="32",scale9Width="32",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="32",width="32",x="390",y="51",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="634",anchorPointX="0.5",anchorPointY="0.5",},
lay_select1={classname="Panel",name="lay_select1",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="160",x="40",y="98",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="635",anchorPointX="0",anchorPointY="0",},
lay_select2={classname="Panel",name="lay_select2",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="160",x="256",y="98",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="636",anchorPointX="0",anchorPointY="0",},
lay_select3={classname="Panel",name="lay_select3",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="160",x="40",y="25",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="637",anchorPointX="0",anchorPointY="0",},
lay_select4={classname="Panel",name="lay_select4",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="160",x="256",y="25",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="638",anchorPointX="0",anchorPointY="0",},
}

return tTable