local tTable = {}

tTable["texturesPng"] = {"ui/p1_commmon2_sep.plist","icon/p1_icon6.plist","ui/bar/v1_bar_b1.png","ui/language/cn/p1_font1.plist","ui/p1_commmon1_sep.plist"}
tTable["index_1"] = {
lay_root={classname="Panel",name="lay_root",parName="root",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="570",width="560",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="25709",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_topinfo={classname="Panel",name="lay_topinfo",parName="lay_root",childCount="7",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen6_b.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="135",capInsetsY="9",height="130",width="524",x="18",y="419",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="25710",anchorPointX="0",anchorPointY="0",},
lay_title={classname="Panel",name="lay_title",parName="lay_root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_xiaobiaoti2.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="186",capInsetsY="25",height="50",width="524",x="18",y="354",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="25719",anchorPointX="0",anchorPointY="0",},
lay_prize={classname="Panel",name="lay_prize",parName="lay_root",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="290",width="524",x="16",y="46",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="25721",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
img_boss={classname="ImageView",name="img_boss",parName="lay_topinfo",ZOrder="5",fileName="#v1_img_boss.png",scale9Enable="false",scale9Height="144",scale9Width="128",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="144",width="128",x="63",y="62",visible="true",touchAble="false",flipX="false",scaleX="0.7",scaleY="0.7",opacity="255",rotation="0",tag="25711",anchorPointX="0.5",anchorPointY="0.5",},
lb_name={classname="Label",name="lb_name",parName="lay_topinfo",ZOrder="5",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="22",height="30",width="106",x="132",y="107",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="25712",anchorPointX="0",anchorPointY="0.5",},
lay_bar={classname="Panel",name="lay_bar",parName="lay_topinfo",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v1_bar_b1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="45",capInsetsY="9",height="18",width="249",x="132",y="69",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="25713",anchorPointX="0",anchorPointY="0",},
img_share={classname="ImageView",name="img_share",parName="lay_topinfo",ZOrder="5",fileName="#v1_btn_fenxiang.png",scale9Enable="false",scale9Height="72",scale9Width="72",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="72",width="72",x="462",y="80",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="25714",anchorPointX="0.5",anchorPointY="0.5",},
lb_share={classname="Label",name="lb_share",parName="lay_topinfo",ZOrder="5",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="分享",fontName="微软雅黑",fontSize="20",height="27",width="40",x="461",y="34",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="25715",anchorPointX="0.5",anchorPointY="0.5",},
lb_pos={classname="Label",name="lb_pos",parName="lay_topinfo",ZOrder="5",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="132",y="49",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="25716",anchorPointX="0",anchorPointY="0.5",},
lb_time={classname="Label",name="lb_time",parName="lay_topinfo",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="132",y="17",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="25717",anchorPointX="0",anchorPointY="0.5",},
lb_tip={classname="Label",name="lb_tip",parName="lay_title",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="15",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="25720",anchorPointX="0",anchorPointY="0.5",},
}

return tTable