local tTable = {}

tTable["texturesPng"] = {"icon/p1_icon_font.plist","ui/big_img/v2_bg_huangchengzhengduo.jpg","ui/v2_bg_popup_b.png"}
tTable["index_1"] = {
view={classname="Panel",name="view",parName="root",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="674",width="560",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="0",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_top={classname="Panel",name="lay_top",parName="view",childCount="6",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="120",width="556",x="2",y="543",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="512",anchorPointX="0",anchorPointY="0",},
lay_middle={classname="Panel",name="lay_middle",parName="view",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="ui/big_img/v2_bg_huangchengzhengduo.jpg",height="340",width="556",x="2",y="195",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="513",anchorPointX="0",anchorPointY="0",},
lay_bottom={classname="Panel",name="lay_bottom",parName="view",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/v2_bg_popup_b.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="150",capInsetsY="25",height="188",width="560",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="514",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_bg={classname="Panel",name="lay_bg",parName="lay_top",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="120",width="556",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="456",anchorPointX="0",anchorPointY="0",},
img_flag={classname="CustomImageView",name="img_flag",parName="lay_top",ZOrder="2",fileName="#v1_img_qun.png",scale9Enable="false",scale9Height="64",scale9Width="51",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="64",width="51",x="36",y="102",visible="true",touchAble="false",flipX="false",scaleX="0.8",scaleY="0.8",opacity="255",rotation="0",tag="438",anchorPointX="0.5",anchorPointY="0.5",},
lay_city_icon={classname="Panel",name="lay_city_icon",parName="lay_top",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="120",width="196",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="439",anchorPointX="0",anchorPointY="0",},
txt_name={classname="CustomLabel",name="txt_name",parName="lay_top",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="194",y="86",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="440",anchorPointX="0",anchorPointY="0.5",},
txt_pos={classname="CustomLabel",name="txt_pos",parName="lay_top",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="194",y="56",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="442",anchorPointX="0",anchorPointY="0.5",},
txt_own={classname="CustomLabel",name="txt_own",parName="lay_top",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="194",y="28",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="443",anchorPointX="0",anchorPointY="0.5",},
txt_state={classname="CustomLabel",name="txt_state",parName="lay_middle",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="24",height="31",width="116",x="275",y="81",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="516",anchorPointX="0.5",anchorPointY="0.5",},
txt_cd={classname="CustomLabel",name="txt_cd",parName="lay_middle",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="26",height="35",width="127",x="275",y="35",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="517",anchorPointX="0.5",anchorPointY="0.5",},
lay_btn_treasury={classname="Panel",name="lay_btn_treasury",parName="lay_bottom",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="60",width="156",x="196",y="68",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="515",anchorPointX="0",anchorPointY="0",},
}

return tTable