local tTable = {}

tTable["texturesPng"] = {"ui/v1_img_zhuanpan.png"}
tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="10",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="ui/v1_img_zhuanpan.png",height="544",width="609",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="13",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_goods1={classname="Panel",name="lay_goods1",parName="default",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="321",y="384",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="14",anchorPointX="0",anchorPointY="0",},
lay_goods2={classname="Panel",name="lay_goods2",parName="default",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="420",y="285",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="15",anchorPointX="0",anchorPointY="0",},
lay_goods3={classname="Panel",name="lay_goods3",parName="default",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="423",y="134",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="16",anchorPointX="0",anchorPointY="0",},
lay_goods4={classname="Panel",name="lay_goods4",parName="default",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="321",y="28",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="17",anchorPointX="0",anchorPointY="0",},
lay_goods5={classname="Panel",name="lay_goods5",parName="default",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="192",y="28",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="18",anchorPointX="0",anchorPointY="0",},
lay_goods6={classname="Panel",name="lay_goods6",parName="default",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="99",y="134",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="19",anchorPointX="0",anchorPointY="0",},
lay_goods7={classname="Panel",name="lay_goods7",parName="default",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="99",y="285",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="20",anchorPointX="0",anchorPointY="0",},
lay_goods8={classname="Panel",name="lay_goods8",parName="default",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="192",y="384",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="21",anchorPointX="0",anchorPointY="0",},
lay_center_text={classname="Panel",name="lay_center_text",parName="default",childCount="4",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="180",width="180",x="212",y="182",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="38",anchorPointX="0",anchorPointY="0",},
lay_center_goods={classname="Panel",name="lay_center_goods",parName="default",ZOrder="6",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="250",y="218",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="43",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
txt_center1={classname="CustomLabel",name="txt_center1",parName="lay_center_text",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="免费次数：6/6",fontName="微软雅黑",fontSize="20",height="27",width="133",x="92",y="129",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="39",anchorPointX="0.5",anchorPointY="0.5",},
txt_center2={classname="CustomLabel",name="txt_center2",parName="lay_center_text",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="每日5点所有道具状",fontName="微软雅黑",fontSize="20",height="27",width="172",x="90",y="96",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="40",anchorPointX="0.5",anchorPointY="0.5",},
txt_center3={classname="CustomLabel",name="txt_center3",parName="lay_center_text",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="态和免费次数都",fontName="微软雅黑",fontSize="20",height="27",width="140",x="96",y="64",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="41",anchorPointX="0.5",anchorPointY="0.5",},
txt_center4={classname="CustomLabel",name="txt_center4",parName="lay_center_text",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="会重置",fontName="微软雅黑",fontSize="20",height="27",width="60",x="90",y="32",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="42",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable