local tTable = {}

tTable["texturesPng"] = {"ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist"}
tTable["index_1"] = {
lay_root={classname="Panel",name="lay_root",parName="root",childCount="9",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_popup2.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="30",capInsetsY="30",height="170",width="170",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="33",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
img_line_1={classname="ImageView",name="img_line_1",parName="lay_root",ZOrder="0",fileName="#v1_line_blue1.png",scale9Enable="true",scale9Height="2",scale9Width="160",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="1",height="2",width="160",x="84",y="160",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="45",anchorPointX="0.5",anchorPointY="0.5",},
img_line_2={classname="ImageView",name="img_line_2",parName="lay_root",ZOrder="0",fileName="#v1_line_blue1.png",scale9Enable="true",scale9Height="2",scale9Width="160",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="1",height="2",width="160",x="84",y="109",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="46",anchorPointX="0.5",anchorPointY="0.5",},
img_line_3={classname="ImageView",name="img_line_3",parName="lay_root",ZOrder="0",fileName="#v1_line_blue1.png",scale9Enable="true",scale9Height="2",scale9Width="160",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="1",height="2",width="160",x="84",y="59",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="47",anchorPointX="0.5",anchorPointY="0.5",},
lb_tip_1={classname="Label",name="lb_tip_1",parName="lay_root",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="9",y="134",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="53",anchorPointX="0",anchorPointY="0.5",},
lb_tip_2={classname="Label",name="lb_tip_2",parName="lay_root",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="9",y="84",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="54",anchorPointX="0",anchorPointY="0.5",},
lb_tip_3={classname="Label",name="lb_tip_3",parName="lay_root",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="9",y="34",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="55",anchorPointX="0",anchorPointY="0.5",},
lay_type_1={classname="Panel",name="lay_type_1",parName="lay_root",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="160",x="5",y="110",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="49",anchorPointX="0",anchorPointY="0",},
lay_type_2={classname="Panel",name="lay_type_2",parName="lay_root",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="160",x="5",y="60",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="51",anchorPointX="0",anchorPointY="0",},
lay_type_3={classname="Panel",name="lay_type_3",parName="lay_root",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="160",x="5",y="10",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="52",anchorPointX="0",anchorPointY="0",},
}

return tTable