local tTable = {}

tTable["texturesPng"] = {"ui/p1_commmon3_sep.plist","ui/p1_commmon1_sep.plist","icon/p1_icon_font.plist","ui/p1_commonse1.plist","ui/bar/v1_bar_b2.png","ui/bg_fight/bg_fight.jpg","ui/bg_fight/bg_fight_gate.png"}
tTable["index_1"] = {
default={classname="Panel",name="default@fill_layout",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1138",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
viewgroup={classname="Panel",name="viewgroup@fill_layout",parName="default",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1138",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
main={classname="Panel",name="main",parName="viewgroup",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1138",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lay_con_top={classname="Panel",name="lay_con_top",parName="main",childCount="4",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="32",capInsetsY="32",height="206",width="640",x="0",y="934",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="14",anchorPointX="0",anchorPointY="0",},
lay_con_center={classname="Panel",name="lay_con_center",parName="main",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1138",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="11",anchorPointX="0",anchorPointY="0",},
lay_con_bottom={classname="Panel",name="lay_con_bottom",parName="main",childCount="2",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="200",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="15",anchorPointX="0",anchorPointY="0",},
}
tTable["index_5"] = {
lay_left={classname="Panel",name="lay_left",parName="lay_con_top",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_img_dikuang1.png",height="72",width="268",x="0",y="134",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="35",anchorPointX="0",anchorPointY="0",},
lay_right={classname="Panel",name="lay_right",parName="lay_con_top",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="72",width="268",x="372",y="134",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="36",anchorPointX="0",anchorPointY="0",},
lay_center={classname="Panel",name="lay_center",parName="lay_con_top",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_img_title2.png",height="66",width="170",x="235",y="140",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="49",anchorPointX="0",anchorPointY="0",},
lay_bottom={classname="Panel",name="lay_bottom",parName="lay_con_top",childCount="9",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_honglanquyu.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="320",capInsetsY="32",height="134",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="50",anchorPointX="0",anchorPointY="0",},
bg_fight={classname="ImageView",name="bg_fight",parName="lay_con_center",ZOrder="0",fileName="ui/bg_fight/bg_fight.jpg",scale9Enable="false",scale9Height="2050",scale9Width="1152",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="2050",width="1152",x="320",y="380",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="13",anchorPointX="0.5",anchorPointY="0.5",},
img_gate={classname="ImageView",name="img_gate",parName="lay_con_center",ZOrder="10",fileName="ui/bg_fight/bg_fight_gate.png",scale9Enable="false",scale9Height="442",scale9Width="424",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="442",width="424",x="684",y="524",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="124",anchorPointX="0.5",anchorPointY="0.5",},
lay_btn_finish={classname="Panel",name="lay_btn_finish",parName="lay_con_bottom",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="460",y="60",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="34",anchorPointX="0",anchorPointY="0",},
lb_jump_tips={classname="Label",name="lb_jump_tips",parName="lay_con_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="536",y="40",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="138",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_6"] = {
img_c_left={classname="ImageView",name="img_c_left",parName="lay_left",ZOrder="0",fileName="#v1_img_han.png",scale9Enable="false",scale9Height="64",scale9Width="51",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="64",width="51",x="25",y="40",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="63",anchorPointX="0.5",anchorPointY="0.5",},
lb_c_name_left={classname="Label",name="lb_c_name_left",parName="lay_left",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="140",y="36",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="64",anchorPointX="0.5",anchorPointY="0.5",},
img_right={classname="ImageView",name="img_right",parName="lay_right",ZOrder="0",fileName="#v1_img_dikuang1.png",scale9Enable="false",scale9Height="72",scale9Width="268",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="72",width="268",x="134",y="36",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="37",anchorPointX="0.5",anchorPointY="0.5",},
img_c_right={classname="ImageView",name="img_c_right",parName="lay_right",ZOrder="10",fileName="#v1_img_qing.png",scale9Enable="false",scale9Height="64",scale9Width="51",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="64",width="51",x="241",y="40",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="65",anchorPointX="0.5",anchorPointY="0.5",},
lb_c_name_right={classname="Label",name="lb_c_name_right",parName="lay_right",ZOrder="10",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="128",y="36",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="66",anchorPointX="0.5",anchorPointY="0.5",},
lb_title={classname="Label",name="lb_title",parName="lay_center",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="攻城战斗",fontName="微软雅黑",fontSize="32",height="41",width="128",x="85",y="33",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="84",anchorPointX="0.5",anchorPointY="0.5",},
img_arrow={classname="ImageView",name="img_arrow",parName="lay_bottom",ZOrder="10",fileName="#v1_img_lanjiantou.png",scale9Enable="false",scale9Height="41",scale9Width="65",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="41",width="65",x="320",y="75",visible="true",touchAble="false",flipX="false",scaleX="0.79999995",scaleY="0.79999995",opacity="255",rotation="0",tag="83",anchorPointX="0.5",anchorPointY="0.5",},
lay_bar_l={classname="Panel",name="lay_bar_l",parName="lay_bottom",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v1_bar_b2.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="41",capInsetsY="6",height="18",width="188",x="10",y="10",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="85",anchorPointX="0",anchorPointY="0",},
lay_bar_r={classname="Panel",name="lay_bar_r",parName="lay_bottom",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v1_bar_b2.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="41",capInsetsY="6",height="18",width="188",x="443",y="10",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="86",anchorPointX="0",anchorPointY="0",},
lb_h_name_l={classname="Label",name="lb_h_name_l",parName="lay_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="赵云老",fontName="微软雅黑",fontSize="18",height="24",width="54",x="313",y="20",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="87",anchorPointX="1",anchorPointY="0.5",},
lb_h_lv_l={classname="Label",name="lb_h_lv_l",parName="lay_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Lv.231",fontName="微软雅黑",fontSize="18",height="24",width="55",x="203",y="20",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="88",anchorPointX="0",anchorPointY="0.5",},
lb_h_name_r={classname="Label",name="lb_h_name_r",parName="lay_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="关云长",fontName="微软雅黑",fontSize="18",height="24",width="54",x="327",y="20",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="89",anchorPointX="0",anchorPointY="0.5",},
lb_h_lv_r={classname="Label",name="lb_h_lv_r",parName="lay_bottom",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Lv.741",fontName="微软雅黑",fontSize="18",height="24",width="55",x="438",y="20",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="90",anchorPointX="1",anchorPointY="0.5",},
lay_h_list_l={classname="Panel",name="lay_h_list_l",parName="lay_bottom",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="95",width="300",x="0",y="32",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="107",anchorPointX="0",anchorPointY="0",},
lay_h_list_r={classname="Panel",name="lay_h_list_r",parName="lay_bottom",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="95",width="300",x="340",y="32",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="108",anchorPointX="0",anchorPointY="0",},
}

return tTable