local tTable = {}

tTable["texturesPng"] = {"ui/language/cn/p2_font1.plist","ui/p2_commmon1_sep.plist","ui/p1_commonse1.plist"}
tTable["index_1"] = {
layout_power_balance={classname="Panel",name="layout_power_balance",parName="root",childCount="8",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="340",width="500",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="204",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lb_par_1={classname="Label",name="lb_par_1",parName="layout_power_balance",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="210",y="303",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="207",anchorPointX="1",anchorPointY="0.5",},
lb_par_2={classname="Label",name="lb_par_2",parName="layout_power_balance",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="290",y="303",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="209",anchorPointX="0",anchorPointY="0.5",},
img_vs={classname="ImageView",name="img_vs",parName="layout_power_balance",ZOrder="0",fileName="#v2_fonts_VS.png",scale9Enable="false",scale9Height="27",scale9Width="42",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="27",width="42",x="250",y="303",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="208",anchorPointX="0.5",anchorPointY="0.5",},
img_bg={classname="ImageView",name="img_bg",parName="layout_power_balance",ZOrder="0",fileName="#v2_img_xiaobiaoti3.png",scale9Enable="false",scale9Height="50",scale9Width="640",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="50",width="640",x="250",y="246",visible="true",touchAble="false",flipX="false",scaleX="0.77",scaleY="0.77",opacity="255",rotation="0",tag="206",anchorPointX="0.5",anchorPointY="0.5",},
img_line_1={classname="ImageView",name="img_line_1",parName="layout_power_balance",ZOrder="0",fileName="#v1_line_blue1.png",scale9Enable="true",scale9Height="2",scale9Width="460",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="1",height="2",width="460",x="250",y="186",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="210",anchorPointX="0.5",anchorPointY="0.5",},
img_line_2={classname="ImageView",name="img_line_2",parName="layout_power_balance",ZOrder="0",fileName="#v1_line_blue1.png",scale9Enable="true",scale9Height="2",scale9Width="460",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="1",height="2",width="460",x="250",y="146",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="211",anchorPointX="0.5",anchorPointY="0.5",},
img_line_3={classname="ImageView",name="img_line_3",parName="layout_power_balance",ZOrder="0",fileName="#v1_line_blue1.png",scale9Enable="true",scale9Height="2",scale9Width="460",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="1",height="2",width="460",x="250",y="106",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="212",anchorPointX="0.5",anchorPointY="0.5",},
img_line_4={classname="ImageView",name="img_line_4",parName="layout_power_balance",ZOrder="0",fileName="#v1_line_blue1.png",scale9Enable="true",scale9Height="2",scale9Width="460",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="1",height="2",width="460",x="250",y="66",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="213",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable