local tTable = {}


tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="194",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_studing={classname="Panel",name="lay_studing",parName="default",childCount="8",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="35",height="174",width="600",x="20",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="11",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
img_di={classname="ImageView",name="img_di",parName="lay_studing",ZOrder="0",fileName="#v2_img_jinduyanjiudi.png",scale9Enable="true",scale9Height="178",scale9Width="640",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="320",capInsetsY="35",height="178",width="640",x="300",y="87",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="561",anchorPointX="0.5",anchorPointY="0.5",},
lb_cost={classname="Label",name="lb_cost",parName="lay_studing",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="530",y="129",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="43",anchorPointX="0.5",anchorPointY="0.5",},
lay_btn={classname="Panel",name="lay_btn",parName="lay_studing",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="455",y="54",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="42",anchorPointX="0",anchorPointY="0",},
lay_detail={classname="Panel",name="lay_detail",parName="lay_studing",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="110",width="300",x="138",y="49",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="36",anchorPointX="0",anchorPointY="0",},
lay_bar={classname="Panel",name="lay_bar",parName="lay_studing",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v1_bar_b1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="45",capInsetsY="9",height="18",width="390",x="165",y="19",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="31",anchorPointX="0",anchorPointY="0",},
img_clock={classname="ImageView",name="img_clock",parName="lay_studing",ZOrder="0",fileName="#v2_img_clock.png",scale9Enable="false",scale9Height="24",scale9Width="24",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="24",width="24",x="54",y="26",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="30",anchorPointX="0.5",anchorPointY="0.5",},
lb_time={classname="Label",name="lb_time",parName="lay_studing",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="55:55:55",fontName="微软雅黑",fontSize="20",height="27",width="82",x="69",y="26",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="29",anchorPointX="0",anchorPointY="0.5",},
lay_icon={classname="Panel",name="lay_icon",parName="lay_studing",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="15",y="49",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="28",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lb_name={classname="Label",name="lb_name",parName="lay_detail",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="科技名",fontName="微软雅黑",fontSize="22",height="30",width="66",x="0",y="90",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="37",anchorPointX="0",anchorPointY="0.5",},
lb_lv={classname="Label",name="lb_lv",parName="lay_detail",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Lv.5",fontName="微软雅黑",fontSize="22",height="30",width="41",x="85",y="90",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="38",anchorPointX="0",anchorPointY="0.5",},
lb_p1={classname="Label",name="lb_p1",parName="lay_detail",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="50% -",fontName="微软雅黑",fontSize="22",height="30",width="63",x="150",y="90",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="39",anchorPointX="0",anchorPointY="0.5",},
lb_p2={classname="Label",name="lb_p2",parName="lay_detail",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="60%",fontName="微软雅黑",fontSize="22",height="30",width="46",x="220",y="90",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="40",anchorPointX="0",anchorPointY="0.5",},
lb_desc={classname="Label",name="lb_desc",parName="lay_detail",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="60",areaWidth="295",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="60",width="295",x="0",y="36",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="41",anchorPointX="0",anchorPointY="0.5",},
}

return tTable