local tTable = {}


tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="480",width="528",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="69",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_btn_chat={classname="Panel",name="lay_btn_chat",parName="default",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="60",width="150",x="186",y="8",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="77",anchorPointX="0",anchorPointY="0",},
lay_detect1={classname="Panel",name="lay_detect1",parName="default",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_bluekelashen.jpg",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="15",capInsetsY="15",height="294",width="145",x="19",y="168",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1407",anchorPointX="0",anchorPointY="0",},
lay_detect2={classname="Panel",name="lay_detect2",parName="default",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_bluekelashen.jpg",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="15",capInsetsY="15",height="294",width="145",x="192",y="168",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1412",anchorPointX="0",anchorPointY="0",},
lay_detect3={classname="Panel",name="lay_detect3",parName="default",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_bluekelashen.jpg",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="15",capInsetsY="15",height="294",width="145",x="366",y="169",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1415",anchorPointX="0",anchorPointY="0",},
txt_tip1={classname="CustomLabel",name="txt_tip1",parName="default",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="60",areaWidth="480",hAlignment="1",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="60",width="480",x="22",y="154",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1418",anchorPointX="0",anchorPointY="1",},
}
tTable["index_3"] = {
txt_detect_name1={classname="CustomLabel",name="txt_detect_name1",parName="lay_detect1",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="74",y="113",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="71",anchorPointX="0.5",anchorPointY="0.5",},
lay_icon1={classname="Panel",name="lay_icon1",parName="lay_detect1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_img_chujizhencha.png",height="100",width="100",x="24",y="141",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1409",anchorPointX="0",anchorPointY="0",},
txt_success1={classname="CustomLabel",name="txt_success1",parName="lay_detect1",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="75",y="267",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="93",anchorPointX="0.5",anchorPointY="0.5",},
lay_btn1={classname="Panel",name="lay_btn1",parName="lay_detect1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="100",x="24",y="3",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="74",anchorPointX="0",anchorPointY="0",},
txt_success2={classname="CustomLabel",name="txt_success2",parName="lay_detect2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="74",y="267",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="94",anchorPointX="0.5",anchorPointY="0.5",},
txt_detect_name2={classname="CustomLabel",name="txt_detect_name2",parName="lay_detect2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="72",y="113",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="72",anchorPointX="0.5",anchorPointY="0.5",},
lay_btn2={classname="Panel",name="lay_btn2",parName="lay_detect2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="100",x="24",y="3",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="75",anchorPointX="0",anchorPointY="0",},
lay_icon2={classname="Panel",name="lay_icon2",parName="lay_detect2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_img_zhongjizhencha.png",height="100",width="100",x="24",y="141",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1413",anchorPointX="0",anchorPointY="0",},
txt_success3={classname="CustomLabel",name="txt_success3",parName="lay_detect3",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="73",y="267",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="95",anchorPointX="0.5",anchorPointY="0.5",},
txt_detect_name3={classname="CustomLabel",name="txt_detect_name3",parName="lay_detect3",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="71",y="113",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="73",anchorPointX="0.5",anchorPointY="0.5",},
lay_btn3={classname="Panel",name="lay_btn3",parName="lay_detect3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="100",x="25",y="3",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="76",anchorPointX="0",anchorPointY="0",},
lay_icon3={classname="Panel",name="lay_icon3",parName="lay_detect3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_img_gaojizhencha.png",height="100",width="100",x="24",y="141",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1416",anchorPointX="0",anchorPointY="0",},
}

return tTable