local tTable = {}

tTable["texturesPng"] = {"ui/p1_commonse1.plist","ui/p1_commmon1_sep.plist"}
tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1066",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="348",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
view={classname="Panel",name="view",parName="default",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1066",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="349",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_info1={classname="Panel",name="lay_info1",parName="view",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen7.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="63",capInsetsY="65",height="130",width="600",x="19",y="920",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1727",anchorPointX="0",anchorPointY="0",},
lay_banner1={classname="Panel",name="lay_banner1",parName="view",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_xiaobiaoti2.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="186",capInsetsY="24",height="48",width="600",x="19",y="868",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1734",anchorPointX="0",anchorPointY="0",},
lay_info2={classname="Panel",name="lay_info2",parName="view",childCount="8",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="138",width="600",x="19",y="730",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1736",anchorPointX="0",anchorPointY="0",},
lay_banner2={classname="Panel",name="lay_banner2",parName="view",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_xiaobiaoti2.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="186",capInsetsY="24",height="48",width="600",x="19",y="683",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1742",anchorPointX="0",anchorPointY="0",},
lay_content={classname="Panel",name="lay_content",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="681",width="600",x="19",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1744",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
txt_name={classname="CustomLabel",name="txt_name",parName="lay_info1",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="148",y="104",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1729",anchorPointX="0",anchorPointY="0.5",},
txt_lv={classname="CustomLabel",name="txt_lv",parName="lay_info1",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="253",y="104",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1730",anchorPointX="0",anchorPointY="0.5",},
txt_pos={classname="CustomLabel",name="txt_pos",parName="lay_info1",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="148",y="59",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1731",anchorPointX="0",anchorPointY="0.5",},
txt_move_time_title={classname="CustomLabel",name="txt_move_time_title",parName="lay_info1",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="148",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1732",anchorPointX="0",anchorPointY="0.5",},
txt_move_time={classname="CustomLabel",name="txt_move_time",parName="lay_info1",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="292",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1733",anchorPointX="0",anchorPointY="0.5",},
txt_banner_tip1={classname="CustomLabel",name="txt_banner_tip1",parName="lay_banner1",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="23",y="24",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1735",anchorPointX="0",anchorPointY="0.5",},
txt_remain_title={classname="CustomLabel",name="txt_remain_title",parName="lay_info2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="219",y="113",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1737",anchorPointX="0.5",anchorPointY="0.5",},
txt_speed_title={classname="CustomLabel",name="txt_speed_title",parName="lay_info2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="220",y="81",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1738",anchorPointX="0.5",anchorPointY="0.5",},
txt_collect_time_title={classname="CustomLabel",name="txt_collect_time_title",parName="lay_info2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="220",y="48",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1739",anchorPointX="0.5",anchorPointY="0.5",},
txt_preview_title={classname="CustomLabel",name="txt_preview_title",parName="lay_info2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="220",y="16",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1740",anchorPointX="0.5",anchorPointY="0.5",},
lay_richtext_speed={classname="Panel",name="lay_richtext_speed",parName="lay_info2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="27",width="95",x="279",y="69",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1741",anchorPointX="0",anchorPointY="0",},
txt_remain={classname="CustomLabel",name="txt_remain",parName="lay_info2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="326",y="113",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="350",anchorPointX="0.5",anchorPointY="0.5",},
txt_collect_time={classname="CustomLabel",name="txt_collect_time",parName="lay_info2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="326",y="50",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="352",anchorPointX="0.5",anchorPointY="0.5",},
txt_preview={classname="CustomLabel",name="txt_preview",parName="lay_info2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="326",y="16",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="353",anchorPointX="0.5",anchorPointY="0.5",},
lay_banner_tip2={classname="CustomLabel",name="lay_banner_tip2",parName="lay_banner2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="72",y="26",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1743",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable