local tTable = {}


tTable["index_1"] = {
layout_root={classname="Panel",name="layout_root@fill_layout",parName="root",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="2",capInsetsWidth="2",capInsetsX="22",capInsetsY="22",height="680",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="50",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_main={classname="Panel",name="lay_main@fill_layout",parName="layout_root",childCount="2",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="610",width="640",x="0",y="70",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="510",anchorPointX="0",anchorPointY="0",},
lay_bottom={classname="Panel",name="lay_bottom",parName="layout_root",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="70",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="505",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_info={classname="Panel",name="lay_info",parName="lay_main",childCount="8",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="160",width="640",x="0",y="450",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="57",anchorPointX="0",anchorPointY="0",},
lay_content={classname="Panel",name="lay_content@fill_layout",parName="lay_main",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="110",height="440",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="62",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lab_index={classname="Label",name="lab_index",parName="lay_info",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="30",y="130",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="54",anchorPointX="0",anchorPointY="0.5",},
lab_remaining_time={classname="Label",name="lab_remaining_time",parName="lay_info",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="320",y="130",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="55",anchorPointX="0.5",anchorPointY="0.5",},
lab_score={classname="Label",name="lab_score",parName="lay_info",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="542",y="130",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="56",anchorPointX="0.5",anchorPointY="0.5",},
lab_question={classname="Label",name="lab_question",parName="lay_info",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="90",areaWidth="580",hAlignment="1",vAlignment="1",text="Text Label",fontName="微软雅黑",fontSize="20",height="90",width="580",x="30",y="100",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="61",anchorPointX="0",anchorPointY="1",},
lab_pre_exam_info={classname="Label",name="lab_pre_exam_info",parName="lay_info",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="22",height="30",width="106",x="320",y="74",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="827",anchorPointX="0.5",anchorPointY="0.5",},
lab_exam_state_tip={classname="Label",name="lab_exam_state_tip",parName="lay_info",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="320",y="42",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="828",anchorPointX="0.5",anchorPointY="0.5",},
lay_share={classname="Panel",name="lay_share",parName="lay_info",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="62",width="155",x="465",y="101",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="725",anchorPointX="0",anchorPointY="0",},
img_line={classname="ImageView",name="img_line",parName="lay_info",ZOrder="0",fileName="#v1_line_blue1.png",scale9Enable="true",scale9Height="2",scale9Width="580",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="0",height="2",width="580",x="320",y="108",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="776",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_5"] = {
img_share={classname="ImageView",name="img_share",parName="lay_share",ZOrder="0",fileName="#v1_btn_fenxiang.png",scale9Enable="false",scale9Height="72",scale9Width="72",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="72",width="72",x="51",y="32",visible="true",touchAble="false",flipX="false",scaleX="0.79999995",scaleY="0.79999995",opacity="255",rotation="0",tag="829",anchorPointX="0.5",anchorPointY="0.5",},
lab_share={classname="Label",name="lab_share",parName="lay_share",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="分享",fontName="微软雅黑",fontSize="20",height="27",width="40",x="78",y="29",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="830",anchorPointX="0",anchorPointY="0.5",},
}

return tTable