local tTable = {}

tTable["texturesPng"] = {"ui/p2_commmon1_sep.plist","ui/language/cn/p2_font_sep.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/bar/v2_bar_b1_zjm.png"}
tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="116",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="36",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
view={classname="Panel",name="view",parName="default",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="116",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="83",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_h_top={classname="Panel",name="lay_h_top",parName="view",childCount="3",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_btn_zjm_zhandouli.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="2",capInsetsY="41",height="60",width="640",x="0",y="56",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="85",anchorPointX="0",anchorPointY="0",},
lay_bottom={classname="Panel",name="lay_bottom",parName="view",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v2_img_zjm_ziyuandi.png",height="38",width="640",x="0",y="19",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="102",anchorPointX="0",anchorPointY="0",},
lay_toux={classname="Panel",name="lay_toux",parName="view",childCount="4",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="116",width="82",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="84",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lay_cz={classname="Panel",name="lay_cz",parName="lay_h_top",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v2_btn_zjm_chongzhi_.png",height="60",width="200",x="440",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="88",anchorPointX="0",anchorPointY="0",},
lay_zl={classname="Panel",name="lay_zl",parName="lay_h_top",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="60",width="240",x="200",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="86",anchorPointX="0",anchorPointY="0",},
lay_vip={classname="Panel",name="lay_vip",parName="lay_h_top",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v2_btn_zjm_VIP.png",height="60",width="200",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="524",anchorPointX="0",anchorPointY="0",},
lay_tili={classname="Panel",name="lay_tili",parName="lay_bottom",childCount="3",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="1",height="36",width="114",x="82",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="137",anchorPointX="0",anchorPointY="0",},
lay_res={classname="Panel",name="lay_res",parName="lay_bottom",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="38",width="444",x="196",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="528",anchorPointX="0",anchorPointY="0",},
img_c={classname="ImageView",name="img_c",parName="lay_toux",ZOrder="10",fileName="#v1_img_qing.png",scale9Enable="false",scale9Height="64",scale9Width="51",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="64",width="51",x="85",y="98",visible="true",touchAble="false",flipX="false",scaleX="0.6999999",scaleY="0.6999999",opacity="255",rotation="0",tag="92",anchorPointX="0.5",anchorPointY="0.5",},
lay_txtop={classname="Panel",name="lay_txtop",parName="lay_toux",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="82",width="82",x="0",y="34",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="522",anchorPointX="0",anchorPointY="0",},
lay_txbottom={classname="Panel",name="lay_txbottom",parName="lay_toux",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_zjm_xuetiaodi.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="41",capInsetsY="12",height="16",width="82",x="1",y="19",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="523",anchorPointX="0",anchorPointY="0",},
lay_lv={classname="Panel",name="lay_lv",parName="lay_toux",childCount="1",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v2_img_dengjidi_zjm.png",height="26",width="26",x="62",y="35",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="608",anchorPointX="0",anchorPointY="0",},
}
tTable["index_5"] = {
lay_cz_v={classname="Panel",name="lay_cz_v",parName="lay_cz",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="22",width="72",x="120",y="20",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="94",anchorPointX="0",anchorPointY="0",},
img_hj={classname="ImageView",name="img_hj",parName="lay_cz",ZOrder="2",fileName="#v1_img_qianbi.png",scale9Enable="false",scale9Height="36",scale9Width="36",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="36",width="36",x="103",y="35",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="183",anchorPointX="0.5",anchorPointY="0.5",},
lay_zjm_zl={classname="Panel",name="lay_zjm_zl",parName="lay_zl",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="200",x="0",y="20",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="527",anchorPointX="0",anchorPointY="0",},
lay_bb={classname="Panel",name="lay_bb",parName="lay_zl",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="20",width="80",x="0",y="2",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="139",anchorPointX="0",anchorPointY="0",},
lay_qb={classname="Panel",name="lay_qb",parName="lay_zl",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="1",capInsetsY="1",height="20",width="80",x="80",y="2",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="141",anchorPointX="0",anchorPointY="0",},
lay_gb={classname="Panel",name="lay_gb",parName="lay_zl",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="20",width="80",x="160",y="2",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="140",anchorPointX="0",anchorPointY="0",},
lb_vip={classname="LabelAtlas",name="lb_vip",parName="lay_vip",ZOrder="0",itemHeight="28",itemWidth="15",startCharMap="0",stringValue="1",charMapFile="ui/atlas/v2_img_zjm_vipshuzi.png",height="28",width="15",x="150",y="29",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="607",anchorPointX="0.5",anchorPointY="0.5",},
img_tl={classname="ImageView",name="img_tl",parName="lay_tili",ZOrder="0",fileName="#v2_img_zjm_tili.png",scale9Enable="false",scale9Height="26",scale9Width="13",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="26",width="13",x="19",y="19",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="98",anchorPointX="0.5",anchorPointY="0.5",},
lay_tl={classname="Panel",name="lay_tl",parName="lay_tili",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="40",width="60",x="40",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="108",anchorPointX="0",anchorPointY="0",},
lb_tl={classname="Label",name="lb_tl",parName="lay_tili",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="888k",fontName="微软雅黑",fontSize="20",height="27",width="47",x="40",y="19",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="142",anchorPointX="0",anchorPointY="0.5",},
lay_icon={classname="Panel",name="lay_icon",parName="lay_txtop",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="76",width="76",x="3",y="3",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="91",anchorPointX="0",anchorPointY="0",},
lay_jy={classname="Panel",name="lay_jy",parName="lay_txbottom",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="ui/bar/v2_bar_b1_zjm.png",height="10",width="74",x="3",y="3",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="90",anchorPointX="0",anchorPointY="0",},
lb_lv={classname="Label",name="lb_lv",parName="lay_lv",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="123",fontName="微软雅黑",fontSize="15",height="20",width="27",x="13",y="13",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="609",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_6"] = {
lb_cz_v={classname="Label",name="lb_cz_v",parName="lay_cz_v",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="154222",fontName="微软雅黑",fontSize="20",height="27",width="72",x="35",y="11",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="95",anchorPointX="0.5",anchorPointY="0.5",},
img_zhanli={classname="ImageView",name="img_zhanli",parName="lay_zjm_zl",ZOrder="0",fileName="#v2_img_zjm_zhanli.png",scale9Enable="false",scale9Height="41",scale9Width="40",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="41",width="40",x="20",y="21",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="526",anchorPointX="0.5",anchorPointY="0.5",},
lb_zl={classname="Label",name="lb_zl",parName="lay_zjm_zl",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="战力：1235",fontName="微软雅黑",fontSize="22",height="30",width="118",x="50",y="21",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="96",anchorPointX="0",anchorPointY="0.5",},
img_bb={classname="ImageView",name="img_bb",parName="lay_bb",ZOrder="0",fileName="#v2_img_zjm_bubing.png",scale9Enable="false",scale9Height="20",scale9Width="20",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="20",width="20",x="15",y="10",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="99",anchorPointX="0.5",anchorPointY="0.5",},
lb_bb={classname="Label",name="lb_bb",parName="lay_bb",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="888k",fontName="微软雅黑",fontSize="20",height="27",width="47",x="30",y="10",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="105",anchorPointX="0",anchorPointY="0.5",},
img_qb={classname="ImageView",name="img_qb",parName="lay_qb",ZOrder="0",fileName="#v2_img_zjm_qibing.png",scale9Enable="false",scale9Height="20",scale9Width="20",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="20",width="20",x="15",y="10",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="101",anchorPointX="0.5",anchorPointY="0.5",},
lb_qb={classname="Label",name="lb_qb",parName="lay_qb",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="1234",fontName="微软雅黑",fontSize="20",height="27",width="48",x="30",y="10",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="107",anchorPointX="0",anchorPointY="0.5",},
img_gb={classname="ImageView",name="img_gb",parName="lay_gb",ZOrder="0",fileName="#v2_img_zjm_gongbing.png",scale9Enable="false",scale9Height="20",scale9Width="20",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="20",width="20",x="15",y="10",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="100",anchorPointX="0.5",anchorPointY="0.5",},
lb_gb={classname="Label",name="lb_gb",parName="lay_gb",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="88k",fontName="微软雅黑",fontSize="20",height="27",width="35",x="30",y="10",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="106",anchorPointX="0",anchorPointY="0.5",},
}

return tTable