local tTable = {}

tTable["texturesPng"] = {"ui/update_bin/v1_upd_blackjianbian.png","ui/update_bin/v1_bar_loading1_lau.png","ui/update_bin/v1_ball.png","ui/update_bin/v1_bar_loading2_lau.png","ui/p1_commmon2_sep.plist","ui/p1_commonse3.plist","ui/p1_commonse1.plist","ui/p1_button1.plist"}
tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1138",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_bottom={classname="Panel",name="lay_bottom",parName="default",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="230",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9",anchorPointX="0",anchorPointY="0",},
lay_tmp={classname="Panel",name="lay_tmp",parName="default",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="938",width="640",x="0",y="130",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="13",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_temp_tips={classname="Panel",name="lay_temp_tips",parName="lay_bottom",childCount="4",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/update_bin/v1_upd_blackjianbian.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="133",capInsetsY="32",height="115",width="640",x="0",y="115",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="26",anchorPointX="0",anchorPointY="0",},
lay_ser={classname="Panel",name="lay_ser",parName="lay_tmp",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_lkgaufreje.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="17",capInsetsY="0",height="35",width="348",x="146",y="170",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="14",anchorPointX="0",anchorPointY="0",},
lay_pk_tips={classname="Panel",name="lay_pk_tips",parName="lay_tmp",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="70",width="300",x="170",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="18",anchorPointX="0",anchorPointY="0",},
lay_gotogame={classname="Panel",name="lay_gotogame",parName="lay_tmp",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="80",width="200",x="220",y="75",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="22",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lb_tips={classname="Label",name="lb_tips",parName="lay_temp_tips",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="320",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="12",anchorPointX="0.5",anchorPointY="0.5",},
lb_slider={classname="Label",name="lb_slider",parName="lay_temp_tips",ZOrder="11",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="320",y="60",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="11",anchorPointX="0.5",anchorPointY="0.5",},
slider={classname="Slider",name="slider",parName="lay_temp_tips",ZOrder="0",percent="50",ballNormal="ui/update_bin/v1_ball.png",barFileName="ui/update_bin/v1_bar_loading1_lau.png",progressBar="ui/update_bin/v1_bar_loading2_lau.png",scale9Enable="false",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="22",width="614",x="320",y="60",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="10",anchorPointX="0.5",anchorPointY="0.5",},
lb_game_tips={classname="Label",name="lb_game_tips",parName="lay_temp_tips",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="320",y="95",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="27",anchorPointX="0.5",anchorPointY="0.5",},
img_state={classname="ImageView",name="img_state",parName="lay_ser",ZOrder="0",fileName="#v1_img_xycj.png",scale9Enable="false",scale9Height="34",scale9Width="34",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="34",width="34",x="50",y="18",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="15",anchorPointX="0.5",anchorPointY="0.5",},
lb_ser_name={classname="Label",name="lb_ser_name",parName="lay_ser",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="24",height="31",width="116",x="174",y="18",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="16",anchorPointX="0.5",anchorPointY="0.5",},
lb_ser_change={classname="Label",name="lb_ser_change",parName="lay_ser",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="换区",fontName="微软雅黑",fontSize="24",height="31",width="48",x="310",y="18",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="17",anchorPointX="0.5",anchorPointY="0.5",},
lay_pk_gou={classname="Panel",name="lay_pk_gou",parName="lay_pk_tips",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v1_img_gouxuankuang.png",height="40",width="40",x="0",y="15",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="19",anchorPointX="0",anchorPointY="0",},
lb_pk={classname="Label",name="lb_pk",parName="lay_pk_tips",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="我同意游戏中存在PK玩法",fontName="微软雅黑",fontSize="18",height="24",width="202",x="50",y="35",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="21",anchorPointX="0",anchorPointY="0.5",},
btn_gotogame={classname="ImageView",name="btn_gotogame",parName="lay_gotogame",ZOrder="0",fileName="#v1_btn_blue1.png",scale9Enable="false",scale9Height="62",scale9Width="155",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="62",width="155",x="100",y="40",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="23",anchorPointX="0.5",anchorPointY="0.5",},
lb_gotogame={classname="Label",name="lb_gotogame",parName="lay_gotogame",ZOrder="10",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="100",y="40",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="24",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_5"] = {
img_pk={classname="ImageView",name="img_pk",parName="lay_pk_gou",ZOrder="0",fileName="#v1_img_gouxuan.png",scale9Enable="false",scale9Height="40",scale9Width="41",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="40",width="41",x="20",y="20",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="20",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable