local tTable = {}

tTable["texturesPng"] = {"ui/p1_commmon1_sep.plist","ui/p2_commmon1_sep.plist"}
tTable["index_1"] = {
layout_chat_private_layer={classname="Panel",name="layout_chat_private_layer@fill_layout",parName="root",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="926",width="600",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1073",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_chat_detail={classname="Panel",name="lay_chat_detail@fill_layout_height",parName="layout_chat_private_layer",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="926",width="512",x="108",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1077",anchorPointX="0",anchorPointY="0",},
lay_fill1={classname="Panel",name="lay_fill1@fill_layout_height",parName="layout_chat_private_layer",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="926",width="130",x="-1",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="22921",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_space={classname="Panel",name="lay_space",parName="lay_chat_detail",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="20",width="600",x="-87",y="906",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="22923",anchorPointX="0",anchorPointY="0",},
lay_tip={classname="Panel",name="lay_tip",parName="lay_chat_detail",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_xitongtishi.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="140",capInsetsY="22",height="44",width="476",x="17",y="863",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1262",anchorPointX="0",anchorPointY="0",},
lay_list_bot={classname="Panel",name="lay_list_bot",parName="lay_fill1",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="76",capInsetsY="12",height="24",width="118",x="-10",y="10",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1074",anchorPointX="0",anchorPointY="0",},
lay_list_top={classname="Panel",name="lay_list_top",parName="lay_fill1",childCount="1",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="24",width="118",x="-10",y="892",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1075",anchorPointX="0",anchorPointY="0",},
lay_frend={classname="Panel",name="lay_frend@fill_layout",parName="lay_fill1",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="874",width="130",x="0",y="37",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="22922",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
lb_tip={classname="Label",name="lb_tip",parName="lay_tip",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="238",y="22",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1263",anchorPointX="0.5",anchorPointY="0.5",},
img_bot={classname="ImageView",name="img_bot",parName="lay_list_bot",ZOrder="0",fileName="#v2_img_huodongshangxiafanjiantou.png",scale9Enable="false",scale9Height="24",scale9Width="116",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="24",width="116",x="59",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1081",anchorPointX="0.5",anchorPointY="0.5",},
img_top={classname="ImageView",name="img_top",parName="lay_list_top",ZOrder="0",fileName="#v2_img_huodongshangxiafanjiantou.png",scale9Enable="false",scale9Height="24",scale9Width="116",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="24",width="116",x="59",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1080",anchorPointX="0.5",anchorPointY="0.5",},
lay_friend_list={classname="Panel",name="lay_friend_list@fill_layout_height",parName="lay_frend",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="858",width="130",x="-8",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1094",anchorPointX="0",anchorPointY="0",},
lay_friend_list_bg={classname="Panel",name="lay_friend_list_bg@fill_layout_height",parName="lay_frend",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_huodongbiaoqiandi.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="19",capInsetsY="19",height="858",width="118",x="-9",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="1076",anchorPointX="0",anchorPointY="0",},
}

return tTable