local tTable = {}

tTable["texturesPng"] = {"ui/v2_bg_kejizonglan.jpg","ui/p1_commmon1_sep.plist","ui/p2_commmon1_sep.plist","icon/p1_icon_ui.plist","ui/language/cn/p2_font1.plist","ui/p1_commmon3_sep.plist"}
tTable["index_1"] = {
lay_main={classname="Panel",name="lay_main@fill_layout",parName="root",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1000",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="33",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_top={classname="Panel",name="lay_top",parName="lay_main",childCount="17",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="290",width="640",x="0",y="710",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="34",anchorPointX="0",anchorPointY="0",},
lay_rank={classname="Panel",name="lay_rank@fill_layout",parName="lay_main",childCount="2",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="658",width="640",x="0",y="52",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="35",anchorPointX="0",anchorPointY="0",},
lay_bot={classname="Panel",name="lay_bot",parName="lay_main",childCount="1",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="32",capInsetsY="32",height="52",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="38",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
img_top_bg={classname="ImageView",name="img_top_bg",parName="lay_top",ZOrder="0",fileName="ui/v2_bg_kejizonglan.jpg",scale9Enable="false",scale9Height="1138",scale9Width="640",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="1138",width="640",x="0",y="290",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="36",anchorPointX="0",anchorPointY="1",},
lay_cont={classname="Panel",name="lay_cont",parName="lay_top",childCount="3",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_black30.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="10",height="70",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="39",anchorPointX="0",anchorPointY="0",},
img_bg_jin={classname="ImageView",name="img_bg_jin",parName="lay_top",ZOrder="5",fileName="#v2_img_jinq.png",scale9Enable="false",scale9Height="230",scale9Width="150",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="230",width="150",x="320",y="194",visible="true",touchAble="false",flipX="false",scaleX="0.6",scaleY="0.6",opacity="255",rotation="0",tag="44",anchorPointX="0.5",anchorPointY="0.5",},
img_bg_yin={classname="ImageView",name="img_bg_yin",parName="lay_top",ZOrder="5",fileName="#v2_img_jinq.png",scale9Enable="false",scale9Height="230",scale9Width="150",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="230",width="150",x="160",y="179",visible="true",touchAble="false",flipX="false",scaleX="0.6",scaleY="0.6",opacity="255",rotation="0",tag="46",anchorPointX="0.5",anchorPointY="0.5",},
img_bg_tong={classname="ImageView",name="img_bg_tong",parName="lay_top",ZOrder="5",fileName="#v2_img_jinq.png",scale9Enable="false",scale9Height="230",scale9Width="150",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="230",width="150",x="480",y="179",visible="true",touchAble="false",flipX="false",scaleX="0.6",scaleY="0.6",opacity="255",rotation="0",tag="47",anchorPointX="0.5",anchorPointY="0.5",},
img_level_1={classname="ImageView",name="img_level_1",parName="lay_top",ZOrder="10",fileName="#v1_img_paixingbang1.png",scale9Enable="false",scale9Height="96",scale9Width="96",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="96",width="96",x="320",y="245",visible="true",touchAble="false",flipX="false",scaleX="0.8",scaleY="0.8",opacity="255",rotation="0",tag="48",anchorPointX="0.5",anchorPointY="0.5",},
img_level_2={classname="ImageView",name="img_level_2",parName="lay_top",ZOrder="10",fileName="#v1_img_paixingbang2.png",scale9Enable="false",scale9Height="96",scale9Width="96",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="96",width="96",x="160",y="230",visible="true",touchAble="false",flipX="false",scaleX="0.8",scaleY="0.8",opacity="255",rotation="0",tag="50",anchorPointX="0.5",anchorPointY="0.5",},
img_level_3={classname="ImageView",name="img_level_3",parName="lay_top",ZOrder="10",fileName="#v1_img_paixingbang3.png",scale9Enable="false",scale9Height="96",scale9Width="96",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="96",width="96",x="480",y="230",visible="true",touchAble="false",flipX="false",scaleX="0.8",scaleY="0.8",opacity="255",rotation="0",tag="51",anchorPointX="0.5",anchorPointY="0.5",},
img_country_1={classname="ImageView",name="img_country_1",parName="lay_top",ZOrder="15",fileName="#v2_fonts_chu.png",scale9Enable="false",scale9Height="58",scale9Width="58",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="58",width="58",x="320",y="180",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="52",anchorPointX="0.5",anchorPointY="0.5",},
img_country_2={classname="ImageView",name="img_country_2",parName="lay_top",ZOrder="150",fileName="#v2_fonts_chu.png",scale9Enable="false",scale9Height="58",scale9Width="58",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="58",width="58",x="160",y="165",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="54",anchorPointX="0.5",anchorPointY="0.5",},
img_country_3={classname="ImageView",name="img_country_3",parName="lay_top",ZOrder="15",fileName="#v2_fonts_chu.png",scale9Enable="false",scale9Height="58",scale9Width="58",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="58",width="58",x="480",y="165",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="55",anchorPointX="0.5",anchorPointY="0.5",},
lb_score_1={classname="Label",name="lb_score_1",parName="lay_top",ZOrder="20",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="320",y="110",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="56",anchorPointX="0.5",anchorPointY="0.5",},
lb_score_2={classname="Label",name="lb_score_2",parName="lay_top",ZOrder="20",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="160",y="95",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="58",anchorPointX="0.5",anchorPointY="0.5",},
lb_score_3={classname="Label",name="lb_score_3",parName="lay_top",ZOrder="20",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="480",y="95",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="59",anchorPointX="0.5",anchorPointY="0.5",},
lb_null_1={classname="Label",name="lb_null_1",parName="lay_top",ZOrder="10",colorB="255",colorG="255",colorR="255",areaHeight="60",areaWidth="60",hAlignment="0",vAlignment="0",text="虚位以待",fontName="微软雅黑",fontSize="20",height="60",width="60",x="320",y="180",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="137",anchorPointX="0.5",anchorPointY="0.5",},
lb_null_2={classname="Label",name="lb_null_2",parName="lay_top",ZOrder="10",colorB="255",colorG="255",colorR="255",areaHeight="60",areaWidth="60",hAlignment="0",vAlignment="0",text="虚位以待",fontName="微软雅黑",fontSize="20",height="60",width="60",x="160",y="165",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="139",anchorPointX="0.5",anchorPointY="0.5",},
lb_null_3={classname="Label",name="lb_null_3",parName="lay_top",ZOrder="10",colorB="255",colorG="255",colorR="255",areaHeight="60",areaWidth="60",hAlignment="0",vAlignment="0",text="虚位以待",fontName="微软雅黑",fontSize="20",height="60",width="60",x="480",y="165",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="140",anchorPointX="0.5",anchorPointY="0.5",},
lay_rank_title={classname="Panel",name="lay_rank_title",parName="lay_rank",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="#v2_img_xiaobiaoti3.png",height="50",width="640",x="0",y="608",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="60",anchorPointX="0",anchorPointY="0",},
lay_list={classname="Panel",name="lay_list@fill_layout",parName="lay_rank",ZOrder="5",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="608",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="70",anchorPointX="0",anchorPointY="0",},
lb_tip_bot={classname="Label",name="lb_tip_bot",parName="lay_bot",ZOrder="10",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="320",y="26",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="40",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_4"] = {
lb_par_1={classname="Label",name="lb_par_1",parName="lay_cont",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="320",y="50",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="41",anchorPointX="0.5",anchorPointY="0.5",},
lb_par_2={classname="Label",name="lb_par_2",parName="lay_cont",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="40",y="20",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="42",anchorPointX="0",anchorPointY="0.5",},
lb_par_3={classname="Label",name="lb_par_3",parName="lay_cont",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="600",y="20",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="43",anchorPointX="1",anchorPointY="0.5",},
}

return tTable