local tTable = {}

tTable["texturesPng"] = {"ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commonse1.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","icon/p1_icon_ui.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","ui/bg_world/v1_img_shijieditu.jpg","ui/p1_commmon1_sep.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","ui/p1_button1.plist","ui/p1_commonse1.plist","ui/bar/v1_bar_b1.png","ui/p1_commonse1.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commonse1.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","icon/p1_icon_ui.plist","ui/p1_commonse1.plist","icon/p1_icon_ui.plist","ui/p1_commonse1.plist","ui/p1_commmon1_sep.plist","ui/p1_commonse1.plist","ui/p1_commonse1.plist","icon/p1_icon_font.plist"}
tTable["index_1"] = {
default={classname="Panel",name="default@fill_layout",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1138",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="32",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
view={classname="Panel",name="view@fill_layout",parName="default",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1138",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="33",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_top={classname="Panel",name="lay_top",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="80",width="640",x="0",y="1059",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="35",anchorPointX="0",anchorPointY="0",},
lay_content={classname="Panel",name="lay_content@fill_layout",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="838",width="640",x="-1",y="200",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="36",anchorPointX="0",anchorPointY="0",},
lay_bottom={classname="Panel",name="lay_bottom",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="180",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="34",anchorPointX="0",anchorPointY="0",},
}

return tTable