local tTable = {}

tTable["texturesPng"] = {"ui/p2_button1.plist","ui/p2_commmon1_sep.plist","ui/p1_commmon3_sep.plist"}
tTable["index_1"] = {
view={classname="Panel",name="view@fill_layout",parName="root",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="817",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="11",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_tabs={classname="Panel",name="lay_tabs",parName="view",childCount="2",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="60",width="640",x="0",y="757",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="368",anchorPointX="0",anchorPointY="0",},
lay_info={classname="Panel",name="lay_info",parName="view",childCount="3",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="46",width="640",x="0",y="711",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="369",anchorPointX="0",anchorPointY="0",},
lay_title={classname="Panel",name="lay_title",parName="view",childCount="4",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_img_biaoqiantiao.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="25",capInsetsY="25",height="60",width="640",x="0",y="651",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="370",anchorPointX="0",anchorPointY="0",},
lay_listview={classname="Panel",name="lay_listview@fill_layout",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="597",width="640",x="0",y="54",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="371",anchorPointX="0",anchorPointY="0",},
lay_bottom={classname="Panel",name="lay_bottom",parName="view",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="32",capInsetsY="32",height="54",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="372",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_tab1={classname="Panel",name="lay_tab1",parName="lay_tabs",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_btn_biaoqian_hkoyp.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="65",capInsetsY="26",height="60",width="320",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="383",anchorPointX="0",anchorPointY="0",},
lay_tab2={classname="Panel",name="lay_tab2",parName="lay_tabs",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_btn_biaoqian_hkoyp.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="65",capInsetsY="26",height="60",width="320",x="320",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="382",anchorPointX="0",anchorPointY="0",},
txt_my_rank={classname="CustomLabel",name="txt_my_rank",parName="lay_info",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="36",y="23",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="388",anchorPointX="0",anchorPointY="0.5",},
txt_my_harm={classname="CustomLabel",name="txt_my_harm",parName="lay_info",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="240",y="23",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="389",anchorPointX="0",anchorPointY="0.5",},
lay_btn_share={classname="Panel",name="lay_btn_share",parName="lay_info",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="490",y="2",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="390",anchorPointX="0",anchorPointY="0",},
txt_title1={classname="CustomLabel",name="txt_title1",parName="lay_title",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="67",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="391",anchorPointX="0.5",anchorPointY="0.5",},
txt_title2={classname="CustomLabel",name="txt_title2",parName="lay_title",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="237",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="392",anchorPointX="0.5",anchorPointY="0.5",},
txt_title3={classname="CustomLabel",name="txt_title3",parName="lay_title",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="406",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="393",anchorPointX="0.5",anchorPointY="0.5",},
txt_title4={classname="CustomLabel",name="txt_title4",parName="lay_title",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="575",y="30",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="394",anchorPointX="0.5",anchorPointY="0.5",},
}
tTable["index_4"] = {
txt_tab1={classname="CustomLabel",name="txt_tab1",parName="lay_tab1",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="160",y="29",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="386",anchorPointX="0.5",anchorPointY="0.5",},
txt_tab2={classname="CustomLabel",name="txt_tab2",parName="lay_tab2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="160",y="29",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="387",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable