local tTable = {}

tTable["texturesPng"] = {"GUI/image.png","ui/p1_commonse1.plist","ui/p2_commmon1_sep.plist","ui/language/cn/p2_font1.plist"}
tTable["index_1"] = {
layout_arena_playerinfo={classname="Panel",name="layout_arena_playerinfo",parName="root",childCount="7",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="440",width="500",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="426",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_info={classname="Panel",name="lay_info",parName="layout_arena_playerinfo",childCount="13",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="420",width="500",x="0",y="10",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="427",anchorPointX="0",anchorPointY="0",},
lay_btn_1={classname="Panel",name="lay_btn_1",parName="layout_arena_playerinfo",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="14",y="-92",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="428",anchorPointX="0",anchorPointY="0",},
lay_btn_2={classname="Panel",name="lay_btn_2",parName="layout_arena_playerinfo",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="188",y="-92",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="431",anchorPointX="0",anchorPointY="0",},
lay_btn_3={classname="Panel",name="lay_btn_3",parName="layout_arena_playerinfo",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="356",y="-92",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="432",anchorPointX="0",anchorPointY="0",},
lay_btn_4={classname="Panel",name="lay_btn_4",parName="layout_arena_playerinfo",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="14",y="-178",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="433",anchorPointX="0",anchorPointY="0",},
lay_btn_5={classname="Panel",name="lay_btn_5",parName="layout_arena_playerinfo",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="188",y="-178",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="434",anchorPointX="0",anchorPointY="0",},
lay_btn_6={classname="Panel",name="lay_btn_6",parName="layout_arena_playerinfo",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="356",y="-178",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="435",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_icon={classname="Panel",name="lay_icon",parName="lay_info",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="108",width="108",x="18",y="276",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="437",anchorPointX="0",anchorPointY="0",},
lb_vip_lv={classname="Label",name="lb_vip_lv",parName="lay_info",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="22",height="30",width="106",x="72",y="401",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="438",anchorPointX="0.5",anchorPointY="0.5",},
img_flag={classname="ImageView",name="img_flag",parName="lay_info",ZOrder="0",fileName="GUI/image.png",scale9Enable="false",scale9Height="80",scale9Width="80",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="80",width="80",x="460",y="367",visible="true",touchAble="false",flipX="false",scaleX="0.7",scaleY="0.7",opacity="255",rotation="0",tag="439",anchorPointX="0.5",anchorPointY="0.5",},
img_dianzan={classname="ImageView",name="img_dianzan",parName="lay_info",ZOrder="0",fileName="#v1_img_dianzan.png",scale9Enable="false",scale9Height="36",scale9Width="36",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="36",width="36",x="153",y="365",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="440",anchorPointX="0.5",anchorPointY="0.5",},
lb_zan={classname="Label",name="lb_zan",parName="lay_info",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="180",y="363",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="441",anchorPointX="0",anchorPointY="0.5",},
lb_lv={classname="Label",name="lb_lv",parName="lay_info",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="140",y="332",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="442",anchorPointX="0",anchorPointY="0.5",},
lb_name={classname="Label",name="lb_name",parName="lay_info",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="140",y="302",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="443",anchorPointX="0",anchorPointY="0.5",},
lb_fc={classname="Label",name="lb_fc",parName="lay_info",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="140",y="271",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="444",anchorPointX="0",anchorPointY="0.5",},
img_line={classname="ImageView",name="img_line",parName="lay_info",ZOrder="0",fileName="#v1_line_blue1.png",scale9Enable="true",scale9Height="2",scale9Width="464",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="1",height="2",width="464",x="250",y="235",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="445",anchorPointX="0.5",anchorPointY="0.5",},
img_arrow_1={classname="ImageView",name="img_arrow_1",parName="lay_info",ZOrder="0",fileName="#v2_img_xsfuduqdd.png",scale9Enable="false",scale9Height="13",scale9Width="157",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="13",width="157",x="20",y="213",visible="true",touchAble="false",flipX="true",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="446",anchorPointX="0",anchorPointY="0.5",},
img_arrow_2={classname="ImageView",name="img_arrow_2",parName="lay_info",ZOrder="0",fileName="#v2_img_xsfuduqdd.png",scale9Enable="false",scale9Height="13",scale9Width="157",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="13",width="157",x="480",y="213",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="447",anchorPointX="1",anchorPointY="0.5",},
img_title={classname="ImageView",name="img_title",parName="lay_info",ZOrder="0",fileName="#v2_fonts_jjczhenrong.png",scale9Enable="false",scale9Height="22",scale9Width="110",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="22",width="110",x="250",y="213",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="448",anchorPointX="0.5",anchorPointY="0.5",},
lb_zhanli={classname="Label",name="lb_zhanli",parName="lay_info",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="250",y="15",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="449",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable