local tTable = {}


tTable["index_1"] = {
default={classname="Panel",name="default@fill_layout",parName="root",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1000",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="14",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
view={classname="Panel",name="view@fill_layout",parName="default",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="1000",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="619",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
lay_bg={classname="Panel",name="lay_bg",parName="view",childCount="14",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="ui/v2_bg_fuxinggaozhao.jpg",height="1000",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="17",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
txt_time={classname="Label",name="txt_time",parName="lay_bg",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="42",y="980",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="287",anchorPointX="0",anchorPointY="0.5",},
txt_point={classname="Label",name="txt_point",parName="lay_bg",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="41",y="954",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="289",anchorPointX="0",anchorPointY="0.5",},
img_clock={classname="ImageView",name="img_clock",parName="lay_bg",ZOrder="2",fileName="#v1_img_shizhong02.png",scale9Enable="false",scale9Height="22",scale9Width="22",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="22",width="22",x="24",y="980",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="286",anchorPointX="0.5",anchorPointY="0.5",},
lay_right={classname="Panel",name="lay_right",parName="lay_bg",childCount="3",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_black50.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="10",height="36",width="140",x="470",y="940",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="301",anchorPointX="0",anchorPointY="0",},
img_btn_one={classname="ImageView",name="img_btn_one",parName="lay_bg",ZOrder="0",fileName="#v2_btn_dankai.png",scale9Enable="false",scale9Height="71",scale9Width="258",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="71",width="258",x="150",y="475",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="304",anchorPointX="0.5",anchorPointY="0.5",},
img_btn_serveral={classname="ImageView",name="img_btn_serveral",parName="lay_bg",ZOrder="0",fileName="#v2_btn_lianka.png",scale9Enable="false",scale9Height="71",scale9Width="258",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="71",width="258",x="490",y="475",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="306",anchorPointX="0.5",anchorPointY="0.5",},
lay_slot1={classname="Panel",name="lay_slot1",parName="lay_bg",childCount="1",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="80",width="80",x="38",y="334",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="307",anchorPointX="0",anchorPointY="0",},
lay_slot2={classname="Panel",name="lay_slot2",parName="lay_bg",childCount="1",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="80",width="80",x="159",y="334",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="309",anchorPointX="0",anchorPointY="0",},
lay_slot3={classname="Panel",name="lay_slot3",parName="lay_bg",childCount="1",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="80",width="80",x="278",y="334",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="310",anchorPointX="0",anchorPointY="0",},
lay_slot4={classname="Panel",name="lay_slot4",parName="lay_bg",childCount="1",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="80",width="80",x="399",y="334",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="311",anchorPointX="0",anchorPointY="0",},
lay_slot5={classname="Panel",name="lay_slot5",parName="lay_bg",childCount="1",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="80",width="80",x="519",y="334",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="312",anchorPointX="0",anchorPointY="0",},
lay_bar={classname="Panel",name="lay_bar",parName="lay_bg",childCount="1",ZOrder="2",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",backGroundImage="ui/bar/v2_bar_bfuxinggaozhao.png",height="20",width="550",x="45",y="297",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="323",anchorPointX="0",anchorPointY="0",},
lay_open_num={classname="Label",name="lay_open_num",parName="lay_bg",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="320",y="243",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="324",anchorPointX="0.5",anchorPointY="0.5",},
txt_desc={classname="Label",name="txt_desc",parName="lay_bg",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="251",areaWidth="600",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="251",width="600",x="20",y="225",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="529",anchorPointX="0",anchorPointY="1",},
}
tTable["index_5"] = {
img1={classname="ImageView",name="img1",parName="lay_right",ZOrder="0",fileName="#i100178.png",scale9Enable="false",scale9Height="96",scale9Width="96",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="96",width="96",x="9",y="18",visible="true",touchAble="false",flipX="false",scaleX="0.6",scaleY="0.6",opacity="255",rotation="0",tag="300",anchorPointX="0.5",anchorPointY="0.5",},
txt_right={classname="Label",name="txt_right",parName="lay_right",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="77",y="18",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="302",anchorPointX="0.5",anchorPointY="0.5",},
img_add={classname="ImageView",name="img_add",parName="lay_right",ZOrder="2",fileName="#v1_btn_increase.png",scale9Enable="false",scale9Height="34",scale9Width="34",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="34",width="34",x="136",y="18",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="569",anchorPointX="0.5",anchorPointY="0.5",},
txt_item_num1={classname="Label",name="txt_item_num1",parName="lay_slot1",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="x10",fontName="微软雅黑",fontSize="18",height="24",width="31",x="40",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="330",anchorPointX="0.5",anchorPointY="0.5",},
txt_item_num2={classname="Label",name="txt_item_num2",parName="lay_slot2",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="40",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="329",anchorPointX="0.5",anchorPointY="0.5",},
txt_item_num3={classname="Label",name="txt_item_num3",parName="lay_slot3",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="40",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="325",anchorPointX="0.5",anchorPointY="0.5",},
txt_item_num4={classname="Label",name="txt_item_num4",parName="lay_slot4",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="40",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="327",anchorPointX="0.5",anchorPointY="0.5",},
txt_item_num5={classname="Label",name="txt_item_num5",parName="lay_slot5",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="18",height="24",width="87",x="40",y="12",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="328",anchorPointX="0.5",anchorPointY="0.5",},
lay_bar2={classname="Panel",name="lay_bar2",parName="lay_bar",childCount="5",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="20",width="520",x="15",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="604",anchorPointX="0",anchorPointY="0",},
}
tTable["index_6"] = {
txt_num1={classname="Label",name="txt_num1",parName="lay_bar2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="18",y="-17",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="598",anchorPointX="0.5",anchorPointY="0.5",},
txt_num2={classname="Label",name="txt_num2",parName="lay_bar2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="139",y="-17",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="600",anchorPointX="0.5",anchorPointY="0.5",},
txt_num3={classname="Label",name="txt_num3",parName="lay_bar2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="258",y="-17",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="601",anchorPointX="0.5",anchorPointY="0.5",},
txt_num4={classname="Label",name="txt_num4",parName="lay_bar2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="379",y="-17",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="602",anchorPointX="0.5",anchorPointY="0.5",},
txt_num5={classname="Label",name="txt_num5",parName="lay_bar2",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="499",y="-17",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="603",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable