local tTable = {}

tTable["texturesPng"] = {"ui/p1_commmon2_sep.plist","ui/p2_commmon1_sep.plist"}
tTable["index_1"] = {
res_collect={classname="Panel",name="res_collect",parName="root",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="530",width="560",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="7",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_employ={classname="Panel",name="lay_employ",parName="res_collect",childCount="1",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_img_kelashen6.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="50",capInsetsY="50",height="130",width="532",x="15",y="383",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="8",anchorPointX="0",anchorPointY="0",},
lay_content={classname="Panel",name="lay_content",parName="res_collect",childCount="34",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v2_line_ziyuanzhengshou1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="20",capInsetsY="20",height="360",width="530",x="15",y="11",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="9",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
img_jianbian={classname="ImageView",name="img_jianbian",parName="lay_employ",ZOrder="0",fileName="#v1_img_kelashen6_b.png",scale9Enable="true",scale9Height="128",scale9Width="532",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="175",capInsetsY="9",height="128",width="532",x="0",y="0",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="11",anchorPointX="0",anchorPointY="0",},
lay_line={classname="Panel",name="lay_line",parName="lay_content",childCount="8",ZOrder="1",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="360",width="530",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="33",anchorPointX="0",anchorPointY="0",},
lb_left_1={classname="Label",name="lb_left_1",parName="lay_content",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="资源",fontName="微软雅黑",fontSize="20",height="27",width="40",x="77",y="343",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="24",anchorPointX="0.5",anchorPointY="0.5",},
lb_left_2={classname="Label",name="lb_left_2",parName="lay_content",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="产量",fontName="微软雅黑",fontSize="20",height="27",width="40",x="31",y="318",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="26",anchorPointX="0.5",anchorPointY="0.5",},
lb_left_3={classname="Label",name="lb_left_3",parName="lay_content",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="基础产量",fontName="微软雅黑",fontSize="20",height="27",width="80",x="53",y="275",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="27",anchorPointX="0.5",anchorPointY="0.5",},
lb_left_4={classname="Label",name="lb_left_4",parName="lay_content",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="科技加成",fontName="微软雅黑",fontSize="20",height="27",width="80",x="53",y="225",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="28",anchorPointX="0.5",anchorPointY="0.5",},
lb_left_5={classname="Label",name="lb_left_5",parName="lay_content",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="季节加成",fontName="微软雅黑",fontSize="20",height="27",width="80",x="53",y="175",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="29",anchorPointX="0.5",anchorPointY="0.5",},
lb_left_6={classname="Label",name="lb_left_6",parName="lay_content",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="文官加成",fontName="微软雅黑",fontSize="20",height="27",width="80",x="53",y="125",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="30",anchorPointX="0.5",anchorPointY="0.5",},
lb_left_7={classname="Label",name="lb_left_7",parName="lay_content",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="活动加成",fontName="微软雅黑",fontSize="20",height="27",width="80",x="53",y="75",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="31",anchorPointX="0.5",anchorPointY="0.5",},
lb_left_8={classname="Label",name="lb_left_8",parName="lay_content",ZOrder="2",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="总产量",fontName="微软雅黑",fontSize="20",height="27",width="60",x="53",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="32",anchorPointX="0.5",anchorPointY="0.5",},
lb_num_1={classname="Label",name="lb_num_1",parName="lay_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="20",height="27",width="48",x="163",y="275",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="34",anchorPointX="0.5",anchorPointY="0.5",},
lb_num_2={classname="Label",name="lb_num_2",parName="lay_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="20",height="27",width="48",x="163",y="225",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="40",anchorPointX="0.5",anchorPointY="0.5",},
lb_num_3={classname="Label",name="lb_num_3",parName="lay_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="20",height="27",width="48",x="163",y="175",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="44",anchorPointX="0.5",anchorPointY="0.5",},
lb_num_4={classname="Label",name="lb_num_4",parName="lay_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="20",height="27",width="48",x="163",y="125",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="49",anchorPointX="0.5",anchorPointY="0.5",},
lb_num_5={classname="Label",name="lb_num_5",parName="lay_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="20",height="27",width="48",x="163",y="75",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="53",anchorPointX="0.5",anchorPointY="0.5",},
lb_num_6={classname="Label",name="lb_num_6",parName="lay_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="20",height="27",width="48",x="163",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="57",anchorPointX="0.5",anchorPointY="0.5",},
lb_num_7={classname="Label",name="lb_num_7",parName="lay_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="20",height="27",width="48",x="265",y="275",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="36",anchorPointX="0.5",anchorPointY="0.5",},
lb_num_8={classname="Label",name="lb_num_8",parName="lay_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="20",height="27",width="48",x="265",y="225",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="41",anchorPointX="0.5",anchorPointY="0.5",},
lb_num_9={classname="Label",name="lb_num_9",parName="lay_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="20",height="27",width="48",x="265",y="175",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="45",anchorPointX="0.5",anchorPointY="0.5",},
lb_num_10={classname="Label",name="lb_num_10",parName="lay_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="20",height="27",width="48",x="265",y="125",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="50",anchorPointX="0.5",anchorPointY="0.5",},
lb_num_11={classname="Label",name="lb_num_11",parName="lay_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="20",height="27",width="48",x="265",y="75",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="54",anchorPointX="0.5",anchorPointY="0.5",},
lb_num_12={classname="Label",name="lb_num_12",parName="lay_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="20",height="27",width="48",x="265",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="58",anchorPointX="0.5",anchorPointY="0.5",},
lb_num_13={classname="Label",name="lb_num_13",parName="lay_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="20",height="27",width="48",x="368",y="275",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="37",anchorPointX="0.5",anchorPointY="0.5",},
lb_num_14={classname="Label",name="lb_num_14",parName="lay_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="20",height="27",width="48",x="368",y="225",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="42",anchorPointX="0.5",anchorPointY="0.5",},
lb_num_15={classname="Label",name="lb_num_15",parName="lay_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="20",height="27",width="48",x="368",y="175",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="46",anchorPointX="0.5",anchorPointY="0.5",},
lb_num_16={classname="Label",name="lb_num_16",parName="lay_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="20",height="27",width="48",x="368",y="125",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="51",anchorPointX="0.5",anchorPointY="0.5",},
lb_num_17={classname="Label",name="lb_num_17",parName="lay_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="20",height="27",width="48",x="368",y="75",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="55",anchorPointX="0.5",anchorPointY="0.5",},
lb_num_18={classname="Label",name="lb_num_18",parName="lay_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="20",height="27",width="48",x="368",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="59",anchorPointX="0.5",anchorPointY="0.5",},
lb_num_19={classname="Label",name="lb_num_19",parName="lay_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="20",height="27",width="48",x="470",y="275",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="38",anchorPointX="0.5",anchorPointY="0.5",},
lb_num_20={classname="Label",name="lb_num_20",parName="lay_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="20",height="27",width="48",x="470",y="225",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="43",anchorPointX="0.5",anchorPointY="0.5",},
lb_num_21={classname="Label",name="lb_num_21",parName="lay_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="20",height="27",width="48",x="470",y="175",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="47",anchorPointX="0.5",anchorPointY="0.5",},
lb_num_22={classname="Label",name="lb_num_22",parName="lay_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="20",height="27",width="48",x="470",y="125",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="52",anchorPointX="0.5",anchorPointY="0.5",},
lb_num_23={classname="Label",name="lb_num_23",parName="lay_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="20",height="27",width="48",x="470",y="75",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="56",anchorPointX="0.5",anchorPointY="0.5",},
lb_num_24={classname="Label",name="lb_num_24",parName="lay_content",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="9999",fontName="微软雅黑",fontSize="20",height="27",width="48",x="470",y="25",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="60",anchorPointX="0.5",anchorPointY="0.5",},
lay_res={classname="Panel",name="lay_res",parName="lay_content",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="58",width="423",x="107",y="300",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="61",anchorPointX="0",anchorPointY="0",},
}
tTable["index_4"] = {
img_line_1={classname="ImageView",name="img_line_1",parName="lay_line",ZOrder="1",fileName="#v2_line_ziyuanzhengshou2.png",scale9Enable="true",scale9Height="2",scale9Width="528",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="2",width="528",x="265",y="50",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="13",anchorPointX="0.5",anchorPointY="0.5",},
img_line_2={classname="ImageView",name="img_line_2",parName="lay_line",ZOrder="1",fileName="#v2_line_ziyuanzhengshou2.png",scale9Enable="true",scale9Height="2",scale9Width="528",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="2",width="528",x="265",y="100",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="16",anchorPointX="0.5",anchorPointY="0.5",},
img_line_3={classname="ImageView",name="img_line_3",parName="lay_line",ZOrder="1",fileName="#v2_line_ziyuanzhengshou2.png",scale9Enable="true",scale9Height="2",scale9Width="528",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="2",width="528",x="265",y="150",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="17",anchorPointX="0.5",anchorPointY="0.5",},
img_line_4={classname="ImageView",name="img_line_4",parName="lay_line",ZOrder="1",fileName="#v2_line_ziyuanzhengshou2.png",scale9Enable="true",scale9Height="2",scale9Width="528",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="2",width="528",x="265",y="200",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="18",anchorPointX="0.5",anchorPointY="0.5",},
img_line_5={classname="ImageView",name="img_line_5",parName="lay_line",ZOrder="1",fileName="#v2_line_ziyuanzhengshou2.png",scale9Enable="true",scale9Height="2",scale9Width="528",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="2",width="528",x="265",y="250",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="19",anchorPointX="0.5",anchorPointY="0.5",},
img_line_6={classname="ImageView",name="img_line_6",parName="lay_line",ZOrder="1",fileName="#v2_line_ziyuanzhengshou2.png",scale9Enable="true",scale9Height="2",scale9Width="528",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="2",width="528",x="265",y="300",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="20",anchorPointX="0.5",anchorPointY="0.5",},
img_line_7={classname="ImageView",name="img_line_7",parName="lay_line",ZOrder="1",fileName="#v2_line_ziyuanzhengshou2.png",scale9Enable="true",scale9Height="2",scale9Width="358",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="2",width="358",x="106",y="180",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="90",tag="22",anchorPointX="0.5",anchorPointY="0.5",},
img_line_xie={classname="ImageView",name="img_line_xie",parName="lay_line",ZOrder="0",fileName="#v2_line_ziyuanzhengshou3.png",scale9Enable="false",scale9Height="61",scale9Width="107",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="61",width="107",x="55",y="329",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="23",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable