local tTable = {}


tTable["index_1"] = {
root={classname="Panel",name="root",parName="root",childCount="10",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="850",width="600",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2040",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
img_yueka={classname="ImageView",name="img_yueka",parName="root",ZOrder="0",fileName="#v1_img_yueka.png",scale9Enable="false",scale9Height="150",scale9Width="142",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="150",width="142",x="116",y="759",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2082",anchorPointX="0.5",anchorPointY="0.5",},
lb_tip_1={classname="Label",name="lb_tip_1",parName="root",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="22",height="30",width="106",x="226",y="812",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2083",anchorPointX="0",anchorPointY="0.5",},
lb_tip_2={classname="Label",name="lb_tip_2",parName="root",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="226",y="768",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2084",anchorPointX="0",anchorPointY="0.5",},
lb_tip_3={classname="Label",name="lb_tip_3",parName="root",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="226",y="736",visible="false",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2085",anchorPointX="0",anchorPointY="0.5",},
lay_btn1={classname="Panel",name="lay_btn1",parName="root",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="130",x="443",y="716",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2086",anchorPointX="0",anchorPointY="0",},
lay_cont={classname="Panel",name="lay_cont",parName="root",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="#v1_bg_kelashen.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="22",capInsetsY="22",height="676",width="600",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2173",anchorPointX="0",anchorPointY="0",},
Image_22={classname="ImageView",name="Image_22",parName="root",ZOrder="0",fileName="#v2_img_vipchanzhi10p.png",scale9Enable="false",scale9Height="35",scale9Width="251",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="35",width="251",x="317",y="763",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2174",anchorPointX="0.5",anchorPointY="0.5",},
Image_23={classname="ImageView",name="Image_23",parName="root",ZOrder="1",fileName="#v2_img_vipzongfan3000.png",scale9Enable="false",scale9Height="26",scale9Width="213",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="26",width="213",x="305",y="729",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2175",anchorPointX="0.5",anchorPointY="0.5",},
Image_24={classname="ImageView",name="Image_24",parName="root",ZOrder="0",fileName="#v2_img_kaivn.png",scale9Enable="false",scale9Height="32",scale9Width="250",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="32",width="250",x="305",y="729",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2176",anchorPointX="0.5",anchorPointY="0.5",},
img_desc_btn={classname="ImageView",name="img_desc_btn",parName="root",ZOrder="0",fileName="#v1_btn_disaduse.png",scale9Enable="false",scale9Height="50",scale9Width="50",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="50",width="50",x="204",y="810",visible="true",touchAble="false",flipX="false",scaleX="0.8",scaleY="0.8",opacity="255",rotation="0",tag="23144",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable