local tTable = {}

tTable["texturesPng"] = {"ui/bar/v2_bar_chongzhi_b.png","icon/p1_icon_ui.plist","ui/v2_bg_banner_chongzhi.jpg"}
tTable["index_1"] = {
root={classname="Panel",name="root",parName="root",childCount="11",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="185",width="640",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="102",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
lay_btn_1={classname="Panel",name="lay_btn_1",parName="root",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="110",x="510",y="88",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="104",anchorPointX="0",anchorPointY="0",},
lay_bar_bg={classname="Panel",name="lay_bar_bg",parName="root",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v2_bar_chongzhi_b.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="45",capInsetsY="9",height="17",width="262",x="190",y="50",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="106",anchorPointX="0",anchorPointY="0",},
img_vip={classname="ImageView",name="img_vip",parName="root",ZOrder="10",fileName="#v2_img_vip1a.png",scale9Enable="false",scale9Height="125",scale9Width="120",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="125",width="120",x="90",y="88",visible="true",touchAble="false",flipX="false",scaleX="0.9",scaleY="0.9",opacity="255",rotation="0",tag="107",anchorPointX="0.5",anchorPointY="0.5",},
lb_tip_1={classname="Label",name="lb_tip_1",parName="root",ZOrder="10",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="再充值",fontName="微软雅黑",fontSize="20",height="27",width="60",x="196",y="120",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="109",anchorPointX="0.5",anchorPointY="0.5",},
lb_tip_2={classname="Label",name="lb_tip_2",parName="root",ZOrder="10",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="可升级至",fontName="微软雅黑",fontSize="20",height="27",width="80",x="352",y="119",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="110",anchorPointX="0",anchorPointY="0.5",},
lb_tip_3={classname="Label",name="lb_tip_3",parName="root",ZOrder="10",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="321",y="85",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2274",anchorPointX="0.5",anchorPointY="0.5",},
lb_gold={classname="Label",name="lb_gold",parName="root",ZOrder="10",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="1090 黄金",fontName="微软雅黑",fontSize="20",height="27",width="94",x="240",y="120",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="111",anchorPointX="0",anchorPointY="0.5",},
lb_viplv={classname="Label",name="lb_viplv",parName="root",ZOrder="10",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="VIP5",fontName="微软雅黑",fontSize="20",height="27",width="44",x="446",y="119",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="112",anchorPointX="0",anchorPointY="0.5",},
lb_vipmax={classname="Label",name="lb_vipmax",parName="root",ZOrder="10",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="当前VIP等级已满！",fontName="微软雅黑",fontSize="20",height="27",width="172",x="321",y="120",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="215",anchorPointX="0.5",anchorPointY="0.5",},
img_bg={classname="ImageView",name="img_bg",parName="root",ZOrder="0",fileName="ui/v2_bg_banner_chongzhi.jpg",scale9Enable="false",scale9Height="185",scale9Width="640",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="185",width="640",x="320",y="0",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2237",anchorPointX="0.5",anchorPointY="0",},
lay_btn_2={classname="Panel",name="lay_btn_2",parName="root",ZOrder="10",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="50",width="110",x="510",y="19",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="2451",anchorPointX="0",anchorPointY="0",},
}

return tTable