local tTable = {}

tTable["texturesPng"] = {"ui/p1_commmon1_sep.plist","ui/daitu.png","ui/bar/v1_bar_b1.png","ui/bar/v1_bar_blue_7.png","ui/p1_commonse1.plist"}
tTable["index_1"] = {
default={classname="Panel",name="default",parName="root",childCount="8",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/big_img_sep/v1_img_shenbingkuang.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="125",capInsetsY="98",height="256",width="250",x="0",y="0",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="15",anchorPointX="0",anchorPointY="0",},
}
tTable["index_2"] = {
img_level={classname="ImageView",name="img_level",parName="default",ZOrder="0",fileName="#v1_img_black30.png",scale9Enable="true",scale9Height="36",scale9Width="84",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="10",capInsetsY="10",height="36",width="84",x="43",y="237",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="16",anchorPointX="0.5",anchorPointY="0.5",},
lb_level={classname="Label",name="lb_level",parName="default",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="等级",fontName="微软雅黑",fontSize="20",height="27",width="40",x="44",y="237",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="17",anchorPointX="0.5",anchorPointY="0.5",},
lay_weaponimg={classname="Panel",name="lay_weaponimg",parName="default",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="150",width="150",x="50",y="76",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="23",anchorPointX="0",anchorPointY="0",},
img_weapons={classname="ImageView",name="img_weapons",parName="default",ZOrder="0",fileName="ui/daitu.png",scale9Enable="false",scale9Height="10",scale9Width="10",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="10",width="10",x="125",y="151",visible="true",touchAble="false",flipX="false",scaleX="0.4999999",scaleY="0.4999999",opacity="255",rotation="0",tag="25",anchorPointX="0.5",anchorPointY="0.5",},
lb_unlock={classname="Label",name="lb_unlock",parName="default",ZOrder="0",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="125",y="38",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="95",anchorPointX="0.5",anchorPointY="0.5",},
lay_bar={classname="Panel",name="lay_bar",parName="default",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="true",backGroundImage="ui/bar/v1_bar_b1.png",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="45",capInsetsY="9",height="14",width="223",x="13",y="11",visible="false",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="103",anchorPointX="0",anchorPointY="0",},
lay_redtip={classname="Panel",name="lay_redtip",parName="default",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="26",width="26",x="223",y="229",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="261",anchorPointX="0",anchorPointY="0",},
lay_canmake={classname="Panel",name="lay_canmake",parName="default",childCount="2",ZOrder="0",useMergedTexture="false",clipAble="false",backGroundScale9Enable="false",height="80",width="80",x="0",y="176",visible="true",touchAble="true",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="402",anchorPointX="0",anchorPointY="0",},
}
tTable["index_3"] = {
pro_bar={classname="LoadingBar",name="pro_bar",parName="lay_bar",ZOrder="0",direction="0",percent="5",texture="ui/bar/v1_bar_blue_7.png",scale9Enable="false",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="14",width="223",x="111",y="6",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="100",anchorPointX="0.5",anchorPointY="0.5",},
lb_percent={classname="Label",name="lb_percent",parName="lay_bar",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="Text Label",fontName="微软雅黑",fontSize="20",height="27",width="95",x="111",y="6",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="0",tag="102",anchorPointX="0.5",anchorPointY="0.5",},
img_hong={classname="ImageView",name="img_hong",parName="lay_canmake",ZOrder="0",fileName="#v1_img_xinpin.png",scale9Enable="false",scale9Height="70",scale9Width="71",capInsetsHeight="1",capInsetsWidth="1",capInsetsX="0",capInsetsY="0",height="70",width="71",x="40",y="40",visible="true",touchAble="false",flipX="false",scaleX="1.1",scaleY="1.1",opacity="255",rotation="0",tag="403",anchorPointX="0.5",anchorPointY="0.5",},
lb_canmake={classname="Label",name="lb_canmake",parName="lay_canmake",ZOrder="1",colorB="255",colorG="255",colorR="255",areaHeight="0",areaWidth="0",hAlignment="0",vAlignment="0",text="可打造",fontName="微软雅黑",fontSize="18",height="24",width="54",x="26",y="55",visible="true",touchAble="false",flipX="false",scaleX="1",scaleY="1",opacity="255",rotation="-45",tag="404",anchorPointX="0.5",anchorPointY="0.5",},
}

return tTable